-- Seed scripts live in this directory and are embedded into cmd/migrate.
--
-- Run one with:  migrate seed --file <name>
--
-- Seeds are never applied automatically. Most are for local development, demo
-- environments and load testing. A reviewed, tenant-scoped configuration seed
-- may be run explicitly during a controlled deployment after a database backup;
-- its file must validate its target tenant and be transactional and idempotent.
-- General production reference data should still use the bulk-import API so it
-- is validated, auditable and restartable.
--
-- ceserve_nigeria.sql is generated with:
-- python3 scripts/generate_ceserve_nigeria_seed.py \
--   --input data/nigeria/postcode-candidates-2026-09-20.csv \
--   --domestic-rates data/carriers/ups-nigeria-2026-domestic-rates.csv \
--   --onforwarding data/carriers/ups-nigeria-2026-onforwarding.csv \
--   --output db/seeds/ceserve_nigeria.sql
SELECT 1;
