-- 0042 Complete country reference catalogue for international addresses.
--
-- Country names and current tender currencies are a 2026-09-25 Unicode CLDR
-- snapshot; ISO-2/ISO-3 identifiers follow ISO 3166-1. XK is the commonly
-- used user-assigned code for Kosovo. Calling codes follow libphonenumber.
--
-- A country being present here makes it selectable reference data only. It
-- does not make a route serviceable: shipment preview still requires active
-- postal geography, service areas, routes and pricing for the selected lane.

WITH catalogue(iso2, iso3, name, phone_code, currency) AS (
VALUES
    ('AF', 'AFG', 'Afghanistan', '+93', 'AFN'),
    ('AL', 'ALB', 'Albania', '+355', 'ALL'),
    ('DZ', 'DZA', 'Algeria', '+213', 'DZD'),
    ('AS', 'ASM', 'American Samoa', '+1', 'USD'),
    ('AD', 'AND', 'Andorra', '+376', 'EUR'),
    ('AO', 'AGO', 'Angola', '+244', 'AOA'),
    ('AI', 'AIA', 'Anguilla', '+1', 'XCD'),
    ('AQ', 'ATA', 'Antarctica', '', 'XXX'),
    ('AG', 'ATG', 'Antigua & Barbuda', '+1', 'XCD'),
    ('AR', 'ARG', 'Argentina', '+54', 'ARS'),
    ('AM', 'ARM', 'Armenia', '+374', 'AMD'),
    ('AW', 'ABW', 'Aruba', '+297', 'AWG'),
    ('AU', 'AUS', 'Australia', '+61', 'AUD'),
    ('AT', 'AUT', 'Austria', '+43', 'EUR'),
    ('AZ', 'AZE', 'Azerbaijan', '+994', 'AZN'),
    ('BS', 'BHS', 'Bahamas', '+1', 'BSD'),
    ('BH', 'BHR', 'Bahrain', '+973', 'BHD'),
    ('BD', 'BGD', 'Bangladesh', '+880', 'BDT'),
    ('BB', 'BRB', 'Barbados', '+1', 'BBD'),
    ('BY', 'BLR', 'Belarus', '+375', 'BYN'),
    ('BE', 'BEL', 'Belgium', '+32', 'EUR'),
    ('BZ', 'BLZ', 'Belize', '+501', 'BZD'),
    ('BJ', 'BEN', 'Benin', '+229', 'XOF'),
    ('BM', 'BMU', 'Bermuda', '+1', 'BMD'),
    ('BT', 'BTN', 'Bhutan', '+975', 'BTN'),
    ('BO', 'BOL', 'Bolivia', '+591', 'BOB'),
    ('BA', 'BIH', 'Bosnia & Herzegovina', '+387', 'BAM'),
    ('BW', 'BWA', 'Botswana', '+267', 'BWP'),
    ('BV', 'BVT', 'Bouvet Island', '+47', 'NOK'),
    ('BR', 'BRA', 'Brazil', '+55', 'BRL'),
    ('IO', 'IOT', 'British Indian Ocean Territory', '+246', 'USD'),
    ('VG', 'VGB', 'British Virgin Islands', '+1', 'USD'),
    ('BN', 'BRN', 'Brunei', '+673', 'BND'),
    ('BG', 'BGR', 'Bulgaria', '+359', 'BGN'),
    ('BF', 'BFA', 'Burkina Faso', '+226', 'XOF'),
    ('BI', 'BDI', 'Burundi', '+257', 'BIF'),
    ('KH', 'KHM', 'Cambodia', '+855', 'KHR'),
    ('CM', 'CMR', 'Cameroon', '+237', 'XAF'),
    ('CA', 'CAN', 'Canada', '+1', 'CAD'),
    ('CV', 'CPV', 'Cape Verde', '+238', 'CVE'),
    ('BQ', 'BES', 'Caribbean Netherlands', '+599', 'USD'),
    ('KY', 'CYM', 'Cayman Islands', '+1', 'KYD'),
    ('CF', 'CAF', 'Central African Republic', '+236', 'XAF'),
    ('TD', 'TCD', 'Chad', '+235', 'XAF'),
    ('CL', 'CHL', 'Chile', '+56', 'CLP'),
    ('CN', 'CHN', 'China', '+86', 'CNY'),
    ('CX', 'CXR', 'Christmas Island', '+61', 'AUD'),
    ('CC', 'CCK', 'Cocos (Keeling) Islands', '+61', 'AUD'),
    ('CO', 'COL', 'Colombia', '+57', 'COP'),
    ('KM', 'COM', 'Comoros', '+269', 'KMF'),
    ('CG', 'COG', 'Congo - Brazzaville', '+242', 'XAF'),
    ('CD', 'COD', 'Congo - Kinshasa', '+243', 'CDF'),
    ('CK', 'COK', 'Cook Islands', '+682', 'NZD'),
    ('CR', 'CRI', 'Costa Rica', '+506', 'CRC'),
    ('HR', 'HRV', 'Croatia', '+385', 'EUR'),
    ('CU', 'CUB', 'Cuba', '+53', 'CUP'),
    ('CW', 'CUW', 'Curaçao', '+599', 'XCG'),
    ('CY', 'CYP', 'Cyprus', '+357', 'EUR'),
    ('CZ', 'CZE', 'Czechia', '+420', 'CZK'),
    ('CI', 'CIV', 'Côte d’Ivoire', '+225', 'XOF'),
    ('DK', 'DNK', 'Denmark', '+45', 'DKK'),
    ('DJ', 'DJI', 'Djibouti', '+253', 'DJF'),
    ('DM', 'DMA', 'Dominica', '+1', 'XCD'),
    ('DO', 'DOM', 'Dominican Republic', '+1', 'DOP'),
    ('EC', 'ECU', 'Ecuador', '+593', 'USD'),
    ('EG', 'EGY', 'Egypt', '+20', 'EGP'),
    ('SV', 'SLV', 'El Salvador', '+503', 'USD'),
    ('GQ', 'GNQ', 'Equatorial Guinea', '+240', 'XAF'),
    ('ER', 'ERI', 'Eritrea', '+291', 'ERN'),
    ('EE', 'EST', 'Estonia', '+372', 'EUR'),
    ('SZ', 'SWZ', 'Eswatini', '+268', 'SZL'),
    ('ET', 'ETH', 'Ethiopia', '+251', 'ETB'),
    ('FK', 'FLK', 'Falkland Islands', '+500', 'FKP'),
    ('FO', 'FRO', 'Faroe Islands', '+298', 'DKK'),
    ('FJ', 'FJI', 'Fiji', '+679', 'FJD'),
    ('FI', 'FIN', 'Finland', '+358', 'EUR'),
    ('FR', 'FRA', 'France', '+33', 'EUR'),
    ('GF', 'GUF', 'French Guiana', '+594', 'EUR'),
    ('PF', 'PYF', 'French Polynesia', '+689', 'XPF'),
    ('TF', 'ATF', 'French Southern Territories', '+262', 'EUR'),
    ('GA', 'GAB', 'Gabon', '+241', 'XAF'),
    ('GM', 'GMB', 'Gambia', '+220', 'GMD'),
    ('GE', 'GEO', 'Georgia', '+995', 'GEL'),
    ('DE', 'DEU', 'Germany', '+49', 'EUR'),
    ('GH', 'GHA', 'Ghana', '+233', 'GHS'),
    ('GI', 'GIB', 'Gibraltar', '+350', 'GIP'),
    ('GR', 'GRC', 'Greece', '+30', 'EUR'),
    ('GL', 'GRL', 'Greenland', '+299', 'DKK'),
    ('GD', 'GRD', 'Grenada', '+1', 'XCD'),
    ('GP', 'GLP', 'Guadeloupe', '+590', 'EUR'),
    ('GU', 'GUM', 'Guam', '+1', 'USD'),
    ('GT', 'GTM', 'Guatemala', '+502', 'GTQ'),
    ('GG', 'GGY', 'Guernsey', '+44', 'GBP'),
    ('GN', 'GIN', 'Guinea', '+224', 'GNF'),
    ('GW', 'GNB', 'Guinea-Bissau', '+245', 'XOF'),
    ('GY', 'GUY', 'Guyana', '+592', 'GYD'),
    ('HT', 'HTI', 'Haiti', '+509', 'HTG'),
    ('HM', 'HMD', 'Heard & McDonald Islands', '+672', 'AUD'),
    ('HN', 'HND', 'Honduras', '+504', 'HNL'),
    ('HK', 'HKG', 'Hong Kong SAR China', '+852', 'HKD'),
    ('HU', 'HUN', 'Hungary', '+36', 'HUF'),
    ('IS', 'ISL', 'Iceland', '+354', 'ISK'),
    ('IN', 'IND', 'India', '+91', 'INR'),
    ('ID', 'IDN', 'Indonesia', '+62', 'IDR'),
    ('IR', 'IRN', 'Iran', '+98', 'IRR'),
    ('IQ', 'IRQ', 'Iraq', '+964', 'IQD'),
    ('IE', 'IRL', 'Ireland', '+353', 'EUR'),
    ('IM', 'IMN', 'Isle of Man', '+44', 'GBP'),
    ('IL', 'ISR', 'Israel', '+972', 'ILS'),
    ('IT', 'ITA', 'Italy', '+39', 'EUR'),
    ('JM', 'JAM', 'Jamaica', '+1', 'JMD'),
    ('JP', 'JPN', 'Japan', '+81', 'JPY'),
    ('JE', 'JEY', 'Jersey', '+44', 'GBP'),
    ('JO', 'JOR', 'Jordan', '+962', 'JOD'),
    ('KZ', 'KAZ', 'Kazakhstan', '+7', 'KZT'),
    ('KE', 'KEN', 'Kenya', '+254', 'KES'),
    ('KI', 'KIR', 'Kiribati', '+686', 'AUD'),
    ('XK', 'XKX', 'Kosovo', '+383', 'EUR'),
    ('KW', 'KWT', 'Kuwait', '+965', 'KWD'),
    ('KG', 'KGZ', 'Kyrgyzstan', '+996', 'KGS'),
    ('LA', 'LAO', 'Laos', '+856', 'LAK'),
    ('LV', 'LVA', 'Latvia', '+371', 'EUR'),
    ('LB', 'LBN', 'Lebanon', '+961', 'LBP'),
    ('LS', 'LSO', 'Lesotho', '+266', 'LSL'),
    ('LR', 'LBR', 'Liberia', '+231', 'LRD'),
    ('LY', 'LBY', 'Libya', '+218', 'LYD'),
    ('LI', 'LIE', 'Liechtenstein', '+423', 'CHF'),
    ('LT', 'LTU', 'Lithuania', '+370', 'EUR'),
    ('LU', 'LUX', 'Luxembourg', '+352', 'EUR'),
    ('MO', 'MAC', 'Macao SAR China', '+853', 'MOP'),
    ('MG', 'MDG', 'Madagascar', '+261', 'MGA'),
    ('MW', 'MWI', 'Malawi', '+265', 'MWK'),
    ('MY', 'MYS', 'Malaysia', '+60', 'MYR'),
    ('MV', 'MDV', 'Maldives', '+960', 'MVR'),
    ('ML', 'MLI', 'Mali', '+223', 'XOF'),
    ('MT', 'MLT', 'Malta', '+356', 'EUR'),
    ('MH', 'MHL', 'Marshall Islands', '+692', 'USD'),
    ('MQ', 'MTQ', 'Martinique', '+596', 'EUR'),
    ('MR', 'MRT', 'Mauritania', '+222', 'MRU'),
    ('MU', 'MUS', 'Mauritius', '+230', 'MUR'),
    ('YT', 'MYT', 'Mayotte', '+262', 'EUR'),
    ('MX', 'MEX', 'Mexico', '+52', 'MXN'),
    ('FM', 'FSM', 'Micronesia', '+691', 'USD'),
    ('MD', 'MDA', 'Moldova', '+373', 'MDL'),
    ('MC', 'MCO', 'Monaco', '+377', 'EUR'),
    ('MN', 'MNG', 'Mongolia', '+976', 'MNT'),
    ('ME', 'MNE', 'Montenegro', '+382', 'EUR'),
    ('MS', 'MSR', 'Montserrat', '+1', 'XCD'),
    ('MA', 'MAR', 'Morocco', '+212', 'MAD'),
    ('MZ', 'MOZ', 'Mozambique', '+258', 'MZN'),
    ('MM', 'MMR', 'Myanmar (Burma)', '+95', 'MMK'),
    ('NA', 'NAM', 'Namibia', '+264', 'NAD'),
    ('NR', 'NRU', 'Nauru', '+674', 'AUD'),
    ('NP', 'NPL', 'Nepal', '+977', 'NPR'),
    ('NL', 'NLD', 'Netherlands', '+31', 'EUR'),
    ('NC', 'NCL', 'New Caledonia', '+687', 'XPF'),
    ('NZ', 'NZL', 'New Zealand', '+64', 'NZD'),
    ('NI', 'NIC', 'Nicaragua', '+505', 'NIO'),
    ('NE', 'NER', 'Niger', '+227', 'XOF'),
    ('NG', 'NGA', 'Nigeria', '+234', 'NGN'),
    ('NU', 'NIU', 'Niue', '+683', 'NZD'),
    ('NF', 'NFK', 'Norfolk Island', '+672', 'AUD'),
    ('KP', 'PRK', 'North Korea', '+850', 'KPW'),
    ('MK', 'MKD', 'North Macedonia', '+389', 'MKD'),
    ('MP', 'MNP', 'Northern Mariana Islands', '+1', 'USD'),
    ('NO', 'NOR', 'Norway', '+47', 'NOK'),
    ('OM', 'OMN', 'Oman', '+968', 'OMR'),
    ('PK', 'PAK', 'Pakistan', '+92', 'PKR'),
    ('PW', 'PLW', 'Palau', '+680', 'USD'),
    ('PS', 'PSE', 'Palestinian Territories', '+970', 'ILS'),
    ('PA', 'PAN', 'Panama', '+507', 'PAB'),
    ('PG', 'PNG', 'Papua New Guinea', '+675', 'PGK'),
    ('PY', 'PRY', 'Paraguay', '+595', 'PYG'),
    ('PE', 'PER', 'Peru', '+51', 'PEN'),
    ('PH', 'PHL', 'Philippines', '+63', 'PHP'),
    ('PN', 'PCN', 'Pitcairn Islands', '+64', 'NZD'),
    ('PL', 'POL', 'Poland', '+48', 'PLN'),
    ('PT', 'PRT', 'Portugal', '+351', 'EUR'),
    ('PR', 'PRI', 'Puerto Rico', '+1', 'USD'),
    ('QA', 'QAT', 'Qatar', '+974', 'QAR'),
    ('RO', 'ROU', 'Romania', '+40', 'RON'),
    ('RU', 'RUS', 'Russia', '+7', 'RUB'),
    ('RW', 'RWA', 'Rwanda', '+250', 'RWF'),
    ('RE', 'REU', 'Réunion', '+262', 'EUR'),
    ('WS', 'WSM', 'Samoa', '+685', 'WST'),
    ('SM', 'SMR', 'San Marino', '+378', 'EUR'),
    ('SA', 'SAU', 'Saudi Arabia', '+966', 'SAR'),
    ('SN', 'SEN', 'Senegal', '+221', 'XOF'),
    ('RS', 'SRB', 'Serbia', '+381', 'RSD'),
    ('SC', 'SYC', 'Seychelles', '+248', 'SCR'),
    ('SL', 'SLE', 'Sierra Leone', '+232', 'SLE'),
    ('SG', 'SGP', 'Singapore', '+65', 'SGD'),
    ('SX', 'SXM', 'Sint Maarten', '+1', 'XCG'),
    ('SK', 'SVK', 'Slovakia', '+421', 'EUR'),
    ('SI', 'SVN', 'Slovenia', '+386', 'EUR'),
    ('SB', 'SLB', 'Solomon Islands', '+677', 'SBD'),
    ('SO', 'SOM', 'Somalia', '+252', 'SOS'),
    ('ZA', 'ZAF', 'South Africa', '+27', 'ZAR'),
    ('GS', 'SGS', 'South Georgia & South Sandwich Islands', '+500', 'GBP'),
    ('KR', 'KOR', 'South Korea', '+82', 'KRW'),
    ('SS', 'SSD', 'South Sudan', '+211', 'SSP'),
    ('ES', 'ESP', 'Spain', '+34', 'EUR'),
    ('LK', 'LKA', 'Sri Lanka', '+94', 'LKR'),
    ('BL', 'BLM', 'St. Barthélemy', '+590', 'EUR'),
    ('SH', 'SHN', 'St. Helena', '+290', 'SHP'),
    ('KN', 'KNA', 'St. Kitts & Nevis', '+1', 'XCD'),
    ('LC', 'LCA', 'St. Lucia', '+1', 'XCD'),
    ('MF', 'MAF', 'St. Martin', '+590', 'EUR'),
    ('PM', 'SPM', 'St. Pierre & Miquelon', '+508', 'EUR'),
    ('VC', 'VCT', 'St. Vincent & Grenadines', '+1', 'XCD'),
    ('SD', 'SDN', 'Sudan', '+249', 'SDG'),
    ('SR', 'SUR', 'Suriname', '+597', 'SRD'),
    ('SJ', 'SJM', 'Svalbard & Jan Mayen', '+47', 'NOK'),
    ('SE', 'SWE', 'Sweden', '+46', 'SEK'),
    ('CH', 'CHE', 'Switzerland', '+41', 'CHF'),
    ('SY', 'SYR', 'Syria', '+963', 'SYP'),
    ('ST', 'STP', 'São Tomé & Príncipe', '+239', 'STN'),
    ('TW', 'TWN', 'Taiwan', '+886', 'TWD'),
    ('TJ', 'TJK', 'Tajikistan', '+992', 'TJS'),
    ('TZ', 'TZA', 'Tanzania', '+255', 'TZS'),
    ('TH', 'THA', 'Thailand', '+66', 'THB'),
    ('TL', 'TLS', 'Timor-Leste', '+670', 'USD'),
    ('TG', 'TGO', 'Togo', '+228', 'XOF'),
    ('TK', 'TKL', 'Tokelau', '+690', 'NZD'),
    ('TO', 'TON', 'Tonga', '+676', 'TOP'),
    ('TT', 'TTO', 'Trinidad & Tobago', '+1', 'TTD'),
    ('TN', 'TUN', 'Tunisia', '+216', 'TND'),
    ('TM', 'TKM', 'Turkmenistan', '+993', 'TMT'),
    ('TC', 'TCA', 'Turks & Caicos Islands', '+1', 'USD'),
    ('TV', 'TUV', 'Tuvalu', '+688', 'AUD'),
    ('TR', 'TUR', 'Türkiye', '+90', 'TRY'),
    ('UM', 'UMI', 'U.S. Outlying Islands', '+1', 'USD'),
    ('VI', 'VIR', 'U.S. Virgin Islands', '+1', 'USD'),
    ('UG', 'UGA', 'Uganda', '+256', 'UGX'),
    ('UA', 'UKR', 'Ukraine', '+380', 'UAH'),
    ('AE', 'ARE', 'United Arab Emirates', '+971', 'AED'),
    ('GB', 'GBR', 'United Kingdom', '+44', 'GBP'),
    ('US', 'USA', 'United States', '+1', 'USD'),
    ('UY', 'URY', 'Uruguay', '+598', 'UYU'),
    ('UZ', 'UZB', 'Uzbekistan', '+998', 'UZS'),
    ('VU', 'VUT', 'Vanuatu', '+678', 'VUV'),
    ('VA', 'VAT', 'Vatican City', '+39', 'EUR'),
    ('VE', 'VEN', 'Venezuela', '+58', 'VES'),
    ('VN', 'VNM', 'Vietnam', '+84', 'VND'),
    ('WF', 'WLF', 'Wallis & Futuna', '+681', 'XPF'),
    ('EH', 'ESH', 'Western Sahara', '+212', 'MAD'),
    ('YE', 'YEM', 'Yemen', '+967', 'YER'),
    ('ZM', 'ZMB', 'Zambia', '+260', 'ZMW'),
    ('ZW', 'ZWE', 'Zimbabwe', '+263', 'ZWG'),
    ('AX', 'ALA', 'Åland Islands', '+358', 'EUR')
)
INSERT INTO countries(public_id, iso2, iso3, name, phone_code, currency, status)
SELECT gen_seed_public_id('cnt'), iso2, iso3, name, phone_code, currency, 'ACTIVE'
FROM catalogue
ON CONFLICT (iso2) DO UPDATE SET
    iso3 = EXCLUDED.iso3,
    name = EXCLUDED.name,
    phone_code = EXCLUDED.phone_code,
    currency = EXCLUDED.currency,
    status = 'ACTIVE';

DO $$
BEGIN
    IF (SELECT count(*) FROM countries WHERE status = 'ACTIVE') < 250 THEN
        RAISE EXCEPTION 'Global country catalogue is incomplete';
    END IF;
END $$;
