// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: billing.sql

package dbgen

import (
	"context"
	"time"
)

const addInvoiceShipment = `-- name: AddInvoiceShipment :one
INSERT INTO invoice_shipments (
    organization_id, invoice_id, shipment_id, awb, amount_minor, tax_minor
) VALUES ($1,$2,$3,$4,$5,$6)
RETURNING id, organization_id, invoice_id, shipment_id, awb, amount_minor, tax_minor, created_at
`

type AddInvoiceShipmentParams struct {
	OrganizationID int64
	InvoiceID      int64
	ShipmentID     int64
	Awb            string
	AmountMinor    int64
	TaxMinor       int64
}

func (q *Queries) AddInvoiceShipment(ctx context.Context, arg AddInvoiceShipmentParams) (InvoiceShipment, error) {
	row := q.db.QueryRow(ctx, addInvoiceShipment,
		arg.OrganizationID,
		arg.InvoiceID,
		arg.ShipmentID,
		arg.Awb,
		arg.AmountMinor,
		arg.TaxMinor,
	)
	var i InvoiceShipment
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.InvoiceID,
		&i.ShipmentID,
		&i.Awb,
		&i.AmountMinor,
		&i.TaxMinor,
		&i.CreatedAt,
	)
	return i, err
}

const allocateInvoiceNumber = `-- name: AllocateInvoiceNumber :one


INSERT INTO invoice_sequences (organization_id, series_code, document_type, prefix, scope_key, current_value)
VALUES ($1, $2, $3,
        $4, $5, 1)
ON CONFLICT (organization_id, series_code, document_type, scope_key)
DO UPDATE SET current_value = invoice_sequences.current_value + 1, updated_at = now()
WHERE invoice_sequences.current_value < invoice_sequences.max_value
RETURNING current_value, prefix, padding
`

type AllocateInvoiceNumberParams struct {
	OrganizationID int64
	SeriesCode     string
	DocumentType   string
	Prefix         string
	ScopeKey       string
}

type AllocateInvoiceNumberRow struct {
	CurrentValue int64
	Prefix       string
	Padding      int32
}

// Billing (M25).
//
// Two properties decide the shape of everything here:
//
//  1. Numbering is concurrency-safe and gapless per series. AllocateInvoiceNumber
//     is one atomic statement, so N concurrent issuers get N distinct numbers
//     without a process-local lock (§22). Tax authorities care about gaps.
//  2. Lines are snapshots. An invoice line copies the amount, the description
//     and the tax at the moment of issue and never joins back to a rate card
//     at read time, so editing a rate card tomorrow cannot change an invoice
//     issued today (§19, §26).
//
// ---------------------------------------------------------------------------
// Numbering
// ---------------------------------------------------------------------------
// The statutory counter. One atomic UPSERT: concurrent issuers serialise on the
// row rather than on an application lock, and the WHERE guard refuses to wrap
// around onto a number that already identifies a document.
func (q *Queries) AllocateInvoiceNumber(ctx context.Context, arg AllocateInvoiceNumberParams) (AllocateInvoiceNumberRow, error) {
	row := q.db.QueryRow(ctx, allocateInvoiceNumber,
		arg.OrganizationID,
		arg.SeriesCode,
		arg.DocumentType,
		arg.Prefix,
		arg.ScopeKey,
	)
	var i AllocateInvoiceNumberRow
	err := row.Scan(&i.CurrentValue, &i.Prefix, &i.Padding)
	return i, err
}

const applyInvoiceTotals = `-- name: ApplyInvoiceTotals :one
UPDATE invoices
   SET subtotal_minor = $1,
       discount_minor = $2,
       taxable_minor = $3,
       tax_minor = $4,
       rounding_minor = $5,
       total_minor = $6,
       shipment_count = $7
 WHERE organization_id = $8 AND id = $9
   AND status = 'DRAFT'
RETURNING id, public_id, organization_id, invoice_number, series_code, document_type, customer_id, business_account_id, billing_run_id, billing_mode, period_start, period_end, issue_date, due_date, status, currency, subtotal_minor, discount_minor, taxable_minor, tax_minor, rounding_minor, total_minor, paid_minor, credited_minor, shipment_count, bill_to, supplier, tax_metadata, journal_transaction_id, document_object_id, notes, cancel_reason, issued_at, issued_by, cancelled_at, request_id, created_by, created_at, updated_at, version
`

type ApplyInvoiceTotalsParams struct {
	SubtotalMinor  int64
	DiscountMinor  int64
	TaxableMinor   int64
	TaxMinor       int64
	RoundingMinor  int64
	TotalMinor     int64
	ShipmentCount  int32
	OrganizationID int64
	ID             int64
}

// Writes the computed header. Only while DRAFT; the invoices_guard trigger
// refuses it once issued.
func (q *Queries) ApplyInvoiceTotals(ctx context.Context, arg ApplyInvoiceTotalsParams) (Invoice, error) {
	row := q.db.QueryRow(ctx, applyInvoiceTotals,
		arg.SubtotalMinor,
		arg.DiscountMinor,
		arg.TaxableMinor,
		arg.TaxMinor,
		arg.RoundingMinor,
		arg.TotalMinor,
		arg.ShipmentCount,
		arg.OrganizationID,
		arg.ID,
	)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrganizationID,
		&i.InvoiceNumber,
		&i.SeriesCode,
		&i.DocumentType,
		&i.CustomerID,
		&i.BusinessAccountID,
		&i.BillingRunID,
		&i.BillingMode,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.IssueDate,
		&i.DueDate,
		&i.Status,
		&i.Currency,
		&i.SubtotalMinor,
		&i.DiscountMinor,
		&i.TaxableMinor,
		&i.TaxMinor,
		&i.RoundingMinor,
		&i.TotalMinor,
		&i.PaidMinor,
		&i.CreditedMinor,
		&i.ShipmentCount,
		&i.BillTo,
		&i.Supplier,
		&i.TaxMetadata,
		&i.JournalTransactionID,
		&i.DocumentObjectID,
		&i.Notes,
		&i.CancelReason,
		&i.IssuedAt,
		&i.IssuedBy,
		&i.CancelledAt,
		&i.RequestID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const attachInvoiceDocument = `-- name: AttachInvoiceDocument :one
UPDATE invoices SET document_object_id = $3
 WHERE organization_id = $1 AND id = $2
RETURNING id, public_id, organization_id, invoice_number, series_code, document_type, customer_id, business_account_id, billing_run_id, billing_mode, period_start, period_end, issue_date, due_date, status, currency, subtotal_minor, discount_minor, taxable_minor, tax_minor, rounding_minor, total_minor, paid_minor, credited_minor, shipment_count, bill_to, supplier, tax_metadata, journal_transaction_id, document_object_id, notes, cancel_reason, issued_at, issued_by, cancelled_at, request_id, created_by, created_at, updated_at, version
`

type AttachInvoiceDocumentParams struct {
	OrganizationID   int64
	ID               int64
	DocumentObjectID *int64
}

func (q *Queries) AttachInvoiceDocument(ctx context.Context, arg AttachInvoiceDocumentParams) (Invoice, error) {
	row := q.db.QueryRow(ctx, attachInvoiceDocument, arg.OrganizationID, arg.ID, arg.DocumentObjectID)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrganizationID,
		&i.InvoiceNumber,
		&i.SeriesCode,
		&i.DocumentType,
		&i.CustomerID,
		&i.BusinessAccountID,
		&i.BillingRunID,
		&i.BillingMode,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.IssueDate,
		&i.DueDate,
		&i.Status,
		&i.Currency,
		&i.SubtotalMinor,
		&i.DiscountMinor,
		&i.TaxableMinor,
		&i.TaxMinor,
		&i.RoundingMinor,
		&i.TotalMinor,
		&i.PaidMinor,
		&i.CreditedMinor,
		&i.ShipmentCount,
		&i.BillTo,
		&i.Supplier,
		&i.TaxMetadata,
		&i.JournalTransactionID,
		&i.DocumentObjectID,
		&i.Notes,
		&i.CancelReason,
		&i.IssuedAt,
		&i.IssuedBy,
		&i.CancelledAt,
		&i.RequestID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const cancelInvoice = `-- name: CancelInvoice :one
UPDATE invoices
   SET status = 'CANCELLED', cancel_reason = $3, cancelled_at = now()
 WHERE organization_id = $1 AND id = $2
   AND status IN ('DRAFT','ISSUED')
   AND paid_minor = 0
RETURNING id, public_id, organization_id, invoice_number, series_code, document_type, customer_id, business_account_id, billing_run_id, billing_mode, period_start, period_end, issue_date, due_date, status, currency, subtotal_minor, discount_minor, taxable_minor, tax_minor, rounding_minor, total_minor, paid_minor, credited_minor, shipment_count, bill_to, supplier, tax_metadata, journal_transaction_id, document_object_id, notes, cancel_reason, issued_at, issued_by, cancelled_at, request_id, created_by, created_at, updated_at, version
`

type CancelInvoiceParams struct {
	OrganizationID int64
	ID             int64
	CancelReason   *string
}

func (q *Queries) CancelInvoice(ctx context.Context, arg CancelInvoiceParams) (Invoice, error) {
	row := q.db.QueryRow(ctx, cancelInvoice, arg.OrganizationID, arg.ID, arg.CancelReason)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrganizationID,
		&i.InvoiceNumber,
		&i.SeriesCode,
		&i.DocumentType,
		&i.CustomerID,
		&i.BusinessAccountID,
		&i.BillingRunID,
		&i.BillingMode,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.IssueDate,
		&i.DueDate,
		&i.Status,
		&i.Currency,
		&i.SubtotalMinor,
		&i.DiscountMinor,
		&i.TaxableMinor,
		&i.TaxMinor,
		&i.RoundingMinor,
		&i.TotalMinor,
		&i.PaidMinor,
		&i.CreditedMinor,
		&i.ShipmentCount,
		&i.BillTo,
		&i.Supplier,
		&i.TaxMetadata,
		&i.JournalTransactionID,
		&i.DocumentObjectID,
		&i.Notes,
		&i.CancelReason,
		&i.IssuedAt,
		&i.IssuedBy,
		&i.CancelledAt,
		&i.RequestID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const completeBillingRun = `-- name: CompleteBillingRun :one
UPDATE billing_runs
   SET status = $1, completed_at = now(),
       invoice_count = $2,
       shipment_count = $3,
       total_minor = $4,
       error_count = $5,
       errors = $6
 WHERE organization_id = $7 AND id = $8
   AND status = 'RUNNING'
RETURNING id, public_id, organization_id, run_code, billing_cycle, period_start, period_end, status, customer_filter, invoice_count, shipment_count, total_minor, currency, error_count, errors, started_at, completed_at, created_by, request_id, created_at, updated_at
`

type CompleteBillingRunParams struct {
	Status         string
	InvoiceCount   int32
	ShipmentCount  int32
	TotalMinor     int64
	ErrorCount     int32
	Errors         []byte
	OrganizationID int64
	ID             int64
}

func (q *Queries) CompleteBillingRun(ctx context.Context, arg CompleteBillingRunParams) (BillingRun, error) {
	row := q.db.QueryRow(ctx, completeBillingRun,
		arg.Status,
		arg.InvoiceCount,
		arg.ShipmentCount,
		arg.TotalMinor,
		arg.ErrorCount,
		arg.Errors,
		arg.OrganizationID,
		arg.ID,
	)
	var i BillingRun
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrganizationID,
		&i.RunCode,
		&i.BillingCycle,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.Status,
		&i.CustomerFilter,
		&i.InvoiceCount,
		&i.ShipmentCount,
		&i.TotalMinor,
		&i.Currency,
		&i.ErrorCount,
		&i.Errors,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedBy,
		&i.RequestID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countInvoices = `-- name: CountInvoices :one
SELECT count(*) FROM invoices i
WHERE i.organization_id = $1
  AND ($2::text IS NULL OR i.status = $2::text)
  AND ($3::bigint IS NULL OR i.customer_id = $3::bigint)
`

type CountInvoicesParams struct {
	OrganizationID int64
	Status         *string
	CustomerID     *int64
}

func (q *Queries) CountInvoices(ctx context.Context, arg CountInvoicesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countInvoices, arg.OrganizationID, arg.Status, arg.CustomerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBillingRun = `-- name: CreateBillingRun :one

INSERT INTO billing_runs (
    public_id, organization_id, run_code, billing_cycle, period_start, period_end,
    status, customer_filter, currency, created_by, request_id
) VALUES ($1,$2,$3,$4,$5,$6,'PENDING',$7,$8,$9,$10)
RETURNING id, public_id, organization_id, run_code, billing_cycle, period_start, period_end, status, customer_filter, invoice_count, shipment_count, total_minor, currency, error_count, errors, started_at, completed_at, created_by, request_id, created_at, updated_at
`

type CreateBillingRunParams struct {
	PublicID       string
	OrganizationID int64
	RunCode        string
	BillingCycle   string
	PeriodStart    time.Time
	PeriodEnd      time.Time
	CustomerFilter []byte
	Currency       string
	CreatedBy      *int64
	RequestID      *string
}

// ---------------------------------------------------------------------------
// Billing runs
// ---------------------------------------------------------------------------
func (q *Queries) CreateBillingRun(ctx context.Context, arg CreateBillingRunParams) (BillingRun, error) {
	row := q.db.QueryRow(ctx, createBillingRun,
		arg.PublicID,
		arg.OrganizationID,
		arg.RunCode,
		arg.BillingCycle,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.CustomerFilter,
		arg.Currency,
		arg.CreatedBy,
		arg.RequestID,
	)
	var i BillingRun
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrganizationID,
		&i.RunCode,
		&i.BillingCycle,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.Status,
		&i.CustomerFilter,
		&i.InvoiceCount,
		&i.ShipmentCount,
		&i.TotalMinor,
		&i.Currency,
		&i.ErrorCount,
		&i.Errors,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedBy,
		&i.RequestID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCreditNote = `-- name: CreateCreditNote :one

INSERT INTO credit_notes (
    public_id, organization_id, note_number, note_type, invoice_id, customer_id,
    reason_code, reason, issue_date, currency, subtotal_minor, tax_minor,
    total_minor, status, tax_metadata, created_by, request_id
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,'DRAFT',$14,$15,$16)
RETURNING id, public_id, organization_id, note_number, note_type, invoice_id, customer_id, reason_code, reason, issue_date, currency, subtotal_minor, tax_minor, total_minor, status, journal_transaction_id, document_object_id, tax_metadata, issued_at, issued_by, approved_by, approved_at, request_id, created_by, created_at, updated_at
`

type CreateCreditNoteParams struct {
	PublicID       string
	OrganizationID int64
	NoteNumber     string
	NoteType       string
	InvoiceID      *int64
	CustomerID     int64
	ReasonCode     string
	Reason         string
	IssueDate      time.Time
	Currency       string
	SubtotalMinor  int64
	TaxMinor       int64
	TotalMinor     int64
	TaxMetadata    []byte
	CreatedBy      *int64
	RequestID      *string
}

// ---------------------------------------------------------------------------
// Credit and debit notes
// ---------------------------------------------------------------------------
func (q *Queries) CreateCreditNote(ctx context.Context, arg CreateCreditNoteParams) (CreditNote, error) {
	row := q.db.QueryRow(ctx, createCreditNote,
		arg.PublicID,
		arg.OrganizationID,
		arg.NoteNumber,
		arg.NoteType,
		arg.InvoiceID,
		arg.CustomerID,
		arg.ReasonCode,
		arg.Reason,
		arg.IssueDate,
		arg.Currency,
		arg.SubtotalMinor,
		arg.TaxMinor,
		arg.TotalMinor,
		arg.TaxMetadata,
		arg.CreatedBy,
		arg.RequestID,
	)
	var i CreditNote
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrganizationID,
		&i.NoteNumber,
		&i.NoteType,
		&i.InvoiceID,
		&i.CustomerID,
		&i.ReasonCode,
		&i.Reason,
		&i.IssueDate,
		&i.Currency,
		&i.SubtotalMinor,
		&i.TaxMinor,
		&i.TotalMinor,
		&i.Status,
		&i.JournalTransactionID,
		&i.DocumentObjectID,
		&i.TaxMetadata,
		&i.IssuedAt,
		&i.IssuedBy,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.RequestID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCreditNoteLine = `-- name: CreateCreditNoteLine :one
INSERT INTO credit_note_lines (
    organization_id, credit_note_id, line_no, description,
    amount_minor, tax_minor, total_minor, currency, invoice_line_id, shipment_id
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)
RETURNING id, organization_id, credit_note_id, line_no, description, amount_minor, tax_minor, total_minor, currency, invoice_line_id, shipment_id, created_at
`

type CreateCreditNoteLineParams struct {
	OrganizationID int64
	CreditNoteID   int64
	LineNo         int32
	Description    string
	AmountMinor    int64
	TaxMinor       int64
	TotalMinor     int64
	Currency       string
	InvoiceLineID  *int64
	ShipmentID     *int64
}

func (q *Queries) CreateCreditNoteLine(ctx context.Context, arg CreateCreditNoteLineParams) (CreditNoteLine, error) {
	row := q.db.QueryRow(ctx, createCreditNoteLine,
		arg.OrganizationID,
		arg.CreditNoteID,
		arg.LineNo,
		arg.Description,
		arg.AmountMinor,
		arg.TaxMinor,
		arg.TotalMinor,
		arg.Currency,
		arg.InvoiceLineID,
		arg.ShipmentID,
	)
	var i CreditNoteLine
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CreditNoteID,
		&i.LineNo,
		&i.Description,
		&i.AmountMinor,
		&i.TaxMinor,
		&i.TotalMinor,
		&i.Currency,
		&i.InvoiceLineID,
		&i.ShipmentID,
		&i.CreatedAt,
	)
	return i, err
}

const createInvoice = `-- name: CreateInvoice :one

INSERT INTO invoices (
    public_id, organization_id, invoice_number, series_code, document_type,
    customer_id, business_account_id, billing_run_id, billing_mode,
    period_start, period_end, issue_date, due_date, status, currency,
    bill_to, supplier, tax_metadata, notes, created_by, request_id
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,'DRAFT',$14,$15,$16,$17,$18,$19,$20)
RETURNING id, public_id, organization_id, invoice_number, series_code, document_type, customer_id, business_account_id, billing_run_id, billing_mode, period_start, period_end, issue_date, due_date, status, currency, subtotal_minor, discount_minor, taxable_minor, tax_minor, rounding_minor, total_minor, paid_minor, credited_minor, shipment_count, bill_to, supplier, tax_metadata, journal_transaction_id, document_object_id, notes, cancel_reason, issued_at, issued_by, cancelled_at, request_id, created_by, created_at, updated_at, version
`

type CreateInvoiceParams struct {
	PublicID          string
	OrganizationID    int64
	InvoiceNumber     string
	SeriesCode        string
	DocumentType      string
	CustomerID        int64
	BusinessAccountID *int64
	BillingRunID      *int64
	BillingMode       string
	PeriodStart       *time.Time
	PeriodEnd         *time.Time
	IssueDate         time.Time
	DueDate           time.Time
	Currency          string
	BillTo            []byte
	Supplier          []byte
	TaxMetadata       []byte
	Notes             *string
	CreatedBy         *int64
	RequestID         *string
}

// ---------------------------------------------------------------------------
// Invoices
// ---------------------------------------------------------------------------
func (q *Queries) CreateInvoice(ctx context.Context, arg CreateInvoiceParams) (Invoice, error) {
	row := q.db.QueryRow(ctx, createInvoice,
		arg.PublicID,
		arg.OrganizationID,
		arg.InvoiceNumber,
		arg.SeriesCode,
		arg.DocumentType,
		arg.CustomerID,
		arg.BusinessAccountID,
		arg.BillingRunID,
		arg.BillingMode,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.IssueDate,
		arg.DueDate,
		arg.Currency,
		arg.BillTo,
		arg.Supplier,
		arg.TaxMetadata,
		arg.Notes,
		arg.CreatedBy,
		arg.RequestID,
	)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrganizationID,
		&i.InvoiceNumber,
		&i.SeriesCode,
		&i.DocumentType,
		&i.CustomerID,
		&i.BusinessAccountID,
		&i.BillingRunID,
		&i.BillingMode,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.IssueDate,
		&i.DueDate,
		&i.Status,
		&i.Currency,
		&i.SubtotalMinor,
		&i.DiscountMinor,
		&i.TaxableMinor,
		&i.TaxMinor,
		&i.RoundingMinor,
		&i.TotalMinor,
		&i.PaidMinor,
		&i.CreditedMinor,
		&i.ShipmentCount,
		&i.BillTo,
		&i.Supplier,
		&i.TaxMetadata,
		&i.JournalTransactionID,
		&i.DocumentObjectID,
		&i.Notes,
		&i.CancelReason,
		&i.IssuedAt,
		&i.IssuedBy,
		&i.CancelledAt,
		&i.RequestID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const createInvoiceLine = `-- name: CreateInvoiceLine :one

INSERT INTO invoice_lines (
    public_id, organization_id, invoice_id, line_no, line_type, description,
    hsn_sac_code, quantity, unit_price_minor, amount_minor, discount_minor,
    taxable_minor, tax_minor, total_minor, currency, shipment_id,
    charge_snapshot_id, metadata
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18)
RETURNING id, public_id, organization_id, invoice_id, line_no, line_type, description, hsn_sac_code, quantity, unit_price_minor, amount_minor, discount_minor, taxable_minor, tax_minor, total_minor, currency, shipment_id, charge_snapshot_id, metadata, created_at
`

type CreateInvoiceLineParams struct {
	PublicID         string
	OrganizationID   int64
	InvoiceID        int64
	LineNo           int32
	LineType         string
	Description      string
	HsnSacCode       *string
	Quantity         int32
	UnitPriceMinor   int64
	AmountMinor      int64
	DiscountMinor    int64
	TaxableMinor     int64
	TaxMinor         int64
	TotalMinor       int64
	Currency         string
	ShipmentID       *int64
	ChargeSnapshotID *int64
	Metadata         []byte
}

// ---------------------------------------------------------------------------
// Invoice lines — snapshots
// ---------------------------------------------------------------------------
func (q *Queries) CreateInvoiceLine(ctx context.Context, arg CreateInvoiceLineParams) (InvoiceLine, error) {
	row := q.db.QueryRow(ctx, createInvoiceLine,
		arg.PublicID,
		arg.OrganizationID,
		arg.InvoiceID,
		arg.LineNo,
		arg.LineType,
		arg.Description,
		arg.HsnSacCode,
		arg.Quantity,
		arg.UnitPriceMinor,
		arg.AmountMinor,
		arg.DiscountMinor,
		arg.TaxableMinor,
		arg.TaxMinor,
		arg.TotalMinor,
		arg.Currency,
		arg.ShipmentID,
		arg.ChargeSnapshotID,
		arg.Metadata,
	)
	var i InvoiceLine
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrganizationID,
		&i.InvoiceID,
		&i.LineNo,
		&i.LineType,
		&i.Description,
		&i.HsnSacCode,
		&i.Quantity,
		&i.UnitPriceMinor,
		&i.AmountMinor,
		&i.DiscountMinor,
		&i.TaxableMinor,
		&i.TaxMinor,
		&i.TotalMinor,
		&i.Currency,
		&i.ShipmentID,
		&i.ChargeSnapshotID,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const createInvoicePayment = `-- name: CreateInvoicePayment :one

INSERT INTO invoice_payments (
    public_id, organization_id, invoice_id, customer_id, payment_number,
    amount_minor, currency, payment_mode, reference, received_on,
    status, journal_transaction_id, recorded_by, request_id
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,'RECORDED',$11,$12,$13)
RETURNING id, public_id, organization_id, invoice_id, customer_id, payment_number, amount_minor, currency, payment_mode, reference, received_on, status, journal_transaction_id, recorded_by, request_id, created_at, updated_at
`

type CreateInvoicePaymentParams struct {
	PublicID             string
	OrganizationID       int64
	InvoiceID            int64
	CustomerID           int64
	PaymentNumber        string
	AmountMinor          int64
	Currency             string
	PaymentMode          string
	Reference            *string
	ReceivedOn           time.Time
	JournalTransactionID *int64
	RecordedBy           int64
	RequestID            *string
}

// ---------------------------------------------------------------------------
// Invoice payments
// ---------------------------------------------------------------------------
func (q *Queries) CreateInvoicePayment(ctx context.Context, arg CreateInvoicePaymentParams) (InvoicePayment, error) {
	row := q.db.QueryRow(ctx, createInvoicePayment,
		arg.PublicID,
		arg.OrganizationID,
		arg.InvoiceID,
		arg.CustomerID,
		arg.PaymentNumber,
		arg.AmountMinor,
		arg.Currency,
		arg.PaymentMode,
		arg.Reference,
		arg.ReceivedOn,
		arg.JournalTransactionID,
		arg.RecordedBy,
		arg.RequestID,
	)
	var i InvoicePayment
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrganizationID,
		&i.InvoiceID,
		&i.CustomerID,
		&i.PaymentNumber,
		&i.AmountMinor,
		&i.Currency,
		&i.PaymentMode,
		&i.Reference,
		&i.ReceivedOn,
		&i.Status,
		&i.JournalTransactionID,
		&i.RecordedBy,
		&i.RequestID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTaxComponent = `-- name: CreateTaxComponent :one

INSERT INTO tax_components (
    public_id, organization_id, invoice_id, invoice_line_id, credit_note_id,
    component_code, component_name, rate_bp, taxable_minor, tax_minor,
    currency, metadata
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12)
RETURNING id, public_id, organization_id, invoice_id, invoice_line_id, credit_note_id, component_code, component_name, rate_bp, taxable_minor, tax_minor, currency, metadata, created_at
`

type CreateTaxComponentParams struct {
	PublicID       string
	OrganizationID int64
	InvoiceID      *int64
	InvoiceLineID  *int64
	CreditNoteID   *int64
	ComponentCode  string
	ComponentName  string
	RateBp         int32
	TaxableMinor   int64
	TaxMinor       int64
	Currency       string
	Metadata       []byte
}

// ---------------------------------------------------------------------------
// Tax components
// ---------------------------------------------------------------------------
func (q *Queries) CreateTaxComponent(ctx context.Context, arg CreateTaxComponentParams) (TaxComponent, error) {
	row := q.db.QueryRow(ctx, createTaxComponent,
		arg.PublicID,
		arg.OrganizationID,
		arg.InvoiceID,
		arg.InvoiceLineID,
		arg.CreditNoteID,
		arg.ComponentCode,
		arg.ComponentName,
		arg.RateBp,
		arg.TaxableMinor,
		arg.TaxMinor,
		arg.Currency,
		arg.Metadata,
	)
	var i TaxComponent
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrganizationID,
		&i.InvoiceID,
		&i.InvoiceLineID,
		&i.CreditNoteID,
		&i.ComponentCode,
		&i.ComponentName,
		&i.RateBp,
		&i.TaxableMinor,
		&i.TaxMinor,
		&i.Currency,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const deleteInvoiceLines = `-- name: DeleteInvoiceLines :exec
DELETE FROM invoice_lines WHERE invoice_id = $1
`

func (q *Queries) DeleteInvoiceLines(ctx context.Context, invoiceID int64) error {
	_, err := q.db.Exec(ctx, deleteInvoiceLines, invoiceID)
	return err
}

const deleteInvoiceShipments = `-- name: DeleteInvoiceShipments :exec
DELETE FROM invoice_shipments WHERE invoice_id = $1
`

func (q *Queries) DeleteInvoiceShipments(ctx context.Context, invoiceID int64) error {
	_, err := q.db.Exec(ctx, deleteInvoiceShipments, invoiceID)
	return err
}

const deleteInvoiceTaxComponents = `-- name: DeleteInvoiceTaxComponents :exec
DELETE FROM tax_components WHERE invoice_id = $1
`

func (q *Queries) DeleteInvoiceTaxComponents(ctx context.Context, invoiceID *int64) error {
	_, err := q.db.Exec(ctx, deleteInvoiceTaxComponents, invoiceID)
	return err
}

const findPaymentByReference = `-- name: FindPaymentByReference :one
SELECT id, public_id, organization_id, invoice_id, customer_id, payment_number, amount_minor, currency, payment_mode, reference, received_on, status, journal_transaction_id, recorded_by, request_id, created_at, updated_at FROM invoice_payments
WHERE organization_id = $1 AND invoice_id = $2 AND reference = $3
`

type FindPaymentByReferenceParams struct {
	OrganizationID int64
	InvoiceID      int64
	Reference      *string
}

// Idempotency probe for payment callbacks: a gateway retrying a webhook must
// not bank the same payment twice.
func (q *Queries) FindPaymentByReference(ctx context.Context, arg FindPaymentByReferenceParams) (InvoicePayment, error) {
	row := q.db.QueryRow(ctx, findPaymentByReference, arg.OrganizationID, arg.InvoiceID, arg.Reference)
	var i InvoicePayment
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrganizationID,
		&i.InvoiceID,
		&i.CustomerID,
		&i.PaymentNumber,
		&i.AmountMinor,
		&i.Currency,
		&i.PaymentMode,
		&i.Reference,
		&i.ReceivedOn,
		&i.Status,
		&i.JournalTransactionID,
		&i.RecordedBy,
		&i.RequestID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBillingRunByPublicID = `-- name: GetBillingRunByPublicID :one
SELECT id, public_id, organization_id, run_code, billing_cycle, period_start, period_end, status, customer_filter, invoice_count, shipment_count, total_minor, currency, error_count, errors, started_at, completed_at, created_by, request_id, created_at, updated_at FROM billing_runs WHERE organization_id = $1 AND public_id = $2
`

type GetBillingRunByPublicIDParams struct {
	OrganizationID int64
	PublicID       string
}

func (q *Queries) GetBillingRunByPublicID(ctx context.Context, arg GetBillingRunByPublicIDParams) (BillingRun, error) {
	row := q.db.QueryRow(ctx, getBillingRunByPublicID, arg.OrganizationID, arg.PublicID)
	var i BillingRun
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrganizationID,
		&i.RunCode,
		&i.BillingCycle,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.Status,
		&i.CustomerFilter,
		&i.InvoiceCount,
		&i.ShipmentCount,
		&i.TotalMinor,
		&i.Currency,
		&i.ErrorCount,
		&i.Errors,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedBy,
		&i.RequestID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCreditNoteByPublicID = `-- name: GetCreditNoteByPublicID :one
SELECT n.id, n.public_id, n.organization_id, n.note_number, n.note_type, n.invoice_id, n.customer_id, n.reason_code, n.reason, n.issue_date, n.currency, n.subtotal_minor, n.tax_minor, n.total_minor, n.status, n.journal_transaction_id, n.document_object_id, n.tax_metadata, n.issued_at, n.issued_by, n.approved_by, n.approved_at, n.request_id, n.created_by, n.created_at, n.updated_at, c.code AS customer_code, c.name AS customer_name,
       i.invoice_number
FROM credit_notes n
JOIN customers c ON c.id = n.customer_id
LEFT JOIN invoices i ON i.id = n.invoice_id
WHERE n.organization_id = $1 AND n.public_id = $2
`

type GetCreditNoteByPublicIDParams struct {
	OrganizationID int64
	PublicID       string
}

type GetCreditNoteByPublicIDRow struct {
	ID                   int64
	PublicID             string
	OrganizationID       int64
	NoteNumber           string
	NoteType             string
	InvoiceID            *int64
	CustomerID           int64
	ReasonCode           string
	Reason               string
	IssueDate            time.Time
	Currency             string
	SubtotalMinor        int64
	TaxMinor             int64
	TotalMinor           int64
	Status               string
	JournalTransactionID *int64
	DocumentObjectID     *int64
	TaxMetadata          []byte
	IssuedAt             *time.Time
	IssuedBy             *int64
	ApprovedBy           *int64
	ApprovedAt           *time.Time
	RequestID            *string
	CreatedBy            *int64
	CreatedAt            time.Time
	UpdatedAt            time.Time
	CustomerCode         string
	CustomerName         string
	InvoiceNumber        *string
}

func (q *Queries) GetCreditNoteByPublicID(ctx context.Context, arg GetCreditNoteByPublicIDParams) (GetCreditNoteByPublicIDRow, error) {
	row := q.db.QueryRow(ctx, getCreditNoteByPublicID, arg.OrganizationID, arg.PublicID)
	var i GetCreditNoteByPublicIDRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrganizationID,
		&i.NoteNumber,
		&i.NoteType,
		&i.InvoiceID,
		&i.CustomerID,
		&i.ReasonCode,
		&i.Reason,
		&i.IssueDate,
		&i.Currency,
		&i.SubtotalMinor,
		&i.TaxMinor,
		&i.TotalMinor,
		&i.Status,
		&i.JournalTransactionID,
		&i.DocumentObjectID,
		&i.TaxMetadata,
		&i.IssuedAt,
		&i.IssuedBy,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.RequestID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CustomerCode,
		&i.CustomerName,
		&i.InvoiceNumber,
	)
	return i, err
}

const getCustomerOutstanding = `-- name: GetCustomerOutstanding :one
SELECT
    COALESCE(SUM(total_minor - paid_minor - credited_minor), 0)::bigint AS outstanding_minor,
    COALESCE(SUM(total_minor - paid_minor - credited_minor)
             FILTER (WHERE due_date < current_date), 0)::bigint AS overdue_minor,
    count(*)::bigint AS invoice_count
FROM invoices
WHERE organization_id = $1 AND customer_id = $2
  AND status IN ('ISSUED','PARTIALLY_PAID','OVERDUE')
`

type GetCustomerOutstandingParams struct {
	OrganizationID int64
	CustomerID     int64
}

type GetCustomerOutstandingRow struct {
	OutstandingMinor int64
	OverdueMinor     int64
	InvoiceCount     int64
}

// What a customer owes across every open invoice. A SUM, never a stored
// balance (§25 applied to receivables as well as COD).
func (q *Queries) GetCustomerOutstanding(ctx context.Context, arg GetCustomerOutstandingParams) (GetCustomerOutstandingRow, error) {
	row := q.db.QueryRow(ctx, getCustomerOutstanding, arg.OrganizationID, arg.CustomerID)
	var i GetCustomerOutstandingRow
	err := row.Scan(&i.OutstandingMinor, &i.OverdueMinor, &i.InvoiceCount)
	return i, err
}

const getInvoiceByID = `-- name: GetInvoiceByID :one
SELECT id, public_id, organization_id, invoice_number, series_code, document_type, customer_id, business_account_id, billing_run_id, billing_mode, period_start, period_end, issue_date, due_date, status, currency, subtotal_minor, discount_minor, taxable_minor, tax_minor, rounding_minor, total_minor, paid_minor, credited_minor, shipment_count, bill_to, supplier, tax_metadata, journal_transaction_id, document_object_id, notes, cancel_reason, issued_at, issued_by, cancelled_at, request_id, created_by, created_at, updated_at, version FROM invoices WHERE organization_id = $1 AND id = $2
`

type GetInvoiceByIDParams struct {
	OrganizationID int64
	ID             int64
}

func (q *Queries) GetInvoiceByID(ctx context.Context, arg GetInvoiceByIDParams) (Invoice, error) {
	row := q.db.QueryRow(ctx, getInvoiceByID, arg.OrganizationID, arg.ID)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrganizationID,
		&i.InvoiceNumber,
		&i.SeriesCode,
		&i.DocumentType,
		&i.CustomerID,
		&i.BusinessAccountID,
		&i.BillingRunID,
		&i.BillingMode,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.IssueDate,
		&i.DueDate,
		&i.Status,
		&i.Currency,
		&i.SubtotalMinor,
		&i.DiscountMinor,
		&i.TaxableMinor,
		&i.TaxMinor,
		&i.RoundingMinor,
		&i.TotalMinor,
		&i.PaidMinor,
		&i.CreditedMinor,
		&i.ShipmentCount,
		&i.BillTo,
		&i.Supplier,
		&i.TaxMetadata,
		&i.JournalTransactionID,
		&i.DocumentObjectID,
		&i.Notes,
		&i.CancelReason,
		&i.IssuedAt,
		&i.IssuedBy,
		&i.CancelledAt,
		&i.RequestID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const getInvoiceByPublicID = `-- name: GetInvoiceByPublicID :one
SELECT i.id, i.public_id, i.organization_id, i.invoice_number, i.series_code, i.document_type, i.customer_id, i.business_account_id, i.billing_run_id, i.billing_mode, i.period_start, i.period_end, i.issue_date, i.due_date, i.status, i.currency, i.subtotal_minor, i.discount_minor, i.taxable_minor, i.tax_minor, i.rounding_minor, i.total_minor, i.paid_minor, i.credited_minor, i.shipment_count, i.bill_to, i.supplier, i.tax_metadata, i.journal_transaction_id, i.document_object_id, i.notes, i.cancel_reason, i.issued_at, i.issued_by, i.cancelled_at, i.request_id, i.created_by, i.created_at, i.updated_at, i.version, c.code AS customer_code, c.name AS customer_name,
       u.full_name AS issued_by_name
FROM invoices i
JOIN customers c ON c.id = i.customer_id
LEFT JOIN users u ON u.id = i.issued_by
WHERE i.organization_id = $1 AND i.public_id = $2
`

type GetInvoiceByPublicIDParams struct {
	OrganizationID int64
	PublicID       string
}

type GetInvoiceByPublicIDRow struct {
	ID                   int64
	PublicID             string
	OrganizationID       int64
	InvoiceNumber        string
	SeriesCode           string
	DocumentType         string
	CustomerID           int64
	BusinessAccountID    *int64
	BillingRunID         *int64
	BillingMode          string
	PeriodStart          *time.Time
	PeriodEnd            *time.Time
	IssueDate            time.Time
	DueDate              time.Time
	Status               string
	Currency             string
	SubtotalMinor        int64
	DiscountMinor        int64
	TaxableMinor         int64
	TaxMinor             int64
	RoundingMinor        int64
	TotalMinor           int64
	PaidMinor            int64
	CreditedMinor        int64
	ShipmentCount        int32
	BillTo               []byte
	Supplier             []byte
	TaxMetadata          []byte
	JournalTransactionID *int64
	DocumentObjectID     *int64
	Notes                *string
	CancelReason         *string
	IssuedAt             *time.Time
	IssuedBy             *int64
	CancelledAt          *time.Time
	RequestID            *string
	CreatedBy            *int64
	CreatedAt            time.Time
	UpdatedAt            time.Time
	Version              int32
	CustomerCode         string
	CustomerName         string
	IssuedByName         *string
}

func (q *Queries) GetInvoiceByPublicID(ctx context.Context, arg GetInvoiceByPublicIDParams) (GetInvoiceByPublicIDRow, error) {
	row := q.db.QueryRow(ctx, getInvoiceByPublicID, arg.OrganizationID, arg.PublicID)
	var i GetInvoiceByPublicIDRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrganizationID,
		&i.InvoiceNumber,
		&i.SeriesCode,
		&i.DocumentType,
		&i.CustomerID,
		&i.BusinessAccountID,
		&i.BillingRunID,
		&i.BillingMode,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.IssueDate,
		&i.DueDate,
		&i.Status,
		&i.Currency,
		&i.SubtotalMinor,
		&i.DiscountMinor,
		&i.TaxableMinor,
		&i.TaxMinor,
		&i.RoundingMinor,
		&i.TotalMinor,
		&i.PaidMinor,
		&i.CreditedMinor,
		&i.ShipmentCount,
		&i.BillTo,
		&i.Supplier,
		&i.TaxMetadata,
		&i.JournalTransactionID,
		&i.DocumentObjectID,
		&i.Notes,
		&i.CancelReason,
		&i.IssuedAt,
		&i.IssuedBy,
		&i.CancelledAt,
		&i.RequestID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
		&i.CustomerCode,
		&i.CustomerName,
		&i.IssuedByName,
	)
	return i, err
}

const getInvoiceSequence = `-- name: GetInvoiceSequence :one
SELECT id, organization_id, series_code, document_type, prefix, scope_key, current_value, max_value, padding, updated_at FROM invoice_sequences
WHERE organization_id = $1 AND series_code = $2 AND document_type = $3 AND scope_key = $4
`

type GetInvoiceSequenceParams struct {
	OrganizationID int64
	SeriesCode     string
	DocumentType   string
	ScopeKey       string
}

func (q *Queries) GetInvoiceSequence(ctx context.Context, arg GetInvoiceSequenceParams) (InvoiceSequence, error) {
	row := q.db.QueryRow(ctx, getInvoiceSequence,
		arg.OrganizationID,
		arg.SeriesCode,
		arg.DocumentType,
		arg.ScopeKey,
	)
	var i InvoiceSequence
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.SeriesCode,
		&i.DocumentType,
		&i.Prefix,
		&i.ScopeKey,
		&i.CurrentValue,
		&i.MaxValue,
		&i.Padding,
		&i.UpdatedAt,
	)
	return i, err
}

const issueCreditNote = `-- name: IssueCreditNote :one
UPDATE credit_notes
   SET status = 'ISSUED', note_number = $1,
       issued_at = now(), issued_by = $2,
       approved_by = $3, approved_at = now(),
       journal_transaction_id = $4
 WHERE organization_id = $5 AND id = $6
   AND status = 'DRAFT'
   AND (created_by IS NULL OR created_by <> $3)
RETURNING id, public_id, organization_id, note_number, note_type, invoice_id, customer_id, reason_code, reason, issue_date, currency, subtotal_minor, tax_minor, total_minor, status, journal_transaction_id, document_object_id, tax_metadata, issued_at, issued_by, approved_by, approved_at, request_id, created_by, created_at, updated_at
`

type IssueCreditNoteParams struct {
	NoteNumber           string
	IssuedBy             *int64
	ApprovedBy           *int64
	JournalTransactionID *int64
	OrganizationID       int64
	ID                   int64
}

// Maker/checker: whoever raised the note cannot be the one who issues it.
// Enforced here and by the credit_notes_maker_is_not_checker CHECK.
func (q *Queries) IssueCreditNote(ctx context.Context, arg IssueCreditNoteParams) (CreditNote, error) {
	row := q.db.QueryRow(ctx, issueCreditNote,
		arg.NoteNumber,
		arg.IssuedBy,
		arg.ApprovedBy,
		arg.JournalTransactionID,
		arg.OrganizationID,
		arg.ID,
	)
	var i CreditNote
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrganizationID,
		&i.NoteNumber,
		&i.NoteType,
		&i.InvoiceID,
		&i.CustomerID,
		&i.ReasonCode,
		&i.Reason,
		&i.IssueDate,
		&i.Currency,
		&i.SubtotalMinor,
		&i.TaxMinor,
		&i.TotalMinor,
		&i.Status,
		&i.JournalTransactionID,
		&i.DocumentObjectID,
		&i.TaxMetadata,
		&i.IssuedAt,
		&i.IssuedBy,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.RequestID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const issueInvoice = `-- name: IssueInvoice :one
UPDATE invoices
   SET status = 'ISSUED', invoice_number = $1,
       issued_at = now(), issued_by = $2,
       journal_transaction_id = $3
 WHERE organization_id = $4 AND id = $5
   AND status = 'DRAFT'
RETURNING id, public_id, organization_id, invoice_number, series_code, document_type, customer_id, business_account_id, billing_run_id, billing_mode, period_start, period_end, issue_date, due_date, status, currency, subtotal_minor, discount_minor, taxable_minor, tax_minor, rounding_minor, total_minor, paid_minor, credited_minor, shipment_count, bill_to, supplier, tax_metadata, journal_transaction_id, document_object_id, notes, cancel_reason, issued_at, issued_by, cancelled_at, request_id, created_by, created_at, updated_at, version
`

type IssueInvoiceParams struct {
	InvoiceNumber        string
	IssuedBy             *int64
	JournalTransactionID *int64
	OrganizationID       int64
	ID                   int64
}

// CAS on DRAFT: two concurrent issuers cannot both stamp a number on one
// invoice, and the loser sees it is already issued.
func (q *Queries) IssueInvoice(ctx context.Context, arg IssueInvoiceParams) (Invoice, error) {
	row := q.db.QueryRow(ctx, issueInvoice,
		arg.InvoiceNumber,
		arg.IssuedBy,
		arg.JournalTransactionID,
		arg.OrganizationID,
		arg.ID,
	)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrganizationID,
		&i.InvoiceNumber,
		&i.SeriesCode,
		&i.DocumentType,
		&i.CustomerID,
		&i.BusinessAccountID,
		&i.BillingRunID,
		&i.BillingMode,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.IssueDate,
		&i.DueDate,
		&i.Status,
		&i.Currency,
		&i.SubtotalMinor,
		&i.DiscountMinor,
		&i.TaxableMinor,
		&i.TaxMinor,
		&i.RoundingMinor,
		&i.TotalMinor,
		&i.PaidMinor,
		&i.CreditedMinor,
		&i.ShipmentCount,
		&i.BillTo,
		&i.Supplier,
		&i.TaxMetadata,
		&i.JournalTransactionID,
		&i.DocumentObjectID,
		&i.Notes,
		&i.CancelReason,
		&i.IssuedAt,
		&i.IssuedBy,
		&i.CancelledAt,
		&i.RequestID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const listBillableShipments = `-- name: ListBillableShipments :many

SELECT s.id, s.public_id, s.awb, s.booked_at, s.chargeable_weight_grams,
       s.origin_pincode, s.destination_pincode, s.currency,
       cs.id AS charge_snapshot_id,
       cs.freight_minor, cs.surcharge_total_minor, cs.discount_total_minor,
       cs.taxable_minor, cs.tax_total_minor, cs.rounding_minor, cs.total_minor,
       cs.line_items
FROM shipments s
JOIN shipment_charge_snapshots cs ON cs.shipment_id = s.id
LEFT JOIN shipment_commercial_snapshots commercial ON commercial.shipment_id = s.id AND commercial.organization_id = s.organization_id
LEFT JOIN invoice_shipments inv ON inv.shipment_id = s.id
WHERE s.organization_id = $1
  AND (CASE WHEN commercial.shipment_id IS NULL THEN s.customer_id ELSE commercial.transport_customer_id END) = $2
  AND s.payment_mode IN ('CREDIT','PREPAID')
  AND s.current_status NOT IN ('CANCELLED')
  AND s.booked_at >= $3::timestamptz
  AND s.booked_at < $4::timestamptz
  AND inv.id IS NULL
ORDER BY s.booked_at, s.id
LIMIT $5
FOR UPDATE OF s
`

type ListBillableShipmentsParams struct {
	OrganizationID int64
	CustomerID     int64
	PeriodStart    time.Time
	PeriodEnd      time.Time
	Limit          int32
}

type ListBillableShipmentsRow struct {
	ID                    int64
	PublicID              string
	Awb                   string
	BookedAt              time.Time
	ChargeableWeightGrams int32
	OriginPincode         string
	DestinationPincode    string
	Currency              string
	ChargeSnapshotID      int64
	FreightMinor          int64
	SurchargeTotalMinor   int64
	DiscountTotalMinor    int64
	TaxableMinor          int64
	TaxTotalMinor         int64
	RoundingMinor         int64
	TotalMinor            int64
	LineItems             []byte
}

// ---------------------------------------------------------------------------
// Billable shipments
// ---------------------------------------------------------------------------
// Delivered shipments for a customer in a window that have not been invoiced.
//
// The charge snapshot is joined here rather than the rate card: the snapshot is
// what the shipment was actually priced at, and it is immutable. Billing from a
// live rate card would let a rate change alter an old invoice.
//
// FOR UPDATE OF s so a concurrent billing run for the same customer blocks
// rather than invoicing the same shipments twice.
func (q *Queries) ListBillableShipments(ctx context.Context, arg ListBillableShipmentsParams) ([]ListBillableShipmentsRow, error) {
	rows, err := q.db.Query(ctx, listBillableShipments,
		arg.OrganizationID,
		arg.CustomerID,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBillableShipmentsRow{}
	for rows.Next() {
		var i ListBillableShipmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.Awb,
			&i.BookedAt,
			&i.ChargeableWeightGrams,
			&i.OriginPincode,
			&i.DestinationPincode,
			&i.Currency,
			&i.ChargeSnapshotID,
			&i.FreightMinor,
			&i.SurchargeTotalMinor,
			&i.DiscountTotalMinor,
			&i.TaxableMinor,
			&i.TaxTotalMinor,
			&i.RoundingMinor,
			&i.TotalMinor,
			&i.LineItems,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBillingRuns = `-- name: ListBillingRuns :many
SELECT id, public_id, organization_id, run_code, billing_cycle, period_start, period_end, status, customer_filter, invoice_count, shipment_count, total_minor, currency, error_count, errors, started_at, completed_at, created_by, request_id, created_at, updated_at FROM billing_runs
WHERE organization_id = $1
  AND ($3::text IS NULL OR status = $3::text)
ORDER BY id DESC
LIMIT $2
`

type ListBillingRunsParams struct {
	OrganizationID int64
	Limit          int32
	Status         *string
}

func (q *Queries) ListBillingRuns(ctx context.Context, arg ListBillingRunsParams) ([]BillingRun, error) {
	rows, err := q.db.Query(ctx, listBillingRuns, arg.OrganizationID, arg.Limit, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BillingRun{}
	for rows.Next() {
		var i BillingRun
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.OrganizationID,
			&i.RunCode,
			&i.BillingCycle,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.Status,
			&i.CustomerFilter,
			&i.InvoiceCount,
			&i.ShipmentCount,
			&i.TotalMinor,
			&i.Currency,
			&i.ErrorCount,
			&i.Errors,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedBy,
			&i.RequestID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCreditNoteLines = `-- name: ListCreditNoteLines :many
SELECT id, organization_id, credit_note_id, line_no, description, amount_minor, tax_minor, total_minor, currency, invoice_line_id, shipment_id, created_at FROM credit_note_lines WHERE credit_note_id = $1 ORDER BY line_no
`

func (q *Queries) ListCreditNoteLines(ctx context.Context, creditNoteID int64) ([]CreditNoteLine, error) {
	rows, err := q.db.Query(ctx, listCreditNoteLines, creditNoteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CreditNoteLine{}
	for rows.Next() {
		var i CreditNoteLine
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.CreditNoteID,
			&i.LineNo,
			&i.Description,
			&i.AmountMinor,
			&i.TaxMinor,
			&i.TotalMinor,
			&i.Currency,
			&i.InvoiceLineID,
			&i.ShipmentID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCreditNotes = `-- name: ListCreditNotes :many
SELECT n.id, n.public_id, n.organization_id, n.note_number, n.note_type, n.invoice_id, n.customer_id, n.reason_code, n.reason, n.issue_date, n.currency, n.subtotal_minor, n.tax_minor, n.total_minor, n.status, n.journal_transaction_id, n.document_object_id, n.tax_metadata, n.issued_at, n.issued_by, n.approved_by, n.approved_at, n.request_id, n.created_by, n.created_at, n.updated_at, c.code AS customer_code
FROM credit_notes n
JOIN customers c ON c.id = n.customer_id
WHERE n.organization_id = $1
  AND ($3::text IS NULL OR n.status = $3::text)
  AND ($4::text IS NULL OR n.note_type = $4::text)
  AND ($5::bigint IS NULL OR n.customer_id = $5::bigint)
  AND ($6::bigint IS NULL OR n.invoice_id = $6::bigint)
  AND ($7::bigint IS NULL OR n.id < $7::bigint)
ORDER BY n.id DESC
LIMIT $2
`

type ListCreditNotesParams struct {
	OrganizationID int64
	Limit          int32
	Status         *string
	NoteType       *string
	CustomerID     *int64
	InvoiceID      *int64
	CursorID       *int64
}

type ListCreditNotesRow struct {
	ID                   int64
	PublicID             string
	OrganizationID       int64
	NoteNumber           string
	NoteType             string
	InvoiceID            *int64
	CustomerID           int64
	ReasonCode           string
	Reason               string
	IssueDate            time.Time
	Currency             string
	SubtotalMinor        int64
	TaxMinor             int64
	TotalMinor           int64
	Status               string
	JournalTransactionID *int64
	DocumentObjectID     *int64
	TaxMetadata          []byte
	IssuedAt             *time.Time
	IssuedBy             *int64
	ApprovedBy           *int64
	ApprovedAt           *time.Time
	RequestID            *string
	CreatedBy            *int64
	CreatedAt            time.Time
	UpdatedAt            time.Time
	CustomerCode         string
}

func (q *Queries) ListCreditNotes(ctx context.Context, arg ListCreditNotesParams) ([]ListCreditNotesRow, error) {
	rows, err := q.db.Query(ctx, listCreditNotes,
		arg.OrganizationID,
		arg.Limit,
		arg.Status,
		arg.NoteType,
		arg.CustomerID,
		arg.InvoiceID,
		arg.CursorID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCreditNotesRow{}
	for rows.Next() {
		var i ListCreditNotesRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.OrganizationID,
			&i.NoteNumber,
			&i.NoteType,
			&i.InvoiceID,
			&i.CustomerID,
			&i.ReasonCode,
			&i.Reason,
			&i.IssueDate,
			&i.Currency,
			&i.SubtotalMinor,
			&i.TaxMinor,
			&i.TotalMinor,
			&i.Status,
			&i.JournalTransactionID,
			&i.DocumentObjectID,
			&i.TaxMetadata,
			&i.IssuedAt,
			&i.IssuedBy,
			&i.ApprovedBy,
			&i.ApprovedAt,
			&i.RequestID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CustomerCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCustomersForBilling = `-- name: ListCustomersForBilling :many
SELECT c.id, c.public_id, c.code, c.name, c.customer_type,
       b.id AS business_account_id, b.billing_cycle, b.payment_terms_days,
       b.currency, b.tax_metadata
FROM customers c
JOIN business_accounts b ON b.customer_id = c.id
WHERE c.organization_id = $1
  AND c.status = 'ACTIVE'
  AND b.status = 'ACTIVE'
  AND ($2::text IS NULL
       OR b.billing_cycle = $2::text)
  AND ($3::bigint IS NULL OR c.id = $3::bigint)
ORDER BY c.code
`

type ListCustomersForBillingParams struct {
	OrganizationID int64
	BillingCycle   *string
	CustomerID     *int64
}

type ListCustomersForBillingRow struct {
	ID                int64
	PublicID          string
	Code              string
	Name              string
	CustomerType      string
	BusinessAccountID int64
	BillingCycle      string
	PaymentTermsDays  int32
	Currency          string
	TaxMetadata       []byte
}

// Business accounts due for periodic billing on a cycle.
func (q *Queries) ListCustomersForBilling(ctx context.Context, arg ListCustomersForBillingParams) ([]ListCustomersForBillingRow, error) {
	rows, err := q.db.Query(ctx, listCustomersForBilling, arg.OrganizationID, arg.BillingCycle, arg.CustomerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCustomersForBillingRow{}
	for rows.Next() {
		var i ListCustomersForBillingRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.Code,
			&i.Name,
			&i.CustomerType,
			&i.BusinessAccountID,
			&i.BillingCycle,
			&i.PaymentTermsDays,
			&i.Currency,
			&i.TaxMetadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvoiceLines = `-- name: ListInvoiceLines :many
SELECT l.id, l.public_id, l.organization_id, l.invoice_id, l.line_no, l.line_type, l.description, l.hsn_sac_code, l.quantity, l.unit_price_minor, l.amount_minor, l.discount_minor, l.taxable_minor, l.tax_minor, l.total_minor, l.currency, l.shipment_id, l.charge_snapshot_id, l.metadata, l.created_at, s.awb
FROM invoice_lines l
LEFT JOIN shipments s ON s.id = l.shipment_id
WHERE l.invoice_id = $1
ORDER BY l.line_no
`

type ListInvoiceLinesRow struct {
	ID               int64
	PublicID         string
	OrganizationID   int64
	InvoiceID        int64
	LineNo           int32
	LineType         string
	Description      string
	HsnSacCode       *string
	Quantity         int32
	UnitPriceMinor   int64
	AmountMinor      int64
	DiscountMinor    int64
	TaxableMinor     int64
	TaxMinor         int64
	TotalMinor       int64
	Currency         string
	ShipmentID       *int64
	ChargeSnapshotID *int64
	Metadata         []byte
	CreatedAt        time.Time
	Awb              *string
}

func (q *Queries) ListInvoiceLines(ctx context.Context, invoiceID int64) ([]ListInvoiceLinesRow, error) {
	rows, err := q.db.Query(ctx, listInvoiceLines, invoiceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInvoiceLinesRow{}
	for rows.Next() {
		var i ListInvoiceLinesRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.OrganizationID,
			&i.InvoiceID,
			&i.LineNo,
			&i.LineType,
			&i.Description,
			&i.HsnSacCode,
			&i.Quantity,
			&i.UnitPriceMinor,
			&i.AmountMinor,
			&i.DiscountMinor,
			&i.TaxableMinor,
			&i.TaxMinor,
			&i.TotalMinor,
			&i.Currency,
			&i.ShipmentID,
			&i.ChargeSnapshotID,
			&i.Metadata,
			&i.CreatedAt,
			&i.Awb,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvoicePayments = `-- name: ListInvoicePayments :many
SELECT p.id, p.public_id, p.organization_id, p.invoice_id, p.customer_id, p.payment_number, p.amount_minor, p.currency, p.payment_mode, p.reference, p.received_on, p.status, p.journal_transaction_id, p.recorded_by, p.request_id, p.created_at, p.updated_at, u.full_name AS recorded_by_name
FROM invoice_payments p
LEFT JOIN users u ON u.id = p.recorded_by
WHERE p.invoice_id = $1
ORDER BY p.received_on DESC, p.id DESC
`

type ListInvoicePaymentsRow struct {
	ID                   int64
	PublicID             string
	OrganizationID       int64
	InvoiceID            int64
	CustomerID           int64
	PaymentNumber        string
	AmountMinor          int64
	Currency             string
	PaymentMode          string
	Reference            *string
	ReceivedOn           time.Time
	Status               string
	JournalTransactionID *int64
	RecordedBy           int64
	RequestID            *string
	CreatedAt            time.Time
	UpdatedAt            time.Time
	RecordedByName       *string
}

func (q *Queries) ListInvoicePayments(ctx context.Context, invoiceID int64) ([]ListInvoicePaymentsRow, error) {
	rows, err := q.db.Query(ctx, listInvoicePayments, invoiceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInvoicePaymentsRow{}
	for rows.Next() {
		var i ListInvoicePaymentsRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.OrganizationID,
			&i.InvoiceID,
			&i.CustomerID,
			&i.PaymentNumber,
			&i.AmountMinor,
			&i.Currency,
			&i.PaymentMode,
			&i.Reference,
			&i.ReceivedOn,
			&i.Status,
			&i.JournalTransactionID,
			&i.RecordedBy,
			&i.RequestID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RecordedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvoiceShipments = `-- name: ListInvoiceShipments :many
SELECT id, organization_id, invoice_id, shipment_id, awb, amount_minor, tax_minor, created_at FROM invoice_shipments WHERE invoice_id = $1 ORDER BY id
`

func (q *Queries) ListInvoiceShipments(ctx context.Context, invoiceID int64) ([]InvoiceShipment, error) {
	rows, err := q.db.Query(ctx, listInvoiceShipments, invoiceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InvoiceShipment{}
	for rows.Next() {
		var i InvoiceShipment
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.InvoiceID,
			&i.ShipmentID,
			&i.Awb,
			&i.AmountMinor,
			&i.TaxMinor,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvoiceTaxComponents = `-- name: ListInvoiceTaxComponents :many
SELECT component_code, component_name, rate_bp,
       SUM(taxable_minor)::bigint AS taxable_minor,
       SUM(tax_minor)::bigint     AS tax_minor,
       currency
FROM tax_components
WHERE invoice_id = $1
GROUP BY component_code, component_name, rate_bp, currency
ORDER BY component_code
`

type ListInvoiceTaxComponentsRow struct {
	ComponentCode string
	ComponentName string
	RateBp        int32
	TaxableMinor  int64
	TaxMinor      int64
	Currency      string
}

func (q *Queries) ListInvoiceTaxComponents(ctx context.Context, invoiceID *int64) ([]ListInvoiceTaxComponentsRow, error) {
	rows, err := q.db.Query(ctx, listInvoiceTaxComponents, invoiceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInvoiceTaxComponentsRow{}
	for rows.Next() {
		var i ListInvoiceTaxComponentsRow
		if err := rows.Scan(
			&i.ComponentCode,
			&i.ComponentName,
			&i.RateBp,
			&i.TaxableMinor,
			&i.TaxMinor,
			&i.Currency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvoices = `-- name: ListInvoices :many
SELECT i.id, i.public_id, i.organization_id, i.invoice_number, i.series_code, i.document_type, i.customer_id, i.business_account_id, i.billing_run_id, i.billing_mode, i.period_start, i.period_end, i.issue_date, i.due_date, i.status, i.currency, i.subtotal_minor, i.discount_minor, i.taxable_minor, i.tax_minor, i.rounding_minor, i.total_minor, i.paid_minor, i.credited_minor, i.shipment_count, i.bill_to, i.supplier, i.tax_metadata, i.journal_transaction_id, i.document_object_id, i.notes, i.cancel_reason, i.issued_at, i.issued_by, i.cancelled_at, i.request_id, i.created_by, i.created_at, i.updated_at, i.version, c.code AS customer_code, c.name AS customer_name
FROM invoices i
JOIN customers c ON c.id = i.customer_id
WHERE i.organization_id = $1
  AND ($3::text IS NULL OR i.status = $3::text)
  AND ($4::bigint IS NULL OR i.customer_id = $4::bigint)
  AND ($5::bigint IS NULL OR i.billing_run_id = $5::bigint)
  AND ($6::date IS NULL OR i.issue_date >= $6::date)
  AND ($7::date IS NULL OR i.issue_date <= $7::date)
  AND ($8::bigint IS NULL OR i.id < $8::bigint)
ORDER BY i.id DESC
LIMIT $2
`

type ListInvoicesParams struct {
	OrganizationID int64
	Limit          int32
	Status         *string
	CustomerID     *int64
	BillingRunID   *int64
	FromDate       *time.Time
	ToDate         *time.Time
	CursorID       *int64
}

type ListInvoicesRow struct {
	ID                   int64
	PublicID             string
	OrganizationID       int64
	InvoiceNumber        string
	SeriesCode           string
	DocumentType         string
	CustomerID           int64
	BusinessAccountID    *int64
	BillingRunID         *int64
	BillingMode          string
	PeriodStart          *time.Time
	PeriodEnd            *time.Time
	IssueDate            time.Time
	DueDate              time.Time
	Status               string
	Currency             string
	SubtotalMinor        int64
	DiscountMinor        int64
	TaxableMinor         int64
	TaxMinor             int64
	RoundingMinor        int64
	TotalMinor           int64
	PaidMinor            int64
	CreditedMinor        int64
	ShipmentCount        int32
	BillTo               []byte
	Supplier             []byte
	TaxMetadata          []byte
	JournalTransactionID *int64
	DocumentObjectID     *int64
	Notes                *string
	CancelReason         *string
	IssuedAt             *time.Time
	IssuedBy             *int64
	CancelledAt          *time.Time
	RequestID            *string
	CreatedBy            *int64
	CreatedAt            time.Time
	UpdatedAt            time.Time
	Version              int32
	CustomerCode         string
	CustomerName         string
}

func (q *Queries) ListInvoices(ctx context.Context, arg ListInvoicesParams) ([]ListInvoicesRow, error) {
	rows, err := q.db.Query(ctx, listInvoices,
		arg.OrganizationID,
		arg.Limit,
		arg.Status,
		arg.CustomerID,
		arg.BillingRunID,
		arg.FromDate,
		arg.ToDate,
		arg.CursorID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInvoicesRow{}
	for rows.Next() {
		var i ListInvoicesRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.OrganizationID,
			&i.InvoiceNumber,
			&i.SeriesCode,
			&i.DocumentType,
			&i.CustomerID,
			&i.BusinessAccountID,
			&i.BillingRunID,
			&i.BillingMode,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.IssueDate,
			&i.DueDate,
			&i.Status,
			&i.Currency,
			&i.SubtotalMinor,
			&i.DiscountMinor,
			&i.TaxableMinor,
			&i.TaxMinor,
			&i.RoundingMinor,
			&i.TotalMinor,
			&i.PaidMinor,
			&i.CreditedMinor,
			&i.ShipmentCount,
			&i.BillTo,
			&i.Supplier,
			&i.TaxMetadata,
			&i.JournalTransactionID,
			&i.DocumentObjectID,
			&i.Notes,
			&i.CancelReason,
			&i.IssuedAt,
			&i.IssuedBy,
			&i.CancelledAt,
			&i.RequestID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Version,
			&i.CustomerCode,
			&i.CustomerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockInvoice = `-- name: LockInvoice :one
SELECT id, public_id, organization_id, invoice_number, series_code, document_type, customer_id, business_account_id, billing_run_id, billing_mode, period_start, period_end, issue_date, due_date, status, currency, subtotal_minor, discount_minor, taxable_minor, tax_minor, rounding_minor, total_minor, paid_minor, credited_minor, shipment_count, bill_to, supplier, tax_metadata, journal_transaction_id, document_object_id, notes, cancel_reason, issued_at, issued_by, cancelled_at, request_id, created_by, created_at, updated_at, version FROM invoices WHERE organization_id = $1 AND id = $2 FOR UPDATE
`

type LockInvoiceParams struct {
	OrganizationID int64
	ID             int64
}

func (q *Queries) LockInvoice(ctx context.Context, arg LockInvoiceParams) (Invoice, error) {
	row := q.db.QueryRow(ctx, lockInvoice, arg.OrganizationID, arg.ID)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrganizationID,
		&i.InvoiceNumber,
		&i.SeriesCode,
		&i.DocumentType,
		&i.CustomerID,
		&i.BusinessAccountID,
		&i.BillingRunID,
		&i.BillingMode,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.IssueDate,
		&i.DueDate,
		&i.Status,
		&i.Currency,
		&i.SubtotalMinor,
		&i.DiscountMinor,
		&i.TaxableMinor,
		&i.TaxMinor,
		&i.RoundingMinor,
		&i.TotalMinor,
		&i.PaidMinor,
		&i.CreditedMinor,
		&i.ShipmentCount,
		&i.BillTo,
		&i.Supplier,
		&i.TaxMetadata,
		&i.JournalTransactionID,
		&i.DocumentObjectID,
		&i.Notes,
		&i.CancelReason,
		&i.IssuedAt,
		&i.IssuedBy,
		&i.CancelledAt,
		&i.RequestID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const markOverdueInvoices = `-- name: MarkOverdueInvoices :exec
UPDATE invoices
   SET status = 'OVERDUE'
 WHERE organization_id = $1
   AND status IN ('ISSUED','PARTIALLY_PAID')
   AND due_date < current_date
`

// Run by the worker. Moves past-due invoices into OVERDUE so the collections
// queue is a query rather than a date comparison in every caller.
func (q *Queries) MarkOverdueInvoices(ctx context.Context, organizationID int64) error {
	_, err := q.db.Exec(ctx, markOverdueInvoices, organizationID)
	return err
}

const recordInvoiceCredit = `-- name: RecordInvoiceCredit :one
UPDATE invoices
   SET credited_minor = credited_minor + $1,
       status = CASE
           WHEN paid_minor + credited_minor + $1 >= total_minor THEN 'PAID'
           ELSE status
       END
 WHERE organization_id = $2 AND id = $3
   AND status IN ('ISSUED','PARTIALLY_PAID','OVERDUE')
RETURNING id, public_id, organization_id, invoice_number, series_code, document_type, customer_id, business_account_id, billing_run_id, billing_mode, period_start, period_end, issue_date, due_date, status, currency, subtotal_minor, discount_minor, taxable_minor, tax_minor, rounding_minor, total_minor, paid_minor, credited_minor, shipment_count, bill_to, supplier, tax_metadata, journal_transaction_id, document_object_id, notes, cancel_reason, issued_at, issued_by, cancelled_at, request_id, created_by, created_at, updated_at, version
`

type RecordInvoiceCreditParams struct {
	AmountMinor    int64
	OrganizationID int64
	ID             int64
}

func (q *Queries) RecordInvoiceCredit(ctx context.Context, arg RecordInvoiceCreditParams) (Invoice, error) {
	row := q.db.QueryRow(ctx, recordInvoiceCredit, arg.AmountMinor, arg.OrganizationID, arg.ID)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrganizationID,
		&i.InvoiceNumber,
		&i.SeriesCode,
		&i.DocumentType,
		&i.CustomerID,
		&i.BusinessAccountID,
		&i.BillingRunID,
		&i.BillingMode,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.IssueDate,
		&i.DueDate,
		&i.Status,
		&i.Currency,
		&i.SubtotalMinor,
		&i.DiscountMinor,
		&i.TaxableMinor,
		&i.TaxMinor,
		&i.RoundingMinor,
		&i.TotalMinor,
		&i.PaidMinor,
		&i.CreditedMinor,
		&i.ShipmentCount,
		&i.BillTo,
		&i.Supplier,
		&i.TaxMetadata,
		&i.JournalTransactionID,
		&i.DocumentObjectID,
		&i.Notes,
		&i.CancelReason,
		&i.IssuedAt,
		&i.IssuedBy,
		&i.CancelledAt,
		&i.RequestID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const recordInvoicePayment = `-- name: RecordInvoicePayment :one
UPDATE invoices
   SET paid_minor = paid_minor + $1,
       status = CASE
           WHEN paid_minor + credited_minor + $1 >= total_minor THEN 'PAID'
           ELSE 'PARTIALLY_PAID'
       END
 WHERE organization_id = $2 AND id = $3
   AND status IN ('ISSUED','PARTIALLY_PAID','OVERDUE')
RETURNING id, public_id, organization_id, invoice_number, series_code, document_type, customer_id, business_account_id, billing_run_id, billing_mode, period_start, period_end, issue_date, due_date, status, currency, subtotal_minor, discount_minor, taxable_minor, tax_minor, rounding_minor, total_minor, paid_minor, credited_minor, shipment_count, bill_to, supplier, tax_metadata, journal_transaction_id, document_object_id, notes, cancel_reason, issued_at, issued_by, cancelled_at, request_id, created_by, created_at, updated_at, version
`

type RecordInvoicePaymentParams struct {
	AmountMinor    int64
	OrganizationID int64
	ID             int64
}

// Payment progress follows the arithmetic rather than a caller's opinion.
func (q *Queries) RecordInvoicePayment(ctx context.Context, arg RecordInvoicePaymentParams) (Invoice, error) {
	row := q.db.QueryRow(ctx, recordInvoicePayment, arg.AmountMinor, arg.OrganizationID, arg.ID)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrganizationID,
		&i.InvoiceNumber,
		&i.SeriesCode,
		&i.DocumentType,
		&i.CustomerID,
		&i.BusinessAccountID,
		&i.BillingRunID,
		&i.BillingMode,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.IssueDate,
		&i.DueDate,
		&i.Status,
		&i.Currency,
		&i.SubtotalMinor,
		&i.DiscountMinor,
		&i.TaxableMinor,
		&i.TaxMinor,
		&i.RoundingMinor,
		&i.TotalMinor,
		&i.PaidMinor,
		&i.CreditedMinor,
		&i.ShipmentCount,
		&i.BillTo,
		&i.Supplier,
		&i.TaxMetadata,
		&i.JournalTransactionID,
		&i.DocumentObjectID,
		&i.Notes,
		&i.CancelReason,
		&i.IssuedAt,
		&i.IssuedBy,
		&i.CancelledAt,
		&i.RequestID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const startBillingRun = `-- name: StartBillingRun :one
UPDATE billing_runs
   SET status = 'RUNNING', started_at = now()
 WHERE organization_id = $1 AND id = $2 AND status = 'PENDING'
RETURNING id, public_id, organization_id, run_code, billing_cycle, period_start, period_end, status, customer_filter, invoice_count, shipment_count, total_minor, currency, error_count, errors, started_at, completed_at, created_by, request_id, created_at, updated_at
`

type StartBillingRunParams struct {
	OrganizationID int64
	ID             int64
}

func (q *Queries) StartBillingRun(ctx context.Context, arg StartBillingRunParams) (BillingRun, error) {
	row := q.db.QueryRow(ctx, startBillingRun, arg.OrganizationID, arg.ID)
	var i BillingRun
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrganizationID,
		&i.RunCode,
		&i.BillingCycle,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.Status,
		&i.CustomerFilter,
		&i.InvoiceCount,
		&i.ShipmentCount,
		&i.TotalMinor,
		&i.Currency,
		&i.ErrorCount,
		&i.Errors,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedBy,
		&i.RequestID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const sumInvoiceLines = `-- name: SumInvoiceLines :one
SELECT
    COALESCE(SUM(amount_minor), 0)::bigint   AS amount_minor,
    COALESCE(SUM(discount_minor), 0)::bigint AS discount_minor,
    COALESCE(SUM(taxable_minor), 0)::bigint  AS taxable_minor,
    COALESCE(SUM(tax_minor), 0)::bigint      AS tax_minor,
    COALESCE(SUM(total_minor), 0)::bigint    AS total_minor,
    count(*)::bigint                          AS line_count
FROM invoice_lines
WHERE invoice_id = $1
`

type SumInvoiceLinesRow struct {
	AmountMinor   int64
	DiscountMinor int64
	TaxableMinor  int64
	TaxMinor      int64
	TotalMinor    int64
	LineCount     int64
}

func (q *Queries) SumInvoiceLines(ctx context.Context, invoiceID int64) (SumInvoiceLinesRow, error) {
	row := q.db.QueryRow(ctx, sumInvoiceLines, invoiceID)
	var i SumInvoiceLinesRow
	err := row.Scan(
		&i.AmountMinor,
		&i.DiscountMinor,
		&i.TaxableMinor,
		&i.TaxMinor,
		&i.TotalMinor,
		&i.LineCount,
	)
	return i, err
}

const sumInvoicePayments = `-- name: SumInvoicePayments :one
SELECT COALESCE(SUM(amount_minor) FILTER (WHERE status IN ('RECORDED','CONFIRMED')), 0)::bigint
           AS paid_minor,
       count(*)::bigint AS payment_count
FROM invoice_payments
WHERE invoice_id = $1
`

type SumInvoicePaymentsRow struct {
	PaidMinor    int64
	PaymentCount int64
}

func (q *Queries) SumInvoicePayments(ctx context.Context, invoiceID int64) (SumInvoicePaymentsRow, error) {
	row := q.db.QueryRow(ctx, sumInvoicePayments, invoiceID)
	var i SumInvoicePaymentsRow
	err := row.Scan(&i.PaidMinor, &i.PaymentCount)
	return i, err
}
