// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: collection.sql

package dbgen

import (
	"context"
	"time"
)

const attachFranchiseCollectionsToSettlement = `-- name: AttachFranchiseCollectionsToSettlement :exec
UPDATE franchise_collections
SET settlement_id = $1, status = 'IN_SETTLEMENT'
WHERE organization_id = $2 AND id = ANY($3::bigint[])
  AND settlement_id IS NULL AND status = 'COLLECTED'
`

type AttachFranchiseCollectionsToSettlementParams struct {
	SettlementID   *int64
	OrganizationID int64
	Ids            []int64
}

func (q *Queries) AttachFranchiseCollectionsToSettlement(ctx context.Context, arg AttachFranchiseCollectionsToSettlementParams) error {
	_, err := q.db.Exec(ctx, attachFranchiseCollectionsToSettlement, arg.SettlementID, arg.OrganizationID, arg.Ids)
	return err
}

const createFranchiseCollection = `-- name: CreateFranchiseCollection :one

INSERT INTO franchise_collections (
    public_id, organization_id, shipment_id, franchise_id, operating_unit_id,
    customer_id, amount_minor, currency, payment_mode, reference,
    collected_at, collected_by, notes, request_id
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14)
RETURNING id, public_id, organization_id, shipment_id, franchise_id, operating_unit_id, customer_id, amount_minor, currency, payment_mode, reference, status, collected_at, collected_by, settlement_id, remitted_at, notes, request_id, created_at, updated_at
`

type CreateFranchiseCollectionParams struct {
	PublicID        string
	OrganizationID  int64
	ShipmentID      int64
	FranchiseID     int64
	OperatingUnitID int64
	CustomerID      int64
	AmountMinor     int64
	Currency        string
	PaymentMode     string
	Reference       *string
	CollectedAt     time.Time
	CollectedBy     int64
	Notes           *string
	RequestID       *string
}

// Franchise counter payment collection.
func (q *Queries) CreateFranchiseCollection(ctx context.Context, arg CreateFranchiseCollectionParams) (FranchiseCollection, error) {
	row := q.db.QueryRow(ctx, createFranchiseCollection,
		arg.PublicID,
		arg.OrganizationID,
		arg.ShipmentID,
		arg.FranchiseID,
		arg.OperatingUnitID,
		arg.CustomerID,
		arg.AmountMinor,
		arg.Currency,
		arg.PaymentMode,
		arg.Reference,
		arg.CollectedAt,
		arg.CollectedBy,
		arg.Notes,
		arg.RequestID,
	)
	var i FranchiseCollection
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrganizationID,
		&i.ShipmentID,
		&i.FranchiseID,
		&i.OperatingUnitID,
		&i.CustomerID,
		&i.AmountMinor,
		&i.Currency,
		&i.PaymentMode,
		&i.Reference,
		&i.Status,
		&i.CollectedAt,
		&i.CollectedBy,
		&i.SettlementID,
		&i.RemittedAt,
		&i.Notes,
		&i.RequestID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFranchiseCollectionByPublicID = `-- name: GetFranchiseCollectionByPublicID :one
SELECT c.id, c.public_id, c.organization_id, c.shipment_id, c.franchise_id, c.operating_unit_id, c.customer_id, c.amount_minor, c.currency, c.payment_mode, c.reference, c.status, c.collected_at, c.collected_by, c.settlement_id, c.remitted_at, c.notes, c.request_id, c.created_at, c.updated_at, s.awb, f.code AS franchise_code, f.name AS franchise_name,
       ou.code AS unit_code, u.full_name AS collected_by_name
FROM franchise_collections c
JOIN shipments s ON s.id = c.shipment_id
JOIN franchises f ON f.id = c.franchise_id
JOIN operating_units ou ON ou.id = c.operating_unit_id
JOIN users u ON u.id = c.collected_by
WHERE c.organization_id = $1 AND c.public_id = $2
`

type GetFranchiseCollectionByPublicIDParams struct {
	OrganizationID int64
	PublicID       string
}

type GetFranchiseCollectionByPublicIDRow struct {
	ID              int64
	PublicID        string
	OrganizationID  int64
	ShipmentID      int64
	FranchiseID     int64
	OperatingUnitID int64
	CustomerID      int64
	AmountMinor     int64
	Currency        string
	PaymentMode     string
	Reference       *string
	Status          string
	CollectedAt     time.Time
	CollectedBy     int64
	SettlementID    *int64
	RemittedAt      *time.Time
	Notes           *string
	RequestID       *string
	CreatedAt       time.Time
	UpdatedAt       time.Time
	Awb             string
	FranchiseCode   string
	FranchiseName   string
	UnitCode        string
	CollectedByName string
}

func (q *Queries) GetFranchiseCollectionByPublicID(ctx context.Context, arg GetFranchiseCollectionByPublicIDParams) (GetFranchiseCollectionByPublicIDRow, error) {
	row := q.db.QueryRow(ctx, getFranchiseCollectionByPublicID, arg.OrganizationID, arg.PublicID)
	var i GetFranchiseCollectionByPublicIDRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrganizationID,
		&i.ShipmentID,
		&i.FranchiseID,
		&i.OperatingUnitID,
		&i.CustomerID,
		&i.AmountMinor,
		&i.Currency,
		&i.PaymentMode,
		&i.Reference,
		&i.Status,
		&i.CollectedAt,
		&i.CollectedBy,
		&i.SettlementID,
		&i.RemittedAt,
		&i.Notes,
		&i.RequestID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Awb,
		&i.FranchiseCode,
		&i.FranchiseName,
		&i.UnitCode,
		&i.CollectedByName,
	)
	return i, err
}

const getFranchiseCollectionByShipment = `-- name: GetFranchiseCollectionByShipment :one
SELECT id, public_id, organization_id, shipment_id, franchise_id, operating_unit_id, customer_id, amount_minor, currency, payment_mode, reference, status, collected_at, collected_by, settlement_id, remitted_at, notes, request_id, created_at, updated_at FROM franchise_collections WHERE organization_id = $1 AND shipment_id = $2
`

type GetFranchiseCollectionByShipmentParams struct {
	OrganizationID int64
	ShipmentID     int64
}

func (q *Queries) GetFranchiseCollectionByShipment(ctx context.Context, arg GetFranchiseCollectionByShipmentParams) (FranchiseCollection, error) {
	row := q.db.QueryRow(ctx, getFranchiseCollectionByShipment, arg.OrganizationID, arg.ShipmentID)
	var i FranchiseCollection
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrganizationID,
		&i.ShipmentID,
		&i.FranchiseID,
		&i.OperatingUnitID,
		&i.CustomerID,
		&i.AmountMinor,
		&i.Currency,
		&i.PaymentMode,
		&i.Reference,
		&i.Status,
		&i.CollectedAt,
		&i.CollectedBy,
		&i.SettlementID,
		&i.RemittedAt,
		&i.Notes,
		&i.RequestID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listFranchiseCollections = `-- name: ListFranchiseCollections :many
SELECT c.id, c.public_id, c.organization_id, c.shipment_id, c.franchise_id, c.operating_unit_id, c.customer_id, c.amount_minor, c.currency, c.payment_mode, c.reference, c.status, c.collected_at, c.collected_by, c.settlement_id, c.remitted_at, c.notes, c.request_id, c.created_at, c.updated_at, s.awb, f.code AS franchise_code, f.name AS franchise_name,
       ou.code AS unit_code, u.full_name AS collected_by_name,
       count(*) OVER () AS total_count
FROM franchise_collections c
JOIN shipments s ON s.id = c.shipment_id
JOIN franchises f ON f.id = c.franchise_id
JOIN operating_units ou ON ou.id = c.operating_unit_id
JOIN users u ON u.id = c.collected_by
WHERE c.organization_id = $1
  AND ($2::bigint IS NULL OR c.franchise_id = $2)
  AND ($3::text IS NULL OR c.status = $3)
  AND ($4::bigint[] IS NULL OR c.operating_unit_id = ANY($4))
ORDER BY c.collected_at DESC, c.id DESC
LIMIT $6 OFFSET $5
`

type ListFranchiseCollectionsParams struct {
	OrganizationID int64
	FranchiseID    *int64
	Status         *string
	ScopedUnitIds  []int64
	RowOffset      int32
	RowLimit       int32
}

type ListFranchiseCollectionsRow struct {
	ID              int64
	PublicID        string
	OrganizationID  int64
	ShipmentID      int64
	FranchiseID     int64
	OperatingUnitID int64
	CustomerID      int64
	AmountMinor     int64
	Currency        string
	PaymentMode     string
	Reference       *string
	Status          string
	CollectedAt     time.Time
	CollectedBy     int64
	SettlementID    *int64
	RemittedAt      *time.Time
	Notes           *string
	RequestID       *string
	CreatedAt       time.Time
	UpdatedAt       time.Time
	Awb             string
	FranchiseCode   string
	FranchiseName   string
	UnitCode        string
	CollectedByName string
	TotalCount      int64
}

func (q *Queries) ListFranchiseCollections(ctx context.Context, arg ListFranchiseCollectionsParams) ([]ListFranchiseCollectionsRow, error) {
	rows, err := q.db.Query(ctx, listFranchiseCollections,
		arg.OrganizationID,
		arg.FranchiseID,
		arg.Status,
		arg.ScopedUnitIds,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFranchiseCollectionsRow{}
	for rows.Next() {
		var i ListFranchiseCollectionsRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.OrganizationID,
			&i.ShipmentID,
			&i.FranchiseID,
			&i.OperatingUnitID,
			&i.CustomerID,
			&i.AmountMinor,
			&i.Currency,
			&i.PaymentMode,
			&i.Reference,
			&i.Status,
			&i.CollectedAt,
			&i.CollectedBy,
			&i.SettlementID,
			&i.RemittedAt,
			&i.Notes,
			&i.RequestID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Awb,
			&i.FranchiseCode,
			&i.FranchiseName,
			&i.UnitCode,
			&i.CollectedByName,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markFranchiseCollectionsRemitted = `-- name: MarkFranchiseCollectionsRemitted :exec
UPDATE franchise_collections SET status = 'REMITTED', remitted_at = now()
WHERE organization_id = $1 AND settlement_id = $2 AND status = 'IN_SETTLEMENT'
`

type MarkFranchiseCollectionsRemittedParams struct {
	OrganizationID int64
	SettlementID   *int64
}

func (q *Queries) MarkFranchiseCollectionsRemitted(ctx context.Context, arg MarkFranchiseCollectionsRemittedParams) error {
	_, err := q.db.Exec(ctx, markFranchiseCollectionsRemitted, arg.OrganizationID, arg.SettlementID)
	return err
}

const releaseFranchiseCollectionsFromSettlement = `-- name: ReleaseFranchiseCollectionsFromSettlement :exec
UPDATE franchise_collections SET settlement_id = NULL, status = 'COLLECTED'
WHERE organization_id = $1 AND settlement_id = $2 AND status = 'IN_SETTLEMENT'
`

type ReleaseFranchiseCollectionsFromSettlementParams struct {
	OrganizationID int64
	SettlementID   *int64
}

func (q *Queries) ReleaseFranchiseCollectionsFromSettlement(ctx context.Context, arg ReleaseFranchiseCollectionsFromSettlementParams) error {
	_, err := q.db.Exec(ctx, releaseFranchiseCollectionsFromSettlement, arg.OrganizationID, arg.SettlementID)
	return err
}

const sweepFranchiseCollectionsForSettlement = `-- name: SweepFranchiseCollectionsForSettlement :many
SELECT c.id, c.public_id, c.organization_id, c.shipment_id, c.franchise_id, c.operating_unit_id, c.customer_id, c.amount_minor, c.currency, c.payment_mode, c.reference, c.status, c.collected_at, c.collected_by, c.settlement_id, c.remitted_at, c.notes, c.request_id, c.created_at, c.updated_at, s.awb
FROM franchise_collections c JOIN shipments s ON s.id = c.shipment_id
WHERE c.organization_id = $1
  AND c.franchise_id = $2
  AND c.status = 'COLLECTED' AND c.settlement_id IS NULL
  AND c.collected_at >= $3::date
  AND c.collected_at < ($4::date + 1)
ORDER BY c.collected_at, c.id
FOR UPDATE OF c
`

type SweepFranchiseCollectionsForSettlementParams struct {
	OrganizationID int64
	FranchiseID    int64
	PeriodStart    time.Time
	PeriodEnd      time.Time
}

type SweepFranchiseCollectionsForSettlementRow struct {
	ID              int64
	PublicID        string
	OrganizationID  int64
	ShipmentID      int64
	FranchiseID     int64
	OperatingUnitID int64
	CustomerID      int64
	AmountMinor     int64
	Currency        string
	PaymentMode     string
	Reference       *string
	Status          string
	CollectedAt     time.Time
	CollectedBy     int64
	SettlementID    *int64
	RemittedAt      *time.Time
	Notes           *string
	RequestID       *string
	CreatedAt       time.Time
	UpdatedAt       time.Time
	Awb             string
}

func (q *Queries) SweepFranchiseCollectionsForSettlement(ctx context.Context, arg SweepFranchiseCollectionsForSettlementParams) ([]SweepFranchiseCollectionsForSettlementRow, error) {
	rows, err := q.db.Query(ctx, sweepFranchiseCollectionsForSettlement,
		arg.OrganizationID,
		arg.FranchiseID,
		arg.PeriodStart,
		arg.PeriodEnd,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SweepFranchiseCollectionsForSettlementRow{}
	for rows.Next() {
		var i SweepFranchiseCollectionsForSettlementRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.OrganizationID,
			&i.ShipmentID,
			&i.FranchiseID,
			&i.OperatingUnitID,
			&i.CustomerID,
			&i.AmountMinor,
			&i.Currency,
			&i.PaymentMode,
			&i.Reference,
			&i.Status,
			&i.CollectedAt,
			&i.CollectedBy,
			&i.SettlementID,
			&i.RemittedAt,
			&i.Notes,
			&i.RequestID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Awb,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
