// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: geography.sql

package dbgen

import (
	"context"
	"time"
)

const claimImportRowBatch = `-- name: ClaimImportRowBatch :many
SELECT id, row_number, raw FROM import_rows
WHERE import_job_id = $1
  AND status = 'PENDING'
  AND id > $2
ORDER BY id
LIMIT $3
`

type ClaimImportRowBatchParams struct {
	ImportJobID int64
	CursorID    int64
	RowLimit    int32
}

type ClaimImportRowBatchRow struct {
	ID        int64
	RowNumber int32
	Raw       []byte
}

func (q *Queries) ClaimImportRowBatch(ctx context.Context, arg ClaimImportRowBatchParams) ([]ClaimImportRowBatchRow, error) {
	rows, err := q.db.Query(ctx, claimImportRowBatch, arg.ImportJobID, arg.CursorID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClaimImportRowBatchRow{}
	for rows.Next() {
		var i ClaimImportRowBatchRow
		if err := rows.Scan(&i.ID, &i.RowNumber, &i.Raw); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countImportRowErrors = `-- name: CountImportRowErrors :one
SELECT count(*) FROM import_rows WHERE import_job_id = $1 AND status = 'FAILED'
`

func (q *Queries) CountImportRowErrors(ctx context.Context, importJobID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countImportRowErrors, importJobID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countZoneReferences = `-- name: CountZoneReferences :one
SELECT
    (SELECT count(*) FROM pincode_zone_mappings WHERE zone_id = $1 AND status = 'ACTIVE') AS mapping_count,
    (SELECT count(*) FROM zone_rates WHERE origin_zone_id = $1 OR destination_zone_id = $1) AS rate_count
`

type CountZoneReferencesRow struct {
	MappingCount int64
	RateCount    int64
}

func (q *Queries) CountZoneReferences(ctx context.Context, zoneID int64) (CountZoneReferencesRow, error) {
	row := q.db.QueryRow(ctx, countZoneReferences, zoneID)
	var i CountZoneReferencesRow
	err := row.Scan(&i.MappingCount, &i.RateCount)
	return i, err
}

const createImportJob = `-- name: CreateImportJob :one

INSERT INTO import_jobs (
    public_id, organization_id, import_type, file_name, file_size_bytes, file_checksum, options, created_by
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8)
RETURNING id, public_id, organization_id, import_type, status, file_name, file_size_bytes, file_checksum, total_rows, processed_rows, success_rows, failed_rows, error_summary, failure_reason, options, job_id, started_at, completed_at, created_by, created_at, updated_at
`

type CreateImportJobParams struct {
	PublicID       string
	OrganizationID *int64
	ImportType     string
	FileName       string
	FileSizeBytes  int64
	FileChecksum   *string
	Options        []byte
	CreatedBy      *int64
}

// ---------------------------------------------------------------------------
// Bulk import
// ---------------------------------------------------------------------------
func (q *Queries) CreateImportJob(ctx context.Context, arg CreateImportJobParams) (ImportJob, error) {
	row := q.db.QueryRow(ctx, createImportJob,
		arg.PublicID,
		arg.OrganizationID,
		arg.ImportType,
		arg.FileName,
		arg.FileSizeBytes,
		arg.FileChecksum,
		arg.Options,
		arg.CreatedBy,
	)
	var i ImportJob
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrganizationID,
		&i.ImportType,
		&i.Status,
		&i.FileName,
		&i.FileSizeBytes,
		&i.FileChecksum,
		&i.TotalRows,
		&i.ProcessedRows,
		&i.SuccessRows,
		&i.FailedRows,
		&i.ErrorSummary,
		&i.FailureReason,
		&i.Options,
		&i.JobID,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createZone = `-- name: CreateZone :one

INSERT INTO zones (public_id, organization_id, code, name, zone_type, description, sort_order)
VALUES ($1,$2,$3,$4,$5,$6,$7)
RETURNING id, public_id, organization_id, code, name, zone_type, description, sort_order, status, created_at, updated_at
`

type CreateZoneParams struct {
	PublicID       string
	OrganizationID int64
	Code           string
	Name           string
	ZoneType       string
	Description    string
	SortOrder      int32
}

// ---------------------------------------------------------------------------
// Zones
// ---------------------------------------------------------------------------
func (q *Queries) CreateZone(ctx context.Context, arg CreateZoneParams) (Zone, error) {
	row := q.db.QueryRow(ctx, createZone,
		arg.PublicID,
		arg.OrganizationID,
		arg.Code,
		arg.Name,
		arg.ZoneType,
		arg.Description,
		arg.SortOrder,
	)
	var i Zone
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrganizationID,
		&i.Code,
		&i.Name,
		&i.ZoneType,
		&i.Description,
		&i.SortOrder,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivatePincodeZoneMapping = `-- name: DeactivatePincodeZoneMapping :execrows
UPDATE pincode_zone_mappings SET status = 'INACTIVE', effective_to = now()
WHERE public_id = $1 AND organization_id = $2 AND status = 'ACTIVE'
`

type DeactivatePincodeZoneMappingParams struct {
	PublicID       string
	OrganizationID int64
}

func (q *Queries) DeactivatePincodeZoneMapping(ctx context.Context, arg DeactivatePincodeZoneMappingParams) (int64, error) {
	result, err := q.db.Exec(ctx, deactivatePincodeZoneMapping, arg.PublicID, arg.OrganizationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const finishImportJob = `-- name: FinishImportJob :exec
UPDATE import_jobs
SET status = $1,
    error_summary = $2,
    failure_reason = $3,
    completed_at = now()
WHERE id = $4
`

type FinishImportJobParams struct {
	Status        string
	ErrorSummary  []byte
	FailureReason *string
	ID            int64
}

func (q *Queries) FinishImportJob(ctx context.Context, arg FinishImportJobParams) error {
	_, err := q.db.Exec(ctx, finishImportJob,
		arg.Status,
		arg.ErrorSummary,
		arg.FailureReason,
		arg.ID,
	)
	return err
}

const finishImportJobFileMeta = `-- name: FinishImportJobFileMeta :exec
UPDATE import_jobs SET file_size_bytes = $2, file_checksum = $3 WHERE id = $1
`

type FinishImportJobFileMetaParams struct {
	ID            int64
	FileSizeBytes int64
	FileChecksum  *string
}

func (q *Queries) FinishImportJobFileMeta(ctx context.Context, arg FinishImportJobFileMetaParams) error {
	_, err := q.db.Exec(ctx, finishImportJobFileMeta, arg.ID, arg.FileSizeBytes, arg.FileChecksum)
	return err
}

const getCountryByISO2 = `-- name: GetCountryByISO2 :one
SELECT id, public_id, iso2, iso3, name, phone_code, currency, status, created_at, updated_at FROM countries WHERE iso2 = $1
`

func (q *Queries) GetCountryByISO2(ctx context.Context, iso2 string) (Country, error) {
	row := q.db.QueryRow(ctx, getCountryByISO2, iso2)
	var i Country
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Iso2,
		&i.Iso3,
		&i.Name,
		&i.PhoneCode,
		&i.Currency,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getImportJobByID = `-- name: GetImportJobByID :one
SELECT id, public_id, organization_id, import_type, status, file_name, file_size_bytes, file_checksum, total_rows, processed_rows, success_rows, failed_rows, error_summary, failure_reason, options, job_id, started_at, completed_at, created_by, created_at, updated_at FROM import_jobs WHERE id = $1
`

func (q *Queries) GetImportJobByID(ctx context.Context, id int64) (ImportJob, error) {
	row := q.db.QueryRow(ctx, getImportJobByID, id)
	var i ImportJob
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrganizationID,
		&i.ImportType,
		&i.Status,
		&i.FileName,
		&i.FileSizeBytes,
		&i.FileChecksum,
		&i.TotalRows,
		&i.ProcessedRows,
		&i.SuccessRows,
		&i.FailedRows,
		&i.ErrorSummary,
		&i.FailureReason,
		&i.Options,
		&i.JobID,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getImportJobByPublicID = `-- name: GetImportJobByPublicID :one
SELECT id, public_id, organization_id, import_type, status, file_name, file_size_bytes, file_checksum, total_rows, processed_rows, success_rows, failed_rows, error_summary, failure_reason, options, job_id, started_at, completed_at, created_by, created_at, updated_at FROM import_jobs
WHERE public_id = $1
  AND (organization_id IS NOT DISTINCT FROM $2)
`

type GetImportJobByPublicIDParams struct {
	PublicID       string
	OrganizationID *int64
}

func (q *Queries) GetImportJobByPublicID(ctx context.Context, arg GetImportJobByPublicIDParams) (ImportJob, error) {
	row := q.db.QueryRow(ctx, getImportJobByPublicID, arg.PublicID, arg.OrganizationID)
	var i ImportJob
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrganizationID,
		&i.ImportType,
		&i.Status,
		&i.FileName,
		&i.FileSizeBytes,
		&i.FileChecksum,
		&i.TotalRows,
		&i.ProcessedRows,
		&i.SuccessRows,
		&i.FailedRows,
		&i.ErrorSummary,
		&i.FailureReason,
		&i.Options,
		&i.JobID,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPincodeByPublicID = `-- name: GetPincodeByPublicID :one
SELECT id, public_id, country_id, code, state_id, district_id, city_id, office_name, latitude, longitude, is_remote, status, metadata, created_at, updated_at FROM pincodes WHERE public_id = $1
`

func (q *Queries) GetPincodeByPublicID(ctx context.Context, publicID string) (Pincode, error) {
	row := q.db.QueryRow(ctx, getPincodeByPublicID, publicID)
	var i Pincode
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.CountryID,
		&i.Code,
		&i.StateID,
		&i.DistrictID,
		&i.CityID,
		&i.OfficeName,
		&i.Latitude,
		&i.Longitude,
		&i.IsRemote,
		&i.Status,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPincodeIDByCode = `-- name: GetPincodeIDByCode :one
SELECT p.id FROM pincodes p
JOIN countries c ON c.id = p.country_id
WHERE p.code = $1 AND c.iso2 = $2
`

type GetPincodeIDByCodeParams struct {
	Code        string
	CountryIso2 string
}

func (q *Queries) GetPincodeIDByCode(ctx context.Context, arg GetPincodeIDByCodeParams) (int64, error) {
	row := q.db.QueryRow(ctx, getPincodeIDByCode, arg.Code, arg.CountryIso2)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getPincodeIDByCodeInCountry = `-- name: GetPincodeIDByCodeInCountry :one
SELECT id FROM pincodes
WHERE code = $1 AND country_id = $2
`

type GetPincodeIDByCodeInCountryParams struct {
	Code      string
	CountryID int64
}

// GetPincodeIDByCodeInCountry resolves a code within an already-known country.
//
// Callers that have resolved the country must use this rather than the ISO
// variant with a default: India and Nigeria both use six-digit codes with a
// non-zero lead, so the same digits can name a real place in either, and
// resolving against the wrong country silently maps a tenant's zone onto
// somebody else's postcode instead of failing.
func (q *Queries) GetPincodeIDByCodeInCountry(ctx context.Context, arg GetPincodeIDByCodeInCountryParams) (int64, error) {
	row := q.db.QueryRow(ctx, getPincodeIDByCodeInCountry, arg.Code, arg.CountryID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getStateByCode = `-- name: GetStateByCode :one
SELECT id, public_id, country_id, code, name, gst_state_code, status, created_at, updated_at FROM states WHERE country_id = $1 AND code = $2
`

type GetStateByCodeParams struct {
	CountryID int64
	Code      string
}

func (q *Queries) GetStateByCode(ctx context.Context, arg GetStateByCodeParams) (State, error) {
	row := q.db.QueryRow(ctx, getStateByCode, arg.CountryID, arg.Code)
	var i State
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.CountryID,
		&i.Code,
		&i.Name,
		&i.GstStateCode,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStateByName = `-- name: GetStateByName :one
SELECT id, public_id, country_id, code, name, gst_state_code, status, created_at, updated_at FROM states WHERE country_id = $1 AND lower(name) = lower($2)
`

type GetStateByNameParams struct {
	CountryID int64
	Lower     string
}

func (q *Queries) GetStateByName(ctx context.Context, arg GetStateByNameParams) (State, error) {
	row := q.db.QueryRow(ctx, getStateByName, arg.CountryID, arg.Lower)
	var i State
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.CountryID,
		&i.Code,
		&i.Name,
		&i.GstStateCode,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getZoneByCode = `-- name: GetZoneByCode :one
SELECT id, public_id, organization_id, code, name, zone_type, description, sort_order, status, created_at, updated_at FROM zones WHERE organization_id = $1 AND code = $2
`

type GetZoneByCodeParams struct {
	OrganizationID int64
	Code           string
}

func (q *Queries) GetZoneByCode(ctx context.Context, arg GetZoneByCodeParams) (Zone, error) {
	row := q.db.QueryRow(ctx, getZoneByCode, arg.OrganizationID, arg.Code)
	var i Zone
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrganizationID,
		&i.Code,
		&i.Name,
		&i.ZoneType,
		&i.Description,
		&i.SortOrder,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getZoneByPublicID = `-- name: GetZoneByPublicID :one
SELECT id, public_id, organization_id, code, name, zone_type, description, sort_order, status, created_at, updated_at FROM zones WHERE public_id = $1 AND organization_id = $2
`

type GetZoneByPublicIDParams struct {
	PublicID       string
	OrganizationID int64
}

func (q *Queries) GetZoneByPublicID(ctx context.Context, arg GetZoneByPublicIDParams) (Zone, error) {
	row := q.db.QueryRow(ctx, getZoneByPublicID, arg.PublicID, arg.OrganizationID)
	var i Zone
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrganizationID,
		&i.Code,
		&i.Name,
		&i.ZoneType,
		&i.Description,
		&i.SortOrder,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

type InsertImportRowsParams struct {
	ImportJobID int64
	RowNumber   int32
	Raw         []byte
}

const linkImportJobToJob = `-- name: LinkImportJobToJob :exec
UPDATE import_jobs SET job_id = $2 WHERE id = $1
`

type LinkImportJobToJobParams struct {
	ID    int64
	JobID *int64
}

func (q *Queries) LinkImportJobToJob(ctx context.Context, arg LinkImportJobToJobParams) error {
	_, err := q.db.Exec(ctx, linkImportJobToJob, arg.ID, arg.JobID)
	return err
}

const listCities = `-- name: ListCities :many
SELECT c.id, c.public_id, c.state_id, c.district_id, c.name, c.tier, c.latitude, c.longitude, c.status, c.created_at, c.updated_at, s.name AS state_name, s.code AS state_code
FROM cities c
JOIN states s ON s.id = c.state_id
WHERE c.status = 'ACTIVE'
  AND ($1::bigint IS NULL OR c.state_id = $1)
  AND ($2::text IS NULL OR lower(c.name) LIKE lower($2) || '%')
ORDER BY c.name
LIMIT $4 OFFSET $3
`

type ListCitiesParams struct {
	StateID   *int64
	Search    *string
	RowOffset int32
	RowLimit  int32
}

type ListCitiesRow struct {
	ID         int64
	PublicID   string
	StateID    int64
	DistrictID *int64
	Name       string
	Tier       string
	Latitude   *float64
	Longitude  *float64
	Status     string
	CreatedAt  time.Time
	UpdatedAt  time.Time
	StateName  string
	StateCode  string
}

func (q *Queries) ListCities(ctx context.Context, arg ListCitiesParams) ([]ListCitiesRow, error) {
	rows, err := q.db.Query(ctx, listCities,
		arg.StateID,
		arg.Search,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCitiesRow{}
	for rows.Next() {
		var i ListCitiesRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.StateID,
			&i.DistrictID,
			&i.Name,
			&i.Tier,
			&i.Latitude,
			&i.Longitude,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StateName,
			&i.StateCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCountries = `-- name: ListCountries :many


SELECT id, public_id, iso2, iso3, name, phone_code, currency, status, created_at, updated_at FROM countries WHERE status = 'ACTIVE' ORDER BY name
`

// Geography, zones and bulk import queries (M03).
// ---------------------------------------------------------------------------
// Countries / states / districts / cities
// ---------------------------------------------------------------------------
func (q *Queries) ListCountries(ctx context.Context) ([]Country, error) {
	rows, err := q.db.Query(ctx, listCountries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Country{}
	for rows.Next() {
		var i Country
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.Iso2,
			&i.Iso3,
			&i.Name,
			&i.PhoneCode,
			&i.Currency,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDistricts = `-- name: ListDistricts :many
SELECT id, public_id, state_id, code, name, status, created_at, updated_at FROM districts WHERE state_id = $1 AND status = 'ACTIVE' ORDER BY name
`

func (q *Queries) ListDistricts(ctx context.Context, stateID int64) ([]District, error) {
	rows, err := q.db.Query(ctx, listDistricts, stateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []District{}
	for rows.Next() {
		var i District
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.StateID,
			&i.Code,
			&i.Name,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDistrictsByState = `-- name: ListDistrictsByState :many
SELECT d.public_id, d.code, d.name, s.code AS state_code, s.name AS state_name
FROM districts d
JOIN states s ON s.id = d.state_id
JOIN countries c ON c.id = s.country_id
WHERE c.iso2 = $1::text
  AND s.code = $2::text
  AND d.status = 'ACTIVE'
ORDER BY d.name
`

type ListDistrictsByStateParams struct {
	Country   string
	StateCode string
}

type ListDistrictsByStateRow struct {
	PublicID  string
	Code      string
	Name      string
	StateCode string
	StateName string
}

// ListDistrictsByState lists a state's districts — Local Government Areas in
// Nigeria — by state code rather than internal id, so a caller holding only
// what a user picked does not need a second round trip.
func (q *Queries) ListDistrictsByState(ctx context.Context, arg ListDistrictsByStateParams) ([]ListDistrictsByStateRow, error) {
	rows, err := q.db.Query(ctx, listDistrictsByState, arg.Country, arg.StateCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDistrictsByStateRow{}
	for rows.Next() {
		var i ListDistrictsByStateRow
		if err := rows.Scan(
			&i.PublicID,
			&i.Code,
			&i.Name,
			&i.StateCode,
			&i.StateName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImportJobs = `-- name: ListImportJobs :many
SELECT i.id, i.public_id, i.organization_id, i.import_type, i.status, i.file_name, i.file_size_bytes, i.file_checksum, i.total_rows, i.processed_rows, i.success_rows, i.failed_rows, i.error_summary, i.failure_reason, i.options, i.job_id, i.started_at, i.completed_at, i.created_by, i.created_at, i.updated_at, count(*) OVER () AS total_count
FROM import_jobs i
WHERE (i.organization_id IS NOT DISTINCT FROM $1)
  AND ($2::text IS NULL OR i.import_type = $2)
  AND ($3::text IS NULL OR i.status = $3)
ORDER BY i.created_at DESC, i.id DESC
LIMIT $5 OFFSET $4
`

type ListImportJobsParams struct {
	OrganizationID *int64
	ImportType     *string
	Status         *string
	RowOffset      int32
	RowLimit       int32
}

type ListImportJobsRow struct {
	ID             int64
	PublicID       string
	OrganizationID *int64
	ImportType     string
	Status         string
	FileName       string
	FileSizeBytes  int64
	FileChecksum   *string
	TotalRows      int32
	ProcessedRows  int32
	SuccessRows    int32
	FailedRows     int32
	ErrorSummary   []byte
	FailureReason  *string
	Options        []byte
	JobID          *int64
	StartedAt      *time.Time
	CompletedAt    *time.Time
	CreatedBy      *int64
	CreatedAt      time.Time
	UpdatedAt      time.Time
	TotalCount     int64
}

func (q *Queries) ListImportJobs(ctx context.Context, arg ListImportJobsParams) ([]ListImportJobsRow, error) {
	rows, err := q.db.Query(ctx, listImportJobs,
		arg.OrganizationID,
		arg.ImportType,
		arg.Status,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListImportJobsRow{}
	for rows.Next() {
		var i ListImportJobsRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.OrganizationID,
			&i.ImportType,
			&i.Status,
			&i.FileName,
			&i.FileSizeBytes,
			&i.FileChecksum,
			&i.TotalRows,
			&i.ProcessedRows,
			&i.SuccessRows,
			&i.FailedRows,
			&i.ErrorSummary,
			&i.FailureReason,
			&i.Options,
			&i.JobID,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImportRowErrors = `-- name: ListImportRowErrors :many
SELECT id, row_number, raw, error_code, error_message
FROM import_rows
WHERE import_job_id = $1 AND status = 'FAILED' AND id > $2
ORDER BY id
LIMIT $3
`

type ListImportRowErrorsParams struct {
	ImportJobID int64
	CursorID    int64
	RowLimit    int32
}

type ListImportRowErrorsRow struct {
	ID           int64
	RowNumber    int32
	Raw          []byte
	ErrorCode    *string
	ErrorMessage *string
}

func (q *Queries) ListImportRowErrors(ctx context.Context, arg ListImportRowErrorsParams) ([]ListImportRowErrorsRow, error) {
	rows, err := q.db.Query(ctx, listImportRowErrors, arg.ImportJobID, arg.CursorID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListImportRowErrorsRow{}
	for rows.Next() {
		var i ListImportRowErrorsRow
		if err := rows.Scan(
			&i.ID,
			&i.RowNumber,
			&i.Raw,
			&i.ErrorCode,
			&i.ErrorMessage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLocalities = `-- name: ListLocalities :many
SELECT id, public_id, pincode_id, name, status, created_at, updated_at FROM localities WHERE pincode_id = $1 AND status = 'ACTIVE' ORDER BY name
`

func (q *Queries) ListLocalities(ctx context.Context, pincodeID int64) ([]Locality, error) {
	rows, err := q.db.Query(ctx, listLocalities, pincodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Locality{}
	for rows.Next() {
		var i Locality
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.PincodeID,
			&i.Name,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPincodeZoneMappings = `-- name: ListPincodeZoneMappings :many
SELECT m.public_id, m.is_remote_override, m.effective_from, m.effective_to, m.status,
       p.code AS pincode, p.is_remote AS pincode_is_remote,
       z.code AS zone_code, z.name AS zone_name,
       s.name AS state_name, c.name AS city_name,
       count(*) OVER () AS total_count
FROM pincode_zone_mappings m
JOIN pincodes p ON p.id = m.pincode_id
JOIN zones z ON z.id = m.zone_id
JOIN states s ON s.id = p.state_id
LEFT JOIN cities c ON c.id = p.city_id
WHERE m.organization_id = $1
  AND m.status = 'ACTIVE'
  AND ($2::bigint IS NULL OR m.zone_id = $2)
  AND ($3::text IS NULL OR p.code LIKE $3 || '%')
ORDER BY p.code
LIMIT $5 OFFSET $4
`

type ListPincodeZoneMappingsParams struct {
	OrganizationID int64
	ZoneID         *int64
	PincodePrefix  *string
	RowOffset      int32
	RowLimit       int32
}

type ListPincodeZoneMappingsRow struct {
	PublicID         string
	IsRemoteOverride *bool
	EffectiveFrom    time.Time
	EffectiveTo      *time.Time
	Status           string
	Pincode          string
	PincodeIsRemote  bool
	ZoneCode         string
	ZoneName         string
	StateName        string
	CityName         *string
	TotalCount       int64
}

func (q *Queries) ListPincodeZoneMappings(ctx context.Context, arg ListPincodeZoneMappingsParams) ([]ListPincodeZoneMappingsRow, error) {
	rows, err := q.db.Query(ctx, listPincodeZoneMappings,
		arg.OrganizationID,
		arg.ZoneID,
		arg.PincodePrefix,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPincodeZoneMappingsRow{}
	for rows.Next() {
		var i ListPincodeZoneMappingsRow
		if err := rows.Scan(
			&i.PublicID,
			&i.IsRemoteOverride,
			&i.EffectiveFrom,
			&i.EffectiveTo,
			&i.Status,
			&i.Pincode,
			&i.PincodeIsRemote,
			&i.ZoneCode,
			&i.ZoneName,
			&i.StateName,
			&i.CityName,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStates = `-- name: ListStates :many
SELECT s.id, s.public_id, s.country_id, s.code, s.name, s.gst_state_code, s.status, s.created_at, s.updated_at FROM states s
JOIN countries c ON c.id = s.country_id
WHERE c.iso2 = $1 AND s.status = 'ACTIVE'
ORDER BY s.name
`

func (q *Queries) ListStates(ctx context.Context, countryIso2 string) ([]State, error) {
	rows, err := q.db.Query(ctx, listStates, countryIso2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []State{}
	for rows.Next() {
		var i State
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.CountryID,
			&i.Code,
			&i.Name,
			&i.GstStateCode,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listZones = `-- name: ListZones :many
SELECT z.id, z.public_id, z.organization_id, z.code, z.name, z.zone_type, z.description, z.sort_order, z.status, z.created_at, z.updated_at, count(*) OVER () AS total_count
FROM zones z
WHERE z.organization_id = $1
  AND ($2::text IS NULL OR z.status = $2)
  AND ($3::text IS NULL OR z.zone_type = $3)
ORDER BY z.sort_order, z.code
LIMIT $5 OFFSET $4
`

type ListZonesParams struct {
	OrganizationID int64
	Status         *string
	ZoneType       *string
	RowOffset      int32
	RowLimit       int32
}

type ListZonesRow struct {
	ID             int64
	PublicID       string
	OrganizationID int64
	Code           string
	Name           string
	ZoneType       string
	Description    string
	SortOrder      int32
	Status         string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	TotalCount     int64
}

func (q *Queries) ListZones(ctx context.Context, arg ListZonesParams) ([]ListZonesRow, error) {
	rows, err := q.db.Query(ctx, listZones,
		arg.OrganizationID,
		arg.Status,
		arg.ZoneType,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListZonesRow{}
	for rows.Next() {
		var i ListZonesRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.OrganizationID,
			&i.Code,
			&i.Name,
			&i.ZoneType,
			&i.Description,
			&i.SortOrder,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lookupPincode = `-- name: LookupPincode :one

SELECT p.id, p.public_id, p.code, p.is_remote, p.status,
       p.latitude, p.longitude, p.office_name,
       p.state_id, s.name AS state_name, s.code AS state_code, s.gst_state_code,
       p.district_id, d.name AS district_name,
       p.city_id, c.name AS city_name, c.tier AS city_tier,
       p.country_id, co.iso2 AS country_iso2
FROM pincodes p
JOIN states s ON s.id = p.state_id
JOIN countries co ON co.id = p.country_id
LEFT JOIN districts d ON d.id = p.district_id
LEFT JOIN cities c ON c.id = p.city_id
WHERE p.code = $1 AND co.iso2 = $2
`

type LookupPincodeParams struct {
	Code        string
	CountryIso2 string
}

type LookupPincodeRow struct {
	ID           int64
	PublicID     string
	Code         string
	IsRemote     bool
	Status       string
	Latitude     *float64
	Longitude    *float64
	OfficeName   *string
	StateID      int64
	StateName    string
	StateCode    string
	GstStateCode *string
	DistrictID   *int64
	DistrictName *string
	CityID       *int64
	CityName     *string
	CityTier     *string
	CountryID    int64
	CountryIso2  string
}

// ---------------------------------------------------------------------------
// PIN codes
// ---------------------------------------------------------------------------
// LookupPincode is the hottest read in the platform: it runs at least twice on
// every booking and on every serviceability check. It is a single index lookup
// on pincodes_code_unique plus three primary-key joins.
func (q *Queries) LookupPincode(ctx context.Context, arg LookupPincodeParams) (LookupPincodeRow, error) {
	row := q.db.QueryRow(ctx, lookupPincode, arg.Code, arg.CountryIso2)
	var i LookupPincodeRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Code,
		&i.IsRemote,
		&i.Status,
		&i.Latitude,
		&i.Longitude,
		&i.OfficeName,
		&i.StateID,
		&i.StateName,
		&i.StateCode,
		&i.GstStateCode,
		&i.DistrictID,
		&i.DistrictName,
		&i.CityID,
		&i.CityName,
		&i.CityTier,
		&i.CountryID,
		&i.CountryIso2,
	)
	return i, err
}

const markImportRowFailed = `-- name: MarkImportRowFailed :exec
UPDATE import_rows
SET status = 'FAILED', error_code = $1,
    error_message = $2, processed_at = now()
WHERE id = $3
`

type MarkImportRowFailedParams struct {
	ErrorCode    *string
	ErrorMessage *string
	ID           int64
}

func (q *Queries) MarkImportRowFailed(ctx context.Context, arg MarkImportRowFailedParams) error {
	_, err := q.db.Exec(ctx, markImportRowFailed, arg.ErrorCode, arg.ErrorMessage, arg.ID)
	return err
}

const markImportRowsSucceeded = `-- name: MarkImportRowsSucceeded :execrows
UPDATE import_rows SET status = 'SUCCEEDED', processed_at = now()
WHERE id = ANY($1::bigint[])
`

func (q *Queries) MarkImportRowsSucceeded(ctx context.Context, rowIds []int64) (int64, error) {
	result, err := q.db.Exec(ctx, markImportRowsSucceeded, rowIds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const recordImportProgress = `-- name: RecordImportProgress :exec
UPDATE import_jobs
SET processed_rows = processed_rows + $1::int,
    success_rows = success_rows + $2::int,
    failed_rows = failed_rows + $3::int
WHERE id = $4
`

type RecordImportProgressParams struct {
	ProcessedDelta int32
	SuccessDelta   int32
	FailedDelta    int32
	ID             int64
}

func (q *Queries) RecordImportProgress(ctx context.Context, arg RecordImportProgressParams) error {
	_, err := q.db.Exec(ctx, recordImportProgress,
		arg.ProcessedDelta,
		arg.SuccessDelta,
		arg.FailedDelta,
		arg.ID,
	)
	return err
}

const resolveZoneForPincode = `-- name: ResolveZoneForPincode :one

SELECT z.id AS zone_id, z.public_id AS zone_public_id, z.code AS zone_code,
       z.name AS zone_name, z.zone_type,
       COALESCE(m.is_remote_override, p.is_remote) AS is_remote,
       m.public_id AS mapping_public_id
FROM pincode_zone_mappings m
JOIN zones z ON z.id = m.zone_id
JOIN pincodes p ON p.id = m.pincode_id
WHERE m.organization_id = $1
  AND m.pincode_id = $2
  AND m.status = 'ACTIVE'
  AND m.effective_from <= $3
  AND (m.effective_to IS NULL OR m.effective_to > $3)
`

type ResolveZoneForPincodeParams struct {
	OrganizationID int64
	PincodeID      int64
	AsOf           time.Time
}

type ResolveZoneForPincodeRow struct {
	ZoneID          int64
	ZonePublicID    string
	ZoneCode        string
	ZoneName        string
	ZoneType        string
	IsRemote        bool
	MappingPublicID string
}

// ---------------------------------------------------------------------------
// PIN code -> zone mappings
// ---------------------------------------------------------------------------
// ResolveZoneForPincode returns the tenant's zone for a PIN code together with
// the effective remote flag (tenant override falling back to the platform
// default). Serviceability and pricing both depend on this being a single
// indexed read.
func (q *Queries) ResolveZoneForPincode(ctx context.Context, arg ResolveZoneForPincodeParams) (ResolveZoneForPincodeRow, error) {
	row := q.db.QueryRow(ctx, resolveZoneForPincode, arg.OrganizationID, arg.PincodeID, arg.AsOf)
	var i ResolveZoneForPincodeRow
	err := row.Scan(
		&i.ZoneID,
		&i.ZonePublicID,
		&i.ZoneCode,
		&i.ZoneName,
		&i.ZoneType,
		&i.IsRemote,
		&i.MappingPublicID,
	)
	return i, err
}

const searchPincodes = `-- name: SearchPincodes :many
SELECT p.id, p.public_id, p.code, p.is_remote, p.status, p.office_name,
       s.name AS state_name, c.name AS city_name, c.tier AS city_tier,
       count(*) OVER () AS total_count
FROM pincodes p
JOIN states s ON s.id = p.state_id
LEFT JOIN cities c ON c.id = p.city_id
WHERE p.status = 'ACTIVE'
  AND ($1::text IS NULL OR p.code LIKE $1 || '%')
  AND ($2::bigint IS NULL OR p.state_id = $2)
  AND ($3::bigint IS NULL OR p.city_id = $3)
  AND ($4::boolean IS NULL OR p.is_remote = $4)
ORDER BY p.code
LIMIT $6 OFFSET $5
`

type SearchPincodesParams struct {
	CodePrefix *string
	StateID    *int64
	CityID     *int64
	IsRemote   *bool
	RowOffset  int32
	RowLimit   int32
}

type SearchPincodesRow struct {
	ID         int64
	PublicID   string
	Code       string
	IsRemote   bool
	Status     string
	OfficeName *string
	StateName  string
	CityName   *string
	CityTier   *string
	TotalCount int64
}

func (q *Queries) SearchPincodes(ctx context.Context, arg SearchPincodesParams) ([]SearchPincodesRow, error) {
	rows, err := q.db.Query(ctx, searchPincodes,
		arg.CodePrefix,
		arg.StateID,
		arg.CityID,
		arg.IsRemote,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchPincodesRow{}
	for rows.Next() {
		var i SearchPincodesRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.Code,
			&i.IsRemote,
			&i.Status,
			&i.OfficeName,
			&i.StateName,
			&i.CityName,
			&i.CityTier,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchPlaces = `-- name: SearchPlaces :many

WITH q AS (
    SELECT $1::text AS term,
           $2::text AS pattern,
           (SELECT id FROM countries WHERE iso2 = $3::text) AS country_id
), matched AS (
    SELECT p.id, p.code, 0 AS rank_class, p.code AS matched_name, 'CODE' AS matched_kind
    FROM pincodes p, q
    WHERE p.country_id = q.country_id AND p.status = 'ACTIVE'
      AND p.code ~>=~ q.term AND p.code ~<~ (q.term || chr(127))
    UNION ALL
    SELECT p.id, p.code, 1, l.name, 'AREA'
    FROM localities l JOIN pincodes p ON p.id = l.pincode_id, q
    WHERE p.country_id = q.country_id AND p.status = 'ACTIVE'
      AND l.status = 'ACTIVE' AND l.name ILIKE '%' || q.pattern || '%'
    UNION ALL
    SELECT p.id, p.code, 2, c.name, 'CITY'
    FROM pincodes p JOIN cities c ON c.id = p.city_id, q
    WHERE p.country_id = q.country_id AND p.status = 'ACTIVE'
      AND c.status = 'ACTIVE' AND c.name ILIKE '%' || q.pattern || '%'
    UNION ALL
    SELECT p.id, p.code, 3, p.office_name, 'OFFICE'
    FROM pincodes p, q
    WHERE p.country_id = q.country_id AND p.status = 'ACTIVE'
      AND p.office_name IS NOT NULL AND p.office_name ILIKE '%' || q.pattern || '%'
    UNION ALL
    SELECT p.id, p.code, 4, d.name, 'DISTRICT'
    FROM pincodes p JOIN districts d ON d.id = p.district_id, q
    WHERE p.country_id = q.country_id AND p.status = 'ACTIVE'
      AND d.status = 'ACTIVE' AND d.name ILIKE '%' || q.pattern || '%'
), best AS (
    SELECT DISTINCT ON (id) id, code, rank_class, matched_name, matched_kind
    FROM matched
    ORDER BY id, rank_class
), top AS (
    SELECT id, code, rank_class, matched_name, matched_kind
    FROM best
    ORDER BY rank_class, length(matched_name), matched_name, code
    LIMIT $4
)
SELECT p.public_id, p.code, p.is_remote,
       t.matched_name::text AS matched_name,
       t.matched_kind::text AS matched_kind,
       s.name AS state_name, s.code AS state_code,
       c.name AS city_name, d.name AS district_name,
       p.office_name
FROM top t
JOIN pincodes p ON p.id = t.id
JOIN states s ON s.id = p.state_id
LEFT JOIN cities c ON c.id = p.city_id
LEFT JOIN districts d ON d.id = p.district_id
ORDER BY t.rank_class, length(t.matched_name), t.matched_name, p.code
`

type SearchPlacesParams struct {
	Term     string
	Pattern  string
	Country  string
	RowLimit int32
}

type SearchPlacesRow struct {
	PublicID     string
	Code         string
	IsRemote     bool
	MatchedName  string
	MatchedKind  string
	StateName    string
	StateCode    string
	CityName     *string
	DistrictName *string
	OfficeName   *string
}

// ---------------------------------------------------------------------------
// Finding a postcode from what a sender knows
// ---------------------------------------------------------------------------
// SearchPlaces resolves a free-text fragment to postcode candidates.
//
// This exists because postcode adoption in Nigeria is poor: senders give an
// area, an LGA and a landmark, not six digits. Every other lookup in this file
// searches by code, which is exactly backwards for a booking form.
//
// One branch per source rather than a single OR: an OR across four tables
// cannot use any of the trigram indexes, and the planner falls back to
// sequential scans of all four. Each branch here is independently indexable.
//
// rank_class orders the branches by how strong the evidence is that this is the
// place the sender meant — an exact code beats a locality name, which beats a
// city, which beats an LGA covering hundreds of streets. DISTINCT ON collapses
// a postcode matched by several branches to its strongest one, so "Ikeja"
// appears once as an area rather than three times as area, office and LGA.
//
// Two things here are deliberate and were measured, not assumed:
//
//   - The code branch uses ~>=~ and ~<~ rather than LIKE. A LIKE pattern built
//     at runtime cannot be turned into index bounds during planning, so it cost
//     a full scan of pincodes on every keystroke, including for a term like
//     "maitama" that can never prefix-match a numeric code. The byte-ordered
//     range is the same set — every code character is ASCII below chr(127), so
//     [term, term||chr(127)) is exactly "starts with term" — and it uses
//     pincodes_prefix_idx with bounds evaluated at execution time.
//
//   - The limit is applied in `top`, before joining back for display columns.
//     Without it the planner estimates the union at its 200-row default, decides
//     a hash join is cheaper, and scans all of pincodes to build it. Limiting
//     first makes the outer side provably tiny and the join an index lookup.
//
// `term` is the raw fragment and `pattern` is the same fragment with LIKE
// wildcards escaped. They are separate parameters because they are consumed by
// different operators: escaping "10_" for ILIKE gives "10\_", which is correct
// as a pattern and wrong as a range bound.
func (q *Queries) SearchPlaces(ctx context.Context, arg SearchPlacesParams) ([]SearchPlacesRow, error) {
	rows, err := q.db.Query(ctx, searchPlaces,
		arg.Term,
		arg.Pattern,
		arg.Country,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchPlacesRow{}
	for rows.Next() {
		var i SearchPlacesRow
		if err := rows.Scan(
			&i.PublicID,
			&i.Code,
			&i.IsRemote,
			&i.MatchedName,
			&i.MatchedKind,
			&i.StateName,
			&i.StateCode,
			&i.CityName,
			&i.DistrictName,
			&i.OfficeName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setImportJobTotals = `-- name: SetImportJobTotals :exec
UPDATE import_jobs SET total_rows = $2 WHERE id = $1
`

type SetImportJobTotalsParams struct {
	ID        int64
	TotalRows int32
}

func (q *Queries) SetImportJobTotals(ctx context.Context, arg SetImportJobTotalsParams) error {
	_, err := q.db.Exec(ctx, setImportJobTotals, arg.ID, arg.TotalRows)
	return err
}

const setPincodeStatus = `-- name: SetPincodeStatus :one
UPDATE pincodes SET status = $2 WHERE public_id = $1 RETURNING id, public_id, country_id, code, state_id, district_id, city_id, office_name, latitude, longitude, is_remote, status, metadata, created_at, updated_at
`

type SetPincodeStatusParams struct {
	PublicID string
	Status   string
}

func (q *Queries) SetPincodeStatus(ctx context.Context, arg SetPincodeStatusParams) (Pincode, error) {
	row := q.db.QueryRow(ctx, setPincodeStatus, arg.PublicID, arg.Status)
	var i Pincode
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.CountryID,
		&i.Code,
		&i.StateID,
		&i.DistrictID,
		&i.CityID,
		&i.OfficeName,
		&i.Latitude,
		&i.Longitude,
		&i.IsRemote,
		&i.Status,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const startImportJob = `-- name: StartImportJob :exec
UPDATE import_jobs SET status = 'PROCESSING', started_at = now() WHERE id = $1
`

func (q *Queries) StartImportJob(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, startImportJob, id)
	return err
}

const updateZone = `-- name: UpdateZone :one
UPDATE zones
SET name = COALESCE($1, name),
    zone_type = COALESCE($2, zone_type),
    description = COALESCE($3, description),
    sort_order = COALESCE($4, sort_order),
    status = COALESCE($5, status)
WHERE public_id = $6 AND organization_id = $7
RETURNING id, public_id, organization_id, code, name, zone_type, description, sort_order, status, created_at, updated_at
`

type UpdateZoneParams struct {
	Name           *string
	ZoneType       *string
	Description    *string
	SortOrder      *int32
	Status         *string
	PublicID       string
	OrganizationID int64
}

func (q *Queries) UpdateZone(ctx context.Context, arg UpdateZoneParams) (Zone, error) {
	row := q.db.QueryRow(ctx, updateZone,
		arg.Name,
		arg.ZoneType,
		arg.Description,
		arg.SortOrder,
		arg.Status,
		arg.PublicID,
		arg.OrganizationID,
	)
	var i Zone
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrganizationID,
		&i.Code,
		&i.Name,
		&i.ZoneType,
		&i.Description,
		&i.SortOrder,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertCity = `-- name: UpsertCity :one
INSERT INTO cities (public_id, state_id, district_id, name, tier, latitude, longitude)
VALUES ($1,$2,$3,$4,$5,$6,$7)
ON CONFLICT (state_id, name) DO UPDATE
    SET district_id = COALESCE(EXCLUDED.district_id, cities.district_id),
        tier = EXCLUDED.tier
RETURNING id, public_id, state_id, district_id, name, tier, latitude, longitude, status, created_at, updated_at
`

type UpsertCityParams struct {
	PublicID   string
	StateID    int64
	DistrictID *int64
	Name       string
	Tier       string
	Latitude   *float64
	Longitude  *float64
}

func (q *Queries) UpsertCity(ctx context.Context, arg UpsertCityParams) (City, error) {
	row := q.db.QueryRow(ctx, upsertCity,
		arg.PublicID,
		arg.StateID,
		arg.DistrictID,
		arg.Name,
		arg.Tier,
		arg.Latitude,
		arg.Longitude,
	)
	var i City
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.StateID,
		&i.DistrictID,
		&i.Name,
		&i.Tier,
		&i.Latitude,
		&i.Longitude,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertCountry = `-- name: UpsertCountry :one
INSERT INTO countries (public_id, iso2, iso3, name, phone_code, currency)
VALUES ($1,$2,$3,$4,$5,$6)
ON CONFLICT (iso2) DO UPDATE SET name = EXCLUDED.name, phone_code = EXCLUDED.phone_code
RETURNING id, public_id, iso2, iso3, name, phone_code, currency, status, created_at, updated_at
`

type UpsertCountryParams struct {
	PublicID  string
	Iso2      string
	Iso3      string
	Name      string
	PhoneCode string
	Currency  string
}

func (q *Queries) UpsertCountry(ctx context.Context, arg UpsertCountryParams) (Country, error) {
	row := q.db.QueryRow(ctx, upsertCountry,
		arg.PublicID,
		arg.Iso2,
		arg.Iso3,
		arg.Name,
		arg.PhoneCode,
		arg.Currency,
	)
	var i Country
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Iso2,
		&i.Iso3,
		&i.Name,
		&i.PhoneCode,
		&i.Currency,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertDistrict = `-- name: UpsertDistrict :one
INSERT INTO districts (public_id, state_id, code, name)
VALUES ($1,$2,$3,$4)
ON CONFLICT (state_id, code) DO UPDATE SET name = EXCLUDED.name
RETURNING id, public_id, state_id, code, name, status, created_at, updated_at
`

type UpsertDistrictParams struct {
	PublicID string
	StateID  int64
	Code     string
	Name     string
}

func (q *Queries) UpsertDistrict(ctx context.Context, arg UpsertDistrictParams) (District, error) {
	row := q.db.QueryRow(ctx, upsertDistrict,
		arg.PublicID,
		arg.StateID,
		arg.Code,
		arg.Name,
	)
	var i District
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.StateID,
		&i.Code,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertLocality = `-- name: UpsertLocality :one
INSERT INTO localities (public_id, pincode_id, name)
VALUES ($1,$2,$3)
ON CONFLICT (pincode_id, name) DO UPDATE SET status = 'ACTIVE'
RETURNING id, public_id, pincode_id, name, status, created_at, updated_at
`

type UpsertLocalityParams struct {
	PublicID  string
	PincodeID int64
	Name      string
}

func (q *Queries) UpsertLocality(ctx context.Context, arg UpsertLocalityParams) (Locality, error) {
	row := q.db.QueryRow(ctx, upsertLocality, arg.PublicID, arg.PincodeID, arg.Name)
	var i Locality
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.PincodeID,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertPincode = `-- name: UpsertPincode :one
INSERT INTO pincodes (
    public_id, country_id, code, state_id, district_id, city_id,
    office_name, latitude, longitude, is_remote
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)
ON CONFLICT (country_id, code) DO UPDATE
    SET state_id = EXCLUDED.state_id,
        district_id = COALESCE(EXCLUDED.district_id, pincodes.district_id),
        city_id = COALESCE(EXCLUDED.city_id, pincodes.city_id),
        office_name = COALESCE(EXCLUDED.office_name, pincodes.office_name),
        latitude = COALESCE(EXCLUDED.latitude, pincodes.latitude),
        longitude = COALESCE(EXCLUDED.longitude, pincodes.longitude),
        is_remote = EXCLUDED.is_remote,
        status = 'ACTIVE'
RETURNING id, public_id, (xmax = 0) AS inserted
`

type UpsertPincodeParams struct {
	PublicID   string
	CountryID  int64
	Code       string
	StateID    int64
	DistrictID *int64
	CityID     *int64
	OfficeName *string
	Latitude   *float64
	Longitude  *float64
	IsRemote   bool
}

type UpsertPincodeRow struct {
	ID       int64
	PublicID string
	Inserted bool
}

func (q *Queries) UpsertPincode(ctx context.Context, arg UpsertPincodeParams) (UpsertPincodeRow, error) {
	row := q.db.QueryRow(ctx, upsertPincode,
		arg.PublicID,
		arg.CountryID,
		arg.Code,
		arg.StateID,
		arg.DistrictID,
		arg.CityID,
		arg.OfficeName,
		arg.Latitude,
		arg.Longitude,
		arg.IsRemote,
	)
	var i UpsertPincodeRow
	err := row.Scan(&i.ID, &i.PublicID, &i.Inserted)
	return i, err
}

const upsertPincodeZoneMapping = `-- name: UpsertPincodeZoneMapping :one
INSERT INTO pincode_zone_mappings (
    public_id, organization_id, pincode_id, zone_id, is_remote_override, effective_from, created_by
) VALUES ($1,$2,$3,$4,$5,$6,$7)
ON CONFLICT (organization_id, pincode_id) WHERE status = 'ACTIVE' DO UPDATE
    SET zone_id = EXCLUDED.zone_id,
        is_remote_override = EXCLUDED.is_remote_override,
        effective_from = EXCLUDED.effective_from
RETURNING id, public_id, organization_id, pincode_id, zone_id, is_remote_override, effective_from, effective_to, status, created_by, created_at, updated_at
`

type UpsertPincodeZoneMappingParams struct {
	PublicID         string
	OrganizationID   int64
	PincodeID        int64
	ZoneID           int64
	IsRemoteOverride *bool
	EffectiveFrom    time.Time
	CreatedBy        *int64
}

func (q *Queries) UpsertPincodeZoneMapping(ctx context.Context, arg UpsertPincodeZoneMappingParams) (PincodeZoneMapping, error) {
	row := q.db.QueryRow(ctx, upsertPincodeZoneMapping,
		arg.PublicID,
		arg.OrganizationID,
		arg.PincodeID,
		arg.ZoneID,
		arg.IsRemoteOverride,
		arg.EffectiveFrom,
		arg.CreatedBy,
	)
	var i PincodeZoneMapping
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrganizationID,
		&i.PincodeID,
		&i.ZoneID,
		&i.IsRemoteOverride,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertState = `-- name: UpsertState :one
INSERT INTO states (public_id, country_id, code, name, gst_state_code)
VALUES ($1,$2,$3,$4,$5)
ON CONFLICT (country_id, code) DO UPDATE
    SET name = EXCLUDED.name, gst_state_code = COALESCE(EXCLUDED.gst_state_code, states.gst_state_code)
RETURNING id, public_id, country_id, code, name, gst_state_code, status, created_at, updated_at
`

type UpsertStateParams struct {
	PublicID     string
	CountryID    int64
	Code         string
	Name         string
	GstStateCode *string
}

func (q *Queries) UpsertState(ctx context.Context, arg UpsertStateParams) (State, error) {
	row := q.db.QueryRow(ctx, upsertState,
		arg.PublicID,
		arg.CountryID,
		arg.Code,
		arg.Name,
		arg.GstStateCode,
	)
	var i State
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.CountryID,
		&i.Code,
		&i.Name,
		&i.GstStateCode,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
