// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: linehaul.sql

package dbgen

import (
	"context"
	"time"
)

const appendTripEvent = `-- name: AppendTripEvent :one
INSERT INTO trip_events (
    public_id, organization_id, trip_id, trip_leg_id, sequence, event_type,
    from_status, to_status, occurred_at, actor_user_id, operating_unit_id,
    latitude, longitude, description, reason_code, request_id, metadata
) VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, $8,
    COALESCE($9::timestamptz, now()), $10,
    $11, $12, $13,
    $14, $15, $16,
    $17
)
RETURNING id, public_id, organization_id, trip_id, trip_leg_id, sequence, event_type, from_status, to_status, occurred_at, recorded_at, actor_user_id, operating_unit_id, latitude, longitude, description, reason_code, request_id, metadata
`

type AppendTripEventParams struct {
	PublicID        string
	OrganizationID  int64
	TripID          int64
	TripLegID       *int64
	Sequence        int32
	EventType       string
	FromStatus      *string
	ToStatus        *string
	OccurredAt      *time.Time
	ActorUserID     *int64
	OperatingUnitID *int64
	Latitude        *float64
	Longitude       *float64
	Description     string
	ReasonCode      *string
	RequestID       *string
	Metadata        []byte
}

func (q *Queries) AppendTripEvent(ctx context.Context, arg AppendTripEventParams) (TripEvent, error) {
	row := q.db.QueryRow(ctx, appendTripEvent,
		arg.PublicID,
		arg.OrganizationID,
		arg.TripID,
		arg.TripLegID,
		arg.Sequence,
		arg.EventType,
		arg.FromStatus,
		arg.ToStatus,
		arg.OccurredAt,
		arg.ActorUserID,
		arg.OperatingUnitID,
		arg.Latitude,
		arg.Longitude,
		arg.Description,
		arg.ReasonCode,
		arg.RequestID,
		arg.Metadata,
	)
	var i TripEvent
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrganizationID,
		&i.TripID,
		&i.TripLegID,
		&i.Sequence,
		&i.EventType,
		&i.FromStatus,
		&i.ToStatus,
		&i.OccurredAt,
		&i.RecordedAt,
		&i.ActorUserID,
		&i.OperatingUnitID,
		&i.Latitude,
		&i.Longitude,
		&i.Description,
		&i.ReasonCode,
		&i.RequestID,
		&i.Metadata,
	)
	return i, err
}

const bumpTripEventSequence = `-- name: BumpTripEventSequence :one
UPDATE trips SET event_sequence = event_sequence + 1
WHERE id = $1 AND organization_id = $2
RETURNING id, event_sequence, status
`

type BumpTripEventSequenceParams struct {
	ID             int64
	OrganizationID int64
}

type BumpTripEventSequenceRow struct {
	ID            int64
	EventSequence int32
	Status        string
}

func (q *Queries) BumpTripEventSequence(ctx context.Context, arg BumpTripEventSequenceParams) (BumpTripEventSequenceRow, error) {
	row := q.db.QueryRow(ctx, bumpTripEventSequence, arg.ID, arg.OrganizationID)
	var i BumpTripEventSequenceRow
	err := row.Scan(&i.ID, &i.EventSequence, &i.Status)
	return i, err
}

const countOpenTripManifests = `-- name: CountOpenTripManifests :one
SELECT count(*) FROM manifests
WHERE trip_id = $1 AND status = 'DRAFT'
`

// Departure validation: every manifest on the trip must be CLOSED (§13).
func (q *Queries) CountOpenTripManifests(ctx context.Context, tripID *int64) (int64, error) {
	row := q.db.QueryRow(ctx, countOpenTripManifests, tripID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCarrier = `-- name: CreateCarrier :one

INSERT INTO carriers (
    public_id, organization_id, code, name, carrier_type, modes,
    contact_name, contact_phone, contact_email, gst_number, metadata
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)
RETURNING id, public_id, organization_id, code, name, carrier_type, modes, contact_name, contact_phone, contact_email, gst_number, is_active, metadata, created_at, updated_at
`

type CreateCarrierParams struct {
	PublicID       string
	OrganizationID int64
	Code           string
	Name           string
	CarrierType    string
	Modes          []string
	ContactName    *string
	ContactPhone   *string
	ContactEmail   *string
	GstNumber      *string
	Metadata       []byte
}

// Line haul (M13).
func (q *Queries) CreateCarrier(ctx context.Context, arg CreateCarrierParams) (Carrier, error) {
	row := q.db.QueryRow(ctx, createCarrier,
		arg.PublicID,
		arg.OrganizationID,
		arg.Code,
		arg.Name,
		arg.CarrierType,
		arg.Modes,
		arg.ContactName,
		arg.ContactPhone,
		arg.ContactEmail,
		arg.GstNumber,
		arg.Metadata,
	)
	var i Carrier
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrganizationID,
		&i.Code,
		&i.Name,
		&i.CarrierType,
		&i.Modes,
		&i.ContactName,
		&i.ContactPhone,
		&i.ContactEmail,
		&i.GstNumber,
		&i.IsActive,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createDriver = `-- name: CreateDriver :one
INSERT INTO drivers (
    public_id, organization_id, carrier_id, user_id, code, full_name, phone,
    licence_number, licence_expiry, base_unit_id, metadata
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)
RETURNING id, public_id, organization_id, carrier_id, user_id, code, full_name, phone, licence_number, licence_expiry, base_unit_id, is_active, metadata, created_at, updated_at
`

type CreateDriverParams struct {
	PublicID       string
	OrganizationID int64
	CarrierID      *int64
	UserID         *int64
	Code           string
	FullName       string
	Phone          string
	LicenceNumber  *string
	LicenceExpiry  *time.Time
	BaseUnitID     *int64
	Metadata       []byte
}

func (q *Queries) CreateDriver(ctx context.Context, arg CreateDriverParams) (Driver, error) {
	row := q.db.QueryRow(ctx, createDriver,
		arg.PublicID,
		arg.OrganizationID,
		arg.CarrierID,
		arg.UserID,
		arg.Code,
		arg.FullName,
		arg.Phone,
		arg.LicenceNumber,
		arg.LicenceExpiry,
		arg.BaseUnitID,
		arg.Metadata,
	)
	var i Driver
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrganizationID,
		&i.CarrierID,
		&i.UserID,
		&i.Code,
		&i.FullName,
		&i.Phone,
		&i.LicenceNumber,
		&i.LicenceExpiry,
		&i.BaseUnitID,
		&i.IsActive,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTrip = `-- name: CreateTrip :one

INSERT INTO trips (
    public_id, organization_id, trip_code, mode, origin_unit_id, destination_unit_id,
    route_definition_id, direction, carrier_id, vehicle_id, primary_driver_id,
    external_reference, scheduled_departure, scheduled_arrival, leg_count,
    created_by_user_id, metadata
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17)
RETURNING id, public_id, organization_id, trip_code, mode, status, origin_unit_id, destination_unit_id, route_definition_id, direction, carrier_id, vehicle_id, primary_driver_id, external_reference, scheduled_departure, scheduled_arrival, actual_departure, actual_arrival, closed_at, cancelled_at, cancellation_reason, current_leg_sequence, leg_count, manifest_count, bag_count, shipment_count, total_weight_grams, departure_odometer_km, arrival_odometer_km, seal_number, event_sequence, created_by_user_id, metadata, created_at, updated_at, version
`

type CreateTripParams struct {
	PublicID           string
	OrganizationID     int64
	TripCode           string
	Mode               string
	OriginUnitID       int64
	DestinationUnitID  int64
	RouteDefinitionID  *int64
	Direction          string
	CarrierID          *int64
	VehicleID          *int64
	PrimaryDriverID    *int64
	ExternalReference  *string
	ScheduledDeparture time.Time
	ScheduledArrival   time.Time
	LegCount           int32
	CreatedByUserID    *int64
	Metadata           []byte
}

// ---------------------------------------------------------------------------
// Trips
// ---------------------------------------------------------------------------
func (q *Queries) CreateTrip(ctx context.Context, arg CreateTripParams) (Trip, error) {
	row := q.db.QueryRow(ctx, createTrip,
		arg.PublicID,
		arg.OrganizationID,
		arg.TripCode,
		arg.Mode,
		arg.OriginUnitID,
		arg.DestinationUnitID,
		arg.RouteDefinitionID,
		arg.Direction,
		arg.CarrierID,
		arg.VehicleID,
		arg.PrimaryDriverID,
		arg.ExternalReference,
		arg.ScheduledDeparture,
		arg.ScheduledArrival,
		arg.LegCount,
		arg.CreatedByUserID,
		arg.Metadata,
	)
	var i Trip
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrganizationID,
		&i.TripCode,
		&i.Mode,
		&i.Status,
		&i.OriginUnitID,
		&i.DestinationUnitID,
		&i.RouteDefinitionID,
		&i.Direction,
		&i.CarrierID,
		&i.VehicleID,
		&i.PrimaryDriverID,
		&i.ExternalReference,
		&i.ScheduledDeparture,
		&i.ScheduledArrival,
		&i.ActualDeparture,
		&i.ActualArrival,
		&i.ClosedAt,
		&i.CancelledAt,
		&i.CancellationReason,
		&i.CurrentLegSequence,
		&i.LegCount,
		&i.ManifestCount,
		&i.BagCount,
		&i.ShipmentCount,
		&i.TotalWeightGrams,
		&i.DepartureOdometerKm,
		&i.ArrivalOdometerKm,
		&i.SealNumber,
		&i.EventSequence,
		&i.CreatedByUserID,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const createTripAssignment = `-- name: CreateTripAssignment :one
INSERT INTO trip_assignments (
    public_id, organization_id, trip_id, trip_leg_id, role, driver_id, user_id,
    assigned_by_user_id, remarks
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9)
RETURNING id, public_id, organization_id, trip_id, trip_leg_id, role, driver_id, user_id, status, assigned_at, assigned_by_user_id, released_at, remarks
`

type CreateTripAssignmentParams struct {
	PublicID         string
	OrganizationID   int64
	TripID           int64
	TripLegID        *int64
	Role             string
	DriverID         *int64
	UserID           *int64
	AssignedByUserID *int64
	Remarks          *string
}

func (q *Queries) CreateTripAssignment(ctx context.Context, arg CreateTripAssignmentParams) (TripAssignment, error) {
	row := q.db.QueryRow(ctx, createTripAssignment,
		arg.PublicID,
		arg.OrganizationID,
		arg.TripID,
		arg.TripLegID,
		arg.Role,
		arg.DriverID,
		arg.UserID,
		arg.AssignedByUserID,
		arg.Remarks,
	)
	var i TripAssignment
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrganizationID,
		&i.TripID,
		&i.TripLegID,
		&i.Role,
		&i.DriverID,
		&i.UserID,
		&i.Status,
		&i.AssignedAt,
		&i.AssignedByUserID,
		&i.ReleasedAt,
		&i.Remarks,
	)
	return i, err
}

const createTripLeg = `-- name: CreateTripLeg :one
INSERT INTO trip_legs (
    public_id, organization_id, trip_id, sequence, origin_unit_id, destination_unit_id,
    scheduled_departure, scheduled_arrival, distance_km
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9)
RETURNING id, public_id, organization_id, trip_id, sequence, origin_unit_id, destination_unit_id, status, scheduled_departure, scheduled_arrival, actual_departure, actual_arrival, distance_km, remarks
`

type CreateTripLegParams struct {
	PublicID           string
	OrganizationID     int64
	TripID             int64
	Sequence           int32
	OriginUnitID       int64
	DestinationUnitID  int64
	ScheduledDeparture time.Time
	ScheduledArrival   time.Time
	DistanceKm         *int32
}

func (q *Queries) CreateTripLeg(ctx context.Context, arg CreateTripLegParams) (TripLeg, error) {
	row := q.db.QueryRow(ctx, createTripLeg,
		arg.PublicID,
		arg.OrganizationID,
		arg.TripID,
		arg.Sequence,
		arg.OriginUnitID,
		arg.DestinationUnitID,
		arg.ScheduledDeparture,
		arg.ScheduledArrival,
		arg.DistanceKm,
	)
	var i TripLeg
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrganizationID,
		&i.TripID,
		&i.Sequence,
		&i.OriginUnitID,
		&i.DestinationUnitID,
		&i.Status,
		&i.ScheduledDeparture,
		&i.ScheduledArrival,
		&i.ActualDeparture,
		&i.ActualArrival,
		&i.DistanceKm,
		&i.Remarks,
	)
	return i, err
}

const createVehicle = `-- name: CreateVehicle :one
INSERT INTO vehicles (
    public_id, organization_id, carrier_id, registration_number, vehicle_type,
    capacity_weight_grams, capacity_volume_cc, base_unit_id,
    insurance_expiry, fitness_expiry, permit_expiry, metadata
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12)
RETURNING id, public_id, organization_id, carrier_id, registration_number, vehicle_type, capacity_weight_grams, capacity_volume_cc, base_unit_id, insurance_expiry, fitness_expiry, permit_expiry, is_active, metadata, created_at, updated_at
`

type CreateVehicleParams struct {
	PublicID            string
	OrganizationID      int64
	CarrierID           *int64
	RegistrationNumber  string
	VehicleType         string
	CapacityWeightGrams *int64
	CapacityVolumeCc    *int64
	BaseUnitID          *int64
	InsuranceExpiry     *time.Time
	FitnessExpiry       *time.Time
	PermitExpiry        *time.Time
	Metadata            []byte
}

func (q *Queries) CreateVehicle(ctx context.Context, arg CreateVehicleParams) (Vehicle, error) {
	row := q.db.QueryRow(ctx, createVehicle,
		arg.PublicID,
		arg.OrganizationID,
		arg.CarrierID,
		arg.RegistrationNumber,
		arg.VehicleType,
		arg.CapacityWeightGrams,
		arg.CapacityVolumeCc,
		arg.BaseUnitID,
		arg.InsuranceExpiry,
		arg.FitnessExpiry,
		arg.PermitExpiry,
		arg.Metadata,
	)
	var i Vehicle
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrganizationID,
		&i.CarrierID,
		&i.RegistrationNumber,
		&i.VehicleType,
		&i.CapacityWeightGrams,
		&i.CapacityVolumeCc,
		&i.BaseUnitID,
		&i.InsuranceExpiry,
		&i.FitnessExpiry,
		&i.PermitExpiry,
		&i.IsActive,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCarrierByPublicID = `-- name: GetCarrierByPublicID :one
SELECT id, public_id, organization_id, code, name, carrier_type, modes, contact_name, contact_phone, contact_email, gst_number, is_active, metadata, created_at, updated_at FROM carriers
WHERE public_id = $1 AND organization_id = $2
`

type GetCarrierByPublicIDParams struct {
	PublicID       string
	OrganizationID int64
}

func (q *Queries) GetCarrierByPublicID(ctx context.Context, arg GetCarrierByPublicIDParams) (Carrier, error) {
	row := q.db.QueryRow(ctx, getCarrierByPublicID, arg.PublicID, arg.OrganizationID)
	var i Carrier
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrganizationID,
		&i.Code,
		&i.Name,
		&i.CarrierType,
		&i.Modes,
		&i.ContactName,
		&i.ContactPhone,
		&i.ContactEmail,
		&i.GstNumber,
		&i.IsActive,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDriverByPublicID = `-- name: GetDriverByPublicID :one
SELECT d.id, d.public_id, d.organization_id, d.carrier_id, d.user_id, d.code, d.full_name, d.phone, d.licence_number, d.licence_expiry, d.base_unit_id, d.is_active, d.metadata, d.created_at, d.updated_at, c.code AS carrier_code, c.name AS carrier_name, ou.code AS base_unit_code
FROM drivers d
LEFT JOIN carriers c ON c.id = d.carrier_id
LEFT JOIN operating_units ou ON ou.id = d.base_unit_id
WHERE d.public_id = $1 AND d.organization_id = $2
`

type GetDriverByPublicIDParams struct {
	PublicID       string
	OrganizationID int64
}

type GetDriverByPublicIDRow struct {
	ID             int64
	PublicID       string
	OrganizationID int64
	CarrierID      *int64
	UserID         *int64
	Code           string
	FullName       string
	Phone          string
	LicenceNumber  *string
	LicenceExpiry  *time.Time
	BaseUnitID     *int64
	IsActive       bool
	Metadata       []byte
	CreatedAt      time.Time
	UpdatedAt      time.Time
	CarrierCode    *string
	CarrierName    *string
	BaseUnitCode   *string
}

func (q *Queries) GetDriverByPublicID(ctx context.Context, arg GetDriverByPublicIDParams) (GetDriverByPublicIDRow, error) {
	row := q.db.QueryRow(ctx, getDriverByPublicID, arg.PublicID, arg.OrganizationID)
	var i GetDriverByPublicIDRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrganizationID,
		&i.CarrierID,
		&i.UserID,
		&i.Code,
		&i.FullName,
		&i.Phone,
		&i.LicenceNumber,
		&i.LicenceExpiry,
		&i.BaseUnitID,
		&i.IsActive,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CarrierCode,
		&i.CarrierName,
		&i.BaseUnitCode,
	)
	return i, err
}

const getTripByPublicID = `-- name: GetTripByPublicID :one
SELECT t.id, t.public_id, t.organization_id, t.trip_code, t.mode, t.status, t.origin_unit_id, t.destination_unit_id, t.route_definition_id, t.direction, t.carrier_id, t.vehicle_id, t.primary_driver_id, t.external_reference, t.scheduled_departure, t.scheduled_arrival, t.actual_departure, t.actual_arrival, t.closed_at, t.cancelled_at, t.cancellation_reason, t.current_leg_sequence, t.leg_count, t.manifest_count, t.bag_count, t.shipment_count, t.total_weight_grams, t.departure_odometer_km, t.arrival_odometer_km, t.seal_number, t.event_sequence, t.created_by_user_id, t.metadata, t.created_at, t.updated_at, t.version,
       o.public_id AS origin_public_id, o.code AS origin_code, o.name AS origin_name,
       d.public_id AS destination_public_id, d.code AS destination_code, d.name AS destination_name,
       c.code AS carrier_code, c.name AS carrier_name,
       v.public_id AS vehicle_public_id, v.registration_number,
       dr.public_id AS driver_public_id, dr.full_name AS driver_name, dr.phone AS driver_phone
FROM trips t
JOIN operating_units o ON o.id = t.origin_unit_id
JOIN operating_units d ON d.id = t.destination_unit_id
LEFT JOIN carriers c ON c.id = t.carrier_id
LEFT JOIN vehicles v ON v.id = t.vehicle_id
LEFT JOIN drivers dr ON dr.id = t.primary_driver_id
WHERE t.public_id = $1 AND t.organization_id = $2
`

type GetTripByPublicIDParams struct {
	PublicID       string
	OrganizationID int64
}

type GetTripByPublicIDRow struct {
	ID                  int64
	PublicID            string
	OrganizationID      int64
	TripCode            string
	Mode                string
	Status              string
	OriginUnitID        int64
	DestinationUnitID   int64
	RouteDefinitionID   *int64
	Direction           string
	CarrierID           *int64
	VehicleID           *int64
	PrimaryDriverID     *int64
	ExternalReference   *string
	ScheduledDeparture  time.Time
	ScheduledArrival    time.Time
	ActualDeparture     *time.Time
	ActualArrival       *time.Time
	ClosedAt            *time.Time
	CancelledAt         *time.Time
	CancellationReason  *string
	CurrentLegSequence  *int32
	LegCount            int32
	ManifestCount       int32
	BagCount            int32
	ShipmentCount       int32
	TotalWeightGrams    int64
	DepartureOdometerKm *int32
	ArrivalOdometerKm   *int32
	SealNumber          *string
	EventSequence       int32
	CreatedByUserID     *int64
	Metadata            []byte
	CreatedAt           time.Time
	UpdatedAt           time.Time
	Version             int32
	OriginPublicID      string
	OriginCode          string
	OriginName          string
	DestinationPublicID string
	DestinationCode     string
	DestinationName     string
	CarrierCode         *string
	CarrierName         *string
	VehiclePublicID     *string
	RegistrationNumber  *string
	DriverPublicID      *string
	DriverName          *string
	DriverPhone         *string
}

func (q *Queries) GetTripByPublicID(ctx context.Context, arg GetTripByPublicIDParams) (GetTripByPublicIDRow, error) {
	row := q.db.QueryRow(ctx, getTripByPublicID, arg.PublicID, arg.OrganizationID)
	var i GetTripByPublicIDRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrganizationID,
		&i.TripCode,
		&i.Mode,
		&i.Status,
		&i.OriginUnitID,
		&i.DestinationUnitID,
		&i.RouteDefinitionID,
		&i.Direction,
		&i.CarrierID,
		&i.VehicleID,
		&i.PrimaryDriverID,
		&i.ExternalReference,
		&i.ScheduledDeparture,
		&i.ScheduledArrival,
		&i.ActualDeparture,
		&i.ActualArrival,
		&i.ClosedAt,
		&i.CancelledAt,
		&i.CancellationReason,
		&i.CurrentLegSequence,
		&i.LegCount,
		&i.ManifestCount,
		&i.BagCount,
		&i.ShipmentCount,
		&i.TotalWeightGrams,
		&i.DepartureOdometerKm,
		&i.ArrivalOdometerKm,
		&i.SealNumber,
		&i.EventSequence,
		&i.CreatedByUserID,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
		&i.OriginPublicID,
		&i.OriginCode,
		&i.OriginName,
		&i.DestinationPublicID,
		&i.DestinationCode,
		&i.DestinationName,
		&i.CarrierCode,
		&i.CarrierName,
		&i.VehiclePublicID,
		&i.RegistrationNumber,
		&i.DriverPublicID,
		&i.DriverName,
		&i.DriverPhone,
	)
	return i, err
}

const getTripLegBySequence = `-- name: GetTripLegBySequence :one
SELECT id, public_id, organization_id, trip_id, sequence, origin_unit_id, destination_unit_id, status, scheduled_departure, scheduled_arrival, actual_departure, actual_arrival, distance_km, remarks FROM trip_legs
WHERE trip_id = $1 AND sequence = $2
FOR UPDATE
`

type GetTripLegBySequenceParams struct {
	TripID   int64
	Sequence int32
}

func (q *Queries) GetTripLegBySequence(ctx context.Context, arg GetTripLegBySequenceParams) (TripLeg, error) {
	row := q.db.QueryRow(ctx, getTripLegBySequence, arg.TripID, arg.Sequence)
	var i TripLeg
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrganizationID,
		&i.TripID,
		&i.Sequence,
		&i.OriginUnitID,
		&i.DestinationUnitID,
		&i.Status,
		&i.ScheduledDeparture,
		&i.ScheduledArrival,
		&i.ActualDeparture,
		&i.ActualArrival,
		&i.DistanceKm,
		&i.Remarks,
	)
	return i, err
}

const getVehicleByPublicID = `-- name: GetVehicleByPublicID :one
SELECT v.id, v.public_id, v.organization_id, v.carrier_id, v.registration_number, v.vehicle_type, v.capacity_weight_grams, v.capacity_volume_cc, v.base_unit_id, v.insurance_expiry, v.fitness_expiry, v.permit_expiry, v.is_active, v.metadata, v.created_at, v.updated_at, c.code AS carrier_code, c.name AS carrier_name, ou.code AS base_unit_code
FROM vehicles v
LEFT JOIN carriers c ON c.id = v.carrier_id
LEFT JOIN operating_units ou ON ou.id = v.base_unit_id
WHERE v.public_id = $1 AND v.organization_id = $2
`

type GetVehicleByPublicIDParams struct {
	PublicID       string
	OrganizationID int64
}

type GetVehicleByPublicIDRow struct {
	ID                  int64
	PublicID            string
	OrganizationID      int64
	CarrierID           *int64
	RegistrationNumber  string
	VehicleType         string
	CapacityWeightGrams *int64
	CapacityVolumeCc    *int64
	BaseUnitID          *int64
	InsuranceExpiry     *time.Time
	FitnessExpiry       *time.Time
	PermitExpiry        *time.Time
	IsActive            bool
	Metadata            []byte
	CreatedAt           time.Time
	UpdatedAt           time.Time
	CarrierCode         *string
	CarrierName         *string
	BaseUnitCode        *string
}

func (q *Queries) GetVehicleByPublicID(ctx context.Context, arg GetVehicleByPublicIDParams) (GetVehicleByPublicIDRow, error) {
	row := q.db.QueryRow(ctx, getVehicleByPublicID, arg.PublicID, arg.OrganizationID)
	var i GetVehicleByPublicIDRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrganizationID,
		&i.CarrierID,
		&i.RegistrationNumber,
		&i.VehicleType,
		&i.CapacityWeightGrams,
		&i.CapacityVolumeCc,
		&i.BaseUnitID,
		&i.InsuranceExpiry,
		&i.FitnessExpiry,
		&i.PermitExpiry,
		&i.IsActive,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CarrierCode,
		&i.CarrierName,
		&i.BaseUnitCode,
	)
	return i, err
}

const listCarriers = `-- name: ListCarriers :many
SELECT id, public_id, organization_id, code, name, carrier_type, modes, contact_name, contact_phone, contact_email, gst_number, is_active, metadata, created_at, updated_at FROM carriers
WHERE organization_id = $1
  AND ($2::boolean IS NULL OR is_active = $2)
  AND ($3::text IS NULL OR carrier_type = $3)
ORDER BY name, id
LIMIT $5 OFFSET $4
`

type ListCarriersParams struct {
	OrganizationID int64
	IsActive       *bool
	CarrierType    *string
	RowOffset      int32
	PageSize       int32
}

func (q *Queries) ListCarriers(ctx context.Context, arg ListCarriersParams) ([]Carrier, error) {
	rows, err := q.db.Query(ctx, listCarriers,
		arg.OrganizationID,
		arg.IsActive,
		arg.CarrierType,
		arg.RowOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Carrier{}
	for rows.Next() {
		var i Carrier
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.OrganizationID,
			&i.Code,
			&i.Name,
			&i.CarrierType,
			&i.Modes,
			&i.ContactName,
			&i.ContactPhone,
			&i.ContactEmail,
			&i.GstNumber,
			&i.IsActive,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDrivers = `-- name: ListDrivers :many
SELECT d.id, d.public_id, d.organization_id, d.carrier_id, d.user_id, d.code, d.full_name, d.phone, d.licence_number, d.licence_expiry, d.base_unit_id, d.is_active, d.metadata, d.created_at, d.updated_at, c.code AS carrier_code, c.name AS carrier_name
FROM drivers d
LEFT JOIN carriers c ON c.id = d.carrier_id
WHERE d.organization_id = $1
  AND ($2::boolean IS NULL OR d.is_active = $2)
  AND ($3::bigint IS NULL OR d.carrier_id = $3)
ORDER BY d.full_name, d.id
LIMIT $5 OFFSET $4
`

type ListDriversParams struct {
	OrganizationID int64
	IsActive       *bool
	CarrierID      *int64
	RowOffset      int32
	PageSize       int32
}

type ListDriversRow struct {
	ID             int64
	PublicID       string
	OrganizationID int64
	CarrierID      *int64
	UserID         *int64
	Code           string
	FullName       string
	Phone          string
	LicenceNumber  *string
	LicenceExpiry  *time.Time
	BaseUnitID     *int64
	IsActive       bool
	Metadata       []byte
	CreatedAt      time.Time
	UpdatedAt      time.Time
	CarrierCode    *string
	CarrierName    *string
}

func (q *Queries) ListDrivers(ctx context.Context, arg ListDriversParams) ([]ListDriversRow, error) {
	rows, err := q.db.Query(ctx, listDrivers,
		arg.OrganizationID,
		arg.IsActive,
		arg.CarrierID,
		arg.RowOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDriversRow{}
	for rows.Next() {
		var i ListDriversRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.OrganizationID,
			&i.CarrierID,
			&i.UserID,
			&i.Code,
			&i.FullName,
			&i.Phone,
			&i.LicenceNumber,
			&i.LicenceExpiry,
			&i.BaseUnitID,
			&i.IsActive,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CarrierCode,
			&i.CarrierName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInboundTrips = `-- name: ListInboundTrips :many
SELECT t.public_id, t.trip_code, t.mode, t.status, t.scheduled_arrival, t.actual_departure,
       t.manifest_count, t.bag_count, t.shipment_count,
       o.code AS origin_code, o.name AS origin_name,
       v.registration_number, dr.full_name AS driver_name, dr.phone AS driver_phone
FROM trips t
JOIN operating_units o ON o.id = t.origin_unit_id
LEFT JOIN vehicles v ON v.id = t.vehicle_id
LEFT JOIN drivers dr ON dr.id = t.primary_driver_id
WHERE t.organization_id = $1
  AND t.destination_unit_id = $2
  AND t.status IN ('DEPARTED','IN_TRANSIT')
ORDER BY t.scheduled_arrival, t.id
LIMIT $3
`

type ListInboundTripsParams struct {
	OrganizationID    int64
	DestinationUnitID int64
	PageSize          int32
}

type ListInboundTripsRow struct {
	PublicID           string
	TripCode           string
	Mode               string
	Status             string
	ScheduledArrival   time.Time
	ActualDeparture    *time.Time
	ManifestCount      int32
	BagCount           int32
	ShipmentCount      int32
	OriginCode         string
	OriginName         string
	RegistrationNumber *string
	DriverName         *string
	DriverPhone        *string
}

func (q *Queries) ListInboundTrips(ctx context.Context, arg ListInboundTripsParams) ([]ListInboundTripsRow, error) {
	rows, err := q.db.Query(ctx, listInboundTrips, arg.OrganizationID, arg.DestinationUnitID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInboundTripsRow{}
	for rows.Next() {
		var i ListInboundTripsRow
		if err := rows.Scan(
			&i.PublicID,
			&i.TripCode,
			&i.Mode,
			&i.Status,
			&i.ScheduledArrival,
			&i.ActualDeparture,
			&i.ManifestCount,
			&i.BagCount,
			&i.ShipmentCount,
			&i.OriginCode,
			&i.OriginName,
			&i.RegistrationNumber,
			&i.DriverName,
			&i.DriverPhone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTripAssignments = `-- name: ListTripAssignments :many
SELECT ta.id, ta.public_id, ta.organization_id, ta.trip_id, ta.trip_leg_id, ta.role, ta.driver_id, ta.user_id, ta.status, ta.assigned_at, ta.assigned_by_user_id, ta.released_at, ta.remarks, d.full_name AS driver_name, d.phone AS driver_phone, d.public_id AS driver_public_id,
       u.full_name AS user_name, u.public_id AS user_public_id
FROM trip_assignments ta
LEFT JOIN drivers d ON d.id = ta.driver_id
LEFT JOIN users u ON u.id = ta.user_id
WHERE ta.trip_id = $1 AND ta.status IN ('ASSIGNED','ACCEPTED')
ORDER BY ta.role, ta.id
`

type ListTripAssignmentsRow struct {
	ID               int64
	PublicID         string
	OrganizationID   int64
	TripID           int64
	TripLegID        *int64
	Role             string
	DriverID         *int64
	UserID           *int64
	Status           string
	AssignedAt       time.Time
	AssignedByUserID *int64
	ReleasedAt       *time.Time
	Remarks          *string
	DriverName       *string
	DriverPhone      *string
	DriverPublicID   *string
	UserName         *string
	UserPublicID     *string
}

func (q *Queries) ListTripAssignments(ctx context.Context, tripID int64) ([]ListTripAssignmentsRow, error) {
	rows, err := q.db.Query(ctx, listTripAssignments, tripID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTripAssignmentsRow{}
	for rows.Next() {
		var i ListTripAssignmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.OrganizationID,
			&i.TripID,
			&i.TripLegID,
			&i.Role,
			&i.DriverID,
			&i.UserID,
			&i.Status,
			&i.AssignedAt,
			&i.AssignedByUserID,
			&i.ReleasedAt,
			&i.Remarks,
			&i.DriverName,
			&i.DriverPhone,
			&i.DriverPublicID,
			&i.UserName,
			&i.UserPublicID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTripEvents = `-- name: ListTripEvents :many
SELECT te.id, te.public_id, te.organization_id, te.trip_id, te.trip_leg_id, te.sequence, te.event_type, te.from_status, te.to_status, te.occurred_at, te.recorded_at, te.actor_user_id, te.operating_unit_id, te.latitude, te.longitude, te.description, te.reason_code, te.request_id, te.metadata, u.full_name AS actor_name, ou.code AS unit_code
FROM trip_events te
LEFT JOIN users u ON u.id = te.actor_user_id
LEFT JOIN operating_units ou ON ou.id = te.operating_unit_id
WHERE te.trip_id = $1
ORDER BY te.sequence DESC
LIMIT $2
`

type ListTripEventsParams struct {
	TripID   int64
	PageSize int32
}

type ListTripEventsRow struct {
	ID              int64
	PublicID        string
	OrganizationID  int64
	TripID          int64
	TripLegID       *int64
	Sequence        int32
	EventType       string
	FromStatus      *string
	ToStatus        *string
	OccurredAt      time.Time
	RecordedAt      time.Time
	ActorUserID     *int64
	OperatingUnitID *int64
	Latitude        *float64
	Longitude       *float64
	Description     string
	ReasonCode      *string
	RequestID       *string
	Metadata        []byte
	ActorName       *string
	UnitCode        *string
}

func (q *Queries) ListTripEvents(ctx context.Context, arg ListTripEventsParams) ([]ListTripEventsRow, error) {
	rows, err := q.db.Query(ctx, listTripEvents, arg.TripID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTripEventsRow{}
	for rows.Next() {
		var i ListTripEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.OrganizationID,
			&i.TripID,
			&i.TripLegID,
			&i.Sequence,
			&i.EventType,
			&i.FromStatus,
			&i.ToStatus,
			&i.OccurredAt,
			&i.RecordedAt,
			&i.ActorUserID,
			&i.OperatingUnitID,
			&i.Latitude,
			&i.Longitude,
			&i.Description,
			&i.ReasonCode,
			&i.RequestID,
			&i.Metadata,
			&i.ActorName,
			&i.UnitCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTripLegs = `-- name: ListTripLegs :many
SELECT tl.id, tl.public_id, tl.organization_id, tl.trip_id, tl.sequence, tl.origin_unit_id, tl.destination_unit_id, tl.status, tl.scheduled_departure, tl.scheduled_arrival, tl.actual_departure, tl.actual_arrival, tl.distance_km, tl.remarks, o.code AS origin_code, o.name AS origin_name,
       d.code AS destination_code, d.name AS destination_name,
       o.public_id AS origin_public_id, d.public_id AS destination_public_id
FROM trip_legs tl
JOIN operating_units o ON o.id = tl.origin_unit_id
JOIN operating_units d ON d.id = tl.destination_unit_id
WHERE tl.trip_id = $1
ORDER BY tl.sequence
`

type ListTripLegsRow struct {
	ID                  int64
	PublicID            string
	OrganizationID      int64
	TripID              int64
	Sequence            int32
	OriginUnitID        int64
	DestinationUnitID   int64
	Status              string
	ScheduledDeparture  time.Time
	ScheduledArrival    time.Time
	ActualDeparture     *time.Time
	ActualArrival       *time.Time
	DistanceKm          *int32
	Remarks             *string
	OriginCode          string
	OriginName          string
	DestinationCode     string
	DestinationName     string
	OriginPublicID      string
	DestinationPublicID string
}

func (q *Queries) ListTripLegs(ctx context.Context, tripID int64) ([]ListTripLegsRow, error) {
	rows, err := q.db.Query(ctx, listTripLegs, tripID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTripLegsRow{}
	for rows.Next() {
		var i ListTripLegsRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.OrganizationID,
			&i.TripID,
			&i.Sequence,
			&i.OriginUnitID,
			&i.DestinationUnitID,
			&i.Status,
			&i.ScheduledDeparture,
			&i.ScheduledArrival,
			&i.ActualDeparture,
			&i.ActualArrival,
			&i.DistanceKm,
			&i.Remarks,
			&i.OriginCode,
			&i.OriginName,
			&i.DestinationCode,
			&i.DestinationName,
			&i.OriginPublicID,
			&i.DestinationPublicID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTripManifests = `-- name: ListTripManifests :many
SELECT m.id, m.public_id, m.manifest_code, m.status, m.bag_count, m.total_shipment_count,
       m.total_piece_count, m.total_weight_grams, m.trip_leg_id,
       o.code AS origin_code, d.code AS destination_code, d.id AS destination_unit_id
FROM manifests m
JOIN operating_units o ON o.id = m.origin_unit_id
JOIN operating_units d ON d.id = m.destination_unit_id
WHERE m.trip_id = $1 AND m.status <> 'CANCELLED'
ORDER BY m.id
`

type ListTripManifestsRow struct {
	ID                 int64
	PublicID           string
	ManifestCode       string
	Status             string
	BagCount           int32
	TotalShipmentCount int32
	TotalPieceCount    int32
	TotalWeightGrams   int64
	TripLegID          *int64
	OriginCode         string
	DestinationCode    string
	DestinationUnitID  int64
}

func (q *Queries) ListTripManifests(ctx context.Context, tripID *int64) ([]ListTripManifestsRow, error) {
	rows, err := q.db.Query(ctx, listTripManifests, tripID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTripManifestsRow{}
	for rows.Next() {
		var i ListTripManifestsRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.ManifestCode,
			&i.Status,
			&i.BagCount,
			&i.TotalShipmentCount,
			&i.TotalPieceCount,
			&i.TotalWeightGrams,
			&i.TripLegID,
			&i.OriginCode,
			&i.DestinationCode,
			&i.DestinationUnitID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrips = `-- name: ListTrips :many
SELECT t.id, t.public_id, t.trip_code, t.mode, t.status, t.direction,
       t.scheduled_departure, t.scheduled_arrival, t.actual_departure, t.actual_arrival,
       t.manifest_count, t.bag_count, t.shipment_count, t.total_weight_grams,
       t.external_reference, t.leg_count, t.current_leg_sequence, t.created_at,
       o.public_id AS origin_public_id, o.code AS origin_code, o.name AS origin_name,
       d.public_id AS destination_public_id, d.code AS destination_code, d.name AS destination_name,
       v.registration_number, dr.full_name AS driver_name, c.name AS carrier_name
FROM trips t
JOIN operating_units o ON o.id = t.origin_unit_id
JOIN operating_units d ON d.id = t.destination_unit_id
LEFT JOIN vehicles v ON v.id = t.vehicle_id
LEFT JOIN drivers dr ON dr.id = t.primary_driver_id
LEFT JOIN carriers c ON c.id = t.carrier_id
WHERE t.organization_id = $1
  AND ($2::text IS NULL OR t.status = $2)
  AND ($3::text IS NULL OR t.mode = $3)
  AND ($4::bigint IS NULL OR t.origin_unit_id = $4)
  AND ($5::bigint IS NULL OR t.destination_unit_id = $5)
  AND ($6::bigint[] IS NULL
       OR t.origin_unit_id = ANY($6) OR t.destination_unit_id = ANY($6))
  AND ($7::timestamptz IS NULL
       OR (t.created_at, t.id) < ($7::timestamptz, $8::bigint))
ORDER BY t.created_at DESC, t.id DESC
LIMIT $9
`

type ListTripsParams struct {
	OrganizationID    int64
	Status            *string
	Mode              *string
	OriginUnitID      *int64
	DestinationUnitID *int64
	UnitIds           []int64
	CursorCreatedAt   *time.Time
	CursorID          *int64
	PageSize          int32
}

type ListTripsRow struct {
	ID                  int64
	PublicID            string
	TripCode            string
	Mode                string
	Status              string
	Direction           string
	ScheduledDeparture  time.Time
	ScheduledArrival    time.Time
	ActualDeparture     *time.Time
	ActualArrival       *time.Time
	ManifestCount       int32
	BagCount            int32
	ShipmentCount       int32
	TotalWeightGrams    int64
	ExternalReference   *string
	LegCount            int32
	CurrentLegSequence  *int32
	CreatedAt           time.Time
	OriginPublicID      string
	OriginCode          string
	OriginName          string
	DestinationPublicID string
	DestinationCode     string
	DestinationName     string
	RegistrationNumber  *string
	DriverName          *string
	CarrierName         *string
}

func (q *Queries) ListTrips(ctx context.Context, arg ListTripsParams) ([]ListTripsRow, error) {
	rows, err := q.db.Query(ctx, listTrips,
		arg.OrganizationID,
		arg.Status,
		arg.Mode,
		arg.OriginUnitID,
		arg.DestinationUnitID,
		arg.UnitIds,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTripsRow{}
	for rows.Next() {
		var i ListTripsRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.TripCode,
			&i.Mode,
			&i.Status,
			&i.Direction,
			&i.ScheduledDeparture,
			&i.ScheduledArrival,
			&i.ActualDeparture,
			&i.ActualArrival,
			&i.ManifestCount,
			&i.BagCount,
			&i.ShipmentCount,
			&i.TotalWeightGrams,
			&i.ExternalReference,
			&i.LegCount,
			&i.CurrentLegSequence,
			&i.CreatedAt,
			&i.OriginPublicID,
			&i.OriginCode,
			&i.OriginName,
			&i.DestinationPublicID,
			&i.DestinationCode,
			&i.DestinationName,
			&i.RegistrationNumber,
			&i.DriverName,
			&i.CarrierName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVehicles = `-- name: ListVehicles :many
SELECT v.id, v.public_id, v.organization_id, v.carrier_id, v.registration_number, v.vehicle_type, v.capacity_weight_grams, v.capacity_volume_cc, v.base_unit_id, v.insurance_expiry, v.fitness_expiry, v.permit_expiry, v.is_active, v.metadata, v.created_at, v.updated_at, c.code AS carrier_code, c.name AS carrier_name
FROM vehicles v
LEFT JOIN carriers c ON c.id = v.carrier_id
WHERE v.organization_id = $1
  AND ($2::boolean IS NULL OR v.is_active = $2)
  AND ($3::bigint IS NULL OR v.carrier_id = $3)
  AND ($4::text IS NULL OR v.vehicle_type = $4)
ORDER BY v.registration_number, v.id
LIMIT $6 OFFSET $5
`

type ListVehiclesParams struct {
	OrganizationID int64
	IsActive       *bool
	CarrierID      *int64
	VehicleType    *string
	RowOffset      int32
	PageSize       int32
}

type ListVehiclesRow struct {
	ID                  int64
	PublicID            string
	OrganizationID      int64
	CarrierID           *int64
	RegistrationNumber  string
	VehicleType         string
	CapacityWeightGrams *int64
	CapacityVolumeCc    *int64
	BaseUnitID          *int64
	InsuranceExpiry     *time.Time
	FitnessExpiry       *time.Time
	PermitExpiry        *time.Time
	IsActive            bool
	Metadata            []byte
	CreatedAt           time.Time
	UpdatedAt           time.Time
	CarrierCode         *string
	CarrierName         *string
}

func (q *Queries) ListVehicles(ctx context.Context, arg ListVehiclesParams) ([]ListVehiclesRow, error) {
	rows, err := q.db.Query(ctx, listVehicles,
		arg.OrganizationID,
		arg.IsActive,
		arg.CarrierID,
		arg.VehicleType,
		arg.RowOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVehiclesRow{}
	for rows.Next() {
		var i ListVehiclesRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.OrganizationID,
			&i.CarrierID,
			&i.RegistrationNumber,
			&i.VehicleType,
			&i.CapacityWeightGrams,
			&i.CapacityVolumeCc,
			&i.BaseUnitID,
			&i.InsuranceExpiry,
			&i.FitnessExpiry,
			&i.PermitExpiry,
			&i.IsActive,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CarrierCode,
			&i.CarrierName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockTripForUpdate = `-- name: LockTripForUpdate :one
SELECT id, public_id, organization_id, trip_code, mode, status, origin_unit_id, destination_unit_id, route_definition_id, direction, carrier_id, vehicle_id, primary_driver_id, external_reference, scheduled_departure, scheduled_arrival, actual_departure, actual_arrival, closed_at, cancelled_at, cancellation_reason, current_leg_sequence, leg_count, manifest_count, bag_count, shipment_count, total_weight_grams, departure_odometer_km, arrival_odometer_km, seal_number, event_sequence, created_by_user_id, metadata, created_at, updated_at, version FROM trips
WHERE public_id = $1 AND organization_id = $2
FOR UPDATE
`

type LockTripForUpdateParams struct {
	PublicID       string
	OrganizationID int64
}

func (q *Queries) LockTripForUpdate(ctx context.Context, arg LockTripForUpdateParams) (Trip, error) {
	row := q.db.QueryRow(ctx, lockTripForUpdate, arg.PublicID, arg.OrganizationID)
	var i Trip
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrganizationID,
		&i.TripCode,
		&i.Mode,
		&i.Status,
		&i.OriginUnitID,
		&i.DestinationUnitID,
		&i.RouteDefinitionID,
		&i.Direction,
		&i.CarrierID,
		&i.VehicleID,
		&i.PrimaryDriverID,
		&i.ExternalReference,
		&i.ScheduledDeparture,
		&i.ScheduledArrival,
		&i.ActualDeparture,
		&i.ActualArrival,
		&i.ClosedAt,
		&i.CancelledAt,
		&i.CancellationReason,
		&i.CurrentLegSequence,
		&i.LegCount,
		&i.ManifestCount,
		&i.BagCount,
		&i.ShipmentCount,
		&i.TotalWeightGrams,
		&i.DepartureOdometerKm,
		&i.ArrivalOdometerKm,
		&i.SealNumber,
		&i.EventSequence,
		&i.CreatedByUserID,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const recalculateTripCounters = `-- name: RecalculateTripCounters :one
UPDATE trips t
SET manifest_count = c.manifests, bag_count = c.bags,
    shipment_count = c.shipments, total_weight_grams = c.weight
FROM (
    SELECT count(*) AS manifests,
           COALESCE(sum(bag_count), 0)::int AS bags,
           COALESCE(sum(total_shipment_count), 0)::int AS shipments,
           COALESCE(sum(total_weight_grams), 0)::bigint AS weight
    FROM manifests
    WHERE trip_id = $1 AND status <> 'CANCELLED'
) c
WHERE t.id = $1
RETURNING t.id, t.public_id, t.organization_id, t.trip_code, t.mode, t.status, t.origin_unit_id, t.destination_unit_id, t.route_definition_id, t.direction, t.carrier_id, t.vehicle_id, t.primary_driver_id, t.external_reference, t.scheduled_departure, t.scheduled_arrival, t.actual_departure, t.actual_arrival, t.closed_at, t.cancelled_at, t.cancellation_reason, t.current_leg_sequence, t.leg_count, t.manifest_count, t.bag_count, t.shipment_count, t.total_weight_grams, t.departure_odometer_km, t.arrival_odometer_km, t.seal_number, t.event_sequence, t.created_by_user_id, t.metadata, t.created_at, t.updated_at, t.version
`

func (q *Queries) RecalculateTripCounters(ctx context.Context, tripID int64) (Trip, error) {
	row := q.db.QueryRow(ctx, recalculateTripCounters, tripID)
	var i Trip
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrganizationID,
		&i.TripCode,
		&i.Mode,
		&i.Status,
		&i.OriginUnitID,
		&i.DestinationUnitID,
		&i.RouteDefinitionID,
		&i.Direction,
		&i.CarrierID,
		&i.VehicleID,
		&i.PrimaryDriverID,
		&i.ExternalReference,
		&i.ScheduledDeparture,
		&i.ScheduledArrival,
		&i.ActualDeparture,
		&i.ActualArrival,
		&i.ClosedAt,
		&i.CancelledAt,
		&i.CancellationReason,
		&i.CurrentLegSequence,
		&i.LegCount,
		&i.ManifestCount,
		&i.BagCount,
		&i.ShipmentCount,
		&i.TotalWeightGrams,
		&i.DepartureOdometerKm,
		&i.ArrivalOdometerKm,
		&i.SealNumber,
		&i.EventSequence,
		&i.CreatedByUserID,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const releaseTripAssignment = `-- name: ReleaseTripAssignment :one
UPDATE trip_assignments SET status = 'RELEASED', released_at = now()
WHERE public_id = $1 AND organization_id = $2
RETURNING id, public_id, organization_id, trip_id, trip_leg_id, role, driver_id, user_id, status, assigned_at, assigned_by_user_id, released_at, remarks
`

type ReleaseTripAssignmentParams struct {
	PublicID       string
	OrganizationID int64
}

func (q *Queries) ReleaseTripAssignment(ctx context.Context, arg ReleaseTripAssignmentParams) (TripAssignment, error) {
	row := q.db.QueryRow(ctx, releaseTripAssignment, arg.PublicID, arg.OrganizationID)
	var i TripAssignment
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrganizationID,
		&i.TripID,
		&i.TripLegID,
		&i.Role,
		&i.DriverID,
		&i.UserID,
		&i.Status,
		&i.AssignedAt,
		&i.AssignedByUserID,
		&i.ReleasedAt,
		&i.Remarks,
	)
	return i, err
}

const updateCarrier = `-- name: UpdateCarrier :one
UPDATE carriers
SET name = COALESCE($1, name),
    carrier_type = COALESCE($2, carrier_type),
    modes = COALESCE($3, modes),
    contact_name = COALESCE($4, contact_name),
    contact_phone = COALESCE($5, contact_phone),
    contact_email = COALESCE($6, contact_email),
    gst_number = COALESCE($7, gst_number),
    is_active = COALESCE($8, is_active)
WHERE public_id = $9 AND organization_id = $10
RETURNING id, public_id, organization_id, code, name, carrier_type, modes, contact_name, contact_phone, contact_email, gst_number, is_active, metadata, created_at, updated_at
`

type UpdateCarrierParams struct {
	Name           *string
	CarrierType    *string
	Modes          []string
	ContactName    *string
	ContactPhone   *string
	ContactEmail   *string
	GstNumber      *string
	IsActive       *bool
	PublicID       string
	OrganizationID int64
}

func (q *Queries) UpdateCarrier(ctx context.Context, arg UpdateCarrierParams) (Carrier, error) {
	row := q.db.QueryRow(ctx, updateCarrier,
		arg.Name,
		arg.CarrierType,
		arg.Modes,
		arg.ContactName,
		arg.ContactPhone,
		arg.ContactEmail,
		arg.GstNumber,
		arg.IsActive,
		arg.PublicID,
		arg.OrganizationID,
	)
	var i Carrier
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrganizationID,
		&i.Code,
		&i.Name,
		&i.CarrierType,
		&i.Modes,
		&i.ContactName,
		&i.ContactPhone,
		&i.ContactEmail,
		&i.GstNumber,
		&i.IsActive,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDriver = `-- name: UpdateDriver :one
UPDATE drivers
SET full_name = COALESCE($1, full_name),
    phone = COALESCE($2, phone),
    carrier_id = COALESCE($3, carrier_id),
    user_id = COALESCE($4, user_id),
    licence_number = COALESCE($5, licence_number),
    licence_expiry = COALESCE($6, licence_expiry),
    base_unit_id = COALESCE($7, base_unit_id),
    is_active = COALESCE($8, is_active)
WHERE public_id = $9 AND organization_id = $10
RETURNING id, public_id, organization_id, carrier_id, user_id, code, full_name, phone, licence_number, licence_expiry, base_unit_id, is_active, metadata, created_at, updated_at
`

type UpdateDriverParams struct {
	FullName       *string
	Phone          *string
	CarrierID      *int64
	UserID         *int64
	LicenceNumber  *string
	LicenceExpiry  *time.Time
	BaseUnitID     *int64
	IsActive       *bool
	PublicID       string
	OrganizationID int64
}

func (q *Queries) UpdateDriver(ctx context.Context, arg UpdateDriverParams) (Driver, error) {
	row := q.db.QueryRow(ctx, updateDriver,
		arg.FullName,
		arg.Phone,
		arg.CarrierID,
		arg.UserID,
		arg.LicenceNumber,
		arg.LicenceExpiry,
		arg.BaseUnitID,
		arg.IsActive,
		arg.PublicID,
		arg.OrganizationID,
	)
	var i Driver
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrganizationID,
		&i.CarrierID,
		&i.UserID,
		&i.Code,
		&i.FullName,
		&i.Phone,
		&i.LicenceNumber,
		&i.LicenceExpiry,
		&i.BaseUnitID,
		&i.IsActive,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTripAssets = `-- name: UpdateTripAssets :one
UPDATE trips
SET vehicle_id = COALESCE($1, vehicle_id),
    primary_driver_id = COALESCE($2, primary_driver_id),
    carrier_id = COALESCE($3, carrier_id),
    external_reference = COALESCE($4, external_reference),
    scheduled_departure = COALESCE($5, scheduled_departure),
    scheduled_arrival = COALESCE($6, scheduled_arrival)
WHERE id = $7 AND organization_id = $8
  AND status IN ('PLANNED','LOADING')
RETURNING id, public_id, organization_id, trip_code, mode, status, origin_unit_id, destination_unit_id, route_definition_id, direction, carrier_id, vehicle_id, primary_driver_id, external_reference, scheduled_departure, scheduled_arrival, actual_departure, actual_arrival, closed_at, cancelled_at, cancellation_reason, current_leg_sequence, leg_count, manifest_count, bag_count, shipment_count, total_weight_grams, departure_odometer_km, arrival_odometer_km, seal_number, event_sequence, created_by_user_id, metadata, created_at, updated_at, version
`

type UpdateTripAssetsParams struct {
	VehicleID          *int64
	PrimaryDriverID    *int64
	CarrierID          *int64
	ExternalReference  *string
	ScheduledDeparture *time.Time
	ScheduledArrival   *time.Time
	ID                 int64
	OrganizationID     int64
}

func (q *Queries) UpdateTripAssets(ctx context.Context, arg UpdateTripAssetsParams) (Trip, error) {
	row := q.db.QueryRow(ctx, updateTripAssets,
		arg.VehicleID,
		arg.PrimaryDriverID,
		arg.CarrierID,
		arg.ExternalReference,
		arg.ScheduledDeparture,
		arg.ScheduledArrival,
		arg.ID,
		arg.OrganizationID,
	)
	var i Trip
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrganizationID,
		&i.TripCode,
		&i.Mode,
		&i.Status,
		&i.OriginUnitID,
		&i.DestinationUnitID,
		&i.RouteDefinitionID,
		&i.Direction,
		&i.CarrierID,
		&i.VehicleID,
		&i.PrimaryDriverID,
		&i.ExternalReference,
		&i.ScheduledDeparture,
		&i.ScheduledArrival,
		&i.ActualDeparture,
		&i.ActualArrival,
		&i.ClosedAt,
		&i.CancelledAt,
		&i.CancellationReason,
		&i.CurrentLegSequence,
		&i.LegCount,
		&i.ManifestCount,
		&i.BagCount,
		&i.ShipmentCount,
		&i.TotalWeightGrams,
		&i.DepartureOdometerKm,
		&i.ArrivalOdometerKm,
		&i.SealNumber,
		&i.EventSequence,
		&i.CreatedByUserID,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const updateTripLegStatus = `-- name: UpdateTripLegStatus :one
UPDATE trip_legs
SET status = $1,
    actual_departure = CASE WHEN $1::text = 'DEPARTED'
                            THEN COALESCE($2::timestamptz, now()) ELSE actual_departure END,
    actual_arrival = CASE WHEN $1::text = 'ARRIVED'
                          THEN COALESCE($2::timestamptz, now()) ELSE actual_arrival END,
    remarks = COALESCE($3, remarks)
WHERE id = $4 AND organization_id = $5
  AND status = $6
RETURNING id, public_id, organization_id, trip_id, sequence, origin_unit_id, destination_unit_id, status, scheduled_departure, scheduled_arrival, actual_departure, actual_arrival, distance_km, remarks
`

type UpdateTripLegStatusParams struct {
	ToStatus       string
	OccurredAt     *time.Time
	Remarks        *string
	ID             int64
	OrganizationID int64
	ExpectedStatus string
}

func (q *Queries) UpdateTripLegStatus(ctx context.Context, arg UpdateTripLegStatusParams) (TripLeg, error) {
	row := q.db.QueryRow(ctx, updateTripLegStatus,
		arg.ToStatus,
		arg.OccurredAt,
		arg.Remarks,
		arg.ID,
		arg.OrganizationID,
		arg.ExpectedStatus,
	)
	var i TripLeg
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrganizationID,
		&i.TripID,
		&i.Sequence,
		&i.OriginUnitID,
		&i.DestinationUnitID,
		&i.Status,
		&i.ScheduledDeparture,
		&i.ScheduledArrival,
		&i.ActualDeparture,
		&i.ActualArrival,
		&i.DistanceKm,
		&i.Remarks,
	)
	return i, err
}

const updateTripStatus = `-- name: UpdateTripStatus :one
UPDATE trips
SET status = $1,
    actual_departure = CASE WHEN $1::text = 'DEPARTED'
                            THEN COALESCE($2::timestamptz, now()) ELSE actual_departure END,
    actual_arrival = CASE WHEN $1::text = 'ARRIVED'
                          THEN COALESCE($2::timestamptz, now()) ELSE actual_arrival END,
    closed_at = CASE WHEN $1::text = 'CLOSED' THEN now() ELSE closed_at END,
    cancelled_at = CASE WHEN $1::text = 'CANCELLED' THEN now() ELSE cancelled_at END,
    cancellation_reason = COALESCE($3, cancellation_reason),
    departure_odometer_km = COALESCE($4, departure_odometer_km),
    arrival_odometer_km = COALESCE($5, arrival_odometer_km),
    seal_number = COALESCE($6, seal_number),
    current_leg_sequence = COALESCE($7, current_leg_sequence),
    event_sequence = event_sequence + 1
WHERE id = $8 AND organization_id = $9
  AND status = $10
RETURNING id, public_id, organization_id, trip_code, mode, status, origin_unit_id, destination_unit_id, route_definition_id, direction, carrier_id, vehicle_id, primary_driver_id, external_reference, scheduled_departure, scheduled_arrival, actual_departure, actual_arrival, closed_at, cancelled_at, cancellation_reason, current_leg_sequence, leg_count, manifest_count, bag_count, shipment_count, total_weight_grams, departure_odometer_km, arrival_odometer_km, seal_number, event_sequence, created_by_user_id, metadata, created_at, updated_at, version
`

type UpdateTripStatusParams struct {
	ToStatus            string
	OccurredAt          *time.Time
	CancellationReason  *string
	DepartureOdometerKm *int32
	ArrivalOdometerKm   *int32
	SealNumber          *string
	CurrentLegSequence  *int32
	ID                  int64
	OrganizationID      int64
	ExpectedStatus      string
}

// Compare-and-swap, so a second dispatcher pressing "depart" gets a conflict
// rather than a second departure event.
func (q *Queries) UpdateTripStatus(ctx context.Context, arg UpdateTripStatusParams) (Trip, error) {
	row := q.db.QueryRow(ctx, updateTripStatus,
		arg.ToStatus,
		arg.OccurredAt,
		arg.CancellationReason,
		arg.DepartureOdometerKm,
		arg.ArrivalOdometerKm,
		arg.SealNumber,
		arg.CurrentLegSequence,
		arg.ID,
		arg.OrganizationID,
		arg.ExpectedStatus,
	)
	var i Trip
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrganizationID,
		&i.TripCode,
		&i.Mode,
		&i.Status,
		&i.OriginUnitID,
		&i.DestinationUnitID,
		&i.RouteDefinitionID,
		&i.Direction,
		&i.CarrierID,
		&i.VehicleID,
		&i.PrimaryDriverID,
		&i.ExternalReference,
		&i.ScheduledDeparture,
		&i.ScheduledArrival,
		&i.ActualDeparture,
		&i.ActualArrival,
		&i.ClosedAt,
		&i.CancelledAt,
		&i.CancellationReason,
		&i.CurrentLegSequence,
		&i.LegCount,
		&i.ManifestCount,
		&i.BagCount,
		&i.ShipmentCount,
		&i.TotalWeightGrams,
		&i.DepartureOdometerKm,
		&i.ArrivalOdometerKm,
		&i.SealNumber,
		&i.EventSequence,
		&i.CreatedByUserID,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const updateVehicle = `-- name: UpdateVehicle :one
UPDATE vehicles
SET vehicle_type = COALESCE($1, vehicle_type),
    carrier_id = COALESCE($2, carrier_id),
    capacity_weight_grams = COALESCE($3, capacity_weight_grams),
    capacity_volume_cc = COALESCE($4, capacity_volume_cc),
    base_unit_id = COALESCE($5, base_unit_id),
    insurance_expiry = COALESCE($6, insurance_expiry),
    fitness_expiry = COALESCE($7, fitness_expiry),
    permit_expiry = COALESCE($8, permit_expiry),
    is_active = COALESCE($9, is_active)
WHERE public_id = $10 AND organization_id = $11
RETURNING id, public_id, organization_id, carrier_id, registration_number, vehicle_type, capacity_weight_grams, capacity_volume_cc, base_unit_id, insurance_expiry, fitness_expiry, permit_expiry, is_active, metadata, created_at, updated_at
`

type UpdateVehicleParams struct {
	VehicleType         *string
	CarrierID           *int64
	CapacityWeightGrams *int64
	CapacityVolumeCc    *int64
	BaseUnitID          *int64
	InsuranceExpiry     *time.Time
	FitnessExpiry       *time.Time
	PermitExpiry        *time.Time
	IsActive            *bool
	PublicID            string
	OrganizationID      int64
}

func (q *Queries) UpdateVehicle(ctx context.Context, arg UpdateVehicleParams) (Vehicle, error) {
	row := q.db.QueryRow(ctx, updateVehicle,
		arg.VehicleType,
		arg.CarrierID,
		arg.CapacityWeightGrams,
		arg.CapacityVolumeCc,
		arg.BaseUnitID,
		arg.InsuranceExpiry,
		arg.FitnessExpiry,
		arg.PermitExpiry,
		arg.IsActive,
		arg.PublicID,
		arg.OrganizationID,
	)
	var i Vehicle
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrganizationID,
		&i.CarrierID,
		&i.RegistrationNumber,
		&i.VehicleType,
		&i.CapacityWeightGrams,
		&i.CapacityVolumeCc,
		&i.BaseUnitID,
		&i.InsuranceExpiry,
		&i.FitnessExpiry,
		&i.PermitExpiry,
		&i.IsActive,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
