// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ndr_rto.sql

package dbgen

import (
	"context"
	"time"
)

const advanceRTOLeg = `-- name: AdvanceRTOLeg :one
UPDATE rto_legs
SET status = $1,
    started_at = CASE WHEN $1::text = 'IN_PROGRESS'
                      THEN COALESCE(started_at, now()) ELSE started_at END,
    completed_at = CASE WHEN $1::text = 'COMPLETED' THEN now() ELSE completed_at END,
    trip_id = COALESCE($2, trip_id),
    manifest_id = COALESCE($3, manifest_id)
WHERE rto_case_id = $4 AND sequence = $5
RETURNING id, organization_id, rto_case_id, sequence, from_unit_id, to_unit_id, leg_type, status, trip_id, manifest_id, started_at, completed_at
`

type AdvanceRTOLegParams struct {
	ToStatus   string
	TripID     *int64
	ManifestID *int64
	RtoCaseID  int64
	Sequence   int32
}

func (q *Queries) AdvanceRTOLeg(ctx context.Context, arg AdvanceRTOLegParams) (RtoLeg, error) {
	row := q.db.QueryRow(ctx, advanceRTOLeg,
		arg.ToStatus,
		arg.TripID,
		arg.ManifestID,
		arg.RtoCaseID,
		arg.Sequence,
	)
	var i RtoLeg
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.RtoCaseID,
		&i.Sequence,
		&i.FromUnitID,
		&i.ToUnitID,
		&i.LegType,
		&i.Status,
		&i.TripID,
		&i.ManifestID,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const applyNDRAddressCorrection = `-- name: ApplyNDRAddressCorrection :one
UPDATE ndr_cases
SET corrected_address_line1 = $1,
    corrected_address_line2 = $2,
    corrected_landmark = $3,
    corrected_pincode = $4,
    corrected_phone = $5,
    corrected_at = now(),
    corrected_by_user_id = $6
WHERE id = $7 AND organization_id = $8
RETURNING id, public_id, organization_id, case_code, shipment_id, status, ndr_reason_id, current_reason_code, attempt_count, max_attempts, branch_id, assigned_to_user_id, current_action, next_attempt_at, corrected_address_line1, corrected_address_line2, corrected_landmark, corrected_pincode, corrected_phone, corrected_at, corrected_by_user_id, opened_at, resolved_at, resolution_notes, metadata, created_at, updated_at, version
`

type ApplyNDRAddressCorrectionParams struct {
	Line1             *string
	Line2             *string
	Landmark          *string
	Pincode           *string
	Phone             *string
	CorrectedByUserID *int64
	ID                int64
	OrganizationID    int64
}

func (q *Queries) ApplyNDRAddressCorrection(ctx context.Context, arg ApplyNDRAddressCorrectionParams) (NdrCase, error) {
	row := q.db.QueryRow(ctx, applyNDRAddressCorrection,
		arg.Line1,
		arg.Line2,
		arg.Landmark,
		arg.Pincode,
		arg.Phone,
		arg.CorrectedByUserID,
		arg.ID,
		arg.OrganizationID,
	)
	var i NdrCase
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrganizationID,
		&i.CaseCode,
		&i.ShipmentID,
		&i.Status,
		&i.NdrReasonID,
		&i.CurrentReasonCode,
		&i.AttemptCount,
		&i.MaxAttempts,
		&i.BranchID,
		&i.AssignedToUserID,
		&i.CurrentAction,
		&i.NextAttemptAt,
		&i.CorrectedAddressLine1,
		&i.CorrectedAddressLine2,
		&i.CorrectedLandmark,
		&i.CorrectedPincode,
		&i.CorrectedPhone,
		&i.CorrectedAt,
		&i.CorrectedByUserID,
		&i.OpenedAt,
		&i.ResolvedAt,
		&i.ResolutionNotes,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const createNDRAction = `-- name: CreateNDRAction :one
INSERT INTO ndr_actions (
    public_id, organization_id, ndr_case_id, sequence, action, requested_by,
    instructions, scheduled_for, contact_name, contact_phone, contact_notes,
    created_by_user_id, metadata
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13)
RETURNING id, public_id, organization_id, ndr_case_id, sequence, action, requested_by, instructions, scheduled_for, contact_name, contact_phone, contact_notes, status, applied_at, created_at, created_by_user_id, metadata
`

type CreateNDRActionParams struct {
	PublicID        string
	OrganizationID  int64
	NdrCaseID       int64
	Sequence        int32
	Action          string
	RequestedBy     string
	Instructions    *string
	ScheduledFor    *time.Time
	ContactName     *string
	ContactPhone    *string
	ContactNotes    *string
	CreatedByUserID *int64
	Metadata        []byte
}

func (q *Queries) CreateNDRAction(ctx context.Context, arg CreateNDRActionParams) (NdrAction, error) {
	row := q.db.QueryRow(ctx, createNDRAction,
		arg.PublicID,
		arg.OrganizationID,
		arg.NdrCaseID,
		arg.Sequence,
		arg.Action,
		arg.RequestedBy,
		arg.Instructions,
		arg.ScheduledFor,
		arg.ContactName,
		arg.ContactPhone,
		arg.ContactNotes,
		arg.CreatedByUserID,
		arg.Metadata,
	)
	var i NdrAction
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrganizationID,
		&i.NdrCaseID,
		&i.Sequence,
		&i.Action,
		&i.RequestedBy,
		&i.Instructions,
		&i.ScheduledFor,
		&i.ContactName,
		&i.ContactPhone,
		&i.ContactNotes,
		&i.Status,
		&i.AppliedAt,
		&i.CreatedAt,
		&i.CreatedByUserID,
		&i.Metadata,
	)
	return i, err
}

const createNDRAttempt = `-- name: CreateNDRAttempt :one
INSERT INTO ndr_attempts (
    public_id, organization_id, ndr_case_id, delivery_attempt_id, attempt_number,
    reason_code, remarks, evidence_object_keys, occurred_at, recorded_by_user_id, metadata
) VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, $8,
    COALESCE($9::timestamptz, now()),
    $10, $11
)
RETURNING id, public_id, organization_id, ndr_case_id, delivery_attempt_id, attempt_number, reason_code, remarks, evidence_object_keys, occurred_at, recorded_at, recorded_by_user_id, metadata
`

type CreateNDRAttemptParams struct {
	PublicID           string
	OrganizationID     int64
	NdrCaseID          int64
	DeliveryAttemptID  *int64
	AttemptNumber      int32
	ReasonCode         string
	Remarks            *string
	EvidenceObjectKeys []string
	OccurredAt         *time.Time
	RecordedByUserID   *int64
	Metadata           []byte
}

func (q *Queries) CreateNDRAttempt(ctx context.Context, arg CreateNDRAttemptParams) (NdrAttempt, error) {
	row := q.db.QueryRow(ctx, createNDRAttempt,
		arg.PublicID,
		arg.OrganizationID,
		arg.NdrCaseID,
		arg.DeliveryAttemptID,
		arg.AttemptNumber,
		arg.ReasonCode,
		arg.Remarks,
		arg.EvidenceObjectKeys,
		arg.OccurredAt,
		arg.RecordedByUserID,
		arg.Metadata,
	)
	var i NdrAttempt
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrganizationID,
		&i.NdrCaseID,
		&i.DeliveryAttemptID,
		&i.AttemptNumber,
		&i.ReasonCode,
		&i.Remarks,
		&i.EvidenceObjectKeys,
		&i.OccurredAt,
		&i.RecordedAt,
		&i.RecordedByUserID,
		&i.Metadata,
	)
	return i, err
}

const createNDRCase = `-- name: CreateNDRCase :one

INSERT INTO ndr_cases (
    public_id, organization_id, case_code, shipment_id, ndr_reason_id,
    current_reason_code, max_attempts, branch_id, current_action, next_attempt_at, metadata
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)
RETURNING id, public_id, organization_id, case_code, shipment_id, status, ndr_reason_id, current_reason_code, attempt_count, max_attempts, branch_id, assigned_to_user_id, current_action, next_attempt_at, corrected_address_line1, corrected_address_line2, corrected_landmark, corrected_pincode, corrected_phone, corrected_at, corrected_by_user_id, opened_at, resolved_at, resolution_notes, metadata, created_at, updated_at, version
`

type CreateNDRCaseParams struct {
	PublicID          string
	OrganizationID    int64
	CaseCode          string
	ShipmentID        int64
	NdrReasonID       *int64
	CurrentReasonCode string
	MaxAttempts       int32
	BranchID          *int64
	CurrentAction     *string
	NextAttemptAt     *time.Time
	Metadata          []byte
}

// ---------------------------------------------------------------------------
// NDR cases
// ---------------------------------------------------------------------------
func (q *Queries) CreateNDRCase(ctx context.Context, arg CreateNDRCaseParams) (NdrCase, error) {
	row := q.db.QueryRow(ctx, createNDRCase,
		arg.PublicID,
		arg.OrganizationID,
		arg.CaseCode,
		arg.ShipmentID,
		arg.NdrReasonID,
		arg.CurrentReasonCode,
		arg.MaxAttempts,
		arg.BranchID,
		arg.CurrentAction,
		arg.NextAttemptAt,
		arg.Metadata,
	)
	var i NdrCase
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrganizationID,
		&i.CaseCode,
		&i.ShipmentID,
		&i.Status,
		&i.NdrReasonID,
		&i.CurrentReasonCode,
		&i.AttemptCount,
		&i.MaxAttempts,
		&i.BranchID,
		&i.AssignedToUserID,
		&i.CurrentAction,
		&i.NextAttemptAt,
		&i.CorrectedAddressLine1,
		&i.CorrectedAddressLine2,
		&i.CorrectedLandmark,
		&i.CorrectedPincode,
		&i.CorrectedPhone,
		&i.CorrectedAt,
		&i.CorrectedByUserID,
		&i.OpenedAt,
		&i.ResolvedAt,
		&i.ResolutionNotes,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const createNDRReason = `-- name: CreateNDRReason :one

INSERT INTO ndr_reasons (
    public_id, organization_id, code, name, description, category, default_action,
    max_attempts, is_customer_fault, requires_evidence, auto_rto_after_max, display_order
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12)
RETURNING id, public_id, organization_id, code, name, description, category, default_action, max_attempts, is_customer_fault, requires_evidence, auto_rto_after_max, is_active, display_order, created_at, updated_at
`

type CreateNDRReasonParams struct {
	PublicID         string
	OrganizationID   int64
	Code             string
	Name             string
	Description      *string
	Category         string
	DefaultAction    string
	MaxAttempts      int32
	IsCustomerFault  bool
	RequiresEvidence bool
	AutoRtoAfterMax  bool
	DisplayOrder     int32
}

// NDR (M17) and RTO (M18).
func (q *Queries) CreateNDRReason(ctx context.Context, arg CreateNDRReasonParams) (NdrReason, error) {
	row := q.db.QueryRow(ctx, createNDRReason,
		arg.PublicID,
		arg.OrganizationID,
		arg.Code,
		arg.Name,
		arg.Description,
		arg.Category,
		arg.DefaultAction,
		arg.MaxAttempts,
		arg.IsCustomerFault,
		arg.RequiresEvidence,
		arg.AutoRtoAfterMax,
		arg.DisplayOrder,
	)
	var i NdrReason
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrganizationID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.Category,
		&i.DefaultAction,
		&i.MaxAttempts,
		&i.IsCustomerFault,
		&i.RequiresEvidence,
		&i.AutoRtoAfterMax,
		&i.IsActive,
		&i.DisplayOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRTOCase = `-- name: CreateRTOCase :one

INSERT INTO rto_cases (
    public_id, organization_id, case_code, shipment_id, ndr_case_id, reason_code,
    reason_notes, initiated_by_user_id, return_branch_id, return_hub_id, origin_hub_id,
    route_resolution_source, route_legs, route_explanation,
    return_contact_name, return_phone, return_line1, return_line2,
    return_city, return_state, return_pincode,
    rto_charge_minor, currency, charge_bearer, charge_rule_notes, metadata
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22,$23,$24,$25,$26)
RETURNING id, public_id, organization_id, case_code, shipment_id, ndr_case_id, status, reason_code, reason_notes, initiated_at, initiated_by_user_id, return_branch_id, return_hub_id, origin_hub_id, route_resolution_source, route_legs, route_explanation, return_contact_name, return_phone, return_line1, return_line2, return_city, return_state, return_pincode, rto_charge_minor, currency, charge_bearer, charge_rule_notes, returned_at, returned_to_name, closed_at, metadata, created_at, updated_at, version
`

type CreateRTOCaseParams struct {
	PublicID              string
	OrganizationID        int64
	CaseCode              string
	ShipmentID            int64
	NdrCaseID             *int64
	ReasonCode            string
	ReasonNotes           *string
	InitiatedByUserID     *int64
	ReturnBranchID        *int64
	ReturnHubID           *int64
	OriginHubID           *int64
	RouteResolutionSource *string
	RouteLegs             []byte
	RouteExplanation      []byte
	ReturnContactName     *string
	ReturnPhone           *string
	ReturnLine1           *string
	ReturnLine2           *string
	ReturnCity            *string
	ReturnState           *string
	ReturnPincode         *string
	RtoChargeMinor        int64
	Currency              string
	ChargeBearer          string
	ChargeRuleNotes       *string
	Metadata              []byte
}

// ---------------------------------------------------------------------------
// RTO
// ---------------------------------------------------------------------------
func (q *Queries) CreateRTOCase(ctx context.Context, arg CreateRTOCaseParams) (RtoCase, error) {
	row := q.db.QueryRow(ctx, createRTOCase,
		arg.PublicID,
		arg.OrganizationID,
		arg.CaseCode,
		arg.ShipmentID,
		arg.NdrCaseID,
		arg.ReasonCode,
		arg.ReasonNotes,
		arg.InitiatedByUserID,
		arg.ReturnBranchID,
		arg.ReturnHubID,
		arg.OriginHubID,
		arg.RouteResolutionSource,
		arg.RouteLegs,
		arg.RouteExplanation,
		arg.ReturnContactName,
		arg.ReturnPhone,
		arg.ReturnLine1,
		arg.ReturnLine2,
		arg.ReturnCity,
		arg.ReturnState,
		arg.ReturnPincode,
		arg.RtoChargeMinor,
		arg.Currency,
		arg.ChargeBearer,
		arg.ChargeRuleNotes,
		arg.Metadata,
	)
	var i RtoCase
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrganizationID,
		&i.CaseCode,
		&i.ShipmentID,
		&i.NdrCaseID,
		&i.Status,
		&i.ReasonCode,
		&i.ReasonNotes,
		&i.InitiatedAt,
		&i.InitiatedByUserID,
		&i.ReturnBranchID,
		&i.ReturnHubID,
		&i.OriginHubID,
		&i.RouteResolutionSource,
		&i.RouteLegs,
		&i.RouteExplanation,
		&i.ReturnContactName,
		&i.ReturnPhone,
		&i.ReturnLine1,
		&i.ReturnLine2,
		&i.ReturnCity,
		&i.ReturnState,
		&i.ReturnPincode,
		&i.RtoChargeMinor,
		&i.Currency,
		&i.ChargeBearer,
		&i.ChargeRuleNotes,
		&i.ReturnedAt,
		&i.ReturnedToName,
		&i.ClosedAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const createRTOLeg = `-- name: CreateRTOLeg :one
INSERT INTO rto_legs (
    organization_id, rto_case_id, sequence, from_unit_id, to_unit_id, leg_type, status
) VALUES ($1,$2,$3,$4,$5,$6,$7)
RETURNING id, organization_id, rto_case_id, sequence, from_unit_id, to_unit_id, leg_type, status, trip_id, manifest_id, started_at, completed_at
`

type CreateRTOLegParams struct {
	OrganizationID int64
	RtoCaseID      int64
	Sequence       int32
	FromUnitID     *int64
	ToUnitID       *int64
	LegType        string
	Status         string
}

func (q *Queries) CreateRTOLeg(ctx context.Context, arg CreateRTOLegParams) (RtoLeg, error) {
	row := q.db.QueryRow(ctx, createRTOLeg,
		arg.OrganizationID,
		arg.RtoCaseID,
		arg.Sequence,
		arg.FromUnitID,
		arg.ToUnitID,
		arg.LegType,
		arg.Status,
	)
	var i RtoLeg
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.RtoCaseID,
		&i.Sequence,
		&i.FromUnitID,
		&i.ToUnitID,
		&i.LegType,
		&i.Status,
		&i.TripID,
		&i.ManifestID,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getActiveNDRCase = `-- name: GetActiveNDRCase :one
SELECT id, public_id, organization_id, case_code, shipment_id, status, ndr_reason_id, current_reason_code, attempt_count, max_attempts, branch_id, assigned_to_user_id, current_action, next_attempt_at, corrected_address_line1, corrected_address_line2, corrected_landmark, corrected_pincode, corrected_phone, corrected_at, corrected_by_user_id, opened_at, resolved_at, resolution_notes, metadata, created_at, updated_at, version FROM ndr_cases
WHERE shipment_id = $1
  AND status IN ('OPEN','PENDING_CUSTOMER','SCHEDULED','ESCALATED')
FOR UPDATE
`

func (q *Queries) GetActiveNDRCase(ctx context.Context, shipmentID int64) (NdrCase, error) {
	row := q.db.QueryRow(ctx, getActiveNDRCase, shipmentID)
	var i NdrCase
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrganizationID,
		&i.CaseCode,
		&i.ShipmentID,
		&i.Status,
		&i.NdrReasonID,
		&i.CurrentReasonCode,
		&i.AttemptCount,
		&i.MaxAttempts,
		&i.BranchID,
		&i.AssignedToUserID,
		&i.CurrentAction,
		&i.NextAttemptAt,
		&i.CorrectedAddressLine1,
		&i.CorrectedAddressLine2,
		&i.CorrectedLandmark,
		&i.CorrectedPincode,
		&i.CorrectedPhone,
		&i.CorrectedAt,
		&i.CorrectedByUserID,
		&i.OpenedAt,
		&i.ResolvedAt,
		&i.ResolutionNotes,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const getActiveRTOCase = `-- name: GetActiveRTOCase :one
SELECT id, public_id, organization_id, case_code, shipment_id, ndr_case_id, status, reason_code, reason_notes, initiated_at, initiated_by_user_id, return_branch_id, return_hub_id, origin_hub_id, route_resolution_source, route_legs, route_explanation, return_contact_name, return_phone, return_line1, return_line2, return_city, return_state, return_pincode, rto_charge_minor, currency, charge_bearer, charge_rule_notes, returned_at, returned_to_name, closed_at, metadata, created_at, updated_at, version FROM rto_cases
WHERE shipment_id = $1
  AND status NOT IN ('RETURNED','DISPOSED','CANCELLED')
FOR UPDATE
`

func (q *Queries) GetActiveRTOCase(ctx context.Context, shipmentID int64) (RtoCase, error) {
	row := q.db.QueryRow(ctx, getActiveRTOCase, shipmentID)
	var i RtoCase
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrganizationID,
		&i.CaseCode,
		&i.ShipmentID,
		&i.NdrCaseID,
		&i.Status,
		&i.ReasonCode,
		&i.ReasonNotes,
		&i.InitiatedAt,
		&i.InitiatedByUserID,
		&i.ReturnBranchID,
		&i.ReturnHubID,
		&i.OriginHubID,
		&i.RouteResolutionSource,
		&i.RouteLegs,
		&i.RouteExplanation,
		&i.ReturnContactName,
		&i.ReturnPhone,
		&i.ReturnLine1,
		&i.ReturnLine2,
		&i.ReturnCity,
		&i.ReturnState,
		&i.ReturnPincode,
		&i.RtoChargeMinor,
		&i.Currency,
		&i.ChargeBearer,
		&i.ChargeRuleNotes,
		&i.ReturnedAt,
		&i.ReturnedToName,
		&i.ClosedAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const getNDRCaseByPublicID = `-- name: GetNDRCaseByPublicID :one
SELECT n.id, n.public_id, n.organization_id, n.case_code, n.shipment_id, n.status, n.ndr_reason_id, n.current_reason_code, n.attempt_count, n.max_attempts, n.branch_id, n.assigned_to_user_id, n.current_action, n.next_attempt_at, n.corrected_address_line1, n.corrected_address_line2, n.corrected_landmark, n.corrected_pincode, n.corrected_phone, n.corrected_at, n.corrected_by_user_id, n.opened_at, n.resolved_at, n.resolution_notes, n.metadata, n.created_at, n.updated_at, n.version, s.public_id AS shipment_public_id, s.awb, s.current_status AS shipment_status,
       s.customer_id, s.destination_branch_id, s.promised_delivery_at,
       b.code AS branch_code, b.name AS branch_name,
       r.name AS reason_name, r.category AS reason_category, r.is_customer_fault,
       u.full_name AS assigned_to_name
FROM ndr_cases n
JOIN shipments s ON s.id = n.shipment_id
LEFT JOIN operating_units b ON b.id = n.branch_id
LEFT JOIN ndr_reasons r ON r.id = n.ndr_reason_id
LEFT JOIN users u ON u.id = n.assigned_to_user_id
WHERE n.public_id = $1 AND n.organization_id = $2
`

type GetNDRCaseByPublicIDParams struct {
	PublicID       string
	OrganizationID int64
}

type GetNDRCaseByPublicIDRow struct {
	ID                    int64
	PublicID              string
	OrganizationID        int64
	CaseCode              string
	ShipmentID            int64
	Status                string
	NdrReasonID           *int64
	CurrentReasonCode     string
	AttemptCount          int32
	MaxAttempts           int32
	BranchID              *int64
	AssignedToUserID      *int64
	CurrentAction         *string
	NextAttemptAt         *time.Time
	CorrectedAddressLine1 *string
	CorrectedAddressLine2 *string
	CorrectedLandmark     *string
	CorrectedPincode      *string
	CorrectedPhone        *string
	CorrectedAt           *time.Time
	CorrectedByUserID     *int64
	OpenedAt              time.Time
	ResolvedAt            *time.Time
	ResolutionNotes       *string
	Metadata              []byte
	CreatedAt             time.Time
	UpdatedAt             time.Time
	Version               int32
	ShipmentPublicID      string
	Awb                   string
	ShipmentStatus        string
	CustomerID            int64
	DestinationBranchID   *int64
	PromisedDeliveryAt    *time.Time
	BranchCode            *string
	BranchName            *string
	ReasonName            *string
	ReasonCategory        *string
	IsCustomerFault       *bool
	AssignedToName        *string
}

func (q *Queries) GetNDRCaseByPublicID(ctx context.Context, arg GetNDRCaseByPublicIDParams) (GetNDRCaseByPublicIDRow, error) {
	row := q.db.QueryRow(ctx, getNDRCaseByPublicID, arg.PublicID, arg.OrganizationID)
	var i GetNDRCaseByPublicIDRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrganizationID,
		&i.CaseCode,
		&i.ShipmentID,
		&i.Status,
		&i.NdrReasonID,
		&i.CurrentReasonCode,
		&i.AttemptCount,
		&i.MaxAttempts,
		&i.BranchID,
		&i.AssignedToUserID,
		&i.CurrentAction,
		&i.NextAttemptAt,
		&i.CorrectedAddressLine1,
		&i.CorrectedAddressLine2,
		&i.CorrectedLandmark,
		&i.CorrectedPincode,
		&i.CorrectedPhone,
		&i.CorrectedAt,
		&i.CorrectedByUserID,
		&i.OpenedAt,
		&i.ResolvedAt,
		&i.ResolutionNotes,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
		&i.ShipmentPublicID,
		&i.Awb,
		&i.ShipmentStatus,
		&i.CustomerID,
		&i.DestinationBranchID,
		&i.PromisedDeliveryAt,
		&i.BranchCode,
		&i.BranchName,
		&i.ReasonName,
		&i.ReasonCategory,
		&i.IsCustomerFault,
		&i.AssignedToName,
	)
	return i, err
}

const getNDRReasonByCode = `-- name: GetNDRReasonByCode :one
SELECT id, public_id, organization_id, code, name, description, category, default_action, max_attempts, is_customer_fault, requires_evidence, auto_rto_after_max, is_active, display_order, created_at, updated_at FROM ndr_reasons
WHERE organization_id = $1 AND code = $2
`

type GetNDRReasonByCodeParams struct {
	OrganizationID int64
	Code           string
}

func (q *Queries) GetNDRReasonByCode(ctx context.Context, arg GetNDRReasonByCodeParams) (NdrReason, error) {
	row := q.db.QueryRow(ctx, getNDRReasonByCode, arg.OrganizationID, arg.Code)
	var i NdrReason
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrganizationID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.Category,
		&i.DefaultAction,
		&i.MaxAttempts,
		&i.IsCustomerFault,
		&i.RequiresEvidence,
		&i.AutoRtoAfterMax,
		&i.IsActive,
		&i.DisplayOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRTOCaseByPublicID = `-- name: GetRTOCaseByPublicID :one
SELECT r.id, r.public_id, r.organization_id, r.case_code, r.shipment_id, r.ndr_case_id, r.status, r.reason_code, r.reason_notes, r.initiated_at, r.initiated_by_user_id, r.return_branch_id, r.return_hub_id, r.origin_hub_id, r.route_resolution_source, r.route_legs, r.route_explanation, r.return_contact_name, r.return_phone, r.return_line1, r.return_line2, r.return_city, r.return_state, r.return_pincode, r.rto_charge_minor, r.currency, r.charge_bearer, r.charge_rule_notes, r.returned_at, r.returned_to_name, r.closed_at, r.metadata, r.created_at, r.updated_at, r.version, s.public_id AS shipment_public_id, s.awb, s.current_status AS shipment_status,
       s.customer_id, s.movement_direction,
       rb.code AS return_branch_code, rb.name AS return_branch_name,
       u.full_name AS initiated_by_name
FROM rto_cases r
JOIN shipments s ON s.id = r.shipment_id
LEFT JOIN operating_units rb ON rb.id = r.return_branch_id
LEFT JOIN users u ON u.id = r.initiated_by_user_id
WHERE r.public_id = $1 AND r.organization_id = $2
`

type GetRTOCaseByPublicIDParams struct {
	PublicID       string
	OrganizationID int64
}

type GetRTOCaseByPublicIDRow struct {
	ID                    int64
	PublicID              string
	OrganizationID        int64
	CaseCode              string
	ShipmentID            int64
	NdrCaseID             *int64
	Status                string
	ReasonCode            string
	ReasonNotes           *string
	InitiatedAt           time.Time
	InitiatedByUserID     *int64
	ReturnBranchID        *int64
	ReturnHubID           *int64
	OriginHubID           *int64
	RouteResolutionSource *string
	RouteLegs             []byte
	RouteExplanation      []byte
	ReturnContactName     *string
	ReturnPhone           *string
	ReturnLine1           *string
	ReturnLine2           *string
	ReturnCity            *string
	ReturnState           *string
	ReturnPincode         *string
	RtoChargeMinor        int64
	Currency              string
	ChargeBearer          string
	ChargeRuleNotes       *string
	ReturnedAt            *time.Time
	ReturnedToName        *string
	ClosedAt              *time.Time
	Metadata              []byte
	CreatedAt             time.Time
	UpdatedAt             time.Time
	Version               int32
	ShipmentPublicID      string
	Awb                   string
	ShipmentStatus        string
	CustomerID            int64
	MovementDirection     string
	ReturnBranchCode      *string
	ReturnBranchName      *string
	InitiatedByName       *string
}

func (q *Queries) GetRTOCaseByPublicID(ctx context.Context, arg GetRTOCaseByPublicIDParams) (GetRTOCaseByPublicIDRow, error) {
	row := q.db.QueryRow(ctx, getRTOCaseByPublicID, arg.PublicID, arg.OrganizationID)
	var i GetRTOCaseByPublicIDRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrganizationID,
		&i.CaseCode,
		&i.ShipmentID,
		&i.NdrCaseID,
		&i.Status,
		&i.ReasonCode,
		&i.ReasonNotes,
		&i.InitiatedAt,
		&i.InitiatedByUserID,
		&i.ReturnBranchID,
		&i.ReturnHubID,
		&i.OriginHubID,
		&i.RouteResolutionSource,
		&i.RouteLegs,
		&i.RouteExplanation,
		&i.ReturnContactName,
		&i.ReturnPhone,
		&i.ReturnLine1,
		&i.ReturnLine2,
		&i.ReturnCity,
		&i.ReturnState,
		&i.ReturnPincode,
		&i.RtoChargeMinor,
		&i.Currency,
		&i.ChargeBearer,
		&i.ChargeRuleNotes,
		&i.ReturnedAt,
		&i.ReturnedToName,
		&i.ClosedAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
		&i.ShipmentPublicID,
		&i.Awb,
		&i.ShipmentStatus,
		&i.CustomerID,
		&i.MovementDirection,
		&i.ReturnBranchCode,
		&i.ReturnBranchName,
		&i.InitiatedByName,
	)
	return i, err
}

const listDueNDRCases = `-- name: ListDueNDRCases :many
SELECT n.id, n.public_id, n.case_code, n.shipment_id, n.current_action, n.next_attempt_at,
       n.attempt_count, n.max_attempts, s.awb, s.current_status
FROM ndr_cases n
JOIN shipments s ON s.id = n.shipment_id
WHERE n.organization_id = $1
  AND n.status IN ('OPEN','SCHEDULED')
  AND n.next_attempt_at IS NOT NULL
  AND n.next_attempt_at <= now()
ORDER BY n.next_attempt_at
LIMIT $2
`

type ListDueNDRCasesParams struct {
	OrganizationID int64
	PageSize       int32
}

type ListDueNDRCasesRow struct {
	ID            int64
	PublicID      string
	CaseCode      string
	ShipmentID    int64
	CurrentAction *string
	NextAttemptAt *time.Time
	AttemptCount  int32
	MaxAttempts   int32
	Awb           string
	CurrentStatus string
}

// Worker sweep: cases whose scheduled reattempt time has arrived.
func (q *Queries) ListDueNDRCases(ctx context.Context, arg ListDueNDRCasesParams) ([]ListDueNDRCasesRow, error) {
	rows, err := q.db.Query(ctx, listDueNDRCases, arg.OrganizationID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDueNDRCasesRow{}
	for rows.Next() {
		var i ListDueNDRCasesRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.CaseCode,
			&i.ShipmentID,
			&i.CurrentAction,
			&i.NextAttemptAt,
			&i.AttemptCount,
			&i.MaxAttempts,
			&i.Awb,
			&i.CurrentStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNDRActions = `-- name: ListNDRActions :many
SELECT na.id, na.public_id, na.organization_id, na.ndr_case_id, na.sequence, na.action, na.requested_by, na.instructions, na.scheduled_for, na.contact_name, na.contact_phone, na.contact_notes, na.status, na.applied_at, na.created_at, na.created_by_user_id, na.metadata, u.full_name AS created_by_name
FROM ndr_actions na
LEFT JOIN users u ON u.id = na.created_by_user_id
WHERE na.ndr_case_id = $1
ORDER BY na.sequence DESC
`

type ListNDRActionsRow struct {
	ID              int64
	PublicID        string
	OrganizationID  int64
	NdrCaseID       int64
	Sequence        int32
	Action          string
	RequestedBy     string
	Instructions    *string
	ScheduledFor    *time.Time
	ContactName     *string
	ContactPhone    *string
	ContactNotes    *string
	Status          string
	AppliedAt       *time.Time
	CreatedAt       time.Time
	CreatedByUserID *int64
	Metadata        []byte
	CreatedByName   *string
}

func (q *Queries) ListNDRActions(ctx context.Context, ndrCaseID int64) ([]ListNDRActionsRow, error) {
	rows, err := q.db.Query(ctx, listNDRActions, ndrCaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNDRActionsRow{}
	for rows.Next() {
		var i ListNDRActionsRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.OrganizationID,
			&i.NdrCaseID,
			&i.Sequence,
			&i.Action,
			&i.RequestedBy,
			&i.Instructions,
			&i.ScheduledFor,
			&i.ContactName,
			&i.ContactPhone,
			&i.ContactNotes,
			&i.Status,
			&i.AppliedAt,
			&i.CreatedAt,
			&i.CreatedByUserID,
			&i.Metadata,
			&i.CreatedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNDRAttempts = `-- name: ListNDRAttempts :many
SELECT na.id, na.public_id, na.organization_id, na.ndr_case_id, na.delivery_attempt_id, na.attempt_number, na.reason_code, na.remarks, na.evidence_object_keys, na.occurred_at, na.recorded_at, na.recorded_by_user_id, na.metadata, u.full_name AS recorded_by_name
FROM ndr_attempts na
LEFT JOIN users u ON u.id = na.recorded_by_user_id
WHERE na.ndr_case_id = $1
ORDER BY na.attempt_number DESC
`

type ListNDRAttemptsRow struct {
	ID                 int64
	PublicID           string
	OrganizationID     int64
	NdrCaseID          int64
	DeliveryAttemptID  *int64
	AttemptNumber      int32
	ReasonCode         string
	Remarks            *string
	EvidenceObjectKeys []string
	OccurredAt         time.Time
	RecordedAt         time.Time
	RecordedByUserID   *int64
	Metadata           []byte
	RecordedByName     *string
}

func (q *Queries) ListNDRAttempts(ctx context.Context, ndrCaseID int64) ([]ListNDRAttemptsRow, error) {
	rows, err := q.db.Query(ctx, listNDRAttempts, ndrCaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNDRAttemptsRow{}
	for rows.Next() {
		var i ListNDRAttemptsRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.OrganizationID,
			&i.NdrCaseID,
			&i.DeliveryAttemptID,
			&i.AttemptNumber,
			&i.ReasonCode,
			&i.Remarks,
			&i.EvidenceObjectKeys,
			&i.OccurredAt,
			&i.RecordedAt,
			&i.RecordedByUserID,
			&i.Metadata,
			&i.RecordedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNDRCases = `-- name: ListNDRCases :many
SELECT n.id, n.public_id, n.case_code, n.status, n.current_reason_code, n.current_action,
       n.attempt_count, n.max_attempts, n.next_attempt_at, n.opened_at, n.resolved_at,
       n.created_at,
       s.public_id AS shipment_public_id, s.awb, s.current_status AS shipment_status,
       s.promised_delivery_at, s.cod_amount_minor, s.payment_mode,
       b.code AS branch_code, b.name AS branch_name,
       c.name AS customer_name, c.code AS customer_code,
       r.name AS reason_name, r.category AS reason_category,
       sa.contact_name AS recipient_name, sa.phone AS recipient_phone, sa.pincode
FROM ndr_cases n
JOIN shipments s ON s.id = n.shipment_id
JOIN customers c ON c.id = s.customer_id
LEFT JOIN operating_units b ON b.id = n.branch_id
LEFT JOIN ndr_reasons r ON r.id = n.ndr_reason_id
LEFT JOIN shipment_address_snapshots sa ON sa.shipment_id = s.id AND sa.role = 'RECIPIENT'
WHERE n.organization_id = $1
  AND ($2::text IS NULL OR n.status = $2)
  AND ($3::text IS NULL OR n.current_reason_code = $3)
  AND ($4::text IS NULL OR n.current_action = $4)
  AND ($5::bigint IS NULL OR n.branch_id = $5)
  AND ($6::bigint[] IS NULL OR n.branch_id = ANY($6))
  AND ($7::bigint[] IS NULL OR s.customer_id = ANY($7))
  AND ($8::timestamptz IS NULL
       OR (n.created_at, n.id) < ($8::timestamptz, $9::bigint))
ORDER BY n.created_at DESC, n.id DESC
LIMIT $10
`

type ListNDRCasesParams struct {
	OrganizationID  int64
	Status          *string
	ReasonCode      *string
	Action          *string
	BranchID        *int64
	UnitIds         []int64
	CustomerIds     []int64
	CursorCreatedAt *time.Time
	CursorID        *int64
	PageSize        int32
}

type ListNDRCasesRow struct {
	ID                 int64
	PublicID           string
	CaseCode           string
	Status             string
	CurrentReasonCode  string
	CurrentAction      *string
	AttemptCount       int32
	MaxAttempts        int32
	NextAttemptAt      *time.Time
	OpenedAt           time.Time
	ResolvedAt         *time.Time
	CreatedAt          time.Time
	ShipmentPublicID   string
	Awb                string
	ShipmentStatus     string
	PromisedDeliveryAt *time.Time
	CodAmountMinor     int64
	PaymentMode        string
	BranchCode         *string
	BranchName         *string
	CustomerName       string
	CustomerCode       string
	ReasonName         *string
	ReasonCategory     *string
	RecipientName      *string
	RecipientPhone     *string
	Pincode            *string
}

func (q *Queries) ListNDRCases(ctx context.Context, arg ListNDRCasesParams) ([]ListNDRCasesRow, error) {
	rows, err := q.db.Query(ctx, listNDRCases,
		arg.OrganizationID,
		arg.Status,
		arg.ReasonCode,
		arg.Action,
		arg.BranchID,
		arg.UnitIds,
		arg.CustomerIds,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNDRCasesRow{}
	for rows.Next() {
		var i ListNDRCasesRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.CaseCode,
			&i.Status,
			&i.CurrentReasonCode,
			&i.CurrentAction,
			&i.AttemptCount,
			&i.MaxAttempts,
			&i.NextAttemptAt,
			&i.OpenedAt,
			&i.ResolvedAt,
			&i.CreatedAt,
			&i.ShipmentPublicID,
			&i.Awb,
			&i.ShipmentStatus,
			&i.PromisedDeliveryAt,
			&i.CodAmountMinor,
			&i.PaymentMode,
			&i.BranchCode,
			&i.BranchName,
			&i.CustomerName,
			&i.CustomerCode,
			&i.ReasonName,
			&i.ReasonCategory,
			&i.RecipientName,
			&i.RecipientPhone,
			&i.Pincode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNDRReasons = `-- name: ListNDRReasons :many
SELECT id, public_id, organization_id, code, name, description, category, default_action, max_attempts, is_customer_fault, requires_evidence, auto_rto_after_max, is_active, display_order, created_at, updated_at FROM ndr_reasons
WHERE organization_id = $1
  AND ($2::boolean IS NULL OR is_active = $2)
ORDER BY display_order, code
`

type ListNDRReasonsParams struct {
	OrganizationID int64
	IsActive       *bool
}

func (q *Queries) ListNDRReasons(ctx context.Context, arg ListNDRReasonsParams) ([]NdrReason, error) {
	rows, err := q.db.Query(ctx, listNDRReasons, arg.OrganizationID, arg.IsActive)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NdrReason{}
	for rows.Next() {
		var i NdrReason
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.OrganizationID,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.Category,
			&i.DefaultAction,
			&i.MaxAttempts,
			&i.IsCustomerFault,
			&i.RequiresEvidence,
			&i.AutoRtoAfterMax,
			&i.IsActive,
			&i.DisplayOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRTOCases = `-- name: ListRTOCases :many
SELECT r.id, r.public_id, r.case_code, r.status, r.reason_code, r.initiated_at, r.returned_at,
       r.rto_charge_minor, r.currency, r.charge_bearer, r.created_at,
       s.public_id AS shipment_public_id, s.awb, s.current_status AS shipment_status,
       rb.code AS return_branch_code, rb.name AS return_branch_name,
       c.name AS customer_name, c.code AS customer_code
FROM rto_cases r
JOIN shipments s ON s.id = r.shipment_id
JOIN customers c ON c.id = s.customer_id
LEFT JOIN operating_units rb ON rb.id = r.return_branch_id
WHERE r.organization_id = $1
  AND ($2::text IS NULL OR r.status = $2)
  AND ($3::bigint IS NULL OR r.return_branch_id = $3)
  AND ($4::bigint[] IS NULL OR r.return_branch_id = ANY($4))
  AND ($5::bigint[] IS NULL OR s.customer_id = ANY($5))
  AND ($6::timestamptz IS NULL
       OR (r.created_at, r.id) < ($6::timestamptz, $7::bigint))
ORDER BY r.created_at DESC, r.id DESC
LIMIT $8
`

type ListRTOCasesParams struct {
	OrganizationID  int64
	Status          *string
	ReturnBranchID  *int64
	UnitIds         []int64
	CustomerIds     []int64
	CursorCreatedAt *time.Time
	CursorID        *int64
	PageSize        int32
}

type ListRTOCasesRow struct {
	ID               int64
	PublicID         string
	CaseCode         string
	Status           string
	ReasonCode       string
	InitiatedAt      time.Time
	ReturnedAt       *time.Time
	RtoChargeMinor   int64
	Currency         string
	ChargeBearer     string
	CreatedAt        time.Time
	ShipmentPublicID string
	Awb              string
	ShipmentStatus   string
	ReturnBranchCode *string
	ReturnBranchName *string
	CustomerName     string
	CustomerCode     string
}

func (q *Queries) ListRTOCases(ctx context.Context, arg ListRTOCasesParams) ([]ListRTOCasesRow, error) {
	rows, err := q.db.Query(ctx, listRTOCases,
		arg.OrganizationID,
		arg.Status,
		arg.ReturnBranchID,
		arg.UnitIds,
		arg.CustomerIds,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRTOCasesRow{}
	for rows.Next() {
		var i ListRTOCasesRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.CaseCode,
			&i.Status,
			&i.ReasonCode,
			&i.InitiatedAt,
			&i.ReturnedAt,
			&i.RtoChargeMinor,
			&i.Currency,
			&i.ChargeBearer,
			&i.CreatedAt,
			&i.ShipmentPublicID,
			&i.Awb,
			&i.ShipmentStatus,
			&i.ReturnBranchCode,
			&i.ReturnBranchName,
			&i.CustomerName,
			&i.CustomerCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRTOLegs = `-- name: ListRTOLegs :many
SELECT rl.id, rl.organization_id, rl.rto_case_id, rl.sequence, rl.from_unit_id, rl.to_unit_id, rl.leg_type, rl.status, rl.trip_id, rl.manifest_id, rl.started_at, rl.completed_at, f.code AS from_code, f.name AS from_name,
       t.code AS to_code, t.name AS to_name
FROM rto_legs rl
LEFT JOIN operating_units f ON f.id = rl.from_unit_id
LEFT JOIN operating_units t ON t.id = rl.to_unit_id
WHERE rl.rto_case_id = $1
ORDER BY rl.sequence
`

type ListRTOLegsRow struct {
	ID             int64
	OrganizationID int64
	RtoCaseID      int64
	Sequence       int32
	FromUnitID     *int64
	ToUnitID       *int64
	LegType        string
	Status         string
	TripID         *int64
	ManifestID     *int64
	StartedAt      *time.Time
	CompletedAt    *time.Time
	FromCode       *string
	FromName       *string
	ToCode         *string
	ToName         *string
}

func (q *Queries) ListRTOLegs(ctx context.Context, rtoCaseID int64) ([]ListRTOLegsRow, error) {
	rows, err := q.db.Query(ctx, listRTOLegs, rtoCaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRTOLegsRow{}
	for rows.Next() {
		var i ListRTOLegsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.RtoCaseID,
			&i.Sequence,
			&i.FromUnitID,
			&i.ToUnitID,
			&i.LegType,
			&i.Status,
			&i.TripID,
			&i.ManifestID,
			&i.StartedAt,
			&i.CompletedAt,
			&i.FromCode,
			&i.FromName,
			&i.ToCode,
			&i.ToName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockNDRCaseForUpdate = `-- name: LockNDRCaseForUpdate :one
SELECT id, public_id, organization_id, case_code, shipment_id, status, ndr_reason_id, current_reason_code, attempt_count, max_attempts, branch_id, assigned_to_user_id, current_action, next_attempt_at, corrected_address_line1, corrected_address_line2, corrected_landmark, corrected_pincode, corrected_phone, corrected_at, corrected_by_user_id, opened_at, resolved_at, resolution_notes, metadata, created_at, updated_at, version FROM ndr_cases
WHERE public_id = $1 AND organization_id = $2
FOR UPDATE
`

type LockNDRCaseForUpdateParams struct {
	PublicID       string
	OrganizationID int64
}

func (q *Queries) LockNDRCaseForUpdate(ctx context.Context, arg LockNDRCaseForUpdateParams) (NdrCase, error) {
	row := q.db.QueryRow(ctx, lockNDRCaseForUpdate, arg.PublicID, arg.OrganizationID)
	var i NdrCase
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrganizationID,
		&i.CaseCode,
		&i.ShipmentID,
		&i.Status,
		&i.NdrReasonID,
		&i.CurrentReasonCode,
		&i.AttemptCount,
		&i.MaxAttempts,
		&i.BranchID,
		&i.AssignedToUserID,
		&i.CurrentAction,
		&i.NextAttemptAt,
		&i.CorrectedAddressLine1,
		&i.CorrectedAddressLine2,
		&i.CorrectedLandmark,
		&i.CorrectedPincode,
		&i.CorrectedPhone,
		&i.CorrectedAt,
		&i.CorrectedByUserID,
		&i.OpenedAt,
		&i.ResolvedAt,
		&i.ResolutionNotes,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const lockRTOCaseForUpdate = `-- name: LockRTOCaseForUpdate :one
SELECT id, public_id, organization_id, case_code, shipment_id, ndr_case_id, status, reason_code, reason_notes, initiated_at, initiated_by_user_id, return_branch_id, return_hub_id, origin_hub_id, route_resolution_source, route_legs, route_explanation, return_contact_name, return_phone, return_line1, return_line2, return_city, return_state, return_pincode, rto_charge_minor, currency, charge_bearer, charge_rule_notes, returned_at, returned_to_name, closed_at, metadata, created_at, updated_at, version FROM rto_cases
WHERE public_id = $1 AND organization_id = $2
FOR UPDATE
`

type LockRTOCaseForUpdateParams struct {
	PublicID       string
	OrganizationID int64
}

func (q *Queries) LockRTOCaseForUpdate(ctx context.Context, arg LockRTOCaseForUpdateParams) (RtoCase, error) {
	row := q.db.QueryRow(ctx, lockRTOCaseForUpdate, arg.PublicID, arg.OrganizationID)
	var i RtoCase
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrganizationID,
		&i.CaseCode,
		&i.ShipmentID,
		&i.NdrCaseID,
		&i.Status,
		&i.ReasonCode,
		&i.ReasonNotes,
		&i.InitiatedAt,
		&i.InitiatedByUserID,
		&i.ReturnBranchID,
		&i.ReturnHubID,
		&i.OriginHubID,
		&i.RouteResolutionSource,
		&i.RouteLegs,
		&i.RouteExplanation,
		&i.ReturnContactName,
		&i.ReturnPhone,
		&i.ReturnLine1,
		&i.ReturnLine2,
		&i.ReturnCity,
		&i.ReturnState,
		&i.ReturnPincode,
		&i.RtoChargeMinor,
		&i.Currency,
		&i.ChargeBearer,
		&i.ChargeRuleNotes,
		&i.ReturnedAt,
		&i.ReturnedToName,
		&i.ClosedAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const markNDRActionApplied = `-- name: MarkNDRActionApplied :one
UPDATE ndr_actions SET status = 'APPLIED', applied_at = now()
WHERE id = $1
RETURNING id, public_id, organization_id, ndr_case_id, sequence, action, requested_by, instructions, scheduled_for, contact_name, contact_phone, contact_notes, status, applied_at, created_at, created_by_user_id, metadata
`

func (q *Queries) MarkNDRActionApplied(ctx context.Context, id int64) (NdrAction, error) {
	row := q.db.QueryRow(ctx, markNDRActionApplied, id)
	var i NdrAction
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrganizationID,
		&i.NdrCaseID,
		&i.Sequence,
		&i.Action,
		&i.RequestedBy,
		&i.Instructions,
		&i.ScheduledFor,
		&i.ContactName,
		&i.ContactPhone,
		&i.ContactNotes,
		&i.Status,
		&i.AppliedAt,
		&i.CreatedAt,
		&i.CreatedByUserID,
		&i.Metadata,
	)
	return i, err
}

const markRTOLegForUnit = `-- name: MarkRTOLegForUnit :one
UPDATE rto_legs
SET status = 'COMPLETED', completed_at = now()
WHERE rto_case_id = $1
  AND to_unit_id = $2
  AND status IN ('PENDING','IN_PROGRESS')
RETURNING id, organization_id, rto_case_id, sequence, from_unit_id, to_unit_id, leg_type, status, trip_id, manifest_id, started_at, completed_at
`

type MarkRTOLegForUnitParams struct {
	RtoCaseID int64
	UnitID    *int64
}

// Advance the reverse journey when the parcel is received at a facility on the
// planned path: complete the leg that ends here and start the next one.
func (q *Queries) MarkRTOLegForUnit(ctx context.Context, arg MarkRTOLegForUnitParams) (RtoLeg, error) {
	row := q.db.QueryRow(ctx, markRTOLegForUnit, arg.RtoCaseID, arg.UnitID)
	var i RtoLeg
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.RtoCaseID,
		&i.Sequence,
		&i.FromUnitID,
		&i.ToUnitID,
		&i.LegType,
		&i.Status,
		&i.TripID,
		&i.ManifestID,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const nextNDRActionSequence = `-- name: NextNDRActionSequence :one
SELECT COALESCE(max(sequence), 0)::int + 1 AS next_sequence FROM ndr_actions
WHERE ndr_case_id = $1
`

func (q *Queries) NextNDRActionSequence(ctx context.Context, ndrCaseID int64) (int32, error) {
	row := q.db.QueryRow(ctx, nextNDRActionSequence, ndrCaseID)
	var next_sequence int32
	err := row.Scan(&next_sequence)
	return next_sequence, err
}

const seedDefaultNDRReasons = `-- name: SeedDefaultNDRReasons :exec
INSERT INTO ndr_reasons (public_id, organization_id, code, name, description, category,
                         default_action, max_attempts, is_customer_fault, requires_evidence,
                         auto_rto_after_max, display_order)
SELECT gen_seed_public_id('ndrs'), $1, d.code, d.name, d.description,
       d.category, d.default_action, d.max_attempts, d.is_customer_fault, d.requires_evidence,
       d.auto_rto_after_max, d.display_order
FROM (VALUES
    ('CUSTOMER_NOT_AVAILABLE','Customer not available','Nobody was present at the delivery address.','CUSTOMER_UNAVAILABLE','REATTEMPT',3,true,false,true,10),
    ('PREMISES_CLOSED','Premises closed','The business or residence was closed at the time of the attempt.','ACCESS','RESCHEDULE',3,false,false,true,20),
    ('ADDRESS_INCOMPLETE','Address incomplete','The address is missing details needed to locate it.','ADDRESS_PROBLEM','ADDRESS_CORRECTION',2,true,false,true,30),
    ('ADDRESS_NOT_FOUND','Address not found','The address could not be located.','ADDRESS_PROBLEM','ADDRESS_CORRECTION',2,true,true,true,40),
    ('CUSTOMER_REFUSED','Customer refused delivery','The consignee declined to accept the shipment.','REFUSED','RTO',1,true,true,true,50),
    ('COD_NOT_READY','COD amount not ready','The consignee could not pay the COD amount.','PAYMENT','REATTEMPT',2,true,false,true,60),
    ('CUSTOMER_RESCHEDULED','Customer asked to reschedule','The consignee requested delivery on another day.','CUSTOMER_UNAVAILABLE','RESCHEDULE',3,true,false,false,70),
    ('PHONE_UNREACHABLE','Consignee unreachable','The consignee could not be contacted by phone.','CUSTOMER_UNAVAILABLE','CONTACT_REQUIRED',3,true,false,true,80),
    ('RESTRICTED_ACCESS','Restricted access','The agent could not enter the premises or area.','ACCESS','CONTACT_REQUIRED',3,false,false,true,90),
    ('WEATHER_DISRUPTION','Weather disruption','Delivery could not be attempted because of weather.','WEATHER','REATTEMPT',5,false,false,false,100),
    ('VEHICLE_BREAKDOWN','Operational delay','The delivery could not be completed for operational reasons.','OPERATIONAL','REATTEMPT',5,false,false,false,110),
    ('SHIPMENT_DAMAGED','Shipment damaged','The shipment was found damaged before delivery.','DAMAGE','ESCALATE',1,false,true,false,120)
) AS d(code, name, description, category, default_action, max_attempts, is_customer_fault,
       requires_evidence, auto_rto_after_max, display_order)
ON CONFLICT DO NOTHING
`

// Give a newly created organization a working NDR catalogue.
//
// Without this a tenant's first failed delivery would be refused for an unknown
// reason code, which is a bad first day. The list matches the defaults migration
// 0019 applied to organizations that already existed; keeping both in SQL means
// there is one definition of "a sensible starting catalogue".
func (q *Queries) SeedDefaultNDRReasons(ctx context.Context, organizationID int64) error {
	_, err := q.db.Exec(ctx, seedDefaultNDRReasons, organizationID)
	return err
}

const supersedePendingNDRActions = `-- name: SupersedePendingNDRActions :execrows
UPDATE ndr_actions SET status = 'SUPERSEDED'
WHERE ndr_case_id = $1 AND status = 'PENDING'
`

func (q *Queries) SupersedePendingNDRActions(ctx context.Context, ndrCaseID int64) (int64, error) {
	result, err := q.db.Exec(ctx, supersedePendingNDRActions, ndrCaseID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateNDRCase = `-- name: UpdateNDRCase :one
UPDATE ndr_cases
SET status = $1,
    current_reason_code = COALESCE($2, current_reason_code),
    ndr_reason_id = COALESCE($3, ndr_reason_id),
    current_action = COALESCE($4, current_action),
    next_attempt_at = CASE WHEN $5::boolean THEN NULL
                           ELSE COALESCE($6, next_attempt_at) END,
    attempt_count = attempt_count + $7::int,
    assigned_to_user_id = COALESCE($8, assigned_to_user_id),
    resolved_at = CASE WHEN $1::text IN
                       ('RESOLVED_DELIVERED','RESOLVED_RTO','RESOLVED_CANCELLED','CLOSED')
                       THEN now() ELSE resolved_at END,
    resolution_notes = COALESCE($9, resolution_notes)
WHERE id = $10 AND organization_id = $11
  AND status = $12
RETURNING id, public_id, organization_id, case_code, shipment_id, status, ndr_reason_id, current_reason_code, attempt_count, max_attempts, branch_id, assigned_to_user_id, current_action, next_attempt_at, corrected_address_line1, corrected_address_line2, corrected_landmark, corrected_pincode, corrected_phone, corrected_at, corrected_by_user_id, opened_at, resolved_at, resolution_notes, metadata, created_at, updated_at, version
`

type UpdateNDRCaseParams struct {
	ToStatus          string
	CurrentReasonCode *string
	NdrReasonID       *int64
	CurrentAction     *string
	ClearNextAttempt  bool
	NextAttemptAt     *time.Time
	AttemptIncrement  int32
	AssignedToUserID  *int64
	ResolutionNotes   *string
	ID                int64
	OrganizationID    int64
	ExpectedStatus    string
}

func (q *Queries) UpdateNDRCase(ctx context.Context, arg UpdateNDRCaseParams) (NdrCase, error) {
	row := q.db.QueryRow(ctx, updateNDRCase,
		arg.ToStatus,
		arg.CurrentReasonCode,
		arg.NdrReasonID,
		arg.CurrentAction,
		arg.ClearNextAttempt,
		arg.NextAttemptAt,
		arg.AttemptIncrement,
		arg.AssignedToUserID,
		arg.ResolutionNotes,
		arg.ID,
		arg.OrganizationID,
		arg.ExpectedStatus,
	)
	var i NdrCase
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrganizationID,
		&i.CaseCode,
		&i.ShipmentID,
		&i.Status,
		&i.NdrReasonID,
		&i.CurrentReasonCode,
		&i.AttemptCount,
		&i.MaxAttempts,
		&i.BranchID,
		&i.AssignedToUserID,
		&i.CurrentAction,
		&i.NextAttemptAt,
		&i.CorrectedAddressLine1,
		&i.CorrectedAddressLine2,
		&i.CorrectedLandmark,
		&i.CorrectedPincode,
		&i.CorrectedPhone,
		&i.CorrectedAt,
		&i.CorrectedByUserID,
		&i.OpenedAt,
		&i.ResolvedAt,
		&i.ResolutionNotes,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const updateNDRReason = `-- name: UpdateNDRReason :one
UPDATE ndr_reasons
SET name = COALESCE($1, name),
    description = COALESCE($2, description),
    category = COALESCE($3, category),
    default_action = COALESCE($4, default_action),
    max_attempts = COALESCE($5, max_attempts),
    is_customer_fault = COALESCE($6, is_customer_fault),
    requires_evidence = COALESCE($7, requires_evidence),
    auto_rto_after_max = COALESCE($8, auto_rto_after_max),
    display_order = COALESCE($9, display_order),
    is_active = COALESCE($10, is_active)
WHERE public_id = $11 AND organization_id = $12
RETURNING id, public_id, organization_id, code, name, description, category, default_action, max_attempts, is_customer_fault, requires_evidence, auto_rto_after_max, is_active, display_order, created_at, updated_at
`

type UpdateNDRReasonParams struct {
	Name             *string
	Description      *string
	Category         *string
	DefaultAction    *string
	MaxAttempts      *int32
	IsCustomerFault  *bool
	RequiresEvidence *bool
	AutoRtoAfterMax  *bool
	DisplayOrder     *int32
	IsActive         *bool
	PublicID         string
	OrganizationID   int64
}

func (q *Queries) UpdateNDRReason(ctx context.Context, arg UpdateNDRReasonParams) (NdrReason, error) {
	row := q.db.QueryRow(ctx, updateNDRReason,
		arg.Name,
		arg.Description,
		arg.Category,
		arg.DefaultAction,
		arg.MaxAttempts,
		arg.IsCustomerFault,
		arg.RequiresEvidence,
		arg.AutoRtoAfterMax,
		arg.DisplayOrder,
		arg.IsActive,
		arg.PublicID,
		arg.OrganizationID,
	)
	var i NdrReason
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrganizationID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.Category,
		&i.DefaultAction,
		&i.MaxAttempts,
		&i.IsCustomerFault,
		&i.RequiresEvidence,
		&i.AutoRtoAfterMax,
		&i.IsActive,
		&i.DisplayOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateRTOCaseStatus = `-- name: UpdateRTOCaseStatus :one
UPDATE rto_cases
SET status = $1,
    returned_at = CASE WHEN $1::text = 'RETURNED' THEN now() ELSE returned_at END,
    returned_to_name = COALESCE($2, returned_to_name),
    closed_at = CASE WHEN $1::text IN ('RETURNED','DISPOSED','CANCELLED')
                     THEN now() ELSE closed_at END
WHERE id = $3 AND organization_id = $4
  AND status = $5
RETURNING id, public_id, organization_id, case_code, shipment_id, ndr_case_id, status, reason_code, reason_notes, initiated_at, initiated_by_user_id, return_branch_id, return_hub_id, origin_hub_id, route_resolution_source, route_legs, route_explanation, return_contact_name, return_phone, return_line1, return_line2, return_city, return_state, return_pincode, rto_charge_minor, currency, charge_bearer, charge_rule_notes, returned_at, returned_to_name, closed_at, metadata, created_at, updated_at, version
`

type UpdateRTOCaseStatusParams struct {
	ToStatus       string
	ReturnedToName *string
	ID             int64
	OrganizationID int64
	ExpectedStatus string
}

func (q *Queries) UpdateRTOCaseStatus(ctx context.Context, arg UpdateRTOCaseStatusParams) (RtoCase, error) {
	row := q.db.QueryRow(ctx, updateRTOCaseStatus,
		arg.ToStatus,
		arg.ReturnedToName,
		arg.ID,
		arg.OrganizationID,
		arg.ExpectedStatus,
	)
	var i RtoCase
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrganizationID,
		&i.CaseCode,
		&i.ShipmentID,
		&i.NdrCaseID,
		&i.Status,
		&i.ReasonCode,
		&i.ReasonNotes,
		&i.InitiatedAt,
		&i.InitiatedByUserID,
		&i.ReturnBranchID,
		&i.ReturnHubID,
		&i.OriginHubID,
		&i.RouteResolutionSource,
		&i.RouteLegs,
		&i.RouteExplanation,
		&i.ReturnContactName,
		&i.ReturnPhone,
		&i.ReturnLine1,
		&i.ReturnLine2,
		&i.ReturnCity,
		&i.ReturnState,
		&i.ReturnPincode,
		&i.RtoChargeMinor,
		&i.Currency,
		&i.ChargeBearer,
		&i.ChargeRuleNotes,
		&i.ReturnedAt,
		&i.ReturnedToName,
		&i.ClosedAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}
