// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: partner.sql

package dbgen

import (
	"context"
	"net/netip"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimDeliveryForSend = `-- name: ClaimDeliveryForSend :one
UPDATE webhook_deliveries
   SET status = 'SENDING', attempt_count = attempt_count + 1
 WHERE organization_id = $1 AND id = $2
   AND status = 'PENDING'
RETURNING id, public_id, organization_id, endpoint_id, event_type, event_id, payload, status, attempt_count, next_attempt_at, last_status_code, last_error, delivered_at, replay_of_id, shipment_id, job_id, created_at, updated_at
`

type ClaimDeliveryForSendParams struct {
	OrganizationID int64
	ID             int64
}

// PENDING -> SENDING only. Never accepts a row already SENDING: that would let
// a second worker deliver a webhook the first is still sending, and a consumer
// would see the same event twice from one delivery. A crashed worker's row is
// recovered by ReclaimStuckDeliveries on a staleness window.
func (q *Queries) ClaimDeliveryForSend(ctx context.Context, arg ClaimDeliveryForSendParams) (WebhookDelivery, error) {
	row := q.db.QueryRow(ctx, claimDeliveryForSend, arg.OrganizationID, arg.ID)
	var i WebhookDelivery
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrganizationID,
		&i.EndpointID,
		&i.EventType,
		&i.EventID,
		&i.Payload,
		&i.Status,
		&i.AttemptCount,
		&i.NextAttemptAt,
		&i.LastStatusCode,
		&i.LastError,
		&i.DeliveredAt,
		&i.ReplayOfID,
		&i.ShipmentID,
		&i.JobID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countDeliveriesByStatus = `-- name: CountDeliveriesByStatus :many
SELECT status, count(*)::bigint AS count
FROM webhook_deliveries
WHERE organization_id = $1 AND created_at >= $2::timestamptz
GROUP BY status
`

type CountDeliveriesByStatusParams struct {
	OrganizationID int64
	Since          time.Time
}

type CountDeliveriesByStatusRow struct {
	Status string
	Count  int64
}

func (q *Queries) CountDeliveriesByStatus(ctx context.Context, arg CountDeliveriesByStatusParams) ([]CountDeliveriesByStatusRow, error) {
	rows, err := q.db.Query(ctx, countDeliveriesByStatus, arg.OrganizationID, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountDeliveriesByStatusRow{}
	for rows.Next() {
		var i CountDeliveriesByStatusRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createAPIKey = `-- name: CreateAPIKey :one


INSERT INTO api_keys (
    public_id, organization_id, name, key_id, secret_hash, secret_hint,
    scopes, allowed_cidrs, expires_at, rate_limit_per_minute, created_by
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)
RETURNING id, public_id, organization_id, name, key_id, secret_hash, secret_hint, scopes, allowed_cidrs, status, expires_at, last_used_at, last_used_ip, request_count, rate_limit_per_minute, revoked_at, revoked_by, revoke_reason, created_by, created_at, updated_at
`

type CreateAPIKeyParams struct {
	PublicID           string
	OrganizationID     int64
	Name               string
	KeyID              string
	SecretHash         string
	SecretHint         string
	Scopes             []string
	AllowedCidrs       []string
	ExpiresAt          *time.Time
	RateLimitPerMinute *int32
	CreatedBy          *int64
}

// Partner API keys and webhooks (M32).
// ---------------------------------------------------------------------------
// API keys
// ---------------------------------------------------------------------------
func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, createAPIKey,
		arg.PublicID,
		arg.OrganizationID,
		arg.Name,
		arg.KeyID,
		arg.SecretHash,
		arg.SecretHint,
		arg.Scopes,
		arg.AllowedCidrs,
		arg.ExpiresAt,
		arg.RateLimitPerMinute,
		arg.CreatedBy,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrganizationID,
		&i.Name,
		&i.KeyID,
		&i.SecretHash,
		&i.SecretHint,
		&i.Scopes,
		&i.AllowedCidrs,
		&i.Status,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.LastUsedIp,
		&i.RequestCount,
		&i.RateLimitPerMinute,
		&i.RevokedAt,
		&i.RevokedBy,
		&i.RevokeReason,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createWebhookAttempt = `-- name: CreateWebhookAttempt :one
INSERT INTO webhook_attempts (
    organization_id, delivery_id, attempt_no, status_code,
    response_body, error_message, duration_ms
) VALUES ($1,$2,$3,$4,$5,$6,$7)
RETURNING id, organization_id, delivery_id, attempt_no, status_code, response_body, error_message, duration_ms, attempted_at
`

type CreateWebhookAttemptParams struct {
	OrganizationID int64
	DeliveryID     int64
	AttemptNo      int32
	StatusCode     *int32
	ResponseBody   *string
	ErrorMessage   *string
	DurationMs     *int32
}

func (q *Queries) CreateWebhookAttempt(ctx context.Context, arg CreateWebhookAttemptParams) (WebhookAttempt, error) {
	row := q.db.QueryRow(ctx, createWebhookAttempt,
		arg.OrganizationID,
		arg.DeliveryID,
		arg.AttemptNo,
		arg.StatusCode,
		arg.ResponseBody,
		arg.ErrorMessage,
		arg.DurationMs,
	)
	var i WebhookAttempt
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.DeliveryID,
		&i.AttemptNo,
		&i.StatusCode,
		&i.ResponseBody,
		&i.ErrorMessage,
		&i.DurationMs,
		&i.AttemptedAt,
	)
	return i, err
}

const createWebhookDelivery = `-- name: CreateWebhookDelivery :one

INSERT INTO webhook_deliveries (
    public_id, organization_id, endpoint_id, event_type, event_id, payload,
    next_attempt_at, shipment_id, replay_of_id
) VALUES (
    $1, $2, $3,
    $4, $5, $6,
    COALESCE($7::timestamptz, now()),
    $8, $9
)
RETURNING id, public_id, organization_id, endpoint_id, event_type, event_id, payload, status, attempt_count, next_attempt_at, last_status_code, last_error, delivered_at, replay_of_id, shipment_id, job_id, created_at, updated_at
`

type CreateWebhookDeliveryParams struct {
	PublicID       string
	OrganizationID int64
	EndpointID     int64
	EventType      string
	EventID        string
	Payload        []byte
	NextAttemptAt  *time.Time
	ShipmentID     *int64
	ReplayOfID     *int64
}

// ---------------------------------------------------------------------------
// Deliveries
// ---------------------------------------------------------------------------
// next_attempt_at defaults to the database's now(), not the application's.
// The two are different clocks: a delivery scheduled from the app's clock is
// compared against the database's in ClaimDeliveryForSend, and a few hundred
// milliseconds of skew is enough to make a webhook that should go out
// immediately sit in the queue until the next poll.
func (q *Queries) CreateWebhookDelivery(ctx context.Context, arg CreateWebhookDeliveryParams) (WebhookDelivery, error) {
	row := q.db.QueryRow(ctx, createWebhookDelivery,
		arg.PublicID,
		arg.OrganizationID,
		arg.EndpointID,
		arg.EventType,
		arg.EventID,
		arg.Payload,
		arg.NextAttemptAt,
		arg.ShipmentID,
		arg.ReplayOfID,
	)
	var i WebhookDelivery
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrganizationID,
		&i.EndpointID,
		&i.EventType,
		&i.EventID,
		&i.Payload,
		&i.Status,
		&i.AttemptCount,
		&i.NextAttemptAt,
		&i.LastStatusCode,
		&i.LastError,
		&i.DeliveredAt,
		&i.ReplayOfID,
		&i.ShipmentID,
		&i.JobID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createWebhookEndpoint = `-- name: CreateWebhookEndpoint :one

INSERT INTO webhook_endpoints (
    public_id, organization_id, name, url, signing_secret,
    max_attempts, timeout_seconds, api_key_id, created_by
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9)
RETURNING id, public_id, organization_id, name, url, signing_secret, status, consecutive_failures, disabled_reason, last_success_at, last_failure_at, max_attempts, timeout_seconds, api_key_id, created_by, created_at, updated_at
`

type CreateWebhookEndpointParams struct {
	PublicID       string
	OrganizationID int64
	Name           string
	Url            string
	SigningSecret  string
	MaxAttempts    int32
	TimeoutSeconds int32
	ApiKeyID       *int64
	CreatedBy      *int64
}

// ---------------------------------------------------------------------------
// Webhook endpoints
// ---------------------------------------------------------------------------
func (q *Queries) CreateWebhookEndpoint(ctx context.Context, arg CreateWebhookEndpointParams) (WebhookEndpoint, error) {
	row := q.db.QueryRow(ctx, createWebhookEndpoint,
		arg.PublicID,
		arg.OrganizationID,
		arg.Name,
		arg.Url,
		arg.SigningSecret,
		arg.MaxAttempts,
		arg.TimeoutSeconds,
		arg.ApiKeyID,
		arg.CreatedBy,
	)
	var i WebhookEndpoint
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrganizationID,
		&i.Name,
		&i.Url,
		&i.SigningSecret,
		&i.Status,
		&i.ConsecutiveFailures,
		&i.DisabledReason,
		&i.LastSuccessAt,
		&i.LastFailureAt,
		&i.MaxAttempts,
		&i.TimeoutSeconds,
		&i.ApiKeyID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createWebhookSubscription = `-- name: CreateWebhookSubscription :one

INSERT INTO webhook_subscriptions (
    public_id, organization_id, endpoint_id, event_type, filter
) VALUES ($1,$2,$3,$4,$5)
ON CONFLICT (endpoint_id, event_type)
DO UPDATE SET filter = EXCLUDED.filter, is_active = true
RETURNING id, public_id, organization_id, endpoint_id, event_type, filter, is_active, created_at
`

type CreateWebhookSubscriptionParams struct {
	PublicID       string
	OrganizationID int64
	EndpointID     int64
	EventType      string
	Filter         []byte
}

// ---------------------------------------------------------------------------
// Subscriptions
// ---------------------------------------------------------------------------
func (q *Queries) CreateWebhookSubscription(ctx context.Context, arg CreateWebhookSubscriptionParams) (WebhookSubscription, error) {
	row := q.db.QueryRow(ctx, createWebhookSubscription,
		arg.PublicID,
		arg.OrganizationID,
		arg.EndpointID,
		arg.EventType,
		arg.Filter,
	)
	var i WebhookSubscription
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrganizationID,
		&i.EndpointID,
		&i.EventType,
		&i.Filter,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const deleteWebhookSubscription = `-- name: DeleteWebhookSubscription :exec
DELETE FROM webhook_subscriptions
WHERE organization_id = $1 AND endpoint_id = $2 AND event_type = $3
`

type DeleteWebhookSubscriptionParams struct {
	OrganizationID int64
	EndpointID     int64
	EventType      string
}

func (q *Queries) DeleteWebhookSubscription(ctx context.Context, arg DeleteWebhookSubscriptionParams) error {
	_, err := q.db.Exec(ctx, deleteWebhookSubscription, arg.OrganizationID, arg.EndpointID, arg.EventType)
	return err
}

const expireAPIKeys = `-- name: ExpireAPIKeys :exec
UPDATE api_keys
   SET status = 'EXPIRED'
 WHERE status = 'ACTIVE' AND expires_at IS NOT NULL AND expires_at < now()
`

// Run by the worker. An expired key stops working whether or not anyone
// remembered to revoke it.
func (q *Queries) ExpireAPIKeys(ctx context.Context) error {
	_, err := q.db.Exec(ctx, expireAPIKeys)
	return err
}

const findAPIKeyByKeyID = `-- name: FindAPIKeyByKeyID :one
SELECT k.id, k.public_id, k.organization_id, k.name, k.key_id, k.secret_hash, k.secret_hint, k.scopes, k.allowed_cidrs, k.status, k.expires_at, k.last_used_at, k.last_used_ip, k.request_count, k.rate_limit_per_minute, k.revoked_at, k.revoked_by, k.revoke_reason, k.created_by, k.created_at, k.updated_at, o.public_id AS organization_public_id, o.code AS organization_code,
       o.currency AS organization_currency, o.timezone AS organization_timezone,
       o.awb_prefix AS organization_awb_prefix
FROM api_keys k
JOIN organizations o ON o.id = k.organization_id
WHERE k.key_id = $1
`

type FindAPIKeyByKeyIDRow struct {
	ID                    int64
	PublicID              string
	OrganizationID        int64
	Name                  string
	KeyID                 string
	SecretHash            string
	SecretHint            string
	Scopes                []string
	AllowedCidrs          []string
	Status                string
	ExpiresAt             *time.Time
	LastUsedAt            *time.Time
	LastUsedIp            *netip.Addr
	RequestCount          int64
	RateLimitPerMinute    *int32
	RevokedAt             *time.Time
	RevokedBy             *int64
	RevokeReason          *string
	CreatedBy             *int64
	CreatedAt             time.Time
	UpdatedAt             time.Time
	OrganizationPublicID  string
	OrganizationCode      string
	OrganizationCurrency  string
	OrganizationTimezone  string
	OrganizationAwbPrefix string
}

// The authentication lookup. key_id is globally unique because it arrives
// before the tenant is known — it is what identifies the organization.
//
// Returns the row whatever its status: the caller must distinguish "no such
// key" from "revoked key" to produce a useful error, and both take the same
// time so the difference is not observable by timing.
func (q *Queries) FindAPIKeyByKeyID(ctx context.Context, keyID string) (FindAPIKeyByKeyIDRow, error) {
	row := q.db.QueryRow(ctx, findAPIKeyByKeyID, keyID)
	var i FindAPIKeyByKeyIDRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrganizationID,
		&i.Name,
		&i.KeyID,
		&i.SecretHash,
		&i.SecretHint,
		&i.Scopes,
		&i.AllowedCidrs,
		&i.Status,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.LastUsedIp,
		&i.RequestCount,
		&i.RateLimitPerMinute,
		&i.RevokedAt,
		&i.RevokedBy,
		&i.RevokeReason,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrganizationPublicID,
		&i.OrganizationCode,
		&i.OrganizationCurrency,
		&i.OrganizationTimezone,
		&i.OrganizationAwbPrefix,
	)
	return i, err
}

const findDeliveryByEvent = `-- name: FindDeliveryByEvent :one
SELECT id, public_id, organization_id, endpoint_id, event_type, event_id, payload, status, attempt_count, next_attempt_at, last_status_code, last_error, delivered_at, replay_of_id, shipment_id, job_id, created_at, updated_at FROM webhook_deliveries
WHERE endpoint_id = $1 AND event_id = $2 AND replay_of_id IS NULL
`

type FindDeliveryByEventParams struct {
	EndpointID int64
	EventID    string
}

// The dedupe probe, mirroring webhook_deliveries_event_idx.
func (q *Queries) FindDeliveryByEvent(ctx context.Context, arg FindDeliveryByEventParams) (WebhookDelivery, error) {
	row := q.db.QueryRow(ctx, findDeliveryByEvent, arg.EndpointID, arg.EventID)
	var i WebhookDelivery
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrganizationID,
		&i.EndpointID,
		&i.EventType,
		&i.EventID,
		&i.Payload,
		&i.Status,
		&i.AttemptCount,
		&i.NextAttemptAt,
		&i.LastStatusCode,
		&i.LastError,
		&i.DeliveredAt,
		&i.ReplayOfID,
		&i.ShipmentID,
		&i.JobID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAPIKeyByPublicID = `-- name: GetAPIKeyByPublicID :one
SELECT id, public_id, organization_id, name, key_id, secret_hash, secret_hint, scopes, allowed_cidrs, status, expires_at, last_used_at, last_used_ip, request_count, rate_limit_per_minute, revoked_at, revoked_by, revoke_reason, created_by, created_at, updated_at FROM api_keys WHERE organization_id = $1 AND public_id = $2
`

type GetAPIKeyByPublicIDParams struct {
	OrganizationID int64
	PublicID       string
}

func (q *Queries) GetAPIKeyByPublicID(ctx context.Context, arg GetAPIKeyByPublicIDParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByPublicID, arg.OrganizationID, arg.PublicID)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrganizationID,
		&i.Name,
		&i.KeyID,
		&i.SecretHash,
		&i.SecretHint,
		&i.Scopes,
		&i.AllowedCidrs,
		&i.Status,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.LastUsedIp,
		&i.RequestCount,
		&i.RateLimitPerMinute,
		&i.RevokedAt,
		&i.RevokedBy,
		&i.RevokeReason,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDeliveryByPublicID = `-- name: GetDeliveryByPublicID :one
SELECT d.id, d.public_id, d.organization_id, d.endpoint_id, d.event_type, d.event_id, d.payload, d.status, d.attempt_count, d.next_attempt_at, d.last_status_code, d.last_error, d.delivered_at, d.replay_of_id, d.shipment_id, d.job_id, d.created_at, d.updated_at, e.url, e.name AS endpoint_name
FROM webhook_deliveries d
JOIN webhook_endpoints e ON e.id = d.endpoint_id
WHERE d.organization_id = $1 AND d.public_id = $2
`

type GetDeliveryByPublicIDParams struct {
	OrganizationID int64
	PublicID       string
}

type GetDeliveryByPublicIDRow struct {
	ID             int64
	PublicID       string
	OrganizationID int64
	EndpointID     int64
	EventType      string
	EventID        string
	Payload        []byte
	Status         string
	AttemptCount   int32
	NextAttemptAt  *time.Time
	LastStatusCode *int32
	LastError      *string
	DeliveredAt    *time.Time
	ReplayOfID     *int64
	ShipmentID     *int64
	JobID          *int64
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Url            string
	EndpointName   string
}

func (q *Queries) GetDeliveryByPublicID(ctx context.Context, arg GetDeliveryByPublicIDParams) (GetDeliveryByPublicIDRow, error) {
	row := q.db.QueryRow(ctx, getDeliveryByPublicID, arg.OrganizationID, arg.PublicID)
	var i GetDeliveryByPublicIDRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrganizationID,
		&i.EndpointID,
		&i.EventType,
		&i.EventID,
		&i.Payload,
		&i.Status,
		&i.AttemptCount,
		&i.NextAttemptAt,
		&i.LastStatusCode,
		&i.LastError,
		&i.DeliveredAt,
		&i.ReplayOfID,
		&i.ShipmentID,
		&i.JobID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Url,
		&i.EndpointName,
	)
	return i, err
}

const getWebhookEndpointByID = `-- name: GetWebhookEndpointByID :one
SELECT id, public_id, organization_id, name, url, signing_secret, status, consecutive_failures, disabled_reason, last_success_at, last_failure_at, max_attempts, timeout_seconds, api_key_id, created_by, created_at, updated_at FROM webhook_endpoints WHERE id = $1
`

func (q *Queries) GetWebhookEndpointByID(ctx context.Context, id int64) (WebhookEndpoint, error) {
	row := q.db.QueryRow(ctx, getWebhookEndpointByID, id)
	var i WebhookEndpoint
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrganizationID,
		&i.Name,
		&i.Url,
		&i.SigningSecret,
		&i.Status,
		&i.ConsecutiveFailures,
		&i.DisabledReason,
		&i.LastSuccessAt,
		&i.LastFailureAt,
		&i.MaxAttempts,
		&i.TimeoutSeconds,
		&i.ApiKeyID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWebhookEndpointByPublicID = `-- name: GetWebhookEndpointByPublicID :one
SELECT id, public_id, organization_id, name, url, signing_secret, status, consecutive_failures, disabled_reason, last_success_at, last_failure_at, max_attempts, timeout_seconds, api_key_id, created_by, created_at, updated_at FROM webhook_endpoints WHERE organization_id = $1 AND public_id = $2
`

type GetWebhookEndpointByPublicIDParams struct {
	OrganizationID int64
	PublicID       string
}

func (q *Queries) GetWebhookEndpointByPublicID(ctx context.Context, arg GetWebhookEndpointByPublicIDParams) (WebhookEndpoint, error) {
	row := q.db.QueryRow(ctx, getWebhookEndpointByPublicID, arg.OrganizationID, arg.PublicID)
	var i WebhookEndpoint
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrganizationID,
		&i.Name,
		&i.Url,
		&i.SigningSecret,
		&i.Status,
		&i.ConsecutiveFailures,
		&i.DisabledReason,
		&i.LastSuccessAt,
		&i.LastFailureAt,
		&i.MaxAttempts,
		&i.TimeoutSeconds,
		&i.ApiKeyID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAPIKeyRequests = `-- name: ListAPIKeyRequests :many
SELECT id, organization_id, api_key_id, method, route, status_code, duration_ms, request_id, error_code, client_ip, occurred_at FROM api_key_requests
WHERE organization_id = $1 AND api_key_id = $2
ORDER BY occurred_at DESC
LIMIT $3
`

type ListAPIKeyRequestsParams struct {
	OrganizationID int64
	ApiKeyID       int64
	Limit          int32
}

func (q *Queries) ListAPIKeyRequests(ctx context.Context, arg ListAPIKeyRequestsParams) ([]ApiKeyRequest, error) {
	rows, err := q.db.Query(ctx, listAPIKeyRequests, arg.OrganizationID, arg.ApiKeyID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiKeyRequest{}
	for rows.Next() {
		var i ApiKeyRequest
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ApiKeyID,
			&i.Method,
			&i.Route,
			&i.StatusCode,
			&i.DurationMs,
			&i.RequestID,
			&i.ErrorCode,
			&i.ClientIp,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAPIKeys = `-- name: ListAPIKeys :many
SELECT id, public_id, organization_id, name, key_id, secret_hint, scopes,
       allowed_cidrs, status, expires_at, last_used_at, last_used_ip,
       request_count, rate_limit_per_minute, revoked_at, revoke_reason,
       created_by, created_at, updated_at,
       -- A window count rather than a second query: an offset page without a
       -- total leaves a client requesting the maximum and guessing whether
       -- there is more.
       count(*) OVER () AS total_count
FROM api_keys
WHERE organization_id = $1
  AND ($4::text IS NULL OR status = $4::text)
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListAPIKeysParams struct {
	OrganizationID int64
	Limit          int32
	Offset         int32
	Status         *string
}

type ListAPIKeysRow struct {
	ID                 int64
	PublicID           string
	OrganizationID     int64
	Name               string
	KeyID              string
	SecretHint         string
	Scopes             []string
	AllowedCidrs       []string
	Status             string
	ExpiresAt          *time.Time
	LastUsedAt         *time.Time
	LastUsedIp         *netip.Addr
	RequestCount       int64
	RateLimitPerMinute *int32
	RevokedAt          *time.Time
	RevokeReason       *string
	CreatedBy          *int64
	CreatedAt          time.Time
	UpdatedAt          time.Time
	TotalCount         int64
}

// Never returns secret_hash. The hint is enough to tell two keys apart.
func (q *Queries) ListAPIKeys(ctx context.Context, arg ListAPIKeysParams) ([]ListAPIKeysRow, error) {
	rows, err := q.db.Query(ctx, listAPIKeys,
		arg.OrganizationID,
		arg.Limit,
		arg.Offset,
		arg.Status,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAPIKeysRow{}
	for rows.Next() {
		var i ListAPIKeysRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.OrganizationID,
			&i.Name,
			&i.KeyID,
			&i.SecretHint,
			&i.Scopes,
			&i.AllowedCidrs,
			&i.Status,
			&i.ExpiresAt,
			&i.LastUsedAt,
			&i.LastUsedIp,
			&i.RequestCount,
			&i.RateLimitPerMinute,
			&i.RevokedAt,
			&i.RevokeReason,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDueWebhookDeliveries = `-- name: ListDueWebhookDeliveries :many
SELECT id, organization_id, public_id FROM webhook_deliveries
WHERE ($1::bigint IS NULL
       OR organization_id = $1::bigint)
  AND status = 'PENDING'
  AND (next_attempt_at IS NULL OR next_attempt_at <= now())
ORDER BY next_attempt_at NULLS FIRST, id
LIMIT $2
`

type ListDueWebhookDeliveriesParams struct {
	OrganizationID *int64
	RowLimit       int32
}

type ListDueWebhookDeliveriesRow struct {
	ID             int64
	OrganizationID int64
	PublicID       string
}

// The webhook twin of ListDueNotifications: a delivery row whose send job was
// never enqueued would otherwise sit PENDING forever, and a partner would be
// missing an event nobody knew about.
func (q *Queries) ListDueWebhookDeliveries(ctx context.Context, arg ListDueWebhookDeliveriesParams) ([]ListDueWebhookDeliveriesRow, error) {
	rows, err := q.db.Query(ctx, listDueWebhookDeliveries, arg.OrganizationID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDueWebhookDeliveriesRow{}
	for rows.Next() {
		var i ListDueWebhookDeliveriesRow
		if err := rows.Scan(&i.ID, &i.OrganizationID, &i.PublicID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEndpointsForEvent = `-- name: ListEndpointsForEvent :many
SELECT e.id, e.public_id, e.organization_id, e.name, e.url, e.signing_secret, e.status, e.consecutive_failures, e.disabled_reason, e.last_success_at, e.last_failure_at, e.max_attempts, e.timeout_seconds, e.api_key_id, e.created_by, e.created_at, e.updated_at
FROM webhook_endpoints e
JOIN webhook_subscriptions s ON s.endpoint_id = e.id
WHERE e.organization_id = $1
  AND e.status = 'ACTIVE'
  AND s.event_type = $2
  AND s.is_active
`

type ListEndpointsForEventParams struct {
	OrganizationID int64
	EventType      string
}

// Every active endpoint that has asked for this event. The fan-out query.
func (q *Queries) ListEndpointsForEvent(ctx context.Context, arg ListEndpointsForEventParams) ([]WebhookEndpoint, error) {
	rows, err := q.db.Query(ctx, listEndpointsForEvent, arg.OrganizationID, arg.EventType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookEndpoint{}
	for rows.Next() {
		var i WebhookEndpoint
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.OrganizationID,
			&i.Name,
			&i.Url,
			&i.SigningSecret,
			&i.Status,
			&i.ConsecutiveFailures,
			&i.DisabledReason,
			&i.LastSuccessAt,
			&i.LastFailureAt,
			&i.MaxAttempts,
			&i.TimeoutSeconds,
			&i.ApiKeyID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhookAttempts = `-- name: ListWebhookAttempts :many
SELECT id, organization_id, delivery_id, attempt_no, status_code, response_body, error_message, duration_ms, attempted_at FROM webhook_attempts WHERE delivery_id = $1 ORDER BY attempt_no
`

func (q *Queries) ListWebhookAttempts(ctx context.Context, deliveryID int64) ([]WebhookAttempt, error) {
	rows, err := q.db.Query(ctx, listWebhookAttempts, deliveryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookAttempt{}
	for rows.Next() {
		var i WebhookAttempt
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.DeliveryID,
			&i.AttemptNo,
			&i.StatusCode,
			&i.ResponseBody,
			&i.ErrorMessage,
			&i.DurationMs,
			&i.AttemptedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhookDeliveries = `-- name: ListWebhookDeliveries :many
SELECT d.id, d.public_id, d.organization_id, d.endpoint_id, d.event_type, d.event_id, d.payload, d.status, d.attempt_count, d.next_attempt_at, d.last_status_code, d.last_error, d.delivered_at, d.replay_of_id, d.shipment_id, d.job_id, d.created_at, d.updated_at, e.name AS endpoint_name
FROM webhook_deliveries d
JOIN webhook_endpoints e ON e.id = d.endpoint_id
WHERE d.organization_id = $1
  AND ($3::bigint IS NULL OR d.endpoint_id = $3::bigint)
  AND ($4::text IS NULL OR d.status = $4::text)
  AND ($5::text IS NULL OR d.event_type = $5::text)
  AND ($6::bigint IS NULL OR d.id < $6::bigint)
ORDER BY d.id DESC
LIMIT $2
`

type ListWebhookDeliveriesParams struct {
	OrganizationID int64
	Limit          int32
	EndpointID     *int64
	Status         *string
	EventType      *string
	CursorID       *int64
}

type ListWebhookDeliveriesRow struct {
	ID             int64
	PublicID       string
	OrganizationID int64
	EndpointID     int64
	EventType      string
	EventID        string
	Payload        []byte
	Status         string
	AttemptCount   int32
	NextAttemptAt  *time.Time
	LastStatusCode *int32
	LastError      *string
	DeliveredAt    *time.Time
	ReplayOfID     *int64
	ShipmentID     *int64
	JobID          *int64
	CreatedAt      time.Time
	UpdatedAt      time.Time
	EndpointName   string
}

func (q *Queries) ListWebhookDeliveries(ctx context.Context, arg ListWebhookDeliveriesParams) ([]ListWebhookDeliveriesRow, error) {
	rows, err := q.db.Query(ctx, listWebhookDeliveries,
		arg.OrganizationID,
		arg.Limit,
		arg.EndpointID,
		arg.Status,
		arg.EventType,
		arg.CursorID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWebhookDeliveriesRow{}
	for rows.Next() {
		var i ListWebhookDeliveriesRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.OrganizationID,
			&i.EndpointID,
			&i.EventType,
			&i.EventID,
			&i.Payload,
			&i.Status,
			&i.AttemptCount,
			&i.NextAttemptAt,
			&i.LastStatusCode,
			&i.LastError,
			&i.DeliveredAt,
			&i.ReplayOfID,
			&i.ShipmentID,
			&i.JobID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EndpointName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhookEndpoints = `-- name: ListWebhookEndpoints :many
SELECT id, public_id, organization_id, name, url, status,
       consecutive_failures, disabled_reason, last_success_at, last_failure_at,
       max_attempts, timeout_seconds, created_at, updated_at,
       count(*) OVER () AS total_count
FROM webhook_endpoints
WHERE organization_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListWebhookEndpointsParams struct {
	OrganizationID int64
	Limit          int32
	Offset         int32
}

type ListWebhookEndpointsRow struct {
	ID                  int64
	PublicID            string
	OrganizationID      int64
	Name                string
	Url                 string
	Status              string
	ConsecutiveFailures int32
	DisabledReason      *string
	LastSuccessAt       *time.Time
	LastFailureAt       *time.Time
	MaxAttempts         int32
	TimeoutSeconds      int32
	CreatedAt           time.Time
	UpdatedAt           time.Time
	TotalCount          int64
}

func (q *Queries) ListWebhookEndpoints(ctx context.Context, arg ListWebhookEndpointsParams) ([]ListWebhookEndpointsRow, error) {
	rows, err := q.db.Query(ctx, listWebhookEndpoints, arg.OrganizationID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWebhookEndpointsRow{}
	for rows.Next() {
		var i ListWebhookEndpointsRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.OrganizationID,
			&i.Name,
			&i.Url,
			&i.Status,
			&i.ConsecutiveFailures,
			&i.DisabledReason,
			&i.LastSuccessAt,
			&i.LastFailureAt,
			&i.MaxAttempts,
			&i.TimeoutSeconds,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhookSubscriptions = `-- name: ListWebhookSubscriptions :many
SELECT id, public_id, organization_id, endpoint_id, event_type, filter, is_active, created_at FROM webhook_subscriptions WHERE endpoint_id = $1 ORDER BY event_type
`

func (q *Queries) ListWebhookSubscriptions(ctx context.Context, endpointID int64) ([]WebhookSubscription, error) {
	rows, err := q.db.Query(ctx, listWebhookSubscriptions, endpointID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookSubscription{}
	for rows.Next() {
		var i WebhookSubscription
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.OrganizationID,
			&i.EndpointID,
			&i.EventType,
			&i.Filter,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDeliveryFailed = `-- name: MarkDeliveryFailed :one
UPDATE webhook_deliveries
   SET status = CASE
           WHEN attempt_count < $1::int THEN 'PENDING'
           ELSE 'DEAD_LETTER'
       END,
       last_status_code = $2,
       last_error = $3,
       -- Scheduled forward from the database clock, for the same reason
       -- CreateWebhookDelivery is: the caller supplies how long to wait, not
       -- when to wake up.
       next_attempt_at = CASE
           WHEN attempt_count < $1::int
           THEN now() + $4::interval
           ELSE NULL
       END
 WHERE organization_id = $5 AND id = $6
RETURNING id, public_id, organization_id, endpoint_id, event_type, event_id, payload, status, attempt_count, next_attempt_at, last_status_code, last_error, delivered_at, replay_of_id, shipment_id, job_id, created_at, updated_at
`

type MarkDeliveryFailedParams struct {
	MaxAttempts    int32
	StatusCode     *int32
	ErrorMessage   *string
	RetryAfter     pgtype.Interval
	OrganizationID int64
	ID             int64
}

func (q *Queries) MarkDeliveryFailed(ctx context.Context, arg MarkDeliveryFailedParams) (WebhookDelivery, error) {
	row := q.db.QueryRow(ctx, markDeliveryFailed,
		arg.MaxAttempts,
		arg.StatusCode,
		arg.ErrorMessage,
		arg.RetryAfter,
		arg.OrganizationID,
		arg.ID,
	)
	var i WebhookDelivery
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrganizationID,
		&i.EndpointID,
		&i.EventType,
		&i.EventID,
		&i.Payload,
		&i.Status,
		&i.AttemptCount,
		&i.NextAttemptAt,
		&i.LastStatusCode,
		&i.LastError,
		&i.DeliveredAt,
		&i.ReplayOfID,
		&i.ShipmentID,
		&i.JobID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markDeliverySucceeded = `-- name: MarkDeliverySucceeded :one
UPDATE webhook_deliveries
   SET status = 'DELIVERED', delivered_at = now(),
       last_status_code = $1, next_attempt_at = NULL,
       last_error = NULL
 WHERE organization_id = $2 AND id = $3
RETURNING id, public_id, organization_id, endpoint_id, event_type, event_id, payload, status, attempt_count, next_attempt_at, last_status_code, last_error, delivered_at, replay_of_id, shipment_id, job_id, created_at, updated_at
`

type MarkDeliverySucceededParams struct {
	StatusCode     *int32
	OrganizationID int64
	ID             int64
}

func (q *Queries) MarkDeliverySucceeded(ctx context.Context, arg MarkDeliverySucceededParams) (WebhookDelivery, error) {
	row := q.db.QueryRow(ctx, markDeliverySucceeded, arg.StatusCode, arg.OrganizationID, arg.ID)
	var i WebhookDelivery
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrganizationID,
		&i.EndpointID,
		&i.EventType,
		&i.EventID,
		&i.Payload,
		&i.Status,
		&i.AttemptCount,
		&i.NextAttemptAt,
		&i.LastStatusCode,
		&i.LastError,
		&i.DeliveredAt,
		&i.ReplayOfID,
		&i.ShipmentID,
		&i.JobID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const reclaimStuckDeliveries = `-- name: ReclaimStuckDeliveries :many
UPDATE webhook_deliveries
   SET status = 'PENDING'
 WHERE ($1::bigint IS NULL
        OR organization_id = $1::bigint)
   AND status = 'SENDING'
   AND updated_at < now() - $2::interval
RETURNING id, public_id, organization_id, endpoint_id, event_type, event_id, payload, status, attempt_count, next_attempt_at, last_status_code, last_error, delivered_at, replay_of_id, shipment_id, job_id, created_at, updated_at
`

type ReclaimStuckDeliveriesParams struct {
	OrganizationID *int64
	StaleAfter     pgtype.Interval
}

// The counterpart to ClaimDeliveryForSend, which accepts PENDING and nothing
// else: a worker that dies mid-send would otherwise strand its row in SENDING
// forever. organization_id is optional so the maintenance sweep covers every
// tenant at once.
func (q *Queries) ReclaimStuckDeliveries(ctx context.Context, arg ReclaimStuckDeliveriesParams) ([]WebhookDelivery, error) {
	rows, err := q.db.Query(ctx, reclaimStuckDeliveries, arg.OrganizationID, arg.StaleAfter)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookDelivery{}
	for rows.Next() {
		var i WebhookDelivery
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.OrganizationID,
			&i.EndpointID,
			&i.EventType,
			&i.EventID,
			&i.Payload,
			&i.Status,
			&i.AttemptCount,
			&i.NextAttemptAt,
			&i.LastStatusCode,
			&i.LastError,
			&i.DeliveredAt,
			&i.ReplayOfID,
			&i.ShipmentID,
			&i.JobID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordAPIKeyRequest = `-- name: RecordAPIKeyRequest :exec
INSERT INTO api_key_requests (
    organization_id, api_key_id, method, route, status_code, duration_ms,
    request_id, error_code, client_ip
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9)
`

type RecordAPIKeyRequestParams struct {
	OrganizationID int64
	ApiKeyID       int64
	Method         string
	Route          string
	StatusCode     int32
	DurationMs     int32
	RequestID      *string
	ErrorCode      *string
	ClientIp       *netip.Addr
}

func (q *Queries) RecordAPIKeyRequest(ctx context.Context, arg RecordAPIKeyRequestParams) error {
	_, err := q.db.Exec(ctx, recordAPIKeyRequest,
		arg.OrganizationID,
		arg.ApiKeyID,
		arg.Method,
		arg.Route,
		arg.StatusCode,
		arg.DurationMs,
		arg.RequestID,
		arg.ErrorCode,
		arg.ClientIp,
	)
	return err
}

const recordWebhookFailure = `-- name: RecordWebhookFailure :one
UPDATE webhook_endpoints
   SET consecutive_failures = consecutive_failures + 1,
       last_failure_at = now(),
       status = CASE WHEN consecutive_failures + 1 >= $1::int
                     THEN 'PAUSED' ELSE status END,
       disabled_reason = CASE WHEN consecutive_failures + 1 >= $1::int
                              THEN 'paused automatically after repeated delivery failures'
                              ELSE disabled_reason END
 WHERE id = $2
RETURNING id, public_id, organization_id, name, url, signing_secret, status, consecutive_failures, disabled_reason, last_success_at, last_failure_at, max_attempts, timeout_seconds, api_key_id, created_by, created_at, updated_at
`

type RecordWebhookFailureParams struct {
	PauseAfter int32
	ID         int64
}

// Counts consecutive failures and auto-pauses a persistently dead endpoint, so
// one broken partner cannot fill the queue with retries forever.
func (q *Queries) RecordWebhookFailure(ctx context.Context, arg RecordWebhookFailureParams) (WebhookEndpoint, error) {
	row := q.db.QueryRow(ctx, recordWebhookFailure, arg.PauseAfter, arg.ID)
	var i WebhookEndpoint
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrganizationID,
		&i.Name,
		&i.Url,
		&i.SigningSecret,
		&i.Status,
		&i.ConsecutiveFailures,
		&i.DisabledReason,
		&i.LastSuccessAt,
		&i.LastFailureAt,
		&i.MaxAttempts,
		&i.TimeoutSeconds,
		&i.ApiKeyID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const recordWebhookSuccess = `-- name: RecordWebhookSuccess :exec
UPDATE webhook_endpoints
   SET consecutive_failures = 0, last_success_at = now()
 WHERE id = $1
`

func (q *Queries) RecordWebhookSuccess(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, recordWebhookSuccess, id)
	return err
}

const revokeAPIKey = `-- name: RevokeAPIKey :one
UPDATE api_keys
   SET status = 'REVOKED', revoked_at = now(), revoked_by = $3, revoke_reason = $4
 WHERE organization_id = $1 AND id = $2 AND status <> 'REVOKED'
RETURNING id, public_id, organization_id, name, key_id, secret_hash, secret_hint, scopes, allowed_cidrs, status, expires_at, last_used_at, last_used_ip, request_count, rate_limit_per_minute, revoked_at, revoked_by, revoke_reason, created_by, created_at, updated_at
`

type RevokeAPIKeyParams struct {
	OrganizationID int64
	ID             int64
	RevokedBy      *int64
	RevokeReason   *string
}

// One-way. The api_keys_guard trigger refuses to bring a revoked key back:
// a leaked credential must never be reinstated.
func (q *Queries) RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, revokeAPIKey,
		arg.OrganizationID,
		arg.ID,
		arg.RevokedBy,
		arg.RevokeReason,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrganizationID,
		&i.Name,
		&i.KeyID,
		&i.SecretHash,
		&i.SecretHint,
		&i.Scopes,
		&i.AllowedCidrs,
		&i.Status,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.LastUsedIp,
		&i.RequestCount,
		&i.RateLimitPerMinute,
		&i.RevokedAt,
		&i.RevokedBy,
		&i.RevokeReason,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setWebhookEndpointStatus = `-- name: SetWebhookEndpointStatus :one
UPDATE webhook_endpoints
   SET status = $1, disabled_reason = $2,
       consecutive_failures = CASE WHEN $1::text = 'ACTIVE' THEN 0
                                   ELSE consecutive_failures END
 WHERE organization_id = $3 AND id = $4
RETURNING id, public_id, organization_id, name, url, signing_secret, status, consecutive_failures, disabled_reason, last_success_at, last_failure_at, max_attempts, timeout_seconds, api_key_id, created_by, created_at, updated_at
`

type SetWebhookEndpointStatusParams struct {
	Status         string
	DisabledReason *string
	OrganizationID int64
	ID             int64
}

func (q *Queries) SetWebhookEndpointStatus(ctx context.Context, arg SetWebhookEndpointStatusParams) (WebhookEndpoint, error) {
	row := q.db.QueryRow(ctx, setWebhookEndpointStatus,
		arg.Status,
		arg.DisabledReason,
		arg.OrganizationID,
		arg.ID,
	)
	var i WebhookEndpoint
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrganizationID,
		&i.Name,
		&i.Url,
		&i.SigningSecret,
		&i.Status,
		&i.ConsecutiveFailures,
		&i.DisabledReason,
		&i.LastSuccessAt,
		&i.LastFailureAt,
		&i.MaxAttempts,
		&i.TimeoutSeconds,
		&i.ApiKeyID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const summariseAPIKeyUsage = `-- name: SummariseAPIKeyUsage :one
SELECT count(*)::bigint AS request_count,
       count(*) FILTER (WHERE status_code >= 400)::bigint AS error_count,
       COALESCE(AVG(duration_ms), 0)::int AS avg_duration_ms
FROM api_key_requests
WHERE api_key_id = $1 AND occurred_at >= $2::timestamptz
`

type SummariseAPIKeyUsageParams struct {
	ApiKeyID int64
	Since    time.Time
}

type SummariseAPIKeyUsageRow struct {
	RequestCount  int64
	ErrorCount    int64
	AvgDurationMs int32
}

func (q *Queries) SummariseAPIKeyUsage(ctx context.Context, arg SummariseAPIKeyUsageParams) (SummariseAPIKeyUsageRow, error) {
	row := q.db.QueryRow(ctx, summariseAPIKeyUsage, arg.ApiKeyID, arg.Since)
	var i SummariseAPIKeyUsageRow
	err := row.Scan(&i.RequestCount, &i.ErrorCount, &i.AvgDurationMs)
	return i, err
}

const suspendAPIKey = `-- name: SuspendAPIKey :one
UPDATE api_keys
   SET status = CASE WHEN $1::boolean THEN 'SUSPENDED' ELSE 'ACTIVE' END
 WHERE organization_id = $2 AND id = $3
   AND status IN ('ACTIVE','SUSPENDED')
RETURNING id, public_id, organization_id, name, key_id, secret_hash, secret_hint, scopes, allowed_cidrs, status, expires_at, last_used_at, last_used_ip, request_count, rate_limit_per_minute, revoked_at, revoked_by, revoke_reason, created_by, created_at, updated_at
`

type SuspendAPIKeyParams struct {
	Suspend        bool
	OrganizationID int64
	ID             int64
}

func (q *Queries) SuspendAPIKey(ctx context.Context, arg SuspendAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, suspendAPIKey, arg.Suspend, arg.OrganizationID, arg.ID)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrganizationID,
		&i.Name,
		&i.KeyID,
		&i.SecretHash,
		&i.SecretHint,
		&i.Scopes,
		&i.AllowedCidrs,
		&i.Status,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.LastUsedIp,
		&i.RequestCount,
		&i.RateLimitPerMinute,
		&i.RevokedAt,
		&i.RevokedBy,
		&i.RevokeReason,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const touchAPIKey = `-- name: TouchAPIKey :exec
UPDATE api_keys
   SET last_used_at = now(), last_used_ip = $1::inet,
       request_count = request_count + 1
 WHERE id = $2
`

type TouchAPIKeyParams struct {
	ClientIp *netip.Addr
	ID       int64
}

// Usage tracking, deliberately fire-and-forget and outside the request's
// transaction: a hot partner key must not serialise every request on one row,
// and a failed update here must never fail the request it describes.
func (q *Queries) TouchAPIKey(ctx context.Context, arg TouchAPIKeyParams) error {
	_, err := q.db.Exec(ctx, touchAPIKey, arg.ClientIp, arg.ID)
	return err
}
