// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: platform.sql

package dbgen

import (
	"context"
	"time"
)

const claimIdempotencyKey = `-- name: ClaimIdempotencyKey :one


INSERT INTO idempotency_keys (
    organization_id, endpoint, idempotency_key, request_hash, user_id, request_id, expires_at
) VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (organization_id, endpoint, idempotency_key) DO NOTHING
RETURNING id, organization_id, endpoint, idempotency_key, request_hash, user_id, status, response_status, response_body, resource_type, resource_public_id, request_id, created_at, completed_at, expires_at
`

type ClaimIdempotencyKeyParams struct {
	OrganizationID int64
	Endpoint       string
	IdempotencyKey string
	RequestHash    []byte
	UserID         *int64
	RequestID      *string
	ExpiresAt      time.Time
}

// Platform runtime queries: idempotency ledger, background jobs, audit trail.
// ---------------------------------------------------------------------------
// Idempotency
// ---------------------------------------------------------------------------
// ClaimIdempotencyKey attempts to reserve a key.
//
// ON CONFLICT DO NOTHING makes the reservation atomic: exactly one concurrent
// caller gets a row back and proceeds, everyone else gets zero rows and must
// read the existing record. This is the whole concurrency control for retried
// bookings — no advisory lock, no Redis.
func (q *Queries) ClaimIdempotencyKey(ctx context.Context, arg ClaimIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, claimIdempotencyKey,
		arg.OrganizationID,
		arg.Endpoint,
		arg.IdempotencyKey,
		arg.RequestHash,
		arg.UserID,
		arg.RequestID,
		arg.ExpiresAt,
	)
	var i IdempotencyKey
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Endpoint,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.UserID,
		&i.Status,
		&i.ResponseStatus,
		&i.ResponseBody,
		&i.ResourceType,
		&i.ResourcePublicID,
		&i.RequestID,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const claimJobs = `-- name: ClaimJobs :many
WITH claimed AS (
    SELECT id FROM jobs
    WHERE status = 'PENDING'
      AND run_at <= now()
      AND queue = ANY($2::text[])
    ORDER BY priority ASC, run_at ASC, id ASC
    LIMIT $3
    FOR UPDATE SKIP LOCKED
)
UPDATE jobs j
SET status = 'RUNNING',
    attempts = j.attempts + 1,
    locked_at = now(),
    locked_by = $1,
    started_at = COALESCE(j.started_at, now())
FROM claimed c
WHERE j.id = c.id
RETURNING j.id, j.public_id, j.organization_id, j.queue, j.job_type, j.payload, j.status, j.priority, j.run_at, j.attempts, j.max_attempts, j.last_error, j.error_count, j.dedupe_key, j.locked_at, j.locked_by, j.started_at, j.completed_at, j.created_by, j.created_at, j.updated_at
`

type ClaimJobsParams struct {
	WorkerID *string
	Queues   []string
	MaxJobs  int32
}

// ClaimJobs takes ownership of up to $3 runnable jobs.
//
// FOR UPDATE SKIP LOCKED lets several workers claim disjoint batches without
// blocking each other; the UPDATE and the SELECT are one statement so a claimed
// job can never be handed to two workers.
func (q *Queries) ClaimJobs(ctx context.Context, arg ClaimJobsParams) ([]Job, error) {
	rows, err := q.db.Query(ctx, claimJobs, arg.WorkerID, arg.Queues, arg.MaxJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.OrganizationID,
			&i.Queue,
			&i.JobType,
			&i.Payload,
			&i.Status,
			&i.Priority,
			&i.RunAt,
			&i.Attempts,
			&i.MaxAttempts,
			&i.LastError,
			&i.ErrorCount,
			&i.DedupeKey,
			&i.LockedAt,
			&i.LockedBy,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const completeIdempotencyKey = `-- name: CompleteIdempotencyKey :exec
UPDATE idempotency_keys
SET status = 'COMPLETED',
    response_status = $4,
    response_body = $5,
    resource_type = $6,
    resource_public_id = $7,
    completed_at = now()
WHERE organization_id = $1 AND endpoint = $2 AND idempotency_key = $3
`

type CompleteIdempotencyKeyParams struct {
	OrganizationID   int64
	Endpoint         string
	IdempotencyKey   string
	ResponseStatus   *int32
	ResponseBody     []byte
	ResourceType     *string
	ResourcePublicID *string
}

func (q *Queries) CompleteIdempotencyKey(ctx context.Context, arg CompleteIdempotencyKeyParams) error {
	_, err := q.db.Exec(ctx, completeIdempotencyKey,
		arg.OrganizationID,
		arg.Endpoint,
		arg.IdempotencyKey,
		arg.ResponseStatus,
		arg.ResponseBody,
		arg.ResourceType,
		arg.ResourcePublicID,
	)
	return err
}

const completeJob = `-- name: CompleteJob :exec
UPDATE jobs
SET status = 'SUCCEEDED', completed_at = now(), locked_at = NULL, locked_by = NULL
WHERE id = $1
`

func (q *Queries) CompleteJob(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, completeJob, id)
	return err
}

const countJobsByQueue = `-- name: CountJobsByQueue :many
SELECT queue, count(*) AS pending FROM jobs
WHERE status = 'PENDING' AND run_at <= now()
GROUP BY queue
`

type CountJobsByQueueRow struct {
	Queue   string
	Pending int64
}

func (q *Queries) CountJobsByQueue(ctx context.Context) ([]CountJobsByQueueRow, error) {
	rows, err := q.db.Query(ctx, countJobsByQueue)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountJobsByQueueRow{}
	for rows.Next() {
		var i CountJobsByQueueRow
		if err := rows.Scan(&i.Queue, &i.Pending); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const enqueueJob = `-- name: EnqueueJob :one

INSERT INTO jobs (
    public_id, organization_id, queue, job_type, payload, priority, run_at, max_attempts, dedupe_key, created_by
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT (dedupe_key) WHERE dedupe_key IS NOT NULL AND status IN ('PENDING','RUNNING') DO NOTHING
RETURNING id, public_id, organization_id, queue, job_type, payload, status, priority, run_at, attempts, max_attempts, last_error, error_count, dedupe_key, locked_at, locked_by, started_at, completed_at, created_by, created_at, updated_at
`

type EnqueueJobParams struct {
	PublicID       string
	OrganizationID *int64
	Queue          string
	JobType        string
	Payload        []byte
	Priority       int16
	RunAt          time.Time
	MaxAttempts    int32
	DedupeKey      *string
	CreatedBy      *int64
}

// ---------------------------------------------------------------------------
// Jobs
// ---------------------------------------------------------------------------
func (q *Queries) EnqueueJob(ctx context.Context, arg EnqueueJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, enqueueJob,
		arg.PublicID,
		arg.OrganizationID,
		arg.Queue,
		arg.JobType,
		arg.Payload,
		arg.Priority,
		arg.RunAt,
		arg.MaxAttempts,
		arg.DedupeKey,
		arg.CreatedBy,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrganizationID,
		&i.Queue,
		&i.JobType,
		&i.Payload,
		&i.Status,
		&i.Priority,
		&i.RunAt,
		&i.Attempts,
		&i.MaxAttempts,
		&i.LastError,
		&i.ErrorCount,
		&i.DedupeKey,
		&i.LockedAt,
		&i.LockedBy,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const failIdempotencyKey = `-- name: FailIdempotencyKey :exec
DELETE FROM idempotency_keys
WHERE organization_id = $1 AND endpoint = $2 AND idempotency_key = $3 AND status = 'IN_PROGRESS'
`

type FailIdempotencyKeyParams struct {
	OrganizationID int64
	Endpoint       string
	IdempotencyKey string
}

// FailIdempotencyKey releases a reservation so the client may retry with the
// same key after a transient failure.
func (q *Queries) FailIdempotencyKey(ctx context.Context, arg FailIdempotencyKeyParams) error {
	_, err := q.db.Exec(ctx, failIdempotencyKey, arg.OrganizationID, arg.Endpoint, arg.IdempotencyKey)
	return err
}

const getIdempotencyKey = `-- name: GetIdempotencyKey :one
SELECT id, organization_id, endpoint, idempotency_key, request_hash, user_id, status, response_status, response_body, resource_type, resource_public_id, request_id, created_at, completed_at, expires_at FROM idempotency_keys
WHERE organization_id = $1 AND endpoint = $2 AND idempotency_key = $3
`

type GetIdempotencyKeyParams struct {
	OrganizationID int64
	Endpoint       string
	IdempotencyKey string
}

func (q *Queries) GetIdempotencyKey(ctx context.Context, arg GetIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, getIdempotencyKey, arg.OrganizationID, arg.Endpoint, arg.IdempotencyKey)
	var i IdempotencyKey
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Endpoint,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.UserID,
		&i.Status,
		&i.ResponseStatus,
		&i.ResponseBody,
		&i.ResourceType,
		&i.ResourcePublicID,
		&i.RequestID,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getJobByPublicID = `-- name: GetJobByPublicID :one
SELECT id, public_id, organization_id, queue, job_type, payload, status, priority, run_at, attempts, max_attempts, last_error, error_count, dedupe_key, locked_at, locked_by, started_at, completed_at, created_by, created_at, updated_at FROM jobs WHERE public_id = $1
`

func (q *Queries) GetJobByPublicID(ctx context.Context, publicID string) (Job, error) {
	row := q.db.QueryRow(ctx, getJobByPublicID, publicID)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrganizationID,
		&i.Queue,
		&i.JobType,
		&i.Payload,
		&i.Status,
		&i.Priority,
		&i.RunAt,
		&i.Attempts,
		&i.MaxAttempts,
		&i.LastError,
		&i.ErrorCount,
		&i.DedupeKey,
		&i.LockedAt,
		&i.LockedBy,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const heartbeat = `-- name: Heartbeat :one

SELECT 1::int AS ok
`

// ---------------------------------------------------------------------------
// Health
// ---------------------------------------------------------------------------
func (q *Queries) Heartbeat(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, heartbeat)
	var ok int32
	err := row.Scan(&ok)
	return ok, err
}

const insertAuditEvent = `-- name: InsertAuditEvent :one

INSERT INTO audit_events (
    public_id, organization_id, actor_user_id, actor_type, actor_label, action,
    resource_type, resource_id, resource_public_id, operating_unit_id,
    request_id, client_ip, reason, before_state, after_state, metadata, occurred_at
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16, COALESCE($17, now()))
RETURNING id, public_id, occurred_at
`

type InsertAuditEventParams struct {
	PublicID         string
	OrganizationID   *int64
	ActorUserID      *int64
	ActorType        string
	ActorLabel       *string
	Action           string
	ResourceType     string
	ResourceID       *int64
	ResourcePublicID *string
	OperatingUnitID  *int64
	RequestID        *string
	ClientIp         *string
	Reason           *string
	BeforeState      []byte
	AfterState       []byte
	Metadata         []byte
	Column17         interface{}
}

type InsertAuditEventRow struct {
	ID         int64
	PublicID   string
	OccurredAt time.Time
}

// ---------------------------------------------------------------------------
// Audit
// ---------------------------------------------------------------------------
func (q *Queries) InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) (InsertAuditEventRow, error) {
	row := q.db.QueryRow(ctx, insertAuditEvent,
		arg.PublicID,
		arg.OrganizationID,
		arg.ActorUserID,
		arg.ActorType,
		arg.ActorLabel,
		arg.Action,
		arg.ResourceType,
		arg.ResourceID,
		arg.ResourcePublicID,
		arg.OperatingUnitID,
		arg.RequestID,
		arg.ClientIp,
		arg.Reason,
		arg.BeforeState,
		arg.AfterState,
		arg.Metadata,
		arg.Column17,
	)
	var i InsertAuditEventRow
	err := row.Scan(&i.ID, &i.PublicID, &i.OccurredAt)
	return i, err
}

const listAuditEvents = `-- name: ListAuditEvents :many
SELECT a.id, a.public_id, a.organization_id, a.actor_user_id, a.actor_type, a.actor_label, a.action, a.resource_type, a.resource_id, a.resource_public_id, a.operating_unit_id, a.request_id, a.client_ip, a.reason, a.before_state, a.after_state, a.metadata, a.occurred_at, u.email AS actor_email, u.full_name AS actor_name
FROM audit_events a
LEFT JOIN users u ON u.id = a.actor_user_id
WHERE a.organization_id = $1
  AND ($2::text IS NULL OR a.action = $2)
  AND ($3::text IS NULL OR a.resource_type = $3)
  AND ($4::text IS NULL OR a.resource_public_id = $4)
  AND ($5::bigint IS NULL OR a.actor_user_id = $5)
  AND ($6::timestamptz IS NULL OR a.occurred_at >= $6)
  AND ($7::timestamptz IS NULL OR a.occurred_at < $7)
  AND ($8::bigint IS NULL OR a.id < $8)
ORDER BY a.occurred_at DESC, a.id DESC
LIMIT $9
`

type ListAuditEventsParams struct {
	OrganizationID   *int64
	Action           *string
	ResourceType     *string
	ResourcePublicID *string
	ActorUserID      *int64
	OccurredFrom     *time.Time
	OccurredTo       *time.Time
	CursorID         *int64
	RowLimit         int32
}

type ListAuditEventsRow struct {
	ID               int64
	PublicID         string
	OrganizationID   *int64
	ActorUserID      *int64
	ActorType        string
	ActorLabel       *string
	Action           string
	ResourceType     string
	ResourceID       *int64
	ResourcePublicID *string
	OperatingUnitID  *int64
	RequestID        *string
	ClientIp         *string
	Reason           *string
	BeforeState      []byte
	AfterState       []byte
	Metadata         []byte
	OccurredAt       time.Time
	ActorEmail       *string
	ActorName        *string
}

func (q *Queries) ListAuditEvents(ctx context.Context, arg ListAuditEventsParams) ([]ListAuditEventsRow, error) {
	rows, err := q.db.Query(ctx, listAuditEvents,
		arg.OrganizationID,
		arg.Action,
		arg.ResourceType,
		arg.ResourcePublicID,
		arg.ActorUserID,
		arg.OccurredFrom,
		arg.OccurredTo,
		arg.CursorID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuditEventsRow{}
	for rows.Next() {
		var i ListAuditEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.OrganizationID,
			&i.ActorUserID,
			&i.ActorType,
			&i.ActorLabel,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.ResourcePublicID,
			&i.OperatingUnitID,
			&i.RequestID,
			&i.ClientIp,
			&i.Reason,
			&i.BeforeState,
			&i.AfterState,
			&i.Metadata,
			&i.OccurredAt,
			&i.ActorEmail,
			&i.ActorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgeExpiredIdempotencyKeys = `-- name: PurgeExpiredIdempotencyKeys :execrows
DELETE FROM idempotency_keys WHERE expires_at < now()
`

func (q *Queries) PurgeExpiredIdempotencyKeys(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, purgeExpiredIdempotencyKeys)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const releaseStuckJobs = `-- name: ReleaseStuckJobs :execrows
UPDATE jobs
SET status = 'PENDING', locked_at = NULL, locked_by = NULL,
    last_error = 'worker lock expired; job requeued'
WHERE status = 'RUNNING' AND locked_at < now() - make_interval(secs => $1::int)
`

// ReleaseStuckJobs recovers jobs whose worker died mid-execution.
func (q *Queries) ReleaseStuckJobs(ctx context.Context, stuckAfterSeconds int32) (int64, error) {
	result, err := q.db.Exec(ctx, releaseStuckJobs, stuckAfterSeconds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const retryJob = `-- name: RetryJob :one
UPDATE jobs
SET status = CASE WHEN attempts >= max_attempts THEN 'DEAD' ELSE 'PENDING' END,
    run_at = CASE WHEN attempts >= max_attempts THEN run_at ELSE now() + make_interval(secs => $1::int) END,
    last_error = $2,
    error_count = error_count + 1,
    locked_at = NULL,
    locked_by = NULL,
    completed_at = CASE WHEN attempts >= max_attempts THEN now() ELSE NULL END
WHERE id = $3
RETURNING status
`

type RetryJobParams struct {
	BackoffSeconds int32
	LastError      *string
	JobID          int64
}

// RetryJob reschedules a failed attempt, or moves the job to the dead-letter
// state once max_attempts is exhausted.
func (q *Queries) RetryJob(ctx context.Context, arg RetryJobParams) (string, error) {
	row := q.db.QueryRow(ctx, retryJob, arg.BackoffSeconds, arg.LastError, arg.JobID)
	var status string
	err := row.Scan(&status)
	return status, err
}

const takeOverStaleIdempotencyKey = `-- name: TakeOverStaleIdempotencyKey :one
UPDATE idempotency_keys
SET created_at = now(), request_id = $1, user_id = $2
WHERE organization_id = $3
  AND endpoint = $4
  AND idempotency_key = $5
  AND status = 'IN_PROGRESS'
  AND created_at < now() - make_interval(secs => $6::int)
RETURNING id, organization_id, endpoint, idempotency_key, request_hash, user_id, status, response_status, response_body, resource_type, resource_public_id, request_id, created_at, completed_at, expires_at
`

type TakeOverStaleIdempotencyKeyParams struct {
	RequestID         *string
	UserID            *int64
	OrganizationID    int64
	Endpoint          string
	IdempotencyKey    string
	StaleAfterSeconds int32
}

// TakeOverStaleIdempotencyKey reclaims a reservation abandoned by a crashed
// process.
//
// This is only safe because the completion write happens inside the same
// transaction as the business work: if a key is still IN_PROGRESS, the work it
// guarded provably did not commit, so re-running it cannot duplicate anything.
func (q *Queries) TakeOverStaleIdempotencyKey(ctx context.Context, arg TakeOverStaleIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, takeOverStaleIdempotencyKey,
		arg.RequestID,
		arg.UserID,
		arg.OrganizationID,
		arg.Endpoint,
		arg.IdempotencyKey,
		arg.StaleAfterSeconds,
	)
	var i IdempotencyKey
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Endpoint,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.UserID,
		&i.Status,
		&i.ResponseStatus,
		&i.ResponseBody,
		&i.ResourceType,
		&i.ResourcePublicID,
		&i.RequestID,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.ExpiresAt,
	)
	return i, err
}
