// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pod_tracking.sql

package dbgen

import (
	"context"
	"net/netip"
	"time"
)

const createPODArtifact = `-- name: CreatePODArtifact :one
INSERT INTO pod_artifacts (
    public_id, organization_id, proof_of_delivery_id, stored_object_id,
    artifact_type, sequence, caption, captured_at
) VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, COALESCE($8::timestamptz, now())
)
RETURNING id, public_id, organization_id, proof_of_delivery_id, stored_object_id, artifact_type, sequence, caption, captured_at
`

type CreatePODArtifactParams struct {
	PublicID          string
	OrganizationID    int64
	ProofOfDeliveryID int64
	StoredObjectID    int64
	ArtifactType      string
	Sequence          int32
	Caption           *string
	CapturedAt        *time.Time
}

func (q *Queries) CreatePODArtifact(ctx context.Context, arg CreatePODArtifactParams) (PodArtifact, error) {
	row := q.db.QueryRow(ctx, createPODArtifact,
		arg.PublicID,
		arg.OrganizationID,
		arg.ProofOfDeliveryID,
		arg.StoredObjectID,
		arg.ArtifactType,
		arg.Sequence,
		arg.Caption,
		arg.CapturedAt,
	)
	var i PodArtifact
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrganizationID,
		&i.ProofOfDeliveryID,
		&i.StoredObjectID,
		&i.ArtifactType,
		&i.Sequence,
		&i.Caption,
		&i.CapturedAt,
	)
	return i, err
}

const createProofOfDelivery = `-- name: CreateProofOfDelivery :one

INSERT INTO proof_of_delivery (
    public_id, organization_id, shipment_id, delivery_attempt_id, pod_type,
    recipient_name, recipient_relationship, recipient_phone,
    recipient_id_type, recipient_id_masked,
    otp_verified, signature_captured, photo_captured,
    delivered_at, delivered_by_user_id, operating_unit_id,
    latitude, longitude, location_accuracy_m, device_id, device_model, remarks, metadata
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22,$23)
RETURNING id, public_id, organization_id, shipment_id, delivery_attempt_id, pod_type, recipient_name, recipient_relationship, recipient_phone, recipient_id_type, recipient_id_masked, otp_verified, signature_captured, photo_captured, delivered_at, recorded_at, delivered_by_user_id, operating_unit_id, latitude, longitude, location_accuracy_m, device_id, device_model, remarks, metadata
`

type CreateProofOfDeliveryParams struct {
	PublicID              string
	OrganizationID        int64
	ShipmentID            int64
	DeliveryAttemptID     *int64
	PodType               string
	RecipientName         string
	RecipientRelationship string
	RecipientPhone        *string
	RecipientIDType       *string
	RecipientIDMasked     *string
	OtpVerified           bool
	SignatureCaptured     bool
	PhotoCaptured         bool
	DeliveredAt           time.Time
	DeliveredByUserID     *int64
	OperatingUnitID       *int64
	Latitude              *float64
	Longitude             *float64
	LocationAccuracyM     *int32
	DeviceID              *string
	DeviceModel           *string
	Remarks               *string
	Metadata              []byte
}

// ---------------------------------------------------------------------------
// Proof of delivery
// ---------------------------------------------------------------------------
func (q *Queries) CreateProofOfDelivery(ctx context.Context, arg CreateProofOfDeliveryParams) (ProofOfDelivery, error) {
	row := q.db.QueryRow(ctx, createProofOfDelivery,
		arg.PublicID,
		arg.OrganizationID,
		arg.ShipmentID,
		arg.DeliveryAttemptID,
		arg.PodType,
		arg.RecipientName,
		arg.RecipientRelationship,
		arg.RecipientPhone,
		arg.RecipientIDType,
		arg.RecipientIDMasked,
		arg.OtpVerified,
		arg.SignatureCaptured,
		arg.PhotoCaptured,
		arg.DeliveredAt,
		arg.DeliveredByUserID,
		arg.OperatingUnitID,
		arg.Latitude,
		arg.Longitude,
		arg.LocationAccuracyM,
		arg.DeviceID,
		arg.DeviceModel,
		arg.Remarks,
		arg.Metadata,
	)
	var i ProofOfDelivery
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrganizationID,
		&i.ShipmentID,
		&i.DeliveryAttemptID,
		&i.PodType,
		&i.RecipientName,
		&i.RecipientRelationship,
		&i.RecipientPhone,
		&i.RecipientIDType,
		&i.RecipientIDMasked,
		&i.OtpVerified,
		&i.SignatureCaptured,
		&i.PhotoCaptured,
		&i.DeliveredAt,
		&i.RecordedAt,
		&i.DeliveredByUserID,
		&i.OperatingUnitID,
		&i.Latitude,
		&i.Longitude,
		&i.LocationAccuracyM,
		&i.DeviceID,
		&i.DeviceModel,
		&i.Remarks,
		&i.Metadata,
	)
	return i, err
}

const createStoredObject = `-- name: CreateStoredObject :one

INSERT INTO stored_objects (
    public_id, organization_id, object_key, bucket, purpose, mime_type, size_bytes,
    checksum_sha256, original_filename, uploaded_by_user_id, retention_until, metadata
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12)
RETURNING id, public_id, organization_id, object_key, bucket, purpose, mime_type, size_bytes, checksum_sha256, original_filename, uploaded_by_user_id, uploaded_at, is_public, retention_until, deleted_at, metadata
`

type CreateStoredObjectParams struct {
	PublicID         string
	OrganizationID   int64
	ObjectKey        string
	Bucket           string
	Purpose          string
	MimeType         string
	SizeBytes        int64
	ChecksumSha256   []byte
	OriginalFilename *string
	UploadedByUserID *int64
	RetentionUntil   *time.Time
	Metadata         []byte
}

// Proof of delivery (M19), object storage and public tracking (M20).
func (q *Queries) CreateStoredObject(ctx context.Context, arg CreateStoredObjectParams) (StoredObject, error) {
	row := q.db.QueryRow(ctx, createStoredObject,
		arg.PublicID,
		arg.OrganizationID,
		arg.ObjectKey,
		arg.Bucket,
		arg.Purpose,
		arg.MimeType,
		arg.SizeBytes,
		arg.ChecksumSha256,
		arg.OriginalFilename,
		arg.UploadedByUserID,
		arg.RetentionUntil,
		arg.Metadata,
	)
	var i StoredObject
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrganizationID,
		&i.ObjectKey,
		&i.Bucket,
		&i.Purpose,
		&i.MimeType,
		&i.SizeBytes,
		&i.ChecksumSha256,
		&i.OriginalFilename,
		&i.UploadedByUserID,
		&i.UploadedAt,
		&i.IsPublic,
		&i.RetentionUntil,
		&i.DeletedAt,
		&i.Metadata,
	)
	return i, err
}

const getProofOfDelivery = `-- name: GetProofOfDelivery :one
SELECT p.id, p.public_id, p.organization_id, p.shipment_id, p.delivery_attempt_id, p.pod_type, p.recipient_name, p.recipient_relationship, p.recipient_phone, p.recipient_id_type, p.recipient_id_masked, p.otp_verified, p.signature_captured, p.photo_captured, p.delivered_at, p.recorded_at, p.delivered_by_user_id, p.operating_unit_id, p.latitude, p.longitude, p.location_accuracy_m, p.device_id, p.device_model, p.remarks, p.metadata, s.public_id AS shipment_public_id, s.awb, s.current_status,
       s.customer_id, s.destination_branch_id, s.origin_branch_id, s.booking_unit_id,
       u.public_id AS delivered_by_public_id, u.full_name AS delivered_by_name,
       ou.code AS unit_code, ou.name AS unit_name
FROM proof_of_delivery p
JOIN shipments s ON s.id = p.shipment_id
LEFT JOIN users u ON u.id = p.delivered_by_user_id
LEFT JOIN operating_units ou ON ou.id = p.operating_unit_id
WHERE p.public_id = $1 AND p.organization_id = $2
`

type GetProofOfDeliveryParams struct {
	PublicID       string
	OrganizationID int64
}

type GetProofOfDeliveryRow struct {
	ID                    int64
	PublicID              string
	OrganizationID        int64
	ShipmentID            int64
	DeliveryAttemptID     *int64
	PodType               string
	RecipientName         string
	RecipientRelationship string
	RecipientPhone        *string
	RecipientIDType       *string
	RecipientIDMasked     *string
	OtpVerified           bool
	SignatureCaptured     bool
	PhotoCaptured         bool
	DeliveredAt           time.Time
	RecordedAt            time.Time
	DeliveredByUserID     *int64
	OperatingUnitID       *int64
	Latitude              *float64
	Longitude             *float64
	LocationAccuracyM     *int32
	DeviceID              *string
	DeviceModel           *string
	Remarks               *string
	Metadata              []byte
	ShipmentPublicID      string
	Awb                   string
	CurrentStatus         string
	CustomerID            int64
	DestinationBranchID   *int64
	OriginBranchID        *int64
	BookingUnitID         *int64
	DeliveredByPublicID   *string
	DeliveredByName       *string
	UnitCode              *string
	UnitName              *string
}

func (q *Queries) GetProofOfDelivery(ctx context.Context, arg GetProofOfDeliveryParams) (GetProofOfDeliveryRow, error) {
	row := q.db.QueryRow(ctx, getProofOfDelivery, arg.PublicID, arg.OrganizationID)
	var i GetProofOfDeliveryRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrganizationID,
		&i.ShipmentID,
		&i.DeliveryAttemptID,
		&i.PodType,
		&i.RecipientName,
		&i.RecipientRelationship,
		&i.RecipientPhone,
		&i.RecipientIDType,
		&i.RecipientIDMasked,
		&i.OtpVerified,
		&i.SignatureCaptured,
		&i.PhotoCaptured,
		&i.DeliveredAt,
		&i.RecordedAt,
		&i.DeliveredByUserID,
		&i.OperatingUnitID,
		&i.Latitude,
		&i.Longitude,
		&i.LocationAccuracyM,
		&i.DeviceID,
		&i.DeviceModel,
		&i.Remarks,
		&i.Metadata,
		&i.ShipmentPublicID,
		&i.Awb,
		&i.CurrentStatus,
		&i.CustomerID,
		&i.DestinationBranchID,
		&i.OriginBranchID,
		&i.BookingUnitID,
		&i.DeliveredByPublicID,
		&i.DeliveredByName,
		&i.UnitCode,
		&i.UnitName,
	)
	return i, err
}

const getProofOfDeliveryForShipment = `-- name: GetProofOfDeliveryForShipment :one
SELECT p.id, p.public_id, p.organization_id, p.shipment_id, p.delivery_attempt_id, p.pod_type, p.recipient_name, p.recipient_relationship, p.recipient_phone, p.recipient_id_type, p.recipient_id_masked, p.otp_verified, p.signature_captured, p.photo_captured, p.delivered_at, p.recorded_at, p.delivered_by_user_id, p.operating_unit_id, p.latitude, p.longitude, p.location_accuracy_m, p.device_id, p.device_model, p.remarks, p.metadata, u.full_name AS delivered_by_name, ou.code AS unit_code
FROM proof_of_delivery p
LEFT JOIN users u ON u.id = p.delivered_by_user_id
LEFT JOIN operating_units ou ON ou.id = p.operating_unit_id
WHERE p.shipment_id = $1 AND p.pod_type = $2
`

type GetProofOfDeliveryForShipmentParams struct {
	ShipmentID int64
	PodType    string
}

type GetProofOfDeliveryForShipmentRow struct {
	ID                    int64
	PublicID              string
	OrganizationID        int64
	ShipmentID            int64
	DeliveryAttemptID     *int64
	PodType               string
	RecipientName         string
	RecipientRelationship string
	RecipientPhone        *string
	RecipientIDType       *string
	RecipientIDMasked     *string
	OtpVerified           bool
	SignatureCaptured     bool
	PhotoCaptured         bool
	DeliveredAt           time.Time
	RecordedAt            time.Time
	DeliveredByUserID     *int64
	OperatingUnitID       *int64
	Latitude              *float64
	Longitude             *float64
	LocationAccuracyM     *int32
	DeviceID              *string
	DeviceModel           *string
	Remarks               *string
	Metadata              []byte
	DeliveredByName       *string
	UnitCode              *string
}

func (q *Queries) GetProofOfDeliveryForShipment(ctx context.Context, arg GetProofOfDeliveryForShipmentParams) (GetProofOfDeliveryForShipmentRow, error) {
	row := q.db.QueryRow(ctx, getProofOfDeliveryForShipment, arg.ShipmentID, arg.PodType)
	var i GetProofOfDeliveryForShipmentRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrganizationID,
		&i.ShipmentID,
		&i.DeliveryAttemptID,
		&i.PodType,
		&i.RecipientName,
		&i.RecipientRelationship,
		&i.RecipientPhone,
		&i.RecipientIDType,
		&i.RecipientIDMasked,
		&i.OtpVerified,
		&i.SignatureCaptured,
		&i.PhotoCaptured,
		&i.DeliveredAt,
		&i.RecordedAt,
		&i.DeliveredByUserID,
		&i.OperatingUnitID,
		&i.Latitude,
		&i.Longitude,
		&i.LocationAccuracyM,
		&i.DeviceID,
		&i.DeviceModel,
		&i.Remarks,
		&i.Metadata,
		&i.DeliveredByName,
		&i.UnitCode,
	)
	return i, err
}

const getPublicTrackingShipment = `-- name: GetPublicTrackingShipment :one

SELECT s.awb,
       s.current_status,
       s.status_changed_at,
       s.piece_count,
       s.promised_delivery_at,
       s.booked_at,
       s.delivered_at,
       s.movement_direction,
       s.cod_amount_minor,
       s.currency,
       s.payment_mode,
       s.route_definition_id,
       sv.name AS service_name,
       origin_unit.name AS origin_unit_name,
       dest_unit.name AS destination_unit_name,
       -- City-level only: a street address must not be readable from an AWB.
       origin_city.name AS origin_city,
       dest_city.name AS destination_city,
       s.origin_pincode,
       s.destination_pincode,
       s.id AS shipment_id,
       s.organization_id
FROM shipments s
JOIN courier_services sv ON sv.id = s.courier_service_id
LEFT JOIN operating_units origin_unit ON origin_unit.id = s.origin_branch_id
LEFT JOIN operating_units dest_unit ON dest_unit.id = s.destination_branch_id
LEFT JOIN countries ctry ON ctry.iso2 = 'NG'
LEFT JOIN pincodes op ON op.code = s.origin_pincode AND op.country_id = ctry.id
LEFT JOIN cities origin_city ON origin_city.id = op.city_id
LEFT JOIN pincodes dp ON dp.code = s.destination_pincode AND dp.country_id = ctry.id
LEFT JOIN cities dest_city ON dest_city.id = dp.city_id
WHERE s.awb = $1
`

type GetPublicTrackingShipmentRow struct {
	Awb                 string
	CurrentStatus       string
	StatusChangedAt     time.Time
	PieceCount          int32
	PromisedDeliveryAt  *time.Time
	BookedAt            time.Time
	DeliveredAt         *time.Time
	MovementDirection   string
	CodAmountMinor      int64
	Currency            string
	PaymentMode         string
	RouteDefinitionID   *int64
	ServiceName         string
	OriginUnitName      *string
	DestinationUnitName *string
	OriginCity          *string
	DestinationCity     *string
	OriginPincode       string
	DestinationPincode  string
	ShipmentID          int64
	OrganizationID      int64
}

// ---------------------------------------------------------------------------
// Public tracking (M20)
// ---------------------------------------------------------------------------
// Deliberately narrow. No internal public ids, no customer identity, no
// financial detail beyond the COD amount the recipient must have ready, no
// operating unit ids. Everything selected here is safe to show anonymously.
// City names come through the PIN code, which is keyed by country. The
// platform is single-country per deployment (§M03), so the join resolves the
// country by its ISO code rather than assuming an id.
func (q *Queries) GetPublicTrackingShipment(ctx context.Context, awb string) (GetPublicTrackingShipmentRow, error) {
	row := q.db.QueryRow(ctx, getPublicTrackingShipment, awb)
	var i GetPublicTrackingShipmentRow
	err := row.Scan(
		&i.Awb,
		&i.CurrentStatus,
		&i.StatusChangedAt,
		&i.PieceCount,
		&i.PromisedDeliveryAt,
		&i.BookedAt,
		&i.DeliveredAt,
		&i.MovementDirection,
		&i.CodAmountMinor,
		&i.Currency,
		&i.PaymentMode,
		&i.RouteDefinitionID,
		&i.ServiceName,
		&i.OriginUnitName,
		&i.DestinationUnitName,
		&i.OriginCity,
		&i.DestinationCity,
		&i.OriginPincode,
		&i.DestinationPincode,
		&i.ShipmentID,
		&i.OrganizationID,
	)
	return i, err
}

const getShipmentDeliveryEstimate = `-- name: GetShipmentDeliveryEstimate :one
SELECT s.promised_delivery_at,
       n.next_attempt_at AS ndr_next_attempt_at,
       n.current_action AS ndr_action
FROM shipments s
LEFT JOIN ndr_cases n ON n.shipment_id = s.id
     AND n.status IN ('OPEN','PENDING_CUSTOMER','SCHEDULED','ESCALATED')
WHERE s.id = $1
`

type GetShipmentDeliveryEstimateRow struct {
	PromisedDeliveryAt *time.Time
	NdrNextAttemptAt   *time.Time
	NdrAction          *string
}

// Promised date plus whatever the NDR workflow has rescheduled to, so public
// tracking can show a realistic date rather than a stale promise.
func (q *Queries) GetShipmentDeliveryEstimate(ctx context.Context, shipmentID int64) (GetShipmentDeliveryEstimateRow, error) {
	row := q.db.QueryRow(ctx, getShipmentDeliveryEstimate, shipmentID)
	var i GetShipmentDeliveryEstimateRow
	err := row.Scan(&i.PromisedDeliveryAt, &i.NdrNextAttemptAt, &i.NdrAction)
	return i, err
}

const getStoredObjectByChecksum = `-- name: GetStoredObjectByChecksum :one
SELECT id, public_id, organization_id, object_key, bucket, purpose, mime_type, size_bytes, checksum_sha256, original_filename, uploaded_by_user_id, uploaded_at, is_public, retention_until, deleted_at, metadata FROM stored_objects
WHERE organization_id = $1
  AND checksum_sha256 = $2
  AND purpose = $3
  AND deleted_at IS NULL
LIMIT 1
`

type GetStoredObjectByChecksumParams struct {
	OrganizationID int64
	ChecksumSha256 []byte
	Purpose        string
}

// Re-uploading identical bytes reuses the stored object instead of paying for
// a second copy. Scoped to the tenant so no cross-tenant inference is possible.
func (q *Queries) GetStoredObjectByChecksum(ctx context.Context, arg GetStoredObjectByChecksumParams) (StoredObject, error) {
	row := q.db.QueryRow(ctx, getStoredObjectByChecksum, arg.OrganizationID, arg.ChecksumSha256, arg.Purpose)
	var i StoredObject
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrganizationID,
		&i.ObjectKey,
		&i.Bucket,
		&i.Purpose,
		&i.MimeType,
		&i.SizeBytes,
		&i.ChecksumSha256,
		&i.OriginalFilename,
		&i.UploadedByUserID,
		&i.UploadedAt,
		&i.IsPublic,
		&i.RetentionUntil,
		&i.DeletedAt,
		&i.Metadata,
	)
	return i, err
}

const getStoredObjectByPublicID = `-- name: GetStoredObjectByPublicID :one
SELECT id, public_id, organization_id, object_key, bucket, purpose, mime_type, size_bytes, checksum_sha256, original_filename, uploaded_by_user_id, uploaded_at, is_public, retention_until, deleted_at, metadata FROM stored_objects
WHERE public_id = $1 AND organization_id = $2
  AND deleted_at IS NULL
`

type GetStoredObjectByPublicIDParams struct {
	PublicID       string
	OrganizationID int64
}

func (q *Queries) GetStoredObjectByPublicID(ctx context.Context, arg GetStoredObjectByPublicIDParams) (StoredObject, error) {
	row := q.db.QueryRow(ctx, getStoredObjectByPublicID, arg.PublicID, arg.OrganizationID)
	var i StoredObject
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrganizationID,
		&i.ObjectKey,
		&i.Bucket,
		&i.Purpose,
		&i.MimeType,
		&i.SizeBytes,
		&i.ChecksumSha256,
		&i.OriginalFilename,
		&i.UploadedByUserID,
		&i.UploadedAt,
		&i.IsPublic,
		&i.RetentionUntil,
		&i.DeletedAt,
		&i.Metadata,
	)
	return i, err
}

const listExpiredObjects = `-- name: ListExpiredObjects :many
SELECT id, public_id, bucket, object_key FROM stored_objects
WHERE retention_until IS NOT NULL AND retention_until < now() AND deleted_at IS NULL
ORDER BY retention_until
LIMIT $1
`

type ListExpiredObjectsRow struct {
	ID        int64
	PublicID  string
	Bucket    string
	ObjectKey string
}

func (q *Queries) ListExpiredObjects(ctx context.Context, pageSize int32) ([]ListExpiredObjectsRow, error) {
	rows, err := q.db.Query(ctx, listExpiredObjects, pageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExpiredObjectsRow{}
	for rows.Next() {
		var i ListExpiredObjectsRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.Bucket,
			&i.ObjectKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPODArtifacts = `-- name: ListPODArtifacts :many
SELECT pa.public_id, pa.artifact_type, pa.sequence, pa.caption, pa.captured_at,
       so.id AS object_id, so.public_id AS object_public_id, so.mime_type, so.size_bytes,
       so.checksum_sha256, so.object_key, so.bucket
FROM pod_artifacts pa
JOIN stored_objects so ON so.id = pa.stored_object_id
WHERE pa.proof_of_delivery_id = $1
  AND so.deleted_at IS NULL
ORDER BY pa.artifact_type, pa.sequence
`

type ListPODArtifactsRow struct {
	PublicID       string
	ArtifactType   string
	Sequence       int32
	Caption        *string
	CapturedAt     time.Time
	ObjectID       int64
	ObjectPublicID string
	MimeType       string
	SizeBytes      int64
	ChecksumSha256 []byte
	ObjectKey      string
	Bucket         string
}

func (q *Queries) ListPODArtifacts(ctx context.Context, proofOfDeliveryID int64) ([]ListPODArtifactsRow, error) {
	rows, err := q.db.Query(ctx, listPODArtifacts, proofOfDeliveryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPODArtifactsRow{}
	for rows.Next() {
		var i ListPODArtifactsRow
		if err := rows.Scan(
			&i.PublicID,
			&i.ArtifactType,
			&i.Sequence,
			&i.Caption,
			&i.CapturedAt,
			&i.ObjectID,
			&i.ObjectPublicID,
			&i.MimeType,
			&i.SizeBytes,
			&i.ChecksumSha256,
			&i.ObjectKey,
			&i.Bucket,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicTrackingEvents = `-- name: ListPublicTrackingEvents :many
SELECT e.event_type,
       e.to_status,
       e.from_status,
       e.occurred_at,
       e.description,
       COALESCE(e.location_pincode, ou.pincode, '') AS location_pincode,
       ou.name AS location_name,
       ou.unit_type AS location_type,
       city.name AS location_city
FROM shipment_events e
LEFT JOIN operating_units ou ON ou.id = e.operating_unit_id
LEFT JOIN countries ctry ON ctry.iso2 = 'NG'
LEFT JOIN pincodes p ON p.code = COALESCE(e.location_pincode, ou.pincode) AND p.country_id = ctry.id
LEFT JOIN cities city ON city.id = p.city_id
WHERE e.shipment_id = $1
  -- Status changes and milestones only; internal remarks never surface.
  AND e.event_type <> 'REMARK'
ORDER BY e.occurred_at ASC, e.sequence ASC
LIMIT $2
`

type ListPublicTrackingEventsParams struct {
	ShipmentID int64
	PageSize   int32
}

type ListPublicTrackingEventsRow struct {
	EventType       string
	ToStatus        string
	FromStatus      *string
	OccurredAt      time.Time
	Description     string
	LocationPincode string
	LocationName    *string
	LocationType    *string
	LocationCity    *string
}

// The customer-facing timeline. internal_remarks, actor identity and reason
// codes are never selected; the facility name is joined but the caller decides
// whether to show it based on the milestone's show_location flag.
func (q *Queries) ListPublicTrackingEvents(ctx context.Context, arg ListPublicTrackingEventsParams) ([]ListPublicTrackingEventsRow, error) {
	rows, err := q.db.Query(ctx, listPublicTrackingEvents, arg.ShipmentID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublicTrackingEventsRow{}
	for rows.Next() {
		var i ListPublicTrackingEventsRow
		if err := rows.Scan(
			&i.EventType,
			&i.ToStatus,
			&i.FromStatus,
			&i.OccurredAt,
			&i.Description,
			&i.LocationPincode,
			&i.LocationName,
			&i.LocationType,
			&i.LocationCity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrackingMilestones = `-- name: ListTrackingMilestones :many
SELECT DISTINCT ON (shipment_status)
       shipment_status, milestone_code, public_title, public_description,
       show_location, display_order
FROM tracking_milestones
WHERE is_active = true
  AND (organization_id = $1 OR organization_id IS NULL)
ORDER BY shipment_status, organization_id NULLS LAST
`

type ListTrackingMilestonesRow struct {
	ShipmentStatus    string
	MilestoneCode     string
	PublicTitle       string
	PublicDescription string
	ShowLocation      bool
	DisplayOrder      int32
}

// Tenant overrides win over the platform defaults. DISTINCT ON picks the tenant
// row when both exist, which keeps the resolution in SQL rather than in Go.
func (q *Queries) ListTrackingMilestones(ctx context.Context, organizationID *int64) ([]ListTrackingMilestonesRow, error) {
	rows, err := q.db.Query(ctx, listTrackingMilestones, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTrackingMilestonesRow{}
	for rows.Next() {
		var i ListTrackingMilestonesRow
		if err := rows.Scan(
			&i.ShipmentStatus,
			&i.MilestoneCode,
			&i.PublicTitle,
			&i.PublicDescription,
			&i.ShowLocation,
			&i.DisplayOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextPODArtifactSequence = `-- name: NextPODArtifactSequence :one
SELECT COALESCE(max(sequence), 0)::int + 1 AS next_sequence FROM pod_artifacts
WHERE proof_of_delivery_id = $1
  AND artifact_type = $2
`

type NextPODArtifactSequenceParams struct {
	ProofOfDeliveryID int64
	ArtifactType      string
}

func (q *Queries) NextPODArtifactSequence(ctx context.Context, arg NextPODArtifactSequenceParams) (int32, error) {
	row := q.db.QueryRow(ctx, nextPODArtifactSequence, arg.ProofOfDeliveryID, arg.ArtifactType)
	var next_sequence int32
	err := row.Scan(&next_sequence)
	return next_sequence, err
}

const recordObjectAccess = `-- name: RecordObjectAccess :exec
INSERT INTO object_access_log (
    organization_id, stored_object_id, accessed_by_user_id, access_type,
    request_id, ip_address, expires_at
) VALUES ($1,$2,$3,$4,$5,$6,$7)
`

type RecordObjectAccessParams struct {
	OrganizationID   int64
	StoredObjectID   int64
	AccessedByUserID *int64
	AccessType       string
	RequestID        *string
	IpAddress        *netip.Addr
	ExpiresAt        *time.Time
}

func (q *Queries) RecordObjectAccess(ctx context.Context, arg RecordObjectAccessParams) error {
	_, err := q.db.Exec(ctx, recordObjectAccess,
		arg.OrganizationID,
		arg.StoredObjectID,
		arg.AccessedByUserID,
		arg.AccessType,
		arg.RequestID,
		arg.IpAddress,
		arg.ExpiresAt,
	)
	return err
}

const softDeleteStoredObject = `-- name: SoftDeleteStoredObject :one
UPDATE stored_objects SET deleted_at = now()
WHERE id = $1 AND organization_id = $2
RETURNING id, public_id, organization_id, object_key, bucket, purpose, mime_type, size_bytes, checksum_sha256, original_filename, uploaded_by_user_id, uploaded_at, is_public, retention_until, deleted_at, metadata
`

type SoftDeleteStoredObjectParams struct {
	ID             int64
	OrganizationID int64
}

func (q *Queries) SoftDeleteStoredObject(ctx context.Context, arg SoftDeleteStoredObjectParams) (StoredObject, error) {
	row := q.db.QueryRow(ctx, softDeleteStoredObject, arg.ID, arg.OrganizationID)
	var i StoredObject
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrganizationID,
		&i.ObjectKey,
		&i.Bucket,
		&i.Purpose,
		&i.MimeType,
		&i.SizeBytes,
		&i.ChecksumSha256,
		&i.OriginalFilename,
		&i.UploadedByUserID,
		&i.UploadedAt,
		&i.IsPublic,
		&i.RetentionUntil,
		&i.DeletedAt,
		&i.Metadata,
	)
	return i, err
}

const upsertTrackingMilestone = `-- name: UpsertTrackingMilestone :one
INSERT INTO tracking_milestones (
    organization_id, shipment_status, milestone_code, public_title,
    public_description, show_location, display_order, is_active
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8)
ON CONFLICT (organization_id, shipment_status)
DO UPDATE SET milestone_code = EXCLUDED.milestone_code,
              public_title = EXCLUDED.public_title,
              public_description = EXCLUDED.public_description,
              show_location = EXCLUDED.show_location,
              display_order = EXCLUDED.display_order,
              is_active = EXCLUDED.is_active
RETURNING id, organization_id, shipment_status, milestone_code, public_title, public_description, show_location, display_order, is_active
`

type UpsertTrackingMilestoneParams struct {
	OrganizationID    *int64
	ShipmentStatus    string
	MilestoneCode     string
	PublicTitle       string
	PublicDescription string
	ShowLocation      bool
	DisplayOrder      int32
	IsActive          bool
}

func (q *Queries) UpsertTrackingMilestone(ctx context.Context, arg UpsertTrackingMilestoneParams) (TrackingMilestone, error) {
	row := q.db.QueryRow(ctx, upsertTrackingMilestone,
		arg.OrganizationID,
		arg.ShipmentStatus,
		arg.MilestoneCode,
		arg.PublicTitle,
		arg.PublicDescription,
		arg.ShowLocation,
		arg.DisplayOrder,
		arg.IsActive,
	)
	var i TrackingMilestone
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ShipmentStatus,
		&i.MilestoneCode,
		&i.PublicTitle,
		&i.PublicDescription,
		&i.ShowLocation,
		&i.DisplayOrder,
		&i.IsActive,
	)
	return i, err
}
