// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: product.sql

package dbgen

import (
	"context"
	"time"
)

const countCourierServiceReferences = `-- name: CountCourierServiceReferences :one
SELECT
    (SELECT count(*) FROM shipments sh WHERE sh.courier_service_id = $1) AS shipment_count,
    (SELECT count(*) FROM zone_rates zr WHERE zr.courier_service_id = $1) AS rate_count,
    (SELECT count(*) FROM route_definitions rd
      WHERE rd.courier_service_id = $1 AND rd.status = 'ACTIVE') AS route_count
`

type CountCourierServiceReferencesRow struct {
	ShipmentCount int64
	RateCount     int64
	RouteCount    int64
}

func (q *Queries) CountCourierServiceReferences(ctx context.Context, serviceID int64) (CountCourierServiceReferencesRow, error) {
	row := q.db.QueryRow(ctx, countCourierServiceReferences, serviceID)
	var i CountCourierServiceReferencesRow
	err := row.Scan(&i.ShipmentCount, &i.RateCount, &i.RouteCount)
	return i, err
}

const createCourierService = `-- name: CreateCourierService :one

INSERT INTO courier_services (
    public_id, organization_id, code, name, description, mode,
    min_weight_grams, max_weight_grams, max_length_mm, max_width_mm, max_height_mm,
    max_dimension_sum_mm, volumetric_divisor, weight_rounding_grams,
    cod_allowed, max_cod_amount_minor, insurance_allowed, max_declared_value_minor,
    sla_transit_hours, sla_rules, cutoff_time, effective_from, effective_to, sort_order, created_by
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22,$23,$24,$25)
RETURNING id, public_id, organization_id, code, name, description, mode, min_weight_grams, max_weight_grams, max_length_mm, max_width_mm, max_height_mm, max_dimension_sum_mm, volumetric_divisor, weight_rounding_grams, cod_allowed, max_cod_amount_minor, insurance_allowed, max_declared_value_minor, sla_transit_hours, sla_rules, cutoff_time, status, effective_from, effective_to, sort_order, created_by, created_at, updated_at, version
`

type CreateCourierServiceParams struct {
	PublicID              string
	OrganizationID        int64
	Code                  string
	Name                  string
	Description           string
	Mode                  string
	MinWeightGrams        int32
	MaxWeightGrams        int32
	MaxLengthMm           *int32
	MaxWidthMm            *int32
	MaxHeightMm           *int32
	MaxDimensionSumMm     *int32
	VolumetricDivisor     int32
	WeightRoundingGrams   int32
	CodAllowed            bool
	MaxCodAmountMinor     *int64
	InsuranceAllowed      bool
	MaxDeclaredValueMinor *int64
	SlaTransitHours       int32
	SlaRules              []byte
	CutoffTime            *string
	EffectiveFrom         time.Time
	EffectiveTo           *time.Time
	SortOrder             int32
	CreatedBy             *int64
}

// Courier product/service queries (M05).
func (q *Queries) CreateCourierService(ctx context.Context, arg CreateCourierServiceParams) (CourierService, error) {
	row := q.db.QueryRow(ctx, createCourierService,
		arg.PublicID,
		arg.OrganizationID,
		arg.Code,
		arg.Name,
		arg.Description,
		arg.Mode,
		arg.MinWeightGrams,
		arg.MaxWeightGrams,
		arg.MaxLengthMm,
		arg.MaxWidthMm,
		arg.MaxHeightMm,
		arg.MaxDimensionSumMm,
		arg.VolumetricDivisor,
		arg.WeightRoundingGrams,
		arg.CodAllowed,
		arg.MaxCodAmountMinor,
		arg.InsuranceAllowed,
		arg.MaxDeclaredValueMinor,
		arg.SlaTransitHours,
		arg.SlaRules,
		arg.CutoffTime,
		arg.EffectiveFrom,
		arg.EffectiveTo,
		arg.SortOrder,
		arg.CreatedBy,
	)
	var i CourierService
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrganizationID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.Mode,
		&i.MinWeightGrams,
		&i.MaxWeightGrams,
		&i.MaxLengthMm,
		&i.MaxWidthMm,
		&i.MaxHeightMm,
		&i.MaxDimensionSumMm,
		&i.VolumetricDivisor,
		&i.WeightRoundingGrams,
		&i.CodAllowed,
		&i.MaxCodAmountMinor,
		&i.InsuranceAllowed,
		&i.MaxDeclaredValueMinor,
		&i.SlaTransitHours,
		&i.SlaRules,
		&i.CutoffTime,
		&i.Status,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.SortOrder,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const deactivateCourierService = `-- name: DeactivateCourierService :one
UPDATE courier_services SET status = 'INACTIVE'
WHERE public_id = $1 AND organization_id = $2
  AND status = 'ACTIVE'
RETURNING id, public_id, organization_id, code, name, description, mode, min_weight_grams, max_weight_grams, max_length_mm, max_width_mm, max_height_mm, max_dimension_sum_mm, volumetric_divisor, weight_rounding_grams, cod_allowed, max_cod_amount_minor, insurance_allowed, max_declared_value_minor, sla_transit_hours, sla_rules, cutoff_time, status, effective_from, effective_to, sort_order, created_by, created_at, updated_at, version
`

type DeactivateCourierServiceParams struct {
	PublicID       string
	OrganizationID int64
}

func (q *Queries) DeactivateCourierService(ctx context.Context, arg DeactivateCourierServiceParams) (CourierService, error) {
	row := q.db.QueryRow(ctx, deactivateCourierService, arg.PublicID, arg.OrganizationID)
	var i CourierService
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrganizationID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.Mode,
		&i.MinWeightGrams,
		&i.MaxWeightGrams,
		&i.MaxLengthMm,
		&i.MaxWidthMm,
		&i.MaxHeightMm,
		&i.MaxDimensionSumMm,
		&i.VolumetricDivisor,
		&i.WeightRoundingGrams,
		&i.CodAllowed,
		&i.MaxCodAmountMinor,
		&i.InsuranceAllowed,
		&i.MaxDeclaredValueMinor,
		&i.SlaTransitHours,
		&i.SlaRules,
		&i.CutoffTime,
		&i.Status,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.SortOrder,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const getActiveCourierServiceByCode = `-- name: GetActiveCourierServiceByCode :one
SELECT id, public_id, organization_id, code, name, description, mode, min_weight_grams, max_weight_grams, max_length_mm, max_width_mm, max_height_mm, max_dimension_sum_mm, volumetric_divisor, weight_rounding_grams, cod_allowed, max_cod_amount_minor, insurance_allowed, max_declared_value_minor, sla_transit_hours, sla_rules, cutoff_time, status, effective_from, effective_to, sort_order, created_by, created_at, updated_at, version FROM courier_services
WHERE organization_id = $1
  AND code = $2
  AND status = 'ACTIVE'
  AND effective_from <= $3::date
  AND (effective_to IS NULL OR effective_to >= $3::date)
`

type GetActiveCourierServiceByCodeParams struct {
	OrganizationID int64
	Code           string
	AsOf           time.Time
}

// GetActiveCourierServiceByCode resolves a product for booking or quoting at a
// point in time, honouring the effective-date window.
func (q *Queries) GetActiveCourierServiceByCode(ctx context.Context, arg GetActiveCourierServiceByCodeParams) (CourierService, error) {
	row := q.db.QueryRow(ctx, getActiveCourierServiceByCode, arg.OrganizationID, arg.Code, arg.AsOf)
	var i CourierService
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrganizationID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.Mode,
		&i.MinWeightGrams,
		&i.MaxWeightGrams,
		&i.MaxLengthMm,
		&i.MaxWidthMm,
		&i.MaxHeightMm,
		&i.MaxDimensionSumMm,
		&i.VolumetricDivisor,
		&i.WeightRoundingGrams,
		&i.CodAllowed,
		&i.MaxCodAmountMinor,
		&i.InsuranceAllowed,
		&i.MaxDeclaredValueMinor,
		&i.SlaTransitHours,
		&i.SlaRules,
		&i.CutoffTime,
		&i.Status,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.SortOrder,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const getCourierServiceByCode = `-- name: GetCourierServiceByCode :one
SELECT id, public_id, organization_id, code, name, description, mode, min_weight_grams, max_weight_grams, max_length_mm, max_width_mm, max_height_mm, max_dimension_sum_mm, volumetric_divisor, weight_rounding_grams, cod_allowed, max_cod_amount_minor, insurance_allowed, max_declared_value_minor, sla_transit_hours, sla_rules, cutoff_time, status, effective_from, effective_to, sort_order, created_by, created_at, updated_at, version FROM courier_services WHERE organization_id = $1 AND code = $2
`

type GetCourierServiceByCodeParams struct {
	OrganizationID int64
	Code           string
}

func (q *Queries) GetCourierServiceByCode(ctx context.Context, arg GetCourierServiceByCodeParams) (CourierService, error) {
	row := q.db.QueryRow(ctx, getCourierServiceByCode, arg.OrganizationID, arg.Code)
	var i CourierService
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrganizationID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.Mode,
		&i.MinWeightGrams,
		&i.MaxWeightGrams,
		&i.MaxLengthMm,
		&i.MaxWidthMm,
		&i.MaxHeightMm,
		&i.MaxDimensionSumMm,
		&i.VolumetricDivisor,
		&i.WeightRoundingGrams,
		&i.CodAllowed,
		&i.MaxCodAmountMinor,
		&i.InsuranceAllowed,
		&i.MaxDeclaredValueMinor,
		&i.SlaTransitHours,
		&i.SlaRules,
		&i.CutoffTime,
		&i.Status,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.SortOrder,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const getCourierServiceByPublicID = `-- name: GetCourierServiceByPublicID :one
SELECT id, public_id, organization_id, code, name, description, mode, min_weight_grams, max_weight_grams, max_length_mm, max_width_mm, max_height_mm, max_dimension_sum_mm, volumetric_divisor, weight_rounding_grams, cod_allowed, max_cod_amount_minor, insurance_allowed, max_declared_value_minor, sla_transit_hours, sla_rules, cutoff_time, status, effective_from, effective_to, sort_order, created_by, created_at, updated_at, version FROM courier_services WHERE public_id = $1 AND organization_id = $2
`

type GetCourierServiceByPublicIDParams struct {
	PublicID       string
	OrganizationID int64
}

func (q *Queries) GetCourierServiceByPublicID(ctx context.Context, arg GetCourierServiceByPublicIDParams) (CourierService, error) {
	row := q.db.QueryRow(ctx, getCourierServiceByPublicID, arg.PublicID, arg.OrganizationID)
	var i CourierService
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrganizationID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.Mode,
		&i.MinWeightGrams,
		&i.MaxWeightGrams,
		&i.MaxLengthMm,
		&i.MaxWidthMm,
		&i.MaxHeightMm,
		&i.MaxDimensionSumMm,
		&i.VolumetricDivisor,
		&i.WeightRoundingGrams,
		&i.CodAllowed,
		&i.MaxCodAmountMinor,
		&i.InsuranceAllowed,
		&i.MaxDeclaredValueMinor,
		&i.SlaTransitHours,
		&i.SlaRules,
		&i.CutoffTime,
		&i.Status,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.SortOrder,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const listCourierServices = `-- name: ListCourierServices :many
SELECT s.id, s.public_id, s.organization_id, s.code, s.name, s.description, s.mode, s.min_weight_grams, s.max_weight_grams, s.max_length_mm, s.max_width_mm, s.max_height_mm, s.max_dimension_sum_mm, s.volumetric_divisor, s.weight_rounding_grams, s.cod_allowed, s.max_cod_amount_minor, s.insurance_allowed, s.max_declared_value_minor, s.sla_transit_hours, s.sla_rules, s.cutoff_time, s.status, s.effective_from, s.effective_to, s.sort_order, s.created_by, s.created_at, s.updated_at, s.version, count(*) OVER () AS total_count
FROM courier_services s
WHERE s.organization_id = $1
  AND ($2::text IS NULL OR s.status = $2)
  AND ($3::text IS NULL OR s.mode = $3)
  AND ($4::boolean IS NULL OR s.cod_allowed = $4)
  AND ($5::text IS NULL
       OR lower(s.name) LIKE '%' || lower($5) || '%'
       OR s.code LIKE upper($5) || '%')
ORDER BY s.sort_order, s.code
LIMIT $7 OFFSET $6
`

type ListCourierServicesParams struct {
	OrganizationID int64
	Status         *string
	Mode           *string
	CodAllowed     *bool
	Search         *string
	RowOffset      int32
	RowLimit       int32
}

type ListCourierServicesRow struct {
	ID                    int64
	PublicID              string
	OrganizationID        int64
	Code                  string
	Name                  string
	Description           string
	Mode                  string
	MinWeightGrams        int32
	MaxWeightGrams        int32
	MaxLengthMm           *int32
	MaxWidthMm            *int32
	MaxHeightMm           *int32
	MaxDimensionSumMm     *int32
	VolumetricDivisor     int32
	WeightRoundingGrams   int32
	CodAllowed            bool
	MaxCodAmountMinor     *int64
	InsuranceAllowed      bool
	MaxDeclaredValueMinor *int64
	SlaTransitHours       int32
	SlaRules              []byte
	CutoffTime            *string
	Status                string
	EffectiveFrom         time.Time
	EffectiveTo           *time.Time
	SortOrder             int32
	CreatedBy             *int64
	CreatedAt             time.Time
	UpdatedAt             time.Time
	Version               int32
	TotalCount            int64
}

func (q *Queries) ListCourierServices(ctx context.Context, arg ListCourierServicesParams) ([]ListCourierServicesRow, error) {
	rows, err := q.db.Query(ctx, listCourierServices,
		arg.OrganizationID,
		arg.Status,
		arg.Mode,
		arg.CodAllowed,
		arg.Search,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCourierServicesRow{}
	for rows.Next() {
		var i ListCourierServicesRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.OrganizationID,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.Mode,
			&i.MinWeightGrams,
			&i.MaxWeightGrams,
			&i.MaxLengthMm,
			&i.MaxWidthMm,
			&i.MaxHeightMm,
			&i.MaxDimensionSumMm,
			&i.VolumetricDivisor,
			&i.WeightRoundingGrams,
			&i.CodAllowed,
			&i.MaxCodAmountMinor,
			&i.InsuranceAllowed,
			&i.MaxDeclaredValueMinor,
			&i.SlaTransitHours,
			&i.SlaRules,
			&i.CutoffTime,
			&i.Status,
			&i.EffectiveFrom,
			&i.EffectiveTo,
			&i.SortOrder,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Version,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCourierService = `-- name: UpdateCourierService :one
UPDATE courier_services
SET name = COALESCE($1, name),
    description = COALESCE($2, description),
    mode = COALESCE($3, mode),
    min_weight_grams = COALESCE($4, min_weight_grams),
    max_weight_grams = COALESCE($5, max_weight_grams),
    max_length_mm = COALESCE($6, max_length_mm),
    max_width_mm = COALESCE($7, max_width_mm),
    max_height_mm = COALESCE($8, max_height_mm),
    max_dimension_sum_mm = COALESCE($9, max_dimension_sum_mm),
    volumetric_divisor = COALESCE($10, volumetric_divisor),
    weight_rounding_grams = COALESCE($11, weight_rounding_grams),
    cod_allowed = COALESCE($12, cod_allowed),
    max_cod_amount_minor = COALESCE($13, max_cod_amount_minor),
    insurance_allowed = COALESCE($14, insurance_allowed),
    max_declared_value_minor = COALESCE($15, max_declared_value_minor),
    sla_transit_hours = COALESCE($16, sla_transit_hours),
    sla_rules = COALESCE($17, sla_rules),
    cutoff_time = COALESCE($18, cutoff_time),
    effective_to = COALESCE($19, effective_to),
    sort_order = COALESCE($20, sort_order),
    status = COALESCE($21, status)
WHERE public_id = $22
  AND organization_id = $23
  AND version = $24
RETURNING id, public_id, organization_id, code, name, description, mode, min_weight_grams, max_weight_grams, max_length_mm, max_width_mm, max_height_mm, max_dimension_sum_mm, volumetric_divisor, weight_rounding_grams, cod_allowed, max_cod_amount_minor, insurance_allowed, max_declared_value_minor, sla_transit_hours, sla_rules, cutoff_time, status, effective_from, effective_to, sort_order, created_by, created_at, updated_at, version
`

type UpdateCourierServiceParams struct {
	Name                  *string
	Description           *string
	Mode                  *string
	MinWeightGrams        *int32
	MaxWeightGrams        *int32
	MaxLengthMm           *int32
	MaxWidthMm            *int32
	MaxHeightMm           *int32
	MaxDimensionSumMm     *int32
	VolumetricDivisor     *int32
	WeightRoundingGrams   *int32
	CodAllowed            *bool
	MaxCodAmountMinor     *int64
	InsuranceAllowed      *bool
	MaxDeclaredValueMinor *int64
	SlaTransitHours       *int32
	SlaRules              []byte
	CutoffTime            *string
	EffectiveTo           *time.Time
	SortOrder             *int32
	Status                *string
	PublicID              string
	OrganizationID        int64
	ExpectedVersion       int32
}

func (q *Queries) UpdateCourierService(ctx context.Context, arg UpdateCourierServiceParams) (CourierService, error) {
	row := q.db.QueryRow(ctx, updateCourierService,
		arg.Name,
		arg.Description,
		arg.Mode,
		arg.MinWeightGrams,
		arg.MaxWeightGrams,
		arg.MaxLengthMm,
		arg.MaxWidthMm,
		arg.MaxHeightMm,
		arg.MaxDimensionSumMm,
		arg.VolumetricDivisor,
		arg.WeightRoundingGrams,
		arg.CodAllowed,
		arg.MaxCodAmountMinor,
		arg.InsuranceAllowed,
		arg.MaxDeclaredValueMinor,
		arg.SlaTransitHours,
		arg.SlaRules,
		arg.CutoffTime,
		arg.EffectiveTo,
		arg.SortOrder,
		arg.Status,
		arg.PublicID,
		arg.OrganizationID,
		arg.ExpectedVersion,
	)
	var i CourierService
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrganizationID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.Mode,
		&i.MinWeightGrams,
		&i.MaxWeightGrams,
		&i.MaxLengthMm,
		&i.MaxWidthMm,
		&i.MaxHeightMm,
		&i.MaxDimensionSumMm,
		&i.VolumetricDivisor,
		&i.WeightRoundingGrams,
		&i.CodAllowed,
		&i.MaxCodAmountMinor,
		&i.InsuranceAllowed,
		&i.MaxDeclaredValueMinor,
		&i.SlaTransitHours,
		&i.SlaRules,
		&i.CutoffTime,
		&i.Status,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.SortOrder,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}
