// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reporting.sql

package dbgen

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelReportRun = `-- name: CancelReportRun :one
UPDATE report_runs
   SET status = 'CANCELLED', completed_at = now()
 WHERE organization_id = $1 AND id = $2 AND status IN ('QUEUED','RUNNING')
RETURNING id, public_id, organization_id, report_type, format, parameters, period_start, period_end, status, row_count, byte_size, object_id, expires_at, started_at, completed_at, error_message, duration_ms, job_id, requested_by, request_id, created_at, updated_at
`

type CancelReportRunParams struct {
	OrganizationID int64
	ID             int64
}

func (q *Queries) CancelReportRun(ctx context.Context, arg CancelReportRunParams) (ReportRun, error) {
	row := q.db.QueryRow(ctx, cancelReportRun, arg.OrganizationID, arg.ID)
	var i ReportRun
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrganizationID,
		&i.ReportType,
		&i.Format,
		&i.Parameters,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.Status,
		&i.RowCount,
		&i.ByteSize,
		&i.ObjectID,
		&i.ExpiresAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ErrorMessage,
		&i.DurationMs,
		&i.JobID,
		&i.RequestedBy,
		&i.RequestID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const completeReportRun = `-- name: CompleteReportRun :one
UPDATE report_runs
   SET status = 'COMPLETED', completed_at = now(),
       object_id = $1, row_count = $2,
       byte_size = $3,
       expires_at = now() + $4::interval,
       duration_ms = (EXTRACT(EPOCH FROM (now() - COALESCE(started_at, now()))) * 1000)::int
 WHERE organization_id = $5 AND id = $6
RETURNING id, public_id, organization_id, report_type, format, parameters, period_start, period_end, status, row_count, byte_size, object_id, expires_at, started_at, completed_at, error_message, duration_ms, job_id, requested_by, request_id, created_at, updated_at
`

type CompleteReportRunParams struct {
	ObjectID       *int64
	RowCount       int64
	ByteSize       int64
	Ttl            pgtype.Interval
	OrganizationID int64
	ID             int64
}

func (q *Queries) CompleteReportRun(ctx context.Context, arg CompleteReportRunParams) (ReportRun, error) {
	row := q.db.QueryRow(ctx, completeReportRun,
		arg.ObjectID,
		arg.RowCount,
		arg.ByteSize,
		arg.Ttl,
		arg.OrganizationID,
		arg.ID,
	)
	var i ReportRun
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrganizationID,
		&i.ReportType,
		&i.Format,
		&i.Parameters,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.Status,
		&i.RowCount,
		&i.ByteSize,
		&i.ObjectID,
		&i.ExpiresAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ErrorMessage,
		&i.DurationMs,
		&i.JobID,
		&i.RequestedBy,
		&i.RequestID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createReportRun = `-- name: CreateReportRun :one

INSERT INTO report_runs (
    public_id, organization_id, report_type, format, parameters,
    period_start, period_end, requested_by, request_id
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9)
RETURNING id, public_id, organization_id, report_type, format, parameters, period_start, period_end, status, row_count, byte_size, object_id, expires_at, started_at, completed_at, error_message, duration_ms, job_id, requested_by, request_id, created_at, updated_at
`

type CreateReportRunParams struct {
	PublicID       string
	OrganizationID int64
	ReportType     string
	Format         string
	Parameters     []byte
	PeriodStart    *time.Time
	PeriodEnd      *time.Time
	RequestedBy    *int64
	RequestID      *string
}

// Report runs (M31).
//
// A report is a job, not a request. The specification forbids building one in
// RAM, so a run is queued, executed by a worker that reads with a cursor and
// streams CSV into object storage, and downloaded through a signed URL that
// expires. Nothing here returns report *rows* — the rows go to the file.
func (q *Queries) CreateReportRun(ctx context.Context, arg CreateReportRunParams) (ReportRun, error) {
	row := q.db.QueryRow(ctx, createReportRun,
		arg.PublicID,
		arg.OrganizationID,
		arg.ReportType,
		arg.Format,
		arg.Parameters,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.RequestedBy,
		arg.RequestID,
	)
	var i ReportRun
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrganizationID,
		&i.ReportType,
		&i.Format,
		&i.Parameters,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.Status,
		&i.RowCount,
		&i.ByteSize,
		&i.ObjectID,
		&i.ExpiresAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ErrorMessage,
		&i.DurationMs,
		&i.JobID,
		&i.RequestedBy,
		&i.RequestID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const expireReportRuns = `-- name: ExpireReportRuns :many
UPDATE report_runs
   SET status = 'EXPIRED'
 WHERE status = 'COMPLETED' AND expires_at IS NOT NULL AND expires_at < now()
RETURNING id, organization_id, public_id, object_id
`

type ExpireReportRunsRow struct {
	ID             int64
	OrganizationID int64
	PublicID       string
	ObjectID       *int64
}

// A completed report whose download window has passed. The rows are returned so
// the sweep can delete the objects too: expiring the record while leaving the
// file in the bucket would be a slow leak of exported customer data.
func (q *Queries) ExpireReportRuns(ctx context.Context) ([]ExpireReportRunsRow, error) {
	rows, err := q.db.Query(ctx, expireReportRuns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExpireReportRunsRow{}
	for rows.Next() {
		var i ExpireReportRunsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.PublicID,
			&i.ObjectID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const failReportRun = `-- name: FailReportRun :one
UPDATE report_runs
   SET status = 'FAILED', completed_at = now(),
       error_message = $1,
       duration_ms = (EXTRACT(EPOCH FROM (now() - COALESCE(started_at, now()))) * 1000)::int
 WHERE organization_id = $2 AND id = $3
RETURNING id, public_id, organization_id, report_type, format, parameters, period_start, period_end, status, row_count, byte_size, object_id, expires_at, started_at, completed_at, error_message, duration_ms, job_id, requested_by, request_id, created_at, updated_at
`

type FailReportRunParams struct {
	ErrorMessage   *string
	OrganizationID int64
	ID             int64
}

func (q *Queries) FailReportRun(ctx context.Context, arg FailReportRunParams) (ReportRun, error) {
	row := q.db.QueryRow(ctx, failReportRun, arg.ErrorMessage, arg.OrganizationID, arg.ID)
	var i ReportRun
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrganizationID,
		&i.ReportType,
		&i.Format,
		&i.Parameters,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.Status,
		&i.RowCount,
		&i.ByteSize,
		&i.ObjectID,
		&i.ExpiresAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ErrorMessage,
		&i.DurationMs,
		&i.JobID,
		&i.RequestedBy,
		&i.RequestID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getReportRunByID = `-- name: GetReportRunByID :one
SELECT id, public_id, organization_id, report_type, format, parameters, period_start, period_end, status, row_count, byte_size, object_id, expires_at, started_at, completed_at, error_message, duration_ms, job_id, requested_by, request_id, created_at, updated_at FROM report_runs WHERE id = $1
`

func (q *Queries) GetReportRunByID(ctx context.Context, id int64) (ReportRun, error) {
	row := q.db.QueryRow(ctx, getReportRunByID, id)
	var i ReportRun
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrganizationID,
		&i.ReportType,
		&i.Format,
		&i.Parameters,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.Status,
		&i.RowCount,
		&i.ByteSize,
		&i.ObjectID,
		&i.ExpiresAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ErrorMessage,
		&i.DurationMs,
		&i.JobID,
		&i.RequestedBy,
		&i.RequestID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getReportRunByPublicID = `-- name: GetReportRunByPublicID :one
SELECT r.id, r.public_id, r.organization_id, r.report_type, r.format, r.parameters, r.period_start, r.period_end, r.status, r.row_count, r.byte_size, r.object_id, r.expires_at, r.started_at, r.completed_at, r.error_message, r.duration_ms, r.job_id, r.requested_by, r.request_id, r.created_at, r.updated_at, o.object_key, o.bucket, o.mime_type, o.size_bytes
FROM report_runs r
LEFT JOIN stored_objects o ON o.id = r.object_id
WHERE r.organization_id = $1 AND r.public_id = $2
`

type GetReportRunByPublicIDParams struct {
	OrganizationID int64
	PublicID       string
}

type GetReportRunByPublicIDRow struct {
	ID             int64
	PublicID       string
	OrganizationID int64
	ReportType     string
	Format         string
	Parameters     []byte
	PeriodStart    *time.Time
	PeriodEnd      *time.Time
	Status         string
	RowCount       int64
	ByteSize       int64
	ObjectID       *int64
	ExpiresAt      *time.Time
	StartedAt      *time.Time
	CompletedAt    *time.Time
	ErrorMessage   *string
	DurationMs     *int32
	JobID          *int64
	RequestedBy    *int64
	RequestID      *string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	ObjectKey      *string
	Bucket         *string
	MimeType       *string
	SizeBytes      *int64
}

func (q *Queries) GetReportRunByPublicID(ctx context.Context, arg GetReportRunByPublicIDParams) (GetReportRunByPublicIDRow, error) {
	row := q.db.QueryRow(ctx, getReportRunByPublicID, arg.OrganizationID, arg.PublicID)
	var i GetReportRunByPublicIDRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrganizationID,
		&i.ReportType,
		&i.Format,
		&i.Parameters,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.Status,
		&i.RowCount,
		&i.ByteSize,
		&i.ObjectID,
		&i.ExpiresAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ErrorMessage,
		&i.DurationMs,
		&i.JobID,
		&i.RequestedBy,
		&i.RequestID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ObjectKey,
		&i.Bucket,
		&i.MimeType,
		&i.SizeBytes,
	)
	return i, err
}

const getStoredObjectKey = `-- name: GetStoredObjectKey :one
SELECT object_key FROM stored_objects WHERE id = $1
`

// Just the key, for the expiry sweep: it deletes the file and does not need the
// rest of the metadata row.
func (q *Queries) GetStoredObjectKey(ctx context.Context, id int64) (string, error) {
	row := q.db.QueryRow(ctx, getStoredObjectKey, id)
	var object_key string
	err := row.Scan(&object_key)
	return object_key, err
}

const listReportRuns = `-- name: ListReportRuns :many
SELECT r.public_id, r.report_type, r.format, r.status, r.period_start, r.period_end,
       r.row_count, r.byte_size, r.expires_at, r.started_at, r.completed_at,
       r.error_message, r.duration_ms, r.created_at,
       u.full_name AS requested_by_name
FROM report_runs r
LEFT JOIN users u ON u.id = r.requested_by
WHERE r.organization_id = $1
  AND ($2::text IS NULL OR r.report_type = $2::text)
  AND ($3::text IS NULL OR r.status = $3::text)
  AND ($4::bigint IS NULL OR r.requested_by = $4::bigint)
  AND ($5::bigint IS NULL OR r.id < $5::bigint)
ORDER BY r.id DESC
LIMIT $6
`

type ListReportRunsParams struct {
	OrganizationID int64
	ReportType     *string
	Status         *string
	RequestedBy    *int64
	CursorID       *int64
	RowLimit       int32
}

type ListReportRunsRow struct {
	PublicID        string
	ReportType      string
	Format          string
	Status          string
	PeriodStart     *time.Time
	PeriodEnd       *time.Time
	RowCount        int64
	ByteSize        int64
	ExpiresAt       *time.Time
	StartedAt       *time.Time
	CompletedAt     *time.Time
	ErrorMessage    *string
	DurationMs      *int32
	CreatedAt       time.Time
	RequestedByName *string
}

func (q *Queries) ListReportRuns(ctx context.Context, arg ListReportRunsParams) ([]ListReportRunsRow, error) {
	rows, err := q.db.Query(ctx, listReportRuns,
		arg.OrganizationID,
		arg.ReportType,
		arg.Status,
		arg.RequestedBy,
		arg.CursorID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReportRunsRow{}
	for rows.Next() {
		var i ListReportRunsRow
		if err := rows.Scan(
			&i.PublicID,
			&i.ReportType,
			&i.Format,
			&i.Status,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.RowCount,
			&i.ByteSize,
			&i.ExpiresAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.ErrorMessage,
			&i.DurationMs,
			&i.CreatedAt,
			&i.RequestedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reportBranchPerformance = `-- name: ReportBranchPerformance :many
SELECT s.id, u.code AS unit_code, u.name AS unit_name, u.unit_type,
       s.stat_date, s.booked_count, s.delivered_count, s.ndr_count,
       s.rto_count, s.sla_breach_count, s.revenue_minor, s.cod_amount_minor
FROM shipment_daily_stats s
JOIN operating_units u ON u.id = s.operating_unit_id
WHERE s.organization_id = $1
  AND s.stat_date >= $2::date
  AND s.stat_date <= $3::date
  AND s.id > $4
ORDER BY s.id
LIMIT $5
`

type ReportBranchPerformanceParams struct {
	OrganizationID int64
	PeriodStart    time.Time
	PeriodEnd      time.Time
	AfterID        int64
	ChunkSize      int32
}

type ReportBranchPerformanceRow struct {
	ID             int64
	UnitCode       string
	UnitName       string
	UnitType       string
	StatDate       time.Time
	BookedCount    int32
	DeliveredCount int32
	NdrCount       int32
	RtoCount       int32
	SlaBreachCount int32
	RevenueMinor   int64
	CodAmountMinor int64
}

// Reads the rollup, not shipments: a branch-performance report over a year is
// 365 rows per branch rather than every parcel they handled.
func (q *Queries) ReportBranchPerformance(ctx context.Context, arg ReportBranchPerformanceParams) ([]ReportBranchPerformanceRow, error) {
	rows, err := q.db.Query(ctx, reportBranchPerformance,
		arg.OrganizationID,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.AfterID,
		arg.ChunkSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReportBranchPerformanceRow{}
	for rows.Next() {
		var i ReportBranchPerformanceRow
		if err := rows.Scan(
			&i.ID,
			&i.UnitCode,
			&i.UnitName,
			&i.UnitType,
			&i.StatDate,
			&i.BookedCount,
			&i.DeliveredCount,
			&i.NdrCount,
			&i.RtoCount,
			&i.SlaBreachCount,
			&i.RevenueMinor,
			&i.CodAmountMinor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reportCODAging = `-- name: ReportCODAging :many
SELECT o.id, o.awb, o.status, o.expected_minor, o.collected_minor, o.remitted_minor,
       o.currency, o.collected_at, o.remitted_at, o.custodian_type,
       f.code AS franchise_code, f.name AS franchise_name,
       EXTRACT(DAY FROM (now() - o.collected_at))::int AS days_held
FROM cod_obligations o
LEFT JOIN franchises f ON f.id = o.destination_franchise_id
WHERE o.organization_id = $1
  AND o.status IN ('AGENT_COLLECTED','BRANCH_RECEIVED','FRANCHISE_CONFIRMED','RECONCILED')
  AND o.id > $2
ORDER BY o.id
LIMIT $3
`

type ReportCODAgingParams struct {
	OrganizationID int64
	AfterID        int64
	ChunkSize      int32
}

type ReportCODAgingRow struct {
	ID             int64
	Awb            string
	Status         string
	ExpectedMinor  int64
	CollectedMinor int64
	RemittedMinor  int64
	Currency       string
	CollectedAt    *time.Time
	RemittedAt     *time.Time
	CustodianType  *string
	FranchiseCode  *string
	FranchiseName  *string
	DaysHeld       int32
}

func (q *Queries) ReportCODAging(ctx context.Context, arg ReportCODAgingParams) ([]ReportCODAgingRow, error) {
	rows, err := q.db.Query(ctx, reportCODAging, arg.OrganizationID, arg.AfterID, arg.ChunkSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReportCODAgingRow{}
	for rows.Next() {
		var i ReportCODAgingRow
		if err := rows.Scan(
			&i.ID,
			&i.Awb,
			&i.Status,
			&i.ExpectedMinor,
			&i.CollectedMinor,
			&i.RemittedMinor,
			&i.Currency,
			&i.CollectedAt,
			&i.RemittedAt,
			&i.CustodianType,
			&i.FranchiseCode,
			&i.FranchiseName,
			&i.DaysHeld,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reportCommissionEntries = `-- name: ReportCommissionEntries :many
SELECT e.id, e.public_id, e.entry_type, e.commission_type, e.amount_minor,
       e.currency, e.earned_on, e.memo,
       f.code AS franchise_code, f.name AS franchise_name,
       s.awb, st.settlement_number
FROM commission_entries e
JOIN franchises f ON f.id = e.franchise_id
LEFT JOIN shipments s ON s.id = e.shipment_id
LEFT JOIN settlements st ON st.id = e.settlement_id
WHERE e.organization_id = $1
  AND e.earned_on >= $2::date
  AND e.earned_on <= $3::date
  AND e.id > $4
ORDER BY e.id
LIMIT $5
`

type ReportCommissionEntriesParams struct {
	OrganizationID int64
	PeriodStart    time.Time
	PeriodEnd      time.Time
	AfterID        int64
	ChunkSize      int32
}

type ReportCommissionEntriesRow struct {
	ID               int64
	PublicID         string
	EntryType        string
	CommissionType   string
	AmountMinor      int64
	Currency         string
	EarnedOn         time.Time
	Memo             *string
	FranchiseCode    string
	FranchiseName    string
	Awb              *string
	SettlementNumber *string
}

func (q *Queries) ReportCommissionEntries(ctx context.Context, arg ReportCommissionEntriesParams) ([]ReportCommissionEntriesRow, error) {
	rows, err := q.db.Query(ctx, reportCommissionEntries,
		arg.OrganizationID,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.AfterID,
		arg.ChunkSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReportCommissionEntriesRow{}
	for rows.Next() {
		var i ReportCommissionEntriesRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.EntryType,
			&i.CommissionType,
			&i.AmountMinor,
			&i.Currency,
			&i.EarnedOn,
			&i.Memo,
			&i.FranchiseCode,
			&i.FranchiseName,
			&i.Awb,
			&i.SettlementNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reportNDRCases = `-- name: ReportNDRCases :many
SELECT n.id, n.case_code, n.status, n.current_reason_code, n.attempt_count,
       n.opened_at, n.resolved_at, n.current_action,
       s.awb, s.destination_pincode,
       b.code AS branch_code
FROM ndr_cases n
JOIN shipments s ON s.id = n.shipment_id
LEFT JOIN operating_units b ON b.id = n.branch_id
WHERE n.organization_id = $1
  AND n.opened_at >= $2::timestamptz
  AND n.opened_at < $3::timestamptz
  AND n.id > $4
ORDER BY n.id
LIMIT $5
`

type ReportNDRCasesParams struct {
	OrganizationID int64
	PeriodStart    time.Time
	PeriodEnd      time.Time
	AfterID        int64
	ChunkSize      int32
}

type ReportNDRCasesRow struct {
	ID                 int64
	CaseCode           string
	Status             string
	CurrentReasonCode  string
	AttemptCount       int32
	OpenedAt           time.Time
	ResolvedAt         *time.Time
	CurrentAction      *string
	Awb                string
	DestinationPincode string
	BranchCode         *string
}

func (q *Queries) ReportNDRCases(ctx context.Context, arg ReportNDRCasesParams) ([]ReportNDRCasesRow, error) {
	rows, err := q.db.Query(ctx, reportNDRCases,
		arg.OrganizationID,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.AfterID,
		arg.ChunkSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReportNDRCasesRow{}
	for rows.Next() {
		var i ReportNDRCasesRow
		if err := rows.Scan(
			&i.ID,
			&i.CaseCode,
			&i.Status,
			&i.CurrentReasonCode,
			&i.AttemptCount,
			&i.OpenedAt,
			&i.ResolvedAt,
			&i.CurrentAction,
			&i.Awb,
			&i.DestinationPincode,
			&i.BranchCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reportShipments = `-- name: ReportShipments :many

SELECT s.id, s.awb, s.reference_number, s.current_status, s.payment_mode,
       s.piece_count, s.actual_weight_grams, s.chargeable_weight_grams,
       s.origin_pincode, s.destination_pincode,
       s.total_amount_minor, s.cod_amount_minor, s.currency,
       s.booked_at, s.status_changed_at, s.promised_delivery_at,
       c.code AS customer_code, c.name AS customer_name,
       sv.code AS service_code,
       ob.code AS origin_branch_code, db.code AS destination_branch_code
FROM shipments s
JOIN customers c ON c.id = s.customer_id
JOIN courier_services sv ON sv.id = s.courier_service_id
LEFT JOIN operating_units ob ON ob.id = s.origin_branch_id
LEFT JOIN operating_units db ON db.id = s.destination_branch_id
WHERE s.organization_id = $1
  AND s.booked_at >= $2::timestamptz
  AND s.booked_at < $3::timestamptz
  AND ($4::bigint IS NULL
       OR s.booking_unit_id = $4::bigint
       OR s.origin_branch_id = $4::bigint)
  AND ($5::text IS NULL OR s.current_status = $5::text)
  AND s.id > $6
ORDER BY s.id
LIMIT $7
`

type ReportShipmentsParams struct {
	OrganizationID int64
	PeriodStart    time.Time
	PeriodEnd      time.Time
	UnitID         *int64
	Status         *string
	AfterID        int64
	ChunkSize      int32
}

type ReportShipmentsRow struct {
	ID                    int64
	Awb                   string
	ReferenceNumber       *string
	CurrentStatus         string
	PaymentMode           string
	PieceCount            int32
	ActualWeightGrams     int32
	ChargeableWeightGrams int32
	OriginPincode         string
	DestinationPincode    string
	TotalAmountMinor      int64
	CodAmountMinor        int64
	Currency              string
	BookedAt              time.Time
	StatusChangedAt       time.Time
	PromisedDeliveryAt    *time.Time
	CustomerCode          string
	CustomerName          string
	ServiceCode           string
	OriginBranchCode      *string
	DestinationBranchCode *string
}

// ---------------------------------------------------------------------------
// The report data sources
//
// Every one of these is a *cursor* read: ordered by a unique key, bounded by a
// row limit, resumable from the last key seen. The worker walks them in chunks
// and writes each chunk straight out, so peak memory is one chunk regardless of
// how many rows the report covers.
//
// None of them may use OFFSET. A million-row report paged by offset re-scans
// the rows it skips on every chunk, which turns a linear export into a
// quadratic one.
// ---------------------------------------------------------------------------
func (q *Queries) ReportShipments(ctx context.Context, arg ReportShipmentsParams) ([]ReportShipmentsRow, error) {
	rows, err := q.db.Query(ctx, reportShipments,
		arg.OrganizationID,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.UnitID,
		arg.Status,
		arg.AfterID,
		arg.ChunkSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReportShipmentsRow{}
	for rows.Next() {
		var i ReportShipmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Awb,
			&i.ReferenceNumber,
			&i.CurrentStatus,
			&i.PaymentMode,
			&i.PieceCount,
			&i.ActualWeightGrams,
			&i.ChargeableWeightGrams,
			&i.OriginPincode,
			&i.DestinationPincode,
			&i.TotalAmountMinor,
			&i.CodAmountMinor,
			&i.Currency,
			&i.BookedAt,
			&i.StatusChangedAt,
			&i.PromisedDeliveryAt,
			&i.CustomerCode,
			&i.CustomerName,
			&i.ServiceCode,
			&i.OriginBranchCode,
			&i.DestinationBranchCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setReportRunJob = `-- name: SetReportRunJob :exec
UPDATE report_runs SET job_id = $2 WHERE id = $1
`

type SetReportRunJobParams struct {
	ID    int64
	JobID *int64
}

func (q *Queries) SetReportRunJob(ctx context.Context, arg SetReportRunJobParams) error {
	_, err := q.db.Exec(ctx, setReportRunJob, arg.ID, arg.JobID)
	return err
}

const startReportRun = `-- name: StartReportRun :one
UPDATE report_runs
   SET status = 'RUNNING', started_at = now()
 WHERE id = $1 AND status = 'QUEUED'
RETURNING id, public_id, organization_id, report_type, format, parameters, period_start, period_end, status, row_count, byte_size, object_id, expires_at, started_at, completed_at, error_message, duration_ms, job_id, requested_by, request_id, created_at, updated_at
`

// QUEUED -> RUNNING, and only that. A run already RUNNING is not restarted:
// two workers generating the same file would both write, and the second would
// overwrite the first's object while the first was still streaming into it.
func (q *Queries) StartReportRun(ctx context.Context, id int64) (ReportRun, error) {
	row := q.db.QueryRow(ctx, startReportRun, id)
	var i ReportRun
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrganizationID,
		&i.ReportType,
		&i.Format,
		&i.Parameters,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.Status,
		&i.RowCount,
		&i.ByteSize,
		&i.ObjectID,
		&i.ExpiresAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ErrorMessage,
		&i.DurationMs,
		&i.JobID,
		&i.RequestedBy,
		&i.RequestID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
