// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: scanning.sql

package dbgen

import (
	"context"
	"time"
)

const appendShipmentEventFull = `-- name: AppendShipmentEventFull :one
INSERT INTO shipment_events (
    public_id, organization_id, shipment_id, sequence, event_type, from_status, to_status,
    occurred_at, client_occurred_at, actor_user_id, actor_type, operating_unit_id,
    location_pincode, location_name, description, internal_remarks, reason_code,
    request_id, idempotency_key, source, device_id, device_model, latitude, longitude, metadata
) VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, COALESCE($8::timestamptz, now()),
    $9, $10, $11,
    $12, $13, $14,
    $15, $16, $17,
    $18, $19, $20,
    $21, $22, $23,
    $24, $25
)
RETURNING id, public_id, organization_id, shipment_id, sequence, event_type, from_status, to_status, occurred_at, recorded_at, actor_user_id, actor_type, operating_unit_id, location_pincode, location_name, description, internal_remarks, reason_code, request_id, idempotency_key, metadata, source, device_id, device_model, latitude, longitude, client_occurred_at
`

type AppendShipmentEventFullParams struct {
	PublicID         string
	OrganizationID   int64
	ShipmentID       int64
	Sequence         int32
	EventType        string
	FromStatus       *string
	ToStatus         string
	OccurredAt       *time.Time
	ClientOccurredAt *time.Time
	ActorUserID      *int64
	ActorType        string
	OperatingUnitID  *int64
	LocationPincode  *string
	LocationName     *string
	Description      string
	InternalRemarks  *string
	ReasonCode       *string
	RequestID        *string
	IdempotencyKey   *string
	Source           string
	DeviceID         *string
	DeviceModel      *string
	Latitude         *float64
	Longitude        *float64
	Metadata         []byte
}

// Append-only history with the full operational envelope (§Operational Event
// Integrity): occurrence versus record time, actor, facility, device, source.
func (q *Queries) AppendShipmentEventFull(ctx context.Context, arg AppendShipmentEventFullParams) (ShipmentEvent, error) {
	row := q.db.QueryRow(ctx, appendShipmentEventFull,
		arg.PublicID,
		arg.OrganizationID,
		arg.ShipmentID,
		arg.Sequence,
		arg.EventType,
		arg.FromStatus,
		arg.ToStatus,
		arg.OccurredAt,
		arg.ClientOccurredAt,
		arg.ActorUserID,
		arg.ActorType,
		arg.OperatingUnitID,
		arg.LocationPincode,
		arg.LocationName,
		arg.Description,
		arg.InternalRemarks,
		arg.ReasonCode,
		arg.RequestID,
		arg.IdempotencyKey,
		arg.Source,
		arg.DeviceID,
		arg.DeviceModel,
		arg.Latitude,
		arg.Longitude,
		arg.Metadata,
	)
	var i ShipmentEvent
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrganizationID,
		&i.ShipmentID,
		&i.Sequence,
		&i.EventType,
		&i.FromStatus,
		&i.ToStatus,
		&i.OccurredAt,
		&i.RecordedAt,
		&i.ActorUserID,
		&i.ActorType,
		&i.OperatingUnitID,
		&i.LocationPincode,
		&i.LocationName,
		&i.Description,
		&i.InternalRemarks,
		&i.ReasonCode,
		&i.RequestID,
		&i.IdempotencyKey,
		&i.Metadata,
		&i.Source,
		&i.DeviceID,
		&i.DeviceModel,
		&i.Latitude,
		&i.Longitude,
		&i.ClientOccurredAt,
	)
	return i, err
}

const applyOperationalTransition = `-- name: ApplyOperationalTransition :one

UPDATE shipments
SET current_status = $1,
    status_changed_at = now(),
    event_sequence = event_sequence + 1,
    current_custody_unit_id = CASE WHEN $2::boolean
                                   THEN $3 ELSE current_custody_unit_id END,
    current_custody_user_id = CASE WHEN $4::boolean
                                   THEN $5 ELSE current_custody_user_id END,
    current_bag_id = CASE WHEN $6::boolean
                          THEN $7 ELSE current_bag_id END,
    current_trip_id = CASE WHEN $8::boolean
                           THEN $9 ELSE current_trip_id END,
    movement_direction = COALESCE($10, movement_direction),
    picked_up_at = CASE WHEN $1::text = 'PICKED_UP'
                        THEN COALESCE(picked_up_at, now()) ELSE picked_up_at END,
    first_ofd_at = CASE WHEN $1::text = 'OUT_FOR_DELIVERY'
                        THEN COALESCE(first_ofd_at, now()) ELSE first_ofd_at END,
    delivered_at = CASE WHEN $1::text IN ('DELIVERED','RTO_DELIVERED')
                        THEN now() ELSE delivered_at END,
    delivery_attempt_count = delivery_attempt_count + $11::int,
    pickup_attempt_count = pickup_attempt_count + $12::int
WHERE id = $13
  AND organization_id = $14
  AND current_status = $15
RETURNING id, public_id, organization_id, awb, reference_number, customer_id, courier_service_id, booked_by_user_id, booking_unit_id, payment_mode, current_status, status_changed_at, event_sequence, origin_branch_id, origin_hub_id, destination_hub_id, destination_branch_id, route_definition_id, origin_pincode, destination_pincode, is_remote_origin, is_remote_destination, current_custody_unit_id, current_custody_user_id, piece_count, actual_weight_grams, volumetric_weight_grams, chargeable_weight_grams, currency, declared_value_minor, cod_amount_minor, insurance_required, total_amount_minor, sla_hours, promised_delivery_at, booked_at, content_description, special_instructions, is_fragile, is_dangerous_goods, cancelled_at, cancelled_by, cancellation_reason, metadata, created_at, updated_at, version, current_bag_id, current_trip_id, movement_direction, delivery_attempt_count, pickup_attempt_count, first_ofd_at, delivered_at, picked_up_at, is_held, hold_reason
`

type ApplyOperationalTransitionParams struct {
	ToStatus                 string
	SetCustodyUnit           bool
	CustodyUnitID            *int64
	SetCustodyUser           bool
	CustodyUserID            *int64
	SetBag                   bool
	BagID                    *int64
	SetTrip                  bool
	TripID                   *int64
	MovementDirection        *string
	DeliveryAttemptIncrement int32
	PickupAttemptIncrement   int32
	ID                       int64
	OrganizationID           int64
	ExpectedStatus           string
}

// ---------------------------------------------------------------------------
// Shipment mutation helpers used by every operational module
// ---------------------------------------------------------------------------
// The single write behind every Release 2 state change.
//
// `current_status = expected_status` makes it a compare-and-swap, so two
// concurrent scans on the same parcel cannot both succeed: the loser updates
// zero rows and is told to retry (§22). It also reserves the next event
// sequence in the same statement, which is what makes the
// UNIQUE(shipment_id, sequence) on shipment_events an effective guard.
func (q *Queries) ApplyOperationalTransition(ctx context.Context, arg ApplyOperationalTransitionParams) (Shipment, error) {
	row := q.db.QueryRow(ctx, applyOperationalTransition,
		arg.ToStatus,
		arg.SetCustodyUnit,
		arg.CustodyUnitID,
		arg.SetCustodyUser,
		arg.CustodyUserID,
		arg.SetBag,
		arg.BagID,
		arg.SetTrip,
		arg.TripID,
		arg.MovementDirection,
		arg.DeliveryAttemptIncrement,
		arg.PickupAttemptIncrement,
		arg.ID,
		arg.OrganizationID,
		arg.ExpectedStatus,
	)
	var i Shipment
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrganizationID,
		&i.Awb,
		&i.ReferenceNumber,
		&i.CustomerID,
		&i.CourierServiceID,
		&i.BookedByUserID,
		&i.BookingUnitID,
		&i.PaymentMode,
		&i.CurrentStatus,
		&i.StatusChangedAt,
		&i.EventSequence,
		&i.OriginBranchID,
		&i.OriginHubID,
		&i.DestinationHubID,
		&i.DestinationBranchID,
		&i.RouteDefinitionID,
		&i.OriginPincode,
		&i.DestinationPincode,
		&i.IsRemoteOrigin,
		&i.IsRemoteDestination,
		&i.CurrentCustodyUnitID,
		&i.CurrentCustodyUserID,
		&i.PieceCount,
		&i.ActualWeightGrams,
		&i.VolumetricWeightGrams,
		&i.ChargeableWeightGrams,
		&i.Currency,
		&i.DeclaredValueMinor,
		&i.CodAmountMinor,
		&i.InsuranceRequired,
		&i.TotalAmountMinor,
		&i.SlaHours,
		&i.PromisedDeliveryAt,
		&i.BookedAt,
		&i.ContentDescription,
		&i.SpecialInstructions,
		&i.IsFragile,
		&i.IsDangerousGoods,
		&i.CancelledAt,
		&i.CancelledBy,
		&i.CancellationReason,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
		&i.CurrentBagID,
		&i.CurrentTripID,
		&i.MovementDirection,
		&i.DeliveryAttemptCount,
		&i.PickupAttemptCount,
		&i.FirstOfdAt,
		&i.DeliveredAt,
		&i.PickedUpAt,
		&i.IsHeld,
		&i.HoldReason,
	)
	return i, err
}

const createShipmentHold = `-- name: CreateShipmentHold :one

INSERT INTO shipment_holds (
    public_id, organization_id, shipment_id, operating_unit_id,
    hold_reason_code, reason, held_by_user_id, expected_release_at, metadata
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9)
RETURNING id, public_id, organization_id, shipment_id, operating_unit_id, hold_reason_code, reason, held_at, held_by_user_id, released_at, released_by_user_id, release_notes, expected_release_at, metadata
`

type CreateShipmentHoldParams struct {
	PublicID          string
	OrganizationID    int64
	ShipmentID        int64
	OperatingUnitID   int64
	HoldReasonCode    string
	Reason            string
	HeldByUserID      *int64
	ExpectedReleaseAt *time.Time
	Metadata          []byte
}

// ---------------------------------------------------------------------------
// Holds
// ---------------------------------------------------------------------------
func (q *Queries) CreateShipmentHold(ctx context.Context, arg CreateShipmentHoldParams) (ShipmentHold, error) {
	row := q.db.QueryRow(ctx, createShipmentHold,
		arg.PublicID,
		arg.OrganizationID,
		arg.ShipmentID,
		arg.OperatingUnitID,
		arg.HoldReasonCode,
		arg.Reason,
		arg.HeldByUserID,
		arg.ExpectedReleaseAt,
		arg.Metadata,
	)
	var i ShipmentHold
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrganizationID,
		&i.ShipmentID,
		&i.OperatingUnitID,
		&i.HoldReasonCode,
		&i.Reason,
		&i.HeldAt,
		&i.HeldByUserID,
		&i.ReleasedAt,
		&i.ReleasedByUserID,
		&i.ReleaseNotes,
		&i.ExpectedReleaseAt,
		&i.Metadata,
	)
	return i, err
}

const getActiveHold = `-- name: GetActiveHold :one
SELECT h.id, h.public_id, h.organization_id, h.shipment_id, h.operating_unit_id, h.hold_reason_code, h.reason, h.held_at, h.held_by_user_id, h.released_at, h.released_by_user_id, h.release_notes, h.expected_release_at, h.metadata, ou.code AS unit_code, ou.name AS unit_name, u.full_name AS held_by_name
FROM shipment_holds h
JOIN operating_units ou ON ou.id = h.operating_unit_id
LEFT JOIN users u ON u.id = h.held_by_user_id
WHERE h.shipment_id = $1 AND h.released_at IS NULL
`

type GetActiveHoldRow struct {
	ID                int64
	PublicID          string
	OrganizationID    int64
	ShipmentID        int64
	OperatingUnitID   int64
	HoldReasonCode    string
	Reason            string
	HeldAt            time.Time
	HeldByUserID      *int64
	ReleasedAt        *time.Time
	ReleasedByUserID  *int64
	ReleaseNotes      *string
	ExpectedReleaseAt *time.Time
	Metadata          []byte
	UnitCode          string
	UnitName          string
	HeldByName        *string
}

func (q *Queries) GetActiveHold(ctx context.Context, shipmentID int64) (GetActiveHoldRow, error) {
	row := q.db.QueryRow(ctx, getActiveHold, shipmentID)
	var i GetActiveHoldRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrganizationID,
		&i.ShipmentID,
		&i.OperatingUnitID,
		&i.HoldReasonCode,
		&i.Reason,
		&i.HeldAt,
		&i.HeldByUserID,
		&i.ReleasedAt,
		&i.ReleasedByUserID,
		&i.ReleaseNotes,
		&i.ExpectedReleaseAt,
		&i.Metadata,
		&i.UnitCode,
		&i.UnitName,
		&i.HeldByName,
	)
	return i, err
}

const getScanEventByDeviceEvent = `-- name: GetScanEventByDeviceEvent :one
SELECT se.id, se.public_id, se.organization_id, se.raw_barcode, se.shipment_id, se.package_id, se.scan_type, se.operating_unit_id, se.scanned_by_user_id, se.device_event_id, se.device_id, se.source, se.occurred_at, se.recorded_at, se.outcome, se.rejection_code, se.rejection_message, se.shipment_event_id, se.from_status, se.to_status, se.latitude, se.longitude, se.reference_type, se.reference_id, se.metadata, s.public_id AS shipment_public_id, s.awb, s.current_status
FROM scan_events se
LEFT JOIN shipments s ON s.id = se.shipment_id
WHERE se.organization_id = $1
  AND se.device_id = $2
  AND se.device_event_id = $3
`

type GetScanEventByDeviceEventParams struct {
	OrganizationID int64
	DeviceID       *string
	DeviceEventID  *string
}

type GetScanEventByDeviceEventRow struct {
	ID               int64
	PublicID         string
	OrganizationID   int64
	RawBarcode       string
	ShipmentID       *int64
	PackageID        *int64
	ScanType         string
	OperatingUnitID  int64
	ScannedByUserID  *int64
	DeviceEventID    *string
	DeviceID         *string
	Source           string
	OccurredAt       time.Time
	RecordedAt       time.Time
	Outcome          string
	RejectionCode    *string
	RejectionMessage *string
	ShipmentEventID  *int64
	FromStatus       *string
	ToStatus         *string
	Latitude         *float64
	Longitude        *float64
	ReferenceType    *string
	ReferenceID      *int64
	Metadata         []byte
	ShipmentPublicID *string
	Awb              *string
	CurrentStatus    *string
}

// Device-level idempotency. A retried upload returns the original outcome.
func (q *Queries) GetScanEventByDeviceEvent(ctx context.Context, arg GetScanEventByDeviceEventParams) (GetScanEventByDeviceEventRow, error) {
	row := q.db.QueryRow(ctx, getScanEventByDeviceEvent, arg.OrganizationID, arg.DeviceID, arg.DeviceEventID)
	var i GetScanEventByDeviceEventRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrganizationID,
		&i.RawBarcode,
		&i.ShipmentID,
		&i.PackageID,
		&i.ScanType,
		&i.OperatingUnitID,
		&i.ScannedByUserID,
		&i.DeviceEventID,
		&i.DeviceID,
		&i.Source,
		&i.OccurredAt,
		&i.RecordedAt,
		&i.Outcome,
		&i.RejectionCode,
		&i.RejectionMessage,
		&i.ShipmentEventID,
		&i.FromStatus,
		&i.ToStatus,
		&i.Latitude,
		&i.Longitude,
		&i.ReferenceType,
		&i.ReferenceID,
		&i.Metadata,
		&i.ShipmentPublicID,
		&i.Awb,
		&i.CurrentStatus,
	)
	return i, err
}

const listActiveHolds = `-- name: ListActiveHolds :many
SELECT h.public_id, h.hold_reason_code, h.reason, h.held_at, h.expected_release_at,
       s.public_id AS shipment_public_id, s.awb, s.current_status,
       ou.code AS unit_code, ou.name AS unit_name,
       u.full_name AS held_by_name
FROM shipment_holds h
JOIN shipments s ON s.id = h.shipment_id
JOIN operating_units ou ON ou.id = h.operating_unit_id
LEFT JOIN users u ON u.id = h.held_by_user_id
WHERE h.organization_id = $1
  AND h.released_at IS NULL
  AND ($2::bigint[] IS NULL OR h.operating_unit_id = ANY($2))
ORDER BY h.held_at DESC, h.id DESC
LIMIT $3
`

type ListActiveHoldsParams struct {
	OrganizationID int64
	UnitIds        []int64
	PageSize       int32
}

type ListActiveHoldsRow struct {
	PublicID          string
	HoldReasonCode    string
	Reason            string
	HeldAt            time.Time
	ExpectedReleaseAt *time.Time
	ShipmentPublicID  string
	Awb               string
	CurrentStatus     string
	UnitCode          string
	UnitName          string
	HeldByName        *string
}

func (q *Queries) ListActiveHolds(ctx context.Context, arg ListActiveHoldsParams) ([]ListActiveHoldsRow, error) {
	rows, err := q.db.Query(ctx, listActiveHolds, arg.OrganizationID, arg.UnitIds, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveHoldsRow{}
	for rows.Next() {
		var i ListActiveHoldsRow
		if err := rows.Scan(
			&i.PublicID,
			&i.HoldReasonCode,
			&i.Reason,
			&i.HeldAt,
			&i.ExpectedReleaseAt,
			&i.ShipmentPublicID,
			&i.Awb,
			&i.CurrentStatus,
			&i.UnitCode,
			&i.UnitName,
			&i.HeldByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScanEvents = `-- name: ListScanEvents :many
SELECT se.id, se.public_id, se.raw_barcode, se.scan_type, se.outcome, se.rejection_code,
       se.rejection_message, se.occurred_at, se.recorded_at, se.from_status, se.to_status,
       se.source, se.device_id,
       s.public_id AS shipment_public_id, s.awb,
       ou.code AS unit_code, ou.name AS unit_name,
       u.public_id AS scanned_by_public_id, u.full_name AS scanned_by_name
FROM scan_events se
LEFT JOIN shipments s ON s.id = se.shipment_id
JOIN operating_units ou ON ou.id = se.operating_unit_id
LEFT JOIN users u ON u.id = se.scanned_by_user_id
WHERE se.organization_id = $1
  AND ($2::bigint IS NULL OR se.operating_unit_id = $2)
  AND ($3::bigint[] IS NULL OR se.operating_unit_id = ANY($3))
  AND ($4::bigint IS NULL OR se.shipment_id = $4)
  AND ($5::text IS NULL OR se.scan_type = $5)
  AND ($6::text IS NULL OR se.outcome = $6)
  AND ($7::timestamptz IS NULL
       OR (se.occurred_at, se.id) < ($7, $8::bigint))
ORDER BY se.occurred_at DESC, se.id DESC
LIMIT $9
`

type ListScanEventsParams struct {
	OrganizationID   int64
	UnitID           *int64
	UnitIds          []int64
	ShipmentID       *int64
	ScanType         *string
	Outcome          *string
	CursorOccurredAt *time.Time
	CursorID         *int64
	PageSize         int32
}

type ListScanEventsRow struct {
	ID                int64
	PublicID          string
	RawBarcode        string
	ScanType          string
	Outcome           string
	RejectionCode     *string
	RejectionMessage  *string
	OccurredAt        time.Time
	RecordedAt        time.Time
	FromStatus        *string
	ToStatus          *string
	Source            string
	DeviceID          *string
	ShipmentPublicID  *string
	Awb               *string
	UnitCode          string
	UnitName          string
	ScannedByPublicID *string
	ScannedByName     *string
}

func (q *Queries) ListScanEvents(ctx context.Context, arg ListScanEventsParams) ([]ListScanEventsRow, error) {
	rows, err := q.db.Query(ctx, listScanEvents,
		arg.OrganizationID,
		arg.UnitID,
		arg.UnitIds,
		arg.ShipmentID,
		arg.ScanType,
		arg.Outcome,
		arg.CursorOccurredAt,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListScanEventsRow{}
	for rows.Next() {
		var i ListScanEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.RawBarcode,
			&i.ScanType,
			&i.Outcome,
			&i.RejectionCode,
			&i.RejectionMessage,
			&i.OccurredAt,
			&i.RecordedAt,
			&i.FromStatus,
			&i.ToStatus,
			&i.Source,
			&i.DeviceID,
			&i.ShipmentPublicID,
			&i.Awb,
			&i.UnitCode,
			&i.UnitName,
			&i.ScannedByPublicID,
			&i.ScannedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShipmentScans = `-- name: ListShipmentScans :many
SELECT se.public_id, se.raw_barcode, se.scan_type, se.outcome, se.occurred_at,
       se.from_status, se.to_status, ou.code AS unit_code, ou.name AS unit_name,
       u.full_name AS scanned_by_name
FROM scan_events se
JOIN operating_units ou ON ou.id = se.operating_unit_id
LEFT JOIN users u ON u.id = se.scanned_by_user_id
WHERE se.shipment_id = $1
ORDER BY se.occurred_at DESC, se.id DESC
LIMIT $2
`

type ListShipmentScansParams struct {
	ShipmentID *int64
	PageSize   int32
}

type ListShipmentScansRow struct {
	PublicID      string
	RawBarcode    string
	ScanType      string
	Outcome       string
	OccurredAt    time.Time
	FromStatus    *string
	ToStatus      *string
	UnitCode      string
	UnitName      string
	ScannedByName *string
}

func (q *Queries) ListShipmentScans(ctx context.Context, arg ListShipmentScansParams) ([]ListShipmentScansRow, error) {
	rows, err := q.db.Query(ctx, listShipmentScans, arg.ShipmentID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListShipmentScansRow{}
	for rows.Next() {
		var i ListShipmentScansRow
		if err := rows.Scan(
			&i.PublicID,
			&i.RawBarcode,
			&i.ScanType,
			&i.Outcome,
			&i.OccurredAt,
			&i.FromStatus,
			&i.ToStatus,
			&i.UnitCode,
			&i.UnitName,
			&i.ScannedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockShipmentByIDForUpdate = `-- name: LockShipmentByIDForUpdate :one
SELECT id, public_id, organization_id, awb, reference_number, customer_id, courier_service_id, booked_by_user_id, booking_unit_id, payment_mode, current_status, status_changed_at, event_sequence, origin_branch_id, origin_hub_id, destination_hub_id, destination_branch_id, route_definition_id, origin_pincode, destination_pincode, is_remote_origin, is_remote_destination, current_custody_unit_id, current_custody_user_id, piece_count, actual_weight_grams, volumetric_weight_grams, chargeable_weight_grams, currency, declared_value_minor, cod_amount_minor, insurance_required, total_amount_minor, sla_hours, promised_delivery_at, booked_at, content_description, special_instructions, is_fragile, is_dangerous_goods, cancelled_at, cancelled_by, cancellation_reason, metadata, created_at, updated_at, version, current_bag_id, current_trip_id, movement_direction, delivery_attempt_count, pickup_attempt_count, first_ofd_at, delivered_at, picked_up_at, is_held, hold_reason FROM shipments
WHERE id = $1 AND organization_id = $2
FOR UPDATE
`

type LockShipmentByIDForUpdateParams struct {
	ID             int64
	OrganizationID int64
}

func (q *Queries) LockShipmentByIDForUpdate(ctx context.Context, arg LockShipmentByIDForUpdateParams) (Shipment, error) {
	row := q.db.QueryRow(ctx, lockShipmentByIDForUpdate, arg.ID, arg.OrganizationID)
	var i Shipment
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrganizationID,
		&i.Awb,
		&i.ReferenceNumber,
		&i.CustomerID,
		&i.CourierServiceID,
		&i.BookedByUserID,
		&i.BookingUnitID,
		&i.PaymentMode,
		&i.CurrentStatus,
		&i.StatusChangedAt,
		&i.EventSequence,
		&i.OriginBranchID,
		&i.OriginHubID,
		&i.DestinationHubID,
		&i.DestinationBranchID,
		&i.RouteDefinitionID,
		&i.OriginPincode,
		&i.DestinationPincode,
		&i.IsRemoteOrigin,
		&i.IsRemoteDestination,
		&i.CurrentCustodyUnitID,
		&i.CurrentCustodyUserID,
		&i.PieceCount,
		&i.ActualWeightGrams,
		&i.VolumetricWeightGrams,
		&i.ChargeableWeightGrams,
		&i.Currency,
		&i.DeclaredValueMinor,
		&i.CodAmountMinor,
		&i.InsuranceRequired,
		&i.TotalAmountMinor,
		&i.SlaHours,
		&i.PromisedDeliveryAt,
		&i.BookedAt,
		&i.ContentDescription,
		&i.SpecialInstructions,
		&i.IsFragile,
		&i.IsDangerousGoods,
		&i.CancelledAt,
		&i.CancelledBy,
		&i.CancellationReason,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
		&i.CurrentBagID,
		&i.CurrentTripID,
		&i.MovementDirection,
		&i.DeliveryAttemptCount,
		&i.PickupAttemptCount,
		&i.FirstOfdAt,
		&i.DeliveredAt,
		&i.PickedUpAt,
		&i.IsHeld,
		&i.HoldReason,
	)
	return i, err
}

const recordScanEvent = `-- name: RecordScanEvent :one
INSERT INTO scan_events (
    public_id, organization_id, raw_barcode, shipment_id, package_id, scan_type,
    operating_unit_id, scanned_by_user_id, device_event_id, device_id, source,
    occurred_at, outcome, rejection_code, rejection_message, shipment_event_id,
    from_status, to_status, latitude, longitude, reference_type, reference_id, metadata
) VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, $8,
    $9, $10, $11,
    COALESCE($12::timestamptz, now()), $13,
    $14, $15,
    $16, $17, $18,
    $19, $20, $21,
    $22, $23
) RETURNING id, public_id, organization_id, raw_barcode, shipment_id, package_id, scan_type, operating_unit_id, scanned_by_user_id, device_event_id, device_id, source, occurred_at, recorded_at, outcome, rejection_code, rejection_message, shipment_event_id, from_status, to_status, latitude, longitude, reference_type, reference_id, metadata
`

type RecordScanEventParams struct {
	PublicID         string
	OrganizationID   int64
	RawBarcode       string
	ShipmentID       *int64
	PackageID        *int64
	ScanType         string
	OperatingUnitID  int64
	ScannedByUserID  *int64
	DeviceEventID    *string
	DeviceID         *string
	Source           string
	OccurredAt       *time.Time
	Outcome          string
	RejectionCode    *string
	RejectionMessage *string
	ShipmentEventID  *int64
	FromStatus       *string
	ToStatus         *string
	Latitude         *float64
	Longitude        *float64
	ReferenceType    *string
	ReferenceID      *int64
	Metadata         []byte
}

func (q *Queries) RecordScanEvent(ctx context.Context, arg RecordScanEventParams) (ScanEvent, error) {
	row := q.db.QueryRow(ctx, recordScanEvent,
		arg.PublicID,
		arg.OrganizationID,
		arg.RawBarcode,
		arg.ShipmentID,
		arg.PackageID,
		arg.ScanType,
		arg.OperatingUnitID,
		arg.ScannedByUserID,
		arg.DeviceEventID,
		arg.DeviceID,
		arg.Source,
		arg.OccurredAt,
		arg.Outcome,
		arg.RejectionCode,
		arg.RejectionMessage,
		arg.ShipmentEventID,
		arg.FromStatus,
		arg.ToStatus,
		arg.Latitude,
		arg.Longitude,
		arg.ReferenceType,
		arg.ReferenceID,
		arg.Metadata,
	)
	var i ScanEvent
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrganizationID,
		&i.RawBarcode,
		&i.ShipmentID,
		&i.PackageID,
		&i.ScanType,
		&i.OperatingUnitID,
		&i.ScannedByUserID,
		&i.DeviceEventID,
		&i.DeviceID,
		&i.Source,
		&i.OccurredAt,
		&i.RecordedAt,
		&i.Outcome,
		&i.RejectionCode,
		&i.RejectionMessage,
		&i.ShipmentEventID,
		&i.FromStatus,
		&i.ToStatus,
		&i.Latitude,
		&i.Longitude,
		&i.ReferenceType,
		&i.ReferenceID,
		&i.Metadata,
	)
	return i, err
}

const releaseShipmentHold = `-- name: ReleaseShipmentHold :one
UPDATE shipment_holds
SET released_at = now(), released_by_user_id = $1,
    release_notes = $2
WHERE shipment_id = $3 AND released_at IS NULL
RETURNING id, public_id, organization_id, shipment_id, operating_unit_id, hold_reason_code, reason, held_at, held_by_user_id, released_at, released_by_user_id, release_notes, expected_release_at, metadata
`

type ReleaseShipmentHoldParams struct {
	ReleasedByUserID *int64
	ReleaseNotes     *string
	ShipmentID       int64
}

func (q *Queries) ReleaseShipmentHold(ctx context.Context, arg ReleaseShipmentHoldParams) (ShipmentHold, error) {
	row := q.db.QueryRow(ctx, releaseShipmentHold, arg.ReleasedByUserID, arg.ReleaseNotes, arg.ShipmentID)
	var i ShipmentHold
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrganizationID,
		&i.ShipmentID,
		&i.OperatingUnitID,
		&i.HoldReasonCode,
		&i.Reason,
		&i.HeldAt,
		&i.HeldByUserID,
		&i.ReleasedAt,
		&i.ReleasedByUserID,
		&i.ReleaseNotes,
		&i.ExpectedReleaseAt,
		&i.Metadata,
	)
	return i, err
}

const reserveShipmentEventSequence = `-- name: ReserveShipmentEventSequence :one
UPDATE shipments SET event_sequence = event_sequence + 1
WHERE id = $1 AND organization_id = $2
RETURNING id, event_sequence, current_status
`

type ReserveShipmentEventSequenceParams struct {
	ID             int64
	OrganizationID int64
}

type ReserveShipmentEventSequenceRow struct {
	ID            int64
	EventSequence int32
	CurrentStatus string
}

// For events that record something without changing status (a location update
// during reverse movement, a remark). Still bumps the counter so the event gets
// a unique, gap-free sequence.
func (q *Queries) ReserveShipmentEventSequence(ctx context.Context, arg ReserveShipmentEventSequenceParams) (ReserveShipmentEventSequenceRow, error) {
	row := q.db.QueryRow(ctx, reserveShipmentEventSequence, arg.ID, arg.OrganizationID)
	var i ReserveShipmentEventSequenceRow
	err := row.Scan(&i.ID, &i.EventSequence, &i.CurrentStatus)
	return i, err
}

const resolveScanBarcode = `-- name: ResolveScanBarcode :one

SELECT s.id, s.public_id, s.awb, s.organization_id, s.current_status, s.movement_direction,
       s.current_custody_unit_id, s.current_custody_user_id, s.current_bag_id, s.current_trip_id,
       s.origin_branch_id, s.origin_hub_id, s.destination_hub_id, s.destination_branch_id,
       s.piece_count, s.chargeable_weight_grams, s.actual_weight_grams,
       s.event_sequence, s.is_held, s.customer_id, s.booking_unit_id,
       s.destination_pincode, s.origin_pincode, s.cod_amount_minor, s.payment_mode,
       p.id AS package_id, p.sequence AS package_sequence
FROM shipments s
LEFT JOIN shipment_packages p
       ON p.piece_barcode = $1 AND p.shipment_id = s.id
WHERE s.organization_id = $2
  AND (s.awb = $1
       OR s.id = (SELECT shipment_id FROM shipment_packages
                   WHERE piece_barcode = $1 LIMIT 1))
`

type ResolveScanBarcodeParams struct {
	Barcode        string
	OrganizationID int64
}

type ResolveScanBarcodeRow struct {
	ID                    int64
	PublicID              string
	Awb                   string
	OrganizationID        int64
	CurrentStatus         string
	MovementDirection     string
	CurrentCustodyUnitID  *int64
	CurrentCustodyUserID  *int64
	CurrentBagID          *int64
	CurrentTripID         *int64
	OriginBranchID        *int64
	OriginHubID           *int64
	DestinationHubID      *int64
	DestinationBranchID   *int64
	PieceCount            int32
	ChargeableWeightGrams int32
	ActualWeightGrams     int32
	EventSequence         int32
	IsHeld                bool
	CustomerID            int64
	BookingUnitID         *int64
	DestinationPincode    string
	OriginPincode         string
	CodAmountMinor        int64
	PaymentMode           string
	PackageID             *int64
	PackageSequence       *int32
}

// Operational scanning (M10) and holds.
// The scanner's hot path: turn a barcode into the shipment plus everything the
// custody check needs, in one round trip.
//
// A barcode is either an AWB or a per-piece barcode. Both are UNIQUE, so the
// lookup is two index probes at worst and returns at most one row.
func (q *Queries) ResolveScanBarcode(ctx context.Context, arg ResolveScanBarcodeParams) (ResolveScanBarcodeRow, error) {
	row := q.db.QueryRow(ctx, resolveScanBarcode, arg.Barcode, arg.OrganizationID)
	var i ResolveScanBarcodeRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Awb,
		&i.OrganizationID,
		&i.CurrentStatus,
		&i.MovementDirection,
		&i.CurrentCustodyUnitID,
		&i.CurrentCustodyUserID,
		&i.CurrentBagID,
		&i.CurrentTripID,
		&i.OriginBranchID,
		&i.OriginHubID,
		&i.DestinationHubID,
		&i.DestinationBranchID,
		&i.PieceCount,
		&i.ChargeableWeightGrams,
		&i.ActualWeightGrams,
		&i.EventSequence,
		&i.IsHeld,
		&i.CustomerID,
		&i.BookingUnitID,
		&i.DestinationPincode,
		&i.OriginPincode,
		&i.CodAmountMinor,
		&i.PaymentMode,
		&i.PackageID,
		&i.PackageSequence,
	)
	return i, err
}

const setShipmentCustody = `-- name: SetShipmentCustody :one
UPDATE shipments
SET current_custody_unit_id = CASE WHEN $1::boolean
                                   THEN $2 ELSE current_custody_unit_id END,
    current_custody_user_id = CASE WHEN $3::boolean
                                   THEN $4 ELSE current_custody_user_id END,
    current_bag_id = CASE WHEN $5::boolean
                          THEN $6 ELSE current_bag_id END,
    current_trip_id = CASE WHEN $7::boolean
                           THEN $8 ELSE current_trip_id END
WHERE id = $9 AND organization_id = $10
RETURNING id, public_id, organization_id, awb, reference_number, customer_id, courier_service_id, booked_by_user_id, booking_unit_id, payment_mode, current_status, status_changed_at, event_sequence, origin_branch_id, origin_hub_id, destination_hub_id, destination_branch_id, route_definition_id, origin_pincode, destination_pincode, is_remote_origin, is_remote_destination, current_custody_unit_id, current_custody_user_id, piece_count, actual_weight_grams, volumetric_weight_grams, chargeable_weight_grams, currency, declared_value_minor, cod_amount_minor, insurance_required, total_amount_minor, sla_hours, promised_delivery_at, booked_at, content_description, special_instructions, is_fragile, is_dangerous_goods, cancelled_at, cancelled_by, cancellation_reason, metadata, created_at, updated_at, version, current_bag_id, current_trip_id, movement_direction, delivery_attempt_count, pickup_attempt_count, first_ofd_at, delivered_at, picked_up_at, is_held, hold_reason
`

type SetShipmentCustodyParams struct {
	SetCustodyUnit bool
	CustodyUnitID  *int64
	SetCustodyUser bool
	CustodyUserID  *int64
	SetBag         bool
	BagID          *int64
	SetTrip        bool
	TripID         *int64
	ID             int64
	OrganizationID int64
}

// Custody-only move: the parcel changed hands without changing lifecycle state,
// which happens when a bag is loaded onto a trip.
func (q *Queries) SetShipmentCustody(ctx context.Context, arg SetShipmentCustodyParams) (Shipment, error) {
	row := q.db.QueryRow(ctx, setShipmentCustody,
		arg.SetCustodyUnit,
		arg.CustodyUnitID,
		arg.SetCustodyUser,
		arg.CustodyUserID,
		arg.SetBag,
		arg.BagID,
		arg.SetTrip,
		arg.TripID,
		arg.ID,
		arg.OrganizationID,
	)
	var i Shipment
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrganizationID,
		&i.Awb,
		&i.ReferenceNumber,
		&i.CustomerID,
		&i.CourierServiceID,
		&i.BookedByUserID,
		&i.BookingUnitID,
		&i.PaymentMode,
		&i.CurrentStatus,
		&i.StatusChangedAt,
		&i.EventSequence,
		&i.OriginBranchID,
		&i.OriginHubID,
		&i.DestinationHubID,
		&i.DestinationBranchID,
		&i.RouteDefinitionID,
		&i.OriginPincode,
		&i.DestinationPincode,
		&i.IsRemoteOrigin,
		&i.IsRemoteDestination,
		&i.CurrentCustodyUnitID,
		&i.CurrentCustodyUserID,
		&i.PieceCount,
		&i.ActualWeightGrams,
		&i.VolumetricWeightGrams,
		&i.ChargeableWeightGrams,
		&i.Currency,
		&i.DeclaredValueMinor,
		&i.CodAmountMinor,
		&i.InsuranceRequired,
		&i.TotalAmountMinor,
		&i.SlaHours,
		&i.PromisedDeliveryAt,
		&i.BookedAt,
		&i.ContentDescription,
		&i.SpecialInstructions,
		&i.IsFragile,
		&i.IsDangerousGoods,
		&i.CancelledAt,
		&i.CancelledBy,
		&i.CancellationReason,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
		&i.CurrentBagID,
		&i.CurrentTripID,
		&i.MovementDirection,
		&i.DeliveryAttemptCount,
		&i.PickupAttemptCount,
		&i.FirstOfdAt,
		&i.DeliveredAt,
		&i.PickedUpAt,
		&i.IsHeld,
		&i.HoldReason,
	)
	return i, err
}

const setShipmentHoldFlag = `-- name: SetShipmentHoldFlag :one
UPDATE shipments
SET is_held = $1, hold_reason = $2
WHERE id = $3 AND organization_id = $4
RETURNING id, is_held, hold_reason
`

type SetShipmentHoldFlagParams struct {
	IsHeld         bool
	HoldReason     *string
	ID             int64
	OrganizationID int64
}

type SetShipmentHoldFlagRow struct {
	ID         int64
	IsHeld     bool
	HoldReason *string
}

func (q *Queries) SetShipmentHoldFlag(ctx context.Context, arg SetShipmentHoldFlagParams) (SetShipmentHoldFlagRow, error) {
	row := q.db.QueryRow(ctx, setShipmentHoldFlag,
		arg.IsHeld,
		arg.HoldReason,
		arg.ID,
		arg.OrganizationID,
	)
	var i SetShipmentHoldFlagRow
	err := row.Scan(&i.ID, &i.IsHeld, &i.HoldReason)
	return i, err
}
