// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: shipment_commercial.sql

package dbgen

import (
	"context"
	"time"
)

const createShipmentCommercialSnapshot = `-- name: CreateShipmentCommercialSnapshot :exec
INSERT INTO shipment_commercial_snapshots(shipment_id, organization_id, insurance, customs, billing, transport_customer_id)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateShipmentCommercialSnapshotParams struct {
	ShipmentID          int64
	OrganizationID      int64
	Insurance           []byte
	Customs             []byte
	Billing             []byte
	TransportCustomerID *int64
}

func (q *Queries) CreateShipmentCommercialSnapshot(ctx context.Context, arg CreateShipmentCommercialSnapshotParams) error {
	_, err := q.db.Exec(ctx, createShipmentCommercialSnapshot,
		arg.ShipmentID,
		arg.OrganizationID,
		arg.Insurance,
		arg.Customs,
		arg.Billing,
		arg.TransportCustomerID,
	)
	return err
}

const getShipmentCommercialSnapshot = `-- name: GetShipmentCommercialSnapshot :one
SELECT insurance, customs, billing, created_at, transport_customer_id FROM shipment_commercial_snapshots
WHERE organization_id = $1 AND shipment_id = $2
`

type GetShipmentCommercialSnapshotParams struct {
	OrganizationID int64
	ShipmentID     int64
}

type GetShipmentCommercialSnapshotRow struct {
	Insurance           []byte
	Customs             []byte
	Billing             []byte
	CreatedAt           time.Time
	TransportCustomerID *int64
}

func (q *Queries) GetShipmentCommercialSnapshot(ctx context.Context, arg GetShipmentCommercialSnapshotParams) (GetShipmentCommercialSnapshotRow, error) {
	row := q.db.QueryRow(ctx, getShipmentCommercialSnapshot, arg.OrganizationID, arg.ShipmentID)
	var i GetShipmentCommercialSnapshotRow
	err := row.Scan(
		&i.Insurance,
		&i.Customs,
		&i.Billing,
		&i.CreatedAt,
		&i.TransportCustomerID,
	)
	return i, err
}
